-- Read-only schema inventory. No business rows, sequence values or credentials.
-- Application objects live in public and netunim_internal; platform schemas are
-- inventoried separately and are prerequisites, never owned by the baseline.
with ns as (select oid,nspname from pg_namespace where nspname in ('public','netunim_internal')),
relations as (select c.*,n.nspname from pg_class c join ns n on n.oid=c.relnamespace where c.relkind in ('r','p','v','m','S'))
select jsonb_build_object(
'schemas',(select jsonb_agg(jsonb_build_object('name',n.nspname,'owner',pg_get_userbyid(p.nspowner),'acl',p.nspacl::text) order by n.nspname) from ns n join pg_namespace p on p.oid=n.oid),
'tables',(select jsonb_agg(jsonb_build_object('schema',c.nspname,'name',c.relname,'kind',c.relkind,'owner',pg_get_userbyid(c.relowner),'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity,'acl',c.relacl::text,'options',c.reloptions,'view',case when c.relkind in ('v','m') then pg_get_viewdef(c.oid,true) end) order by c.nspname,c.relname) from relations c where c.relkind<>'S'),
'columns',(select jsonb_agg(jsonb_build_object('schema',c.nspname,'table',c.relname,'name',a.attname,'position',a.attnum,'type',format_type(a.atttypid,a.atttypmod),'not_null',a.attnotnull,'identity',a.attidentity,'generated',a.attgenerated,'default',pg_get_expr(d.adbin,d.adrelid),'acl',a.attacl::text,'collation',case when a.attcollation<>t.typcollation then a.attcollation::regcollation::text end) order by c.nspname,c.relname,a.attnum) from relations c join pg_attribute a on a.attrelid=c.oid and a.attnum>0 and not a.attisdropped join pg_type t on t.oid=a.atttypid left join pg_attrdef d on d.adrelid=c.oid and d.adnum=a.attnum where c.relkind<>'S'),
'constraints',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',p.conname,'type',p.contype,'definition',pg_get_constraintdef(p.oid,true),'validated',p.convalidated) order by n.nspname,c.relname,p.conname) from pg_constraint p join ns n on n.oid=p.connamespace join pg_class c on c.oid=p.conrelid),
'indexes',(select jsonb_agg(jsonb_build_object('schema',c.nspname,'table',c.relname,'name',ic.relname,'definition',pg_get_indexdef(i.indexrelid),'valid',i.indisvalid,'constraint',exists(select 1 from pg_constraint p where p.conindid=i.indexrelid)) order by c.nspname,c.relname,ic.relname) from relations c join pg_index i on i.indrelid=c.oid join pg_class ic on ic.oid=i.indexrelid),
'sequences',(select jsonb_agg(jsonb_build_object('schema',c.nspname,'name',c.relname,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'type',format_type(s.seqtypid,null),'start',s.seqstart::text,'increment',s.seqincrement::text,'min',s.seqmin::text,'max',s.seqmax::text,'cache',s.seqcache::text,'cycle',s.seqcycle,'owned_by',(select jsonb_build_object('schema',tn.nspname,'table',t.relname,'column',a.attname,'dependency',d.deptype) from pg_depend d join pg_class t on t.oid=d.refobjid join pg_namespace tn on tn.oid=t.relnamespace join pg_attribute a on a.attrelid=t.oid and a.attnum=d.refobjsubid where d.classid='pg_class'::regclass and d.objid=c.oid and d.refobjsubid>0 and d.deptype in ('a','i'))) order by c.nspname,c.relname) from relations c join pg_sequence s on s.seqrelid=c.oid),
'functions',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',p.proname,'identity',pg_get_function_identity_arguments(p.oid),'definition',pg_get_functiondef(p.oid),'owner',pg_get_userbyid(p.proowner),'security_definer',p.prosecdef,'config',p.proconfig,'acl',p.proacl::text,'authenticated',has_function_privilege('authenticated',p.oid,'EXECUTE'),'anon',has_function_privilege('anon',p.oid,'EXECUTE')) order by n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)) from pg_proc p join ns n on n.oid=p.pronamespace where p.prokind in ('f','p') and not exists(select 1 from pg_depend d where d.classid='pg_proc'::regclass and d.objid=p.oid and d.deptype='e')),
'policies',(select jsonb_agg(jsonb_build_object('schema',schemaname,'table',tablename,'name',policyname,'permissive',permissive,'roles',roles,'command',cmd,'using',qual,'check',with_check) order by schemaname,tablename,policyname) from pg_policies where schemaname in (select nspname from ns)),
'triggers',(select jsonb_agg(jsonb_build_object('schema',c.nspname,'table',c.relname,'name',t.tgname,'enabled',t.tgenabled,'definition',pg_get_triggerdef(t.oid,true)) order by c.nspname,c.relname,t.tgname) from relations c join pg_trigger t on t.tgrelid=c.oid where not t.tgisinternal),
'event_triggers',(select jsonb_agg(jsonb_build_object('name',e.evtname,'event',e.evtevent,'enabled',e.evtenabled,'tags',e.evttags,'schema',n.nspname,'function',p.proname,'owner',pg_get_userbyid(e.evtowner)) order by e.evtname) from pg_event_trigger e join pg_proc p on p.oid=e.evtfoid join ns n on n.oid=p.pronamespace),
'default_privileges',(select jsonb_agg(jsonb_build_object('schema',coalesce(n.nspname,''),'owner',pg_get_userbyid(d.defaclrole),'type',d.defaclobjtype,'acl',d.defaclacl::text) order by n.nspname,d.defaclrole,d.defaclobjtype) from pg_default_acl d left join pg_namespace n on n.oid=d.defaclnamespace where d.defaclnamespace=0 or n.nspname in (select nspname from ns)),
'types',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',t.typname,'kind',t.typtype) order by n.nspname,t.typname) from pg_type t join ns n on n.oid=t.typnamespace where t.typtype in ('e','d')),
'operations',jsonb_build_object(
  'pg_cron',exists(select 1 from pg_extension where extname='pg_cron'),
  'full_visibility',exists(select 1 from pg_roles where rolname=current_user and (rolsuper or rolbypassrls)),
  'database',current_database(), 'server_port',inet_server_port(),
  'timezone',current_setting('cron.timezone',true),
  'launch_active_jobs',current_setting('cron.launch_active_jobs',true),
  'jobs',(select coalesce(jsonb_agg(to_jsonb(j) order by j.jobid),'[]') from cron.job j)),
'extensions',(select jsonb_agg(jsonb_build_object('name',e.extname,'schema',n.nspname,'version',e.extversion) order by e.extname) from pg_extension e join pg_namespace n on n.oid=e.extnamespace),
'platform_schemas',(select jsonb_agg(jsonb_build_object('name',nspname,'owner',pg_get_userbyid(nspowner),'acl',nspacl::text) order by nspname) from pg_namespace where nspname not like 'pg_%' and nspname<>'information_schema' and nspname not in (select nspname from ns))
) as inventory;
