-- Shared Checks Domain — Supabase Data Safety v1
-- התקנה/תחזוקה של מקור האמת המשותף לצ'קים.
-- אין בסקריפט זה העברה של נתוני ייצור ישנים מתוך kupa/order_management.
-- למעבר מהמערכת הישנה יש להשתמש ב-cutover.sql בלבד לאחר preflight והקפאת עבודה.

begin;
set local lock_timeout = '10s';
set local statement_timeout = '90s';

-- סדר פיננסי מונוטוני משותף לצילום יתרת בנק ולהפקדת צ'ק.
-- השרת בלבד מקצה מספרים; אין להסתמך על שעוני מחשבי הקצה לסדר אירועים כספיים.
create sequence if not exists public.shared_financial_event_seq as bigint;
revoke all on sequence public.shared_financial_event_seq from public, anon, authenticated;
grant usage on sequence public.shared_financial_event_seq to authenticated;

create table if not exists public.shared_checks_documents (
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null default 'main',
  revision bigint not null default 1 check (revision > 0),
  state jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (owner_id, document_name)
);

create table if not exists public.shared_checks_document_backups (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null,
  revision bigint not null check (revision > 0),
  state jsonb not null,
  saved_at timestamptz not null default now()
);

create table if not exists public.shared_checks_periodic_backups (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null,
  revision bigint not null check (revision > 0),
  state jsonb not null,
  saved_at timestamptz not null default now()
);

create index if not exists shared_checks_backups_owner_doc_saved_idx
  on public.shared_checks_document_backups(owner_id, document_name, saved_at desc);
create index if not exists shared_checks_periodic_owner_doc_saved_idx
  on public.shared_checks_periodic_backups(owner_id, document_name, saved_at desc);
create unique index if not exists shared_checks_backups_owner_doc_revision_uidx
  on public.shared_checks_document_backups(owner_id, document_name, revision);
create unique index if not exists shared_checks_periodic_owner_doc_revision_uidx
  on public.shared_checks_periodic_backups(owner_id, document_name, revision);

-- מסמך חי: אובייקט עם מערך checks בלבד כדומיין העסקי המרכזי.
-- היסטוריית גיבוי מקבלת אותו חוזה מבני.
alter table public.shared_checks_documents drop constraint if exists shared_checks_documents_state_shape_check;
alter table public.shared_checks_documents
  add constraint shared_checks_documents_state_shape_check
  check (
    jsonb_typeof(state) = 'object'
    and jsonb_typeof(state->'checks') = 'array'
    and jsonb_typeof(state->'bankEvents') = 'array'
  ) not valid;

alter table public.shared_checks_document_backups drop constraint if exists shared_checks_document_backups_state_shape_check;
alter table public.shared_checks_document_backups
  add constraint shared_checks_document_backups_state_shape_check
  check (
    jsonb_typeof(state) = 'object'
    and jsonb_typeof(state->'checks') = 'array'
    and jsonb_typeof(state->'bankEvents') = 'array'
  ) not valid;

alter table public.shared_checks_periodic_backups drop constraint if exists shared_checks_periodic_backups_state_shape_check;
alter table public.shared_checks_periodic_backups
  add constraint shared_checks_periodic_backups_state_shape_check
  check (
    jsonb_typeof(state) = 'object'
    and jsonb_typeof(state->'checks') = 'array'
    and jsonb_typeof(state->'bankEvents') = 'array'
  ) not valid;

alter table public.shared_checks_documents validate constraint shared_checks_documents_state_shape_check;
alter table public.shared_checks_document_backups validate constraint shared_checks_document_backups_state_shape_check;
alter table public.shared_checks_periodic_backups validate constraint shared_checks_periodic_backups_state_shape_check;

alter table public.shared_checks_documents enable row level security;
alter table public.shared_checks_document_backups enable row level security;
alter table public.shared_checks_periodic_backups enable row level security;

revoke all on table public.shared_checks_documents from anon, authenticated;
revoke all on table public.shared_checks_document_backups from anon, authenticated;
revoke all on table public.shared_checks_periodic_backups from anon, authenticated;
grant select, insert, update on table public.shared_checks_documents to authenticated;
grant select, insert, delete on table public.shared_checks_document_backups to authenticated;
grant select, insert, delete on table public.shared_checks_periodic_backups to authenticated;

revoke all on sequence public.shared_checks_document_backups_id_seq from public, anon;
revoke all on sequence public.shared_checks_periodic_backups_id_seq from public, anon;
grant usage, select on sequence public.shared_checks_document_backups_id_seq to authenticated;
grant usage, select on sequence public.shared_checks_periodic_backups_id_seq to authenticated;

drop policy if exists "shared_checks_documents_select_own" on public.shared_checks_documents;
create policy "shared_checks_documents_select_own" on public.shared_checks_documents
for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists "shared_checks_documents_insert_own" on public.shared_checks_documents;
create policy "shared_checks_documents_insert_own" on public.shared_checks_documents
for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists "shared_checks_documents_update_own" on public.shared_checks_documents;
create policy "shared_checks_documents_update_own" on public.shared_checks_documents
for update to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id)
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists "shared_checks_backups_select_own" on public.shared_checks_document_backups;
create policy "shared_checks_backups_select_own" on public.shared_checks_document_backups
for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists "shared_checks_backups_insert_own" on public.shared_checks_document_backups;
create policy "shared_checks_backups_insert_own" on public.shared_checks_document_backups
for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists "shared_checks_backups_delete_own" on public.shared_checks_document_backups;
create policy "shared_checks_backups_delete_own" on public.shared_checks_document_backups
for delete to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists "shared_checks_periodic_select_own" on public.shared_checks_periodic_backups;
create policy "shared_checks_periodic_select_own" on public.shared_checks_periodic_backups
for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists "shared_checks_periodic_insert_own" on public.shared_checks_periodic_backups;
create policy "shared_checks_periodic_insert_own" on public.shared_checks_periodic_backups
for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists "shared_checks_periodic_delete_own" on public.shared_checks_periodic_backups;
create policy "shared_checks_periodic_delete_own" on public.shared_checks_periodic_backups
for delete to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

create or replace function public.shared_checks_guard_document_write()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
begin
  if current_user = 'authenticated'
     and coalesce(current_setting('app.shared_checks_rpc_write', true), '') <> '1' then
    raise exception 'direct_shared_checks_write_forbidden'
      using errcode = '42501',
            hint = 'Use save_shared_checks_document RPC so revision checks and backups cannot be bypassed.';
  end if;
  if tg_op = 'UPDATE' and (
       new.owner_id is distinct from old.owner_id
       or new.document_name is distinct from old.document_name
     ) then
    raise exception 'shared_checks_identity_change_forbidden' using errcode = '22023';
  end if;
  return new;
end;
$$;
revoke all on function public.shared_checks_guard_document_write() from public, anon;
grant execute on function public.shared_checks_guard_document_write() to authenticated;

drop trigger if exists shared_checks_documents_write_guard on public.shared_checks_documents;
create trigger shared_checks_documents_write_guard
before insert or update on public.shared_checks_documents
for each row execute function public.shared_checks_guard_document_write();

-- מחליפים במפורש כדי שניתן יהיה להוסיף state לפלט גם אם הייתה גרסה קודמת.
drop function if exists public.save_shared_checks_document(text, bigint, jsonb);
create function public.save_shared_checks_document(
  p_document_name text,
  p_expected_revision bigint,
  p_state jsonb
)
returns table(revision bigint, updated_at timestamptz, state jsonb)
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_owner uuid := auth.uid();
  v_current_revision bigint;
  v_old_state jsonb;
  v_old_updated_at timestamptz;
  v_server_state jsonb;
  v_server_checks jsonb := '[]'::jsonb;
  v_bank_events jsonb := '[]'::jsonb;
  v_check jsonb;
  v_old_check jsonb;
  v_check_id text;
  v_status text;
  v_old_status text;
  v_is_deposited boolean;
  v_was_deposited boolean;
  v_old_effect numeric;
  v_new_effect numeric;
  v_effect_delta numeric;
  v_event_seq bigint;
  v_now timestamptz;
  v_new_revision bigint;
  v_new_updated_at timestamptz;
begin
  if v_owner is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;
  -- Shared per-user financial writer gate: fail fast instead of filling the PostgREST pool.
  if not pg_try_advisory_xact_lock(
    hashtextextended('netunim_financial_write:' || v_owner::text, 0)
  ) then
    raise exception 'save_busy'
      using errcode = 'PT429',
            hint = 'Another financial save is already in progress. Retry later.';
  end if;
  perform set_config('lock_timeout', '100ms', true);
  if p_document_name is null or btrim(p_document_name) = '' then
    raise exception 'invalid_document_name' using errcode = '22023';
  end if;
  if p_expected_revision is null or p_expected_revision < 0 then
    raise exception 'invalid_expected_revision' using errcode = '22023';
  end if;
  if p_state is null
     or jsonb_typeof(p_state) is distinct from 'object'
     or jsonb_typeof(p_state->'checks') is distinct from 'array' then
    raise exception 'invalid_shared_checks_state'
      using errcode = '22023', hint = 'State must be an object containing a checks array.';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(p_state->'checks') c
    where jsonb_typeof(c) is distinct from 'object'
       or nullif(btrim(c->>'id'), '') is null
       or jsonb_typeof(c->'amount') is distinct from 'number'
       or jsonb_typeof(c->'dueDate') is distinct from 'string'
       or jsonb_typeof(c->'status') is distinct from 'string'
       or (c->>'status') not in ('בקופה','הופקד - במעקב','נפרע','חזר','בוטל')
  ) then
    raise exception 'invalid_shared_check_record' using errcode = '22023';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(p_state->'checks') c
    group by c->>'id'
    having count(*) > 1
  ) then
    raise exception 'duplicate_shared_check_id' using errcode = '23505';
  end if;

  perform set_config('app.shared_checks_rpc_write', '1', true);

  select d.revision, d.state, d.updated_at
    into v_current_revision, v_old_state, v_old_updated_at
  from public.shared_checks_documents d
  where d.owner_id = v_owner and d.document_name = p_document_name
  for update;

  if v_old_state is not null and jsonb_typeof(v_old_state->'bankEvents') = 'array' then
    v_bank_events := v_old_state->'bankEvents';
  end if;

  -- Fail closed against a stale/bootstrap client interpreting an empty local shell as "delete every check".
  -- Normal single-record deletion remains available, including deletion of the final remaining check.
  if v_old_state is not null
     and jsonb_typeof(v_old_state->'checks') = 'array'
     and jsonb_array_length(v_old_state->'checks') > 1
     and jsonb_array_length(p_state->'checks') = 0 then
    raise exception 'bulk_delete_all_shared_checks_forbidden'
      using errcode = '22023', hint = 'Refresh from shared_checks_documents before attempting a bulk deletion.';
  end if;

  -- הלקוח שולח את מצב הצ'קים בלבד. depositSeq/depositedAt ו-bankEvents הם server-authoritative.
  -- כל שינוי בהשפעה הכספית של צ'ק יוצר אירוע delta מונוטוני, כולל החזרה, שינוי סכום ומחיקה.
  for v_check in select value from jsonb_array_elements(p_state->'checks') loop
    v_check_id := v_check->>'id';
    v_status := v_check->>'status';
    v_is_deposited := v_status in ('הופקד - במעקב','נפרע');
    v_old_check := null;
    if v_old_state is not null then
      select c.value into v_old_check
      from jsonb_array_elements(v_old_state->'checks') c(value)
      where c.value->>'id' = v_check_id
      limit 1;
    end if;
    v_old_status := coalesce(v_old_check->>'status','');
    v_was_deposited := v_old_status in ('הופקד - במעקב','נפרע');
    v_old_effect := case when v_was_deposited then coalesce((v_old_check->>'amount')::numeric,0) else 0 end;
    v_new_effect := case when v_is_deposited then coalesce((v_check->>'amount')::numeric,0) else 0 end;
    v_effect_delta := v_new_effect - v_old_effect;
    v_event_seq := null;
    v_now := null;

    -- כל metadata שהלקוח החזיר מנוקה ומוחזר מהמצב השרת/מהאירוע החדש בלבד.
    v_check := v_check - 'depositSeq' - 'depositedAt' - 'bankEvents';

    if v_is_deposited and not v_was_deposited then
      v_event_seq := nextval('public.shared_financial_event_seq');
      v_now := clock_timestamp();
      v_check := v_check || jsonb_build_object('depositSeq', v_event_seq, 'depositedAt', v_now);
    elsif v_old_check is not null then
      -- retry אחרי ACK שאבד מקבל שוב בדיוק את metadata שכבר אושר בשרת.
      v_check := v_check || jsonb_build_object(
        'depositSeq', coalesce(v_old_check->'depositSeq','null'::jsonb),
        'depositedAt', coalesce(v_old_check->'depositedAt','null'::jsonb)
      );
    else
      v_check := v_check || jsonb_build_object('depositSeq', null, 'depositedAt', null);
    end if;

    if v_effect_delta <> 0 then
      if v_event_seq is null then
        v_event_seq := nextval('public.shared_financial_event_seq');
        v_now := clock_timestamp();
      end if;
      v_bank_events := v_bank_events || jsonb_build_array(jsonb_build_object(
        'seq', v_event_seq,
        'at', v_now,
        'delta', v_effect_delta,
        'kind', 'check_effect_delta',
        'checkId', v_check_id
      ));
    end if;

    v_server_checks := v_server_checks || jsonb_build_array(v_check);
  end loop;

  -- מחיקת צ'ק בעל השפעה בנקאית חייבת ליצור reversal גם לאחר שהרשומה עצמה נעלמה.
  if v_old_state is not null then
    for v_old_check in
      select c.value
      from jsonb_array_elements(v_old_state->'checks') c(value)
      where not exists (
        select 1 from jsonb_array_elements(p_state->'checks') n(value)
        where n.value->>'id' = c.value->>'id'
      )
    loop
      v_old_status := coalesce(v_old_check->>'status','');
      if v_old_status in ('הופקד - במעקב','נפרע') then
        v_old_effect := coalesce((v_old_check->>'amount')::numeric,0);
        if v_old_effect <> 0 then
          v_event_seq := nextval('public.shared_financial_event_seq');
          v_now := clock_timestamp();
          v_bank_events := v_bank_events || jsonb_build_array(jsonb_build_object(
            'seq', v_event_seq,
            'at', v_now,
            'delta', -v_old_effect,
            'kind', 'check_effect_delta',
            'checkId', v_old_check->>'id'
          ));
        end if;
      end if;
    end loop;
  end if;

  v_server_state := jsonb_build_object('version',1,'checks',v_server_checks,'bankEvents',v_bank_events);

  if v_current_revision is null then
    if coalesce(p_expected_revision, 0) <> 0 then
      raise exception 'revision_conflict' using errcode = '40001';
    end if;
    insert into public.shared_checks_documents(owner_id, document_name, revision, state, updated_at)
    values (v_owner, p_document_name, 1, v_server_state, now())
    returning shared_checks_documents.revision, shared_checks_documents.updated_at, shared_checks_documents.state
      into v_new_revision, v_new_updated_at, v_server_state;
    insert into public.shared_checks_periodic_backups(owner_id, document_name, revision, state, saved_at)
    values (v_owner, p_document_name, v_new_revision, v_server_state, v_new_updated_at)
    on conflict do nothing;
    return query select v_new_revision, v_new_updated_at, v_server_state;
    return;
  end if;

  -- Idempotency לפני conflict: lost ACK עם expected revision ישן אינו יוצר כשל שווא.
  if v_old_state = v_server_state then
    return query select v_current_revision, v_old_updated_at, v_old_state;
    return;
  end if;
  if v_current_revision <> p_expected_revision then
    raise exception 'revision_conflict' using errcode = '40001';
  end if;

  insert into public.shared_checks_document_backups(owner_id, document_name, revision, state, saved_at)
  values (v_owner, p_document_name, v_current_revision, v_old_state, v_old_updated_at)
  on conflict do nothing;

  update public.shared_checks_documents d
  set revision = d.revision + 1, state = v_server_state, updated_at = now()
  where d.owner_id = v_owner and d.document_name = p_document_name
  returning d.revision, d.updated_at, d.state
    into v_new_revision, v_new_updated_at, v_server_state;

  if not exists (
    select 1 from public.shared_checks_periodic_backups p
    where p.owner_id = v_owner and p.document_name = p_document_name
      and p.saved_at > now() - interval '12 hours'
  ) then
    insert into public.shared_checks_periodic_backups(owner_id, document_name, revision, state, saved_at)
    values (v_owner, p_document_name, v_new_revision, v_server_state, v_new_updated_at)
    on conflict do nothing;
  end if;

  delete from public.shared_checks_periodic_backups p
  where p.owner_id = v_owner and p.document_name = p_document_name
    and p.saved_at < now() - interval '365 days';

  delete from public.shared_checks_document_backups b
  where b.owner_id = v_owner and b.document_name = p_document_name
    and b.id in (
      select x.id from public.shared_checks_document_backups x
      where x.owner_id = v_owner and x.document_name = p_document_name
      order by x.saved_at desc, x.id desc offset 200
    );

  return query select v_new_revision, v_new_updated_at, v_server_state;
end;
$$;
revoke all on function public.save_shared_checks_document(text, bigint, jsonb) from public, anon;
grant execute on function public.save_shared_checks_document(text, bigint, jsonb) to authenticated;

commit;
