from pathlib import Path
import json
import subprocess

ROOT=Path(__file__).resolve().parents[1]
SITE=ROOT/'netunim-kupa/site'
BRIDGE=ROOT/'netunim-kupa/bank-bridge'
errors=[]

def ok(condition,message):
    print(('PASS' if condition else 'FAIL'),message)
    if not condition: errors.append(message)

for rel in ['server.mjs','lib.mjs','isracard-camoufox.mjs','provision-camoufox.mjs']:
    r=subprocess.run(['node','--check',str(BRIDGE/rel)],capture_output=True,text=True)
    ok(r.returncode==0,f'bank bridge: {rel} has valid JavaScript syntax')
    if r.returncode: print(r.stderr)
for rel in ['assets/js/domains/bank/bridge.js','assets/js/domains/bank/feed.js','assets/js/domains/bank/controller.js','assets/js/domains/bank/view.js','assets/js/domains/credit/sync-feed.js','assets/js/domains/credit/controller.js','assets/js/domains/credit/model.js','assets/js/domains/credit/view.js','assets/js/ui/actions.js','assets/js/main.js','assets/js/state/normalization.js']:
    r=subprocess.run(['node','--check',str(SITE/rel)],capture_output=True,text=True)
    ok(r.returncode==0,f'bank site: {rel} has valid JavaScript syntax')
    if r.returncode: print(r.stderr)

r=subprocess.run(['node',str(ROOT/'tests/bank_bridge_models.test.mjs')],cwd=ROOT,capture_output=True,text=True)
if r.stdout: print(r.stdout.strip())
if r.stderr: print(r.stderr.strip())
ok(r.returncode==0,'bank bridge models: staged data/feed/MFA model tests pass')

r=subprocess.run(['node',str(ROOT/'tests/credit_sync_models.test.mjs')],cwd=ROOT,capture_output=True,text=True)
if r.stdout: print(r.stdout.strip())
if r.stderr: print(r.stderr.strip())
ok(r.returncode==0,'credit sync models: multi-profile, cutover/rollback and forecast semantics pass')

ORDERS_SITE=ROOT/'netunim-orders/site'
for rel in ['assets/js/domains/finance/bridge.js','assets/js/domains/finance/bank-feed.js','assets/js/domains/finance/credit-feed.js','assets/js/domains/finance/controller.js','assets/js/domains/bank/cache.js','assets/js/cloud/transport.js','assets/js/lifecycle.js','assets/js/ui/cloud.js','assets/js/main.js']:
    r=subprocess.run(['node','--check',str(ORDERS_SITE/rel)],capture_output=True,text=True)
    ok(r.returncode==0,f'orders finance sync: {rel} has valid JavaScript syntax')
    if r.returncode: print(r.stderr)

r=subprocess.run(['node',str(ROOT/'tests/orders_finance_sync_models.test.mjs')],cwd=ROOT,capture_output=True,text=True)
if r.stdout: print(r.stdout.strip())
if r.stderr: print(r.stderr.strip())
ok(r.returncode==0,'orders finance sync models: shared freshness and conflict-safe cross-app updates pass')

r=subprocess.run(['node',str(ROOT/'tests/cross_app_finance_freshness.test.mjs')],cwd=ROOT,capture_output=True,text=True)
if r.stdout: print(r.stdout.strip())
if r.stderr: print(r.stderr.strip())
ok(r.returncode==0,'cross-app finance freshness: Kupa rechecks the shared cloud clock before automatic bank/credit scraping')

server=(BRIDGE/'server.mjs').read_text(encoding='utf-8')
lib=(BRIDGE/'lib.mjs').read_text(encoding='utf-8')
camoufox=(BRIDGE/'isracard-camoufox.mjs').read_text(encoding='utf-8')
camoufox_provisioner=(BRIDGE/'provision-camoufox.mjs').read_text(encoding='utf-8')
controller=(SITE/'assets/js/domains/bank/controller.js').read_text(encoding='utf-8')
client=(SITE/'assets/js/domains/bank/bridge.js').read_text(encoding='utf-8')
feed=(SITE/'assets/js/domains/bank/feed.js').read_text(encoding='utf-8')
view=(SITE/'assets/js/domains/bank/view.js').read_text(encoding='utf-8')
actions=(SITE/'assets/js/ui/actions.js').read_text(encoding='utf-8')
main=(SITE/'assets/js/main.js').read_text(encoding='utf-8')
normalization=(SITE/'assets/js/state/normalization.js').read_text(encoding='utf-8')
credit_controller=(SITE/'assets/js/domains/credit/controller.js').read_text(encoding='utf-8')
credit_client=(SITE/'assets/js/domains/bank/bridge.js').read_text(encoding='utf-8')
credit_feed=(SITE/'assets/js/domains/credit/sync-feed.js').read_text(encoding='utf-8')
credit_model=(SITE/'assets/js/domains/credit/model.js').read_text(encoding='utf-8')
credit_view=(SITE/'assets/js/domains/credit/view.js').read_text(encoding='utf-8')
app_css=(SITE/'assets/app.css').read_text(encoding='utf-8')
bank_model=(SITE/'assets/js/domains/bank/model.js').read_text(encoding='utf-8')
orders_readout=(ROOT/'netunim-orders/site/assets/js/domains/bank/readout.js').read_text(encoding='utf-8')
orders_finance_controller=(ROOT/'netunim-orders/site/assets/js/domains/finance/controller.js').read_text(encoding='utf-8')
orders_finance_bridge=(ROOT/'netunim-orders/site/assets/js/domains/finance/bridge.js').read_text(encoding='utf-8')
orders_cloud_transport=(ROOT/'netunim-orders/site/assets/js/cloud/transport.js').read_text(encoding='utf-8')
orders_lifecycle=(ROOT/'netunim-orders/site/assets/js/lifecycle.js').read_text(encoding='utf-8')
orders_headers=(ROOT/'netunim-orders/site/_headers').read_text(encoding='utf-8')
orders_worker=(ROOT/'netunim-orders/site/service-worker.js').read_text(encoding='utf-8')
contexts=(SITE/'assets/js/state/contexts.js').read_text(encoding='utf-8')
navigation=(SITE/'assets/js/ui/navigation.js').read_text(encoding='utf-8')
headers=(SITE/'_headers').read_text(encoding='utf-8')
worker=(SITE/'service-worker.js').read_text(encoding='utf-8')
sync_merge=(SITE/'assets/js/sync/merge.js').read_text(encoding='utf-8')
installer=(BRIDGE/'install_bank_bridge.bat').read_text(encoding='utf-8')
start_script=(BRIDGE/'start_bank_bridge.bat').read_text(encoding='utf-8')
launcher_path=BRIDGE/'launch_hidden.vbs'
launcher=launcher_path.read_text(encoding='ascii') if launcher_path.exists() else ''
package=json.loads((BRIDGE/'package.json').read_text(encoding='utf-8'))

ok(BRIDGE.is_dir() and not str(BRIDGE).startswith(str(SITE)), 'bank bridge security: scraper and credentials component stays outside the public site root')
ok("const HOST='127.0.0.1'" in server and 'activeServer.listen(PORT,HOST' in server, 'bank bridge security: HTTP service binds to loopback only')
ok('System.Security.Cryptography.DataProtectionScope]::CurrentUser' in server and 'ProtectedData]::Protect' in server and 'ProtectedData]::Unprotect' in server, 'bank bridge security: Hapoalim credentials use Windows DPAPI CurrentUser encryption')
ok('Bearer ' in server and 'timingSafeEqual' in server and "req.url==='/health'" in server, 'bank bridge security: private routes require a timing-safe bearer key')
ok(package.get('dependencies',{}).get('israeli-bank-scrapers')=='6.9.0', 'bank bridge dependency: scraper version is pinned exactly')
ok(package.get('netunimRuntimeDependencies',{}).get('camoufox-js')=='0.12.0' and package.get('netunimRuntimeDependencies',{}).get('playwright-core')=='1.60.0' and package.get('netunimRuntimeDependencies',{}).get('fingerprint-generator')=='2.1.86', 'bank bridge dependency: Amex Camoufox/Playwright/fingerprint-generator runtime versions are pinned explicitly')
ok(package.get('allowScripts',{}).get('puppeteer') is False and 'PUPPETEER_SKIP_DOWNLOAD=true' in installer, 'bank bridge dependency: Puppeteer browser download/install script is disabled')
ok('findInstalledBrowser' in server and 'executablePath:browserPath' in server and '--user-data-dir=${BROWSER_PROFILE_DIR}' in server and '--profile-directory=Default' in server and 'rememberBrowser' in server, 'bank bridge browser: one installed Chrome/Edge choice and a dedicated persistent local profile are reused across runs')
ok('selectAccountDescriptor' in server and 'parseAccountSelector' in server and 'availableAccounts' in server and 'branchNumber' in server and 'MULTIPLE_ACCOUNTS' in lib, 'bank bridge account guard: Hapoalim bank 12 + exact branch/account are selected before bank reads and ambiguous account numbers return safe choices')

# Login root-cause guard: Hapoalim can change the successful SPA URL. A real authenticated data session, not a hard-coded route, is authoritative.
ok('readHapoalimSessionState' in server and 'hapoalimSessionIsAuthenticated' in server and "[...originalSuccess,async()=>hapoalimSessionIsAuthenticated(scraper.page)]" in server, 'bank login classification: a working authenticated accounts API is accepted as success even when the post-login URL is unknown to the pinned scraper')
ok('enableHapoalimSessionAwareLogin(scraper,{interactive})' in server and 'SILENT_AUTH_TIMEOUT_MS' in server and 'NETUNIM_SILENT_AUTH_TIMEOUT' in lib, 'bank login adapter: silent refresh no longer uses the pinned scraper URL result alone and reports AUTH_REQUIRED when no authenticated session is established')
ok('tryReuseSavedHapoalimSession' in server and 'sessionUrl' in server and 'safeHapoalimSessionUrl' in server and "`${url.origin}${url.pathname}`" in server, 'bank session reuse: successful profile session path is reused before a new credential login and query/hash tokens are never persisted')

# Root cause guard: do not reintroduce the monolithic library scrape that couples every account, balance and transaction fetch.
ok('scraper.login(' in server and 'scraper.initialize(' in server and 'fetchSelectedHapoalimSnapshot' in server and 'scraper.scrape(profile.credentials)' in server and "if(profile.provider==='amex')" in server and 'scrapeCreditWithCamoufox' in server, 'financial adapters: Hapoalim keeps staged bank reads, Cal/Max/native Isracard keep upstream scrapers, and Amex uses the dedicated Camoufox adapter')
ok('waitForHapoalimSessionReady' in server and 'window.bnhpApp?.restContext' in server and '/ServerServices/general/accounts' in server and 'HAPOALIM_POST_LOGIN_TIMEOUT_MS' in server and 'HAPOALIM_NAVIGATION_STABLE_MS' in server, 'bank post-login readiness: visible homepage is not treated as data-ready until authenticated SPA/API state remains stable across navigation')
ok('balanceAndCreditLimit' in server and "runStage('balance'" in server and 'currentBalance' in server, 'bank balance: selected account balance is fetched independently as the authoritative required result')
ok('retryTransientNavigation' in server and 'pageFetchJsonOnce' in server and 'HAPOALIM_DATA_RETRY_LIMIT' in server and 'isTransientNavigationError' in server, 'bank navigation recovery: balance/transaction reads retry only transient destroyed execution contexts after re-establishing a stable authenticated page')
ok('/current-account/transactions?' in server and "method:'POST'" in server and 'numItemsPerPage=${HAPOALIM_TRANSACTION_LIMIT}' in server and 'normalizeRecentTransactions' in server and 'HAPOALIM_TRANSACTION_LOOKBACK_DAYS' in server and 'HAPOALIM_TRANSACTION_LIMIT' in server, 'bank transactions: full rolling thirty-day Hapoalim page is fetched separately without the historical twenty-row trim')
ok('enrichHapoalimChequeTransactions' in server and 'pfmDetails' in server and 'buildHapoalimAdditionalDetailsUrl' in server and 'normalizeHapoalimAdditionalDetails' in server and 'isHapoalimChequeTransaction' in server and 'beneficiary names' in lib, 'bank cheque details: only explicit cheque-deposit activity descriptions follow Hapoalim additional-information; beneficiary text cannot create false positives')
ok('UNSAFE_DETAIL_URL' in lib and 'hasDocumentReference' in lib and 'isUnsafeTechnicalDetailKey' in lib and 'isDocumentDetailKey' in lib and 'checkItems' in lib and 'generic PFM' not in lib, 'bank cheque detail security: additional requests stay on Hapoalim origin, sensitive document/session values are not persisted, and only structured cheque rows survive normalization')
ok("catch(e){transactionWarning=" in server and 'snapshot:{balance' in server and 'transactionWarning' in server, 'bank partial success: transaction failure is non-fatal after a valid balance has been read')
ok('const warnings=[result.accounts?.business?.transactionWarning' in server and 'lastWarning:warnings' in server and 'lastErrorStage' in server and 'safeError(error)' in server, 'bank diagnostics: status records per-account warnings plus stage/code instead of collapsing every data failure into an opaque HTTP 400')

ok(launcher_path.exists() and all(b < 128 for b in launcher_path.read_bytes()), 'bank bridge startup: launcher is ASCII-only and cannot corrupt Hebrew Windows paths')
ok('ExpandEnvironmentStrings("%LOCALAPPDATA%")' in launcher and '%~dp0' not in launcher and 'shell.Run command, 0, False' in launcher, 'bank bridge startup: launcher resolves stable LOCALAPPDATA at runtime and starts hidden')
ok('%APPROOT%\\app' in installer and 'app-staging' in installer and 'npm ci' in installer and '--doctor' in installer, 'bank bridge install: runtime is staged and validated in a stable per-user location before activation')
ok('--stop-existing' in installer and "req.url==='/shutdown'" in server and 'stopVerifiedListener' in server, 'bank bridge upgrade: an existing verified bridge is stopped before replacing its runtime')
ok('node "%STAGING%\\server.mjs" --stop-existing' in installer and 'if exist "%APPDIR%" (' in installer and 'The previous Bank Bridge runtime could not be removed.' in installer, 'bank bridge upgrade: validated staging code performs shutdown and activation fails closed if old runtime remains locked')
ok('const BRIDGE_VERSION=21' in server and 'version:BRIDGE_VERSION' in server and 'Number(j.version)>=21' in installer and '/health' in installer, 'financial bridge install: installer verifies Bridge v21 after hidden startup')
ok('const CREDIT_BRIDGE_VERSION=20' in credit_controller and 'transactionDate:purchaseDate' in camoufox and 'transactionDate:tx.transactionDate||null' in lib and 'transactionDate:iso(txn.transactionDate)' in credit_feed, 'credit bridge v20: exact issuer purchase date is preserved as a separate optional field from installment and billing dates')
ok('camoufox-js@0.12.0' in installer and 'playwright-core@1.60.0' in installer and 'fingerprint-generator@2.1.86' in installer and 'CAMOUFOX_INSTALL_DIR=%APPROOT%\\camoufox' in installer and 'provision-camoufox.mjs' in installer and 'node provision-camoufox.mjs' in installer and 'CamoufoxFetcher' in camoufox_provisioner and 'camoufoxPath(false)' in camoufox_provisioner and 'installedVerStr()' in camoufox_provisioner and 'node_modules\\camoufox-js\\dist\\__main__.js fetch' not in installer and 'downloadMMDB' not in camoufox_provisioner and 'doctorCamoufox()' in server, 'Amex runtime install: only the required Camoufox browser is provisioned in stable LOCALAPPDATA; optional GeoIP cannot block installation, and a real browser launch is doctor-checked before activation')
ok('geoip:' not in camoufox and 'downloadMMDB' not in camoufox_provisioner, 'Amex Camoufox install: Netunim does not request GeoIP spoofing, so the optional GeoLite MMDB is not a runtime/install dependency')
ok('>> "%LOCALAPPDATA%\\NetunimKupaBankBridge\\bridge.log" 2>&1' in start_script, 'bank bridge startup: background output goes to a log instead of popup error windows')

ok('syncSharedChecksFromCloud({quiet:true,required:true})' in controller and 'sharedChecksObservedSequence()' in controller and 'snapshotSeq:observedSeq' in controller, 'bank snapshot integrity: remote balance uses existing synchronized check watermark before saving')
ok("source:'hapoalim'" in controller and 'commitBankSnapshot(business.balance' in controller, 'bank snapshot integrity: only the business Hapoalim balance enters through the same snapshot commit path as manual balance')
ok('return b===null?null:b+bankAdjustmentsTotalData(state)' in bank_model and 'bankCheckEffectsTotal' not in bank_model and 'bankDerivedCheckDeposits' not in bank_model, 'bank source of truth: check workflow events never alter the synchronized or manually captured bank balance')
ok('normalizeBankFeed' in controller and 'bankFeed:businessFeed' in controller and 'homeBankFeed:nextHomeFeed' in controller and 'feed:nextFeed' in controller and 'homeFeed:nextHomeFeed' in controller and 'n.bank.feed=normalizeBankFeed(n.bank.feed)' in normalization and 'n.bank.homeFeed=normalizeBankFeed(n.bank.homeFeed)' in normalization, 'bank feed persistence: business and home feeds are normalized separately while the business feed remains canonical for Kupa')
ok('bankSyncAt:nextSyncAt' in controller and 'n.bank.bankSyncAt=n.bank.feed?.syncedAt' in normalization, 'bank multi-computer schedule: last successful bank sync is derived from the shared canonical feed')
ok('bankAutoRefreshDue(lastSyncAt,now)' in controller and 'BANK_AUTO_INTERVAL_MS=24*60*60*1000' in client, 'bank auto refresh: due time is exactly 24h from the shared successful bank sync, not from a manual balance edit')
ok('markAutoAttempt' in controller and 'AUTO_RETRY_COOLDOWN_MS=60*60*1000' in client, 'bank auto refresh: failed background attempts are rate-limited locally')
ok("refreshBankBalance({interactive:false,auto:true})" in controller and "'refresh-bank-from-hapoalim':(element,event)=>{event?.preventDefault();event?.stopPropagation();refreshBankBalance({interactive:false,auto:false})}" in actions and "'open-bank-auth':(element,event)=>{event?.preventDefault();event?.stopPropagation();refreshBankBalance({interactive:true,auto:false})}" in actions, 'bank refresh modes: automatic/manual refresh are silent; visible authentication is explicit and toolbar buttons do not toggle the disclosure')
ok('INTERACTIVE_AUTH_TIMEOUT_MS=10*60*1000' in lib and 'SILENT_AUTH_TIMEOUT_MS=90*1000' in lib and 'waitForTerminalLoginResult' in server and 'enableHapoalimSessionAwareLogin' in server, 'bank authentication: both silent and interactive login wait for a terminal result with separate bounded timeouts')
ok('INTERACTIVE_BRIDGE_TIMEOUT_MS=15*60*1000' in client and 'timeoutMs:interactive?INTERACTIVE_BRIDGE_TIMEOUT_MS:180000' in client, 'bank timeouts: site request window outlives interactive MFA and silent staged API readiness')
ok('bridgeVersion:BRIDGE_VERSION' in server and 'const BANK_BRIDGE_VERSION=21' in controller and 'upgradeRequired=bridgeVersion<BANK_BRIDGE_VERSION' in controller, 'bank bridge upgrade handshake: bank UI requires v21 so failed-refresh timestamps survive reloads')

ok('BANK_FEED_VERSION=4' in feed and 'BANK_FEED_TRANSACTION_LIMIT=1000' in feed and 'balanceAfter' in feed and 'bankReference' in feed and 'checkItems' in feed and 'transactionWarning' in feed, 'bank shared contract: v4 feed keeps full thirty-day transactions plus structured verified cheque rows')
ok(all(x in view for x in ['id="bankBusinessBranchNumberInput"','id="bankBusinessAccountNumberInput"','id="bankHomeBranchNumberInput"','id="bankHomeAccountNumberInput"','select-bank-bridge-account','set-bank-account-view']), 'bank account UI: business/home branch and account are explicit, exact discovered accounts are selectable, and transaction view can switch roles')
ok("req.url==='/account-selection'" in server and "selectAccount({role='business',branchNumber,accountNumber})" in client and 'selectBankBridgeAccount(role,branchNumber,accountNumber)' in controller, 'bank account selection: a discovered branch/account updates only its business/home role without re-entering the bank password')
ok('lastErrorHttpStatus' in server and 'lastAvailableAccounts' in server and 'e.availableAccounts' in client, 'bank diagnostics: HTTP status and safe account choices survive the loopback error envelope instead of being hidden behind generic 400')
ok('lastErrorAt' in server and 'lastErrorAt:s.lastErrorAt||null' in controller and "title:'נכשל'" in view and 'syncTimeLabel(lastFailure)' in view, 'bank sync status: failed refresh time is persisted by Bridge v21 and the collapsed row shows only failed + timestamp')
ok("'set-bank-account-view':(element,event)=>{event?.preventDefault();event?.stopPropagation();setBankAccountView" in actions and 'syncBankAccountTabs' in view, 'bank account tabs: switching business/home inside the summary never toggles the synchronization disclosure')
ok('accounts:{business,home}' in server and 'fetchHapoalimAccountSnapshot(page,businessSelected,stableReady)' in server and 'fetchHapoalimAccountSnapshot(page,homeSelected,businessResult.ready)' in server and 'homeFailure=safeError' in server and 'accountFailures:{home:homeFailure}' in server and 'DUPLICATE_ACCOUNT_ROLE' in server, 'bank dual-account session: business is authoritative, home is fetched in the same authenticated session, and a home-only failure is isolated without blocking the business snapshot')
ok('businessBranchNumber' in server and 'businessAccountNumber' in server and 'homeBranchNumber' in server and 'homeAccountNumber' in server and 'legacySelector' in server, 'bank credential migration: legacy single-account selection is retained as business while home account fields are added explicitly')
ok('currentBalance:wholeMoney(numeric)' in controller and 'homeFeed:nextHomeFeed' in controller and 'return b===null?null:b+bankAdjustmentsTotalData(state)' in bank_model and 'homeFeed' not in bank_model, 'bank calculation boundary: home data is persisted for viewing but only business currentBalance can participate in Kupa bank totals')
ok('homeFailure?undefined:null' in controller and "message:homeFailure?'החשבון העסקי עודכן בהצלחה; החשבון הביתי לא עודכן ונשמר הנתון הביתי האחרון.'" in controller and 'lastWarningCode:homeFailure?.code' in controller and 'lastWarningStage:homeFailure?.stage' in controller and 'lastWarningHttpStatus:Number(homeFailure?.httpStatus)' in controller and 'lastWarningCode:homeFailure?.code' in server and "accountRole:meta.lastAccountRole==='home'" in server, 'bank partial-home resilience: a home-only failure preserves the previous home feed even before status resolves, still commits business data, and keeps role-aware corrective diagnostics')
ok('homeFeed:mergeValue' in sync_merge and 'homeFeed:mergeValuePreferLocal' in sync_merge and 'feed:mergeValue' in sync_merge, 'bank cloud merge: business and home bank feeds survive three-way synchronization independently')
ok('bankSyncHeadlineMarkup' in view and 'bank-transactions-table' in view and '<th>חובה</th><th>זכות</th><th>יתרה לאחר תנועה</th>' in view and 'balanceAfter' in view and 'יתרת עו״ש' in view and 'חשבון עסקי' in view and 'חשבון ביתי' in view, 'bank UI: compact dual-account tabs switch the displayed balance/feed and the bank-like table keeps authoritative per-transaction balances')
ok('bankChequeDetailsMarkup' in view and 'שיקים בהפקדה:' in view and 'מס׳ שיק' in view and 'אסמכתת הפקדה:' in view and 'bank-cheque-items' in view and 'transaction Status Code' not in view and 'מזהה סידורי בבנק:' not in view, 'bank cheque UI: only structured cheque-deposit rows/aggregate reference are shown; generic PFM fields and internal serials are hidden')
ok('<details class="bank-sync-settings">' in view and '<summary class="bank-sync-toolbar">' in view and '${bankAccountTabsMarkup()}' in view and 'id="bankSyncHeadline"' in view and 'bank-sync-disclosure-label' in view and "bridgeUi.busy?'מעדכן…':'רענן'" in view and 'רענן שני חשבונות' not in view and view.index('<button type="button" class="btn" data-action="open-bank-auth"')>view.index('<div class="bank-sync-settings-body">') and view.index('<div class="bank-transactions-region">')>view.index('</details>'), 'bank UI: account tabs + compact sync state + refresh share the collapsed row, while explicit bank authentication is visible only inside the opened sync panel')
ok('id="bankBridgePairForm"' in view and 'id="bankBridgeCredentialsForm"' in view and view.count('<form ')==2 and 'onsubmit=' not in view, 'bank credentials UI: token and bank credentials are two independent semantic forms with no inline CSP handler')
ok("addEventListener('submit',event=>event.preventDefault())" in view and "'save-bank-bridge-token'" in actions and 'saveBankBridgeToken:(...args)=>domainsBankController.saveBankBridgeToken' in main, 'bank forms: submit suppression and local Bridge pairing are wired through JavaScript/delegated actions')
ok('id="bankPasswordInput"' in view and 'autocomplete="current-password"' in view, 'bank credentials UI: password control has a semantic credentials-form owner')
ok('localStorage.setItem(TOKEN_KEY' in client and 'localStorage.setItem(AUTO_KEY' in client and 'localStorage.setItem(AUTO_ATTEMPT_KEY' in client and 'localStorage.setItem(userCode' not in client and 'localStorage.setItem(password' not in client, 'bank credentials security: browser persistence is limited to local bridge token/refresh preferences, never Hapoalim credentials')
ok('http://127.0.0.1:8765' in headers and "connect-src 'self'" in headers, 'bank CSP: only intended loopback bridge is added to connect-src')
ok('./assets/js/domains/bank/bridge.js' in worker and './assets/js/domains/bank/controller.js' in worker and './assets/js/domains/bank/feed.js' in worker, 'bank PWA: bridge/controller/canonical feed modules are part of deterministic app shell')

# Credit-card sync contracts: credentials remain local/encrypted, multiple identities per issuer are supported,
# synchronized issuer data is canonical, manual rows are additive only, and only normalized finance data enters Kupa state/cloud.
ok("const CREDIT_PROFILES_FILE=path.join(APP_DIR,'credit-card-profiles.dpapi')" in server and 'protectText(JSON.stringify' in server and 'readCreditProfiles' in server and 'writeCreditProfiles' in server, 'credit security: issuer credentials are stored only in the local DPAPI vault')
ok("req.url==='/credit/status'" in server and "req.url==='/credit/profiles'" in server and "req.url==='/credit/reset'" in server and "req.url==='/credit/sync'" in server, 'credit bridge API: local profile management/status/reset/sync routes are authenticated loopback endpoints')
ok("const map={visaCal:CompanyTypes.visaCal,max:CompanyTypes.max,isracard:CompanyTypes.isracard,amex:CompanyTypes.amex}" in server and 'CompanyTypes?.visaCal' in server and 'CompanyTypes?.max' in server and 'CompanyTypes?.isracard' in server and 'CompanyTypes?.amex' in server, 'credit providers: pinned scraper integration is explicit for Cal, MAX, Isracard and Amex')
ok("amex:{baseUrl:'https://he.americanexpress.co.il',companyCode:'77'}" in camoufox and "isracard:{baseUrl:'https://digital.isracard.co.il',companyCode:'11'}" in camoufox and "reqName=ValidateIdData" in camoufox and "reqName=performLogonI" in camoufox, 'Amex Camoufox adapter: provider URLs/company codes and the fixed-password ValidateIdData/performLogonI protocol match the upstream scraper')
ok('camoufoxLaunchOptions' in camoufox and "os:'windows'" in camoufox and 'screen:{...CAMOUFOX_SCREEN}' in camoufox and 'openQualifiedLoginSession' in camoufox and 'createSaneCamoufoxFingerprint' not in camoufox and 'sanitizeCamoufoxFingerprint' not in camoufox and "fingerprint,i_know_what_im_doing:true" not in camoufox and 'detector-dom.min.js' in camoufox, 'Amex WAF root fix: Camoufox owns BrowserForge generation through supported OS/screen constraints, while the anonymous issuer response—not collector sentinel fields—qualifies the session before credentials')
ok('classifyCamoufoxProviderResponse' in camoufox and "'CREDIT_LOGIN_HTML_RESPONSE'" in camoufox and "'CREDIT_DATA_HTML_RESPONSE'" in camoufox and "'CREDIT_AUTOMATION_BLOCKED'" in camoufox and "'CREDIT_PROVIDER_RATE_LIMITED'" in camoufox, 'Amex WAF diagnostics: 403 automation blocks and 429 rate limits are distinguished without exposing issuer HTML')
ok('isCamoufoxRetryableNativeFailure(failure)' in server and "profile.provider==='isracard'" in server and 'CREDIT_INVALID_PASSWORD' in camoufox, 'Isracard fallback: only WAF/HTML native failures may switch browser engines; invalid credentials never trigger a duplicate login attempt')
ok('JSON.stringify(data||{})' in camoufox and 'result?.text' in camoufox and 'request' not in camoufox.split('function pageFetchJson',1)[1].split('function accountsUrl',1)[0].lower(), 'Amex diagnostics security: fetch errors retain status/stage only and never embed credential-bearing request bodies or raw HTML')
ok("mastercard" not in lib.lower() or "creditprovidersupported('mastercard')" not in lib.lower(), 'credit providers: Mastercard is not invented as a separate issuer login')
ok("visaCal:{label:'כאל',credentialFields:['username','password']}" in lib and "max:{label:'MAX',credentialFields:['username','password']}" in lib and "isracard:{label:'ישראכרט',credentialFields:['id','card6Digits','password']}" in lib and "amex:{label:'American Express',credentialFields:['id','card6Digits','password']}" in lib, 'credit credentials: issuer-specific required login fields match the pinned scraper contract, including separate Amex identity')
ok('futureMonthsToScrape:CREDIT_FUTURE_MONTHS' in server and 'combineInstallments:false' in server and 'additionalTransactionInformation:false' in server and 'includeRawTransaction:false' in server, 'credit scraping: future issuer charge dates are requested without raw/sensitive transaction payloads')
ok('for(const profile of enabled)' in server and 'await scrapeCreditProfile(profile,{interactive})' in server, 'credit multi-profile: same-issuer identities run sequentially to avoid cross-login races')
ok('profileId:requestedId||randomUUID()' in server and 'normalizeCreditProfileInput({...body' in server, 'credit multi-computer: a cloud profile id can be bound to local credentials on another computer')
ok('creditProfilesShareLoginIdentity' in lib and 'CREDIT_DUPLICATE_LOGIN' in server and 'חיבור אחד מחזיר את כל הכרטיסים' in server, 'credit identity model: one local login per owner/provider is enforced so one issuer login cannot be duplicated once per discovered card')
ok("req.url==='/credit/reset'" in server and 'resetCreditProfiles()' in server and 'resetCreditProfiles(){return request' in credit_client and 'resetCreditSync' in credit_controller and "'reset-credit-sync'" in actions and 'איפוס מלא' in credit_view, 'credit full reset: encrypted local profiles and synchronized Kupa/cloud state have one explicit start-over workflow')
ok('CREDIT_LOGIN_HTML_RESPONSE' in lib and 'reqName=ValidateIdData' in lib and 'creditThrownScrapeFailure' in server and 'safeCreditErrorMessage' in credit_feed and 'Sisma' in credit_feed, 'credit diagnostics security: issuer HTML failures identify the safe pre-password stage without persisting credential-bearing scraper payloads')
ok('CREDIT_HISTORY_DAYS=130' in lib and 'futureMonthsToScrape:CREDIT_FUTURE_MONTHS' in server and 'combineInstallments:false' in server, 'credit scrape horizon: issuer refresh keeps 130 historical days for three complete prior calendar months and requests twelve future months without combining installments')
ok('creditErrors:Array.isArray(error?.creditErrors)' in server and 'if(!result.profiles.length&&result.errors.length)' in server, 'credit diagnostics: per-profile failures survive the loopback error envelope')
ok("stage:String(error?.stage||'').slice(0,80)" in server and "httpStatus:Number(error?.httpStatus)||0" in server and "stage:text(e?.stage||'',80)" in credit_feed and "httpStatus:Math.max(0,Math.trunc(Number(e?.httpStatus)||0))" in credit_feed, 'credit diagnostics: safe issuer stage and HTTP status survive persistence so 403 and 429 remain distinguishable')
ok('mergeCreditSyncResult' in credit_controller and 'Array.isArray(e?.creditErrors)' in credit_controller and "profiles:[],errors:e.creditErrors" in credit_controller, 'credit partial failure: failed refreshes preserve prior successful profile data and persist actionable diagnostics')
ok("mode:'synced'" in credit_feed and "return [...syncedInstallmentsData(state),...(Array.isArray(state?.credits)?state.credits:[]).flatMap(creditSchedule)]" in credit_model and 'setCreditSyncMode' not in credit_controller and 'set-credit-sync-mode' not in actions, 'credit source model: synchronized issuer rows are always canonical and post-migration manual rows are additive only')
ok('creditSyncSourceVersion<CREDIT_SYNC_VERSION?[]' in normalization and 'CREDIT_SYNC_VERSION=3' in credit_feed, 'credit migration: historical manual credit rows are removed exactly once on the v2-to-v3 cutover')
ok('syncedCreditSeries' in credit_feed and 'creditMonthlyDetailData' in credit_model and 'עסקאות ותשלומים' in credit_view and 'תאריך עסקה' in credit_view and 'חיוב בחודש' in credit_view and 'אופק חלקי' in credit_view, 'credit detail UI: synchronized purchases render actual known installment charges by selected month without inventing missing future installments')
ok('CREDIT_DETAIL_HISTORY_MONTHS=3' in credit_model and 'creditMonthlyDetailData' in credit_model and 'credit-detail-month-tabs' in credit_view and 'credit-detail-month-tab' in credit_view and 'month.items.some(item=>item.date>=detailToday)' in credit_view and 'היסטוריית עסקאות שהסתיימו' not in credit_view and 'עסקאות ותשלומים פעילים' not in credit_view and '.credit-detail-month-tabs' in app_css, 'credit detail lifecycle: active and completed transactions share one month browser, default to the nearest upcoming actual charge, keep three prior calendar months and expose all actually known future billing months')
ok('availableCredit:directAvailable??maxAvailable' in lib and "provider==='max'" in lib and 'cardFrame:finite(account.cardFrame)' in credit_feed and 'creditFrameMarkup' in credit_view, 'credit frame availability: MAX exact OpenToBuy and issuer limits survive normalization without inventing unavailable values for other issuers')
ok('kupaSyncedInstallments' in orders_readout and 'kupaBusinessInstallments' in orders_readout and "row.account==='עסקי'" in orders_readout and 'creditSync' in orders_readout and 'checkEffects' not in orders_readout, 'Orders Kupa readout: synchronized credit remains visible but only business-classified credit enters the cross-app Kupa net calculation')
ok('סיכום חודשי לפי כרטיס' not in credit_view and 'סה״כ לכרטיס' not in credit_view and 'creditMonthlySummaryMarkup' not in credit_view and 'credit-month-summary' not in app_css, 'credit summary UI: redundant monthly-by-card summary is removed because the unified month browser already exposes monthly totals and transaction detail')
ok('creditCardMappingKey(profile.profileId,account.accountNumber)' in credit_view and 'set-credit-card-included' in credit_view and 'set-credit-card-hidden' in credit_view and "option ${accountClass==='עסקי'" in credit_view, 'credit classification: every discovered card has independent include/exclude, hide/show and business/home mapping')
ok("'credit-account-filter'" in actions and "'credit-provider-filter'" in actions and "'credit-card-filter'" in actions and "'credit-owner-filter'" not in actions and "creditAccountFilter:'all'" in contexts and "creditOwnerFilter" not in contexts and "creditProviderFilter:'all'" in contexts and "creditCardFilter:'all'" in contexts and 'creditOwnerFilter' not in credit_view and 'כל בעלי הכרטיסים' not in credit_view and 'filterMatch(ui,row)' in credit_view, 'credit filters: the page exposes only business/home, issuer and individual-card dimensions; the removed owner filter leaves no stale UI state or action')
ok('businessInstallmentsData(state)' in bank_model and 'nextBusinessCreditCycleData(state' in bank_model and "filter(x=>x.account==='עסקי')" in credit_model, 'credit cash-flow ownership: included home cards stay reportable but only business-classified credit reaches bank/Kupa calculations')
ok('credit-forecast-month' in credit_view and 'credit-forecast-row' in credit_view and 'credit-forecast-breakdown' in credit_view and 'creditForecastColumns' in credit_view and 'Math.ceil(months.length/2)' in credit_view and credit_view.index('עסקאות ותשלומים') < credit_view.index("${summary.hasData?renderSyncedAccounts(summary):''}"), 'credit UI hierarchy: balanced two-column expandable monthly forecast leads into the unified monthly transaction browser, with live issuer data last and no duplicate monthly summary')
ok('primaryCardFilterMatch' in credit_view and 'includedCards.filter(card=>primaryCardFilterMatch(ui,card))' in credit_view and "const provider=ui.creditProviderFilter||'all'" in credit_view and "if(provider==='all')return ''" in credit_view and 'card.provider===provider' in credit_view and "ui.creditProviderFilter==='all'||(ui.creditCardFilter!=='all'&&!availableCardKeys.has(ui.creditCardFilter))" in credit_view, 'credit filter controls: business/home constrains issuer availability, while individual card controls stay hidden until one issuer is selected and stale card selections reset safely')
ok('creditMonthlyDetailRow' in credit_view and 'installmentCell' in credit_view and 'Number(item.totalParts)>1' in credit_view and '<span class="muted">מהחברה</span>' not in credit_view and 'syncedBulkPlaceholder' in credit_view and "ui.bulkCollection==='credits'?'<td class=\"bulk-check-col\"></td>':''" in credit_view and 'credit-detail-col-card' in credit_view and 'credit-detail-description' in credit_view and '.credit-detail-table{width:100%;min-width:0;table-layout:fixed}' in app_css and '.credit-detail-section table{min-width:1040px}' not in app_css, 'credit detail polish: synchronized rows match the conditional bulk-selection header, columns stay semantically aligned, and fixed compact sizing avoids the old horizontal-scroll layout')
ok("'credit-detail-focus'" in actions and "'credit-detail-month'" in actions and "'clear-credit-detail-focus'" in actions and "creditDetailFocus:null" in contexts and 'creditMonthlyDetailData' in credit_view and 'rowCardKey(item)===detailFocus.cardKey' in credit_view and 'scrollIntoView' in actions and 'data-click-arg1' in credit_view and 'credit-active-transactions' in credit_view, 'credit forecast drilldown: month/card focus stays transient while the unified month browser can switch months independently of the primary card filter')
ok('אותו מבנה קומפקטי של לוח הבקרה' not in credit_view and 'המסננים למעלה חלים גם כאן' not in credit_view and 'סה״כ במסנן' not in credit_view and 'סה״כ: ${money(future.reduce' in credit_view and 'credit-filter-primary' in credit_view, 'credit toolbar polish: redundant helper copy is removed and range/account filters share the primary row with concise totals')
ok('grid-template-columns:210px minmax(0,1fr)' in app_css and '.credit-filter-primary{display:flex' in app_css and '.credit-filter-selects,.credit-filter-stats{display:flex;align-items:center;gap:8px;flex-wrap:nowrap}' in app_css and '.credit-forecast-column{flex:1 1 0' in app_css and '.credit-forecast-list{flex-direction:column}' in app_css and '.credit-forecast-card-button' in app_css and '.credit-detail-focus' in app_css, 'credit layout: desktop navigation is narrower, top filters/totals align in one row, forecast columns stay balanced, and month-card drilldown has dedicated affordance')
ok("CREDIT_AUTO_INTERVAL_MS=24*60*60*1000" in credit_controller and 'maybeAutoRefreshCreditSync' in credit_controller and 'maybeAutoRefreshCreditSync()' in navigation, 'credit auto refresh: synchronized issuer data can refresh once per shared successful day while browsing Kupa')
ok("localStorage.setItem(CREDIT_AUTO_KEY" in credit_controller and 'username' not in credit_feed and 'password' not in credit_feed, 'credit credentials boundary: browser/cloud feed contains preferences and normalized finance data, never issuer usernames/passwords')
ok("creditSync:{version:3,mode:'synced'" in contexts and 'n.creditSync=normalizeCreditSync(n.creditSync)' in normalization, 'credit state: new state starts directly in the synchronized-primary v3 model')
ok('isShekelTransaction' in credit_feed and 'foreign-currency rows' in credit_feed.lower(), 'credit forecast safety: non-ILS charged amounts do not silently enter shekel cash-flow totals')
ok('./assets/js/domains/credit/sync-feed.js' in worker and './assets/js/domains/credit/controller.js' in worker, 'credit PWA: synchronization modules are part of the deterministic app shell')


ok("/rest/v1/rpc/save_kupa_document" in orders_cloud_transport and 'p_expected_revision:expected' in orders_cloud_transport, 'Orders finance ownership: updates reuse the canonical Kupa revision-checked RPC instead of creating a second finance document')
ok('readKupaReadOnlyCloud()' in orders_finance_controller and 'revisionConflict(result)' in orders_finance_controller and 'for(let attempt=0;attempt<3;attempt++)' in orders_finance_controller, 'Orders finance concurrency: bank/credit mutations re-read and retry on Kupa revision conflicts instead of overwriting unrelated changes')
ok('currentBalance:kupaWholeMoney(business.balance)' in orders_finance_controller and 'feed:businessFeed' in orders_finance_controller and 'homeFeed:nextHomeFeed' in orders_finance_controller, 'Orders bank sync: business remains authoritative while business/home feeds are stored in the same canonical Kupa bank object')
ok('mergeCreditSyncResult(kupa.creditSync,result)' in orders_finance_controller and 'cardMappings' in (ROOT/'netunim-orders/site/assets/js/domains/finance/credit-feed.js').read_text(encoding='utf-8'), 'Orders credit sync: issuer refresh preserves existing Kupa card mappings and prior successful profiles')
ok('FINANCE_AUTO_INTERVAL_MS=24*60*60*1000' in orders_finance_bridge and 'await refreshKupaReadout({force:true,renderIfChanged:true})' in orders_finance_controller and 'financeRefreshDue(bankLastSyncAt(checksSession.kupaCloudReadState))' in orders_finance_controller and 'financeRefreshDue(creditLastSyncAt(checksSession.kupaCloudReadState))' in orders_finance_controller, 'Orders finance auto refresh: the shared Kupa cloud timestamps are re-read before each daily scrape so a sync from either app suppresses the other')
ok("const TOKEN_KEY='netunim_kupa_bank_bridge_token_v1'" in orders_finance_bridge and 'bridgeTokenConfigured' in orders_finance_controller and 'p_state' not in orders_finance_bridge, 'Orders bridge security: the device pairing token remains browser-local and is never copied into Kupa/Supabase state')
ok('http://127.0.0.1:8765' in orders_headers, 'Orders CSP: only the intended loopback Bank Bridge endpoint is added to connect-src')
ok('./assets/js/domains/finance/controller.js' in orders_worker and './assets/js/domains/finance/bridge.js' in orders_worker and './assets/js/domains/finance/credit-feed.js' in orders_worker, 'Orders finance PWA: cross-app synchronization modules are part of the deterministic offline shell')
ok('startFinanceAutoSync();' in orders_lifecycle, 'Orders lifecycle: finance auto scheduling starts only after normal Orders boot/cloud recovery completes')
ok('refreshFinanceCloudSnapshot' in main and "readSupabaseDocument()" in main and 'syncDocument.cloudPoll()' in main, 'Kupa cross-app freshness: automatic finance refresh has a direct shared-cloud preflight instead of waiting for the 12-second poll')
ok('refreshFinanceCloudSnapshot' in controller and 'bankAutoRefreshDue(sharedBankLastSyncAt(latest.state||model.state))' in controller, 'Kupa bank cross-app freshness: a fresh Orders bank snapshot suppresses the local automatic Bridge scrape')
ok('refreshFinanceCloudSnapshot' in credit_controller and "due(latest.state?.creditSync?.syncedAt)" in credit_controller and 'retryWait=autoAttemptDelayMs()' in credit_controller, 'Kupa credit cross-app freshness: a fresh Orders credit sync suppresses the local scrape and failed attempts do not wake every second')
ok('bankAttemptDelayMs' in orders_finance_bridge and 'creditAttemptDelayMs' in orders_finance_bridge and 'retryWait+250' in orders_finance_controller, 'Orders finance scheduler: the one-hour failure cooldown is honored by timers instead of polling every second')

if errors:
    print('\nERRORS',len(errors))
    for item in errors: print('-',item)
    raise SystemExit(1)
print('\nALL BANK BRIDGE CONTRACTS PASSED')
