import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {
  CREDIT_CONNECTOR_CONTRACT_VERSION,
  MAX_PROVIDER_SCHEMA_VERSION,
  VISA_CAL_PROVIDER_SCHEMA_VERSION,
  VisaCalAdapter,
  applyVisaCalLoginNavigationPolicy,
  MaxAdapter,
  buildCreditMonthPlan,
  classifyCreditHttpResponse,
  createCreditProviderAdapter,
  creditSyncScope,
  extractMaxTransactionCandidates,
  normalizeMaxRawTransaction,
  parseRetryAfter,
  parseVisaCalFrame,
  prepareVisaCalBrowserIdentity,
  parseVisaCalMonthData,
  postVisaCalJson,
  isVisaCalInvalidPasswordErrorUrl,
  visaCalHasAuthenticatedSessionState,
} from '../netunim-kupa/bank-bridge/credit-adapters.mjs';
import {launchCamoufox,parseIsracardFamilyAccountsResponse,parseIsracardFamilyCardListBalances,parseIsracardFamilyTransactionsResponse} from '../netunim-kupa/bank-bridge/isracard-camoufox.mjs';
import {creditIdentityDirectory,deleteCreditIdentity} from '../netunim-kupa/bank-bridge/credit-identity.mjs';
import {createCreditDiagnosticLog,responseShapeFingerprint,safeCreditResponseShape,sanitizeCreditDiagnosticEvent} from '../netunim-kupa/bank-bridge/credit-diagnostics.mjs';
import {buildCreditDataDiagnosticPayload,maxRawTransactionTime} from '../netunim-kupa/bank-bridge/credit-data-diagnostics.mjs';
import {AMEX_DIGITAL_V3_SCHEMA_VERSION,buildAmexDigitalV3LogonRequest,classifyAmexDigitalV3LogonResult,normalizeAmexDigitalV3ApprovedTransaction,normalizeAmexDigitalV3Voucher,parseAmexDigitalV3Cards,prepareAmexDigitalV3Page} from '../netunim-kupa/bank-bridge/amex-digitalv3.mjs';
import {ISRACARD_DIGITAL_V3_SCHEMA_VERSION,normalizeIsracardDigitalV3ApprovedTransaction,normalizeIsracardDigitalV3Voucher,parseIsracardDigitalV3Cards} from '../netunim-kupa/bank-bridge/isracard-digitalv3.mjs';
import {filterExcludedGroupCards,isApprovedTransactionSettled,preserveInstalledChromiumIdentity,unsettledApprovedTransactions} from '../netunim-kupa/bank-bridge/isracard-group-utils.mjs';

assert.equal(CREDIT_CONNECTOR_CONTRACT_VERSION,2);

const settledApproval={purchaseDate:'07/09/2026',businessName:' בית עסק ',originalAmount:75,currencyIso:'ILS'},settledVoucher={purchaseDate:'07/09/2026',businessName:'בית עסק',originalAmount:75,originalCurrencyIso:'ILS'};
assert.equal(isApprovedTransactionSettled(settledApproval,[settledVoucher]),true,'DigitalV3 settlement matching uses the upstream PR #1159 purchase-date/amount/currency/merchant contract');
assert.deepEqual(unsettledApprovedTransactions([settledApproval,{...settledApproval,businessName:'עסק אחר'}],[],[{immediateVouchersCurrencyDate:[settledVoucher]}]).map(row=>row.businessName),['עסק אחר'],'immediate-debit vouchers suppress the same pending approval just like statement vouchers');
const excludedSeen=[];assert.deepEqual(filterExcludedGroupCards([{cardSuffix:'1111'},{cardSuffix:'2222'}],['1111'],suffix=>excludedSeen.push(suffix)).map(row=>row.cardSuffix),['2222']);assert.deepEqual(excludedSeen,['1111'],'excluded Isracard-family cards are removed immediately after discovery, before per-card data calls');

const amexMonth=new Date('2026-12-01T00:00:00.000Z');
assert.deepEqual(parseIsracardFamilyAccountsResponse({Header:{Status:'7'}},amexMonth),[],'Amex DashboardMonth non-success is an upstream-compatible empty month, not a false provider failure');
assert.deepEqual(parseIsracardFamilyTransactionsResponse({Header:{Status:'7'}},[],new Date('2026-09-01T00:00:00.000Z'),amexMonth),{},'Amex CardsTransactionsList non-success is an upstream-compatible empty month');
assert.throws(()=>parseIsracardFamilyAccountsResponse({Header:{Status:'1'},DashboardMonthBean:{}},amexMonth),error=>error.code==='CREDIT_PROVIDER_SCHEMA_ERROR'&&error.stage==='DashboardMonth 2026-12','a Status=1 DashboardMonth still requires the documented cardsCharges schema');
assert.throws(()=>parseIsracardFamilyTransactionsResponse({Header:{Status:'1'},CardsTransactionsListBean:{Index1:{CurrentCardTransactions:[{txnIsrael:[{fullPurchaseDate:'01/12/2026'}]}]}}},[],new Date('2026-09-01T00:00:00.000Z'),amexMonth),error=>error.code==='CREDIT_PROVIDER_SCHEMA_ERROR'&&error.stage==='CardsTransactionsList 2026-12','transactions without a safe card-index mapping cannot be silently discarded');
const amexFrames=parseIsracardFamilyCardListBalances('עבור כרטיס שמסתיים ב7392\nניצלת עד כה 9,564.99 מתוך מסגרת האשראי 15,500 נכון לתאריך 10/08/2026',new Date('2026-09-03T00:00:00Z'));
assert.deepEqual(amexFrames.get('7392'),{balance:-9564.99,balanceDate:'2026-08-10T00:00:00',cardFrame:15500},'Camoufox parses the same Amex balance/frame semantics introduced upstream in israeli-bank-scrapers 6.10.0');
const isracardFrames=parseIsracardFamilyCardListBalances('מסטרקארד\n7392\n₪9,564.99 לחיוב ב-10.09\nמסגרת: ₪15,500\nנותר לניצול: ₪5,935.01\n1234\nמסגרת: ₪5,000\nנותר לניצול: ₪4,328.00',new Date('2026-09-03T00:00:00Z'));
assert.deepEqual(isracardFrames.get('7392'),{balance:-9564.99,balanceDate:'2026-09-10T00:00:00',cardFrame:15500});
assert.deepEqual(isracardFrames.get('1234'),{balance:-672,balanceDate:'2026-09-10T00:00:00',cardFrame:5000},'a single Isracard billing date is safely shared with an active card whose block omits it');
const cancelledFrame=parseIsracardFamilyCardListBalances('7392 מבוטל\nמסגרת: ₪0\nנותר לניצול: ₪0.00',new Date('2026-09-03T00:00:00Z')).get('7392');
assert.deepEqual(cancelledFrame,{balance:0,cardFrame:0},'zero-frame cancelled cards never inherit an unrelated billing date');
const fixedNow=new Date('2026-09-03T06:00:00.000Z'),profile={profileId:'cal-profile',provider:'visaCal',label:'כאל בדיקה',credentials:{username:'local-user',password:'never-log-me'}};
const plan=buildCreditMonthPlan({startDate:new Date('2026-05-01T00:00:00Z'),futureMonths:12,now:fixedNow});
assert.equal(plan.at(-1).month,'2027-09','the connector keeps the full +12-month issuer horizon');
assert.equal(plan.find(row=>row.month==='2026-10').tier,'core','the nearest future month is part of required core coverage');
assert.equal(plan.find(row=>row.month==='2026-11').tier,'forecast','later issuer months are forecast enrichment');
const quickScope=creditSyncScope({syncMode:'quick',now:fixedNow}),forecastScope=creditSyncScope({syncMode:'forecast',now:fixedNow}),recoveryScope=creditSyncScope({syncMode:'recovery',now:fixedNow});
assert.equal(quickScope.startDate.toISOString().slice(0,10),'2026-08-04','quick scope reaches 30 days back');assert.equal(quickScope.futureMonths,1,'quick scope reaches one month forward');
assert.equal(forecastScope.startDate.toISOString().slice(0,10),'2026-08-04','forecast scope also rechecks the recent 30 days');assert.equal(forecastScope.futureMonths,12,'forecast scope reaches twelve months forward');
assert.equal(recoveryScope.startDate.toISOString().slice(0,10),'2026-04-26','recovery scope preserves the 130-day history window');assert.equal(recoveryScope.futureMonths,12,'recovery also rebuilds the twelve-month forecast');
assert.equal(creditSyncScope({syncMode:'daily',now:fixedNow}).syncMode,'quick','legacy daily requests remain backwards compatible');assert.equal(creditSyncScope({syncMode:'full',now:fixedNow}).syncMode,'recovery','legacy full requests keep their old heavy recovery meaning');

const encodedDigitalCards=JSON.stringify([{cardSuffix:'7392',companyCode:'11',isActive:true,isBlock:false},{cardSuffix:'6774',companyCode:'77',isActive:true,isBlock:false}]);
assert.deepEqual(parseIsracardDigitalV3Cards({isSuccess:true,data:{cardsList:encodedDigitalCards}}).map(card=>card.cardSuffix),['7392','6774'],'Isracard DigitalV3 accepts the current production cardsList contract when the provider returns the list as a JSON-encoded string');
assert.deepEqual(parseAmexDigitalV3Cards({isSuccess:true,data:{cardsList:encodedDigitalCards}}).map(card=>card.companyCode),['11','77'],'Amex DigitalV3 accepts the same current string-encoded cardsList contract and preserves each card companyCode for per-card transaction requests');
assert.throws(()=>parseIsracardDigitalV3Cards({isSuccess:true,data:{cardsList:'{broken'}}),error=>error.code==='CREDIT_PROVIDER_SCHEMA_ERROR'&&error.stage==='CardList','malformed string-encoded cardsList fails closed instead of silently losing cards');

function response(body,{status=200,headers={}}={}){return {status,headers:{get:name=>headers[String(name).toLowerCase()]||null},text:async()=>typeof body==='string'?body:JSON.stringify(body)}}
function transaction(card,month){return {trnIntId:`${card}-${month}`,trnTypeCode:'5',trnPurchaseDate:`${month}-02T00:00:00.000Z`,debCrdDate:`${month}-10T00:00:00.000Z`,trnAmt:25,amtBeforeConvAndIndex:25,trnCurrencySymbol:'₪',debCrdCurrencySymbol:'₪',merchantName:'fixture merchant',transTypeCommentDetails:''}}
function calMonth(card,month){return {statusCode:1,result:{bankAccounts:[{debitDates:[{transactions:[transaction(card,month)]}],immidiateDebits:{debitDays:[]}}]}}}
function fakeScraper(overrides={}){const calls={initialize:0,login:0,cards:0,auth:0,terminate:0},identity=chromiumIdentityFixture();return {calls,identityState:identity.state,scraper:{page:identity.page,getLoginOptions:()=>({loginUrl:'https://www.cal-online.co.il/',fields:[],submitButtonSelector:'button',possibleResults:{}}),initialize:async()=>{calls.initialize++},login:async()=>{calls.login++;return {success:true}},getCards:async()=>{calls.cards++;return [{cardUniqueId:'card-a',last4Digits:'1111'},{cardUniqueId:'card-b',last4Digits:'2222'}]},getAuthorizationHeader:async()=>{calls.auth++;return 'CALAuthScheme safe-test-token'},getXSiteId:async()=> 'site-id',terminate:async()=>{calls.terminate++},...overrides}}}
function fetchFixture({failureMonth='',failureCard='',failureKind='provider',framesBody=null,pendingBody=null}={}){return async(url,options)=>{const body=JSON.parse(options.body);if(url.includes('/Frames/'))return response(framesBody??{result:{calIssuedCards:{cardLevelFrames:[{cardUniqueId:body.cardsForFrameData[0].cardUniqueId,nextTotalDebit:100,nextDebitDate:'2026-09-10'}],frameLimitForCardAmount:10000}}});if(url.includes('/approvals/'))return response(pendingBody??{statusCode:96});const month=`${body.year}-${String(body.month).padStart(2,'0')}`,card=body.cardUniqueId;if(month===failureMonth&&card===failureCard){if(failureKind==='schema')return response({statusCode:1,result:{changed:true}});if(failureKind==='html')return response('<!doctype html><html>maintenance</html>');return response({statusCode:9,title:'temporary issuer failure'})}return response(calMonth(card,month))}}
function adapterFor(scraper,fetchImpl,syncMode='recovery',options={}){return new VisaCalAdapter({profile,CompanyTypes:{visaCal:'visaCal'},createScraper:()=>scraper,browserPath:'browser.exe',fetchImpl,requestDelayMs:0,now:()=>new Date(fixedNow),syncMode,...options})}

const calApiUrl='https://api.cal-online.co.il/Frames/api/Frames/GetFrameStatus';
let browserApiArgs=null,browserApiNodeCalls=0;const browserApiResult=await postVisaCalJson({evaluate:async(_fn,url,data,headers,timeoutMs)=>{browserApiArgs={url,data,headers,timeoutMs};return {status:200,body:'{"statusCode":1,"result":{"ok":true}}',retryAfter:''}}},async()=>{browserApiNodeCalls++;throw new Error('node should not run')},calApiUrl,{x:1},{browserHeaders:{Authorization:'CALAuthScheme test','X-Site-Id':'site'},nodeHeaders:{Authorization:'CALAuthScheme test'},stage:'Frames'});
assert.equal(browserApiResult.transport,'browser','Cal data API prefers the authenticated browser network path from PR #1193');assert.equal(browserApiNodeCalls,0,'a browser HTTP response never triggers the Node fallback');assert.deepEqual(browserApiArgs.headers,{Authorization:'CALAuthScheme test','X-Site-Id':'site'},'browser API calls pass only application auth headers and let Chromium own Origin/Referer/browser identity');
let blockedNodeCalls=0;await assert.rejects(()=>postVisaCalJson({evaluate:async()=>({status:403,body:'<html>Request Rejected</html>',retryAfter:''})},async()=>{blockedNodeCalls++;return response({statusCode:1})},calApiUrl,{}, {stage:'Frames'}),error=>error.code==='CREDIT_AUTOMATION_BLOCKED'&&error.transport==='browser','a real browser HTTP rejection is authoritative and is not hidden by a second network path');assert.equal(blockedNodeCalls,0);
let fallbackCalls=0,fallbackHeaders=null;const fallbackResult=await postVisaCalJson({evaluate:async()=>{throw new TypeError('Failed to fetch')}},async(_url,options)=>{fallbackCalls++;fallbackHeaders=options.headers;return response({statusCode:1})},calApiUrl,{x:2},{browserHeaders:{Authorization:'browser-token'},nodeHeaders:{Authorization:'node-token','User-Agent':'native-browser'},stage:'Frames'});assert.equal(fallbackResult.transport,'node-fallback');assert.equal(fallbackCalls,1,'Cal performs exactly one bounded Node fallback only when the in-page request produced no HTTP response');assert.equal(fallbackHeaders.Accept,'application/json');assert.equal(fallbackHeaders.Authorization,'node-token');assert.equal(fallbackHeaders['User-Agent'],'native-browser');
await assert.rejects(()=>postVisaCalJson({evaluate:async()=>({status:200,body:'<html>Request Rejected</html>',retryAfter:''})},async()=>response({statusCode:1}),calApiUrl,{}, {stage:'Frames'}),error=>error.code==='CREDIT_PROVIDER_RESPONSE_NOT_JSON'&&error.transport==='browser','Cal HTML block pages are classified at the browser response boundary instead of surfacing an opaque JSON parse error');
const invalidPasswordUrl=message=>'https://digital-web.cal-online.co.il/calconnect/error;headers=%5Bobject%20Object%5D;status=400;statusText=OK;url=https:%2F%2Fconnect.cal-online.co.il%2Fcol-rest%2Fcalconnect%2Fauthentication%2Flogin;ok=false;name=HttpErrorResponse;message=Http%20failure%20response;error='+encodeURIComponent(message);
assert.equal(isVisaCalInvalidPasswordErrorUrl(invalidPasswordUrl('שם המשתמש או הסיסמה שהוזנו שגויים')),true,'Cal recognizes the current iframe-local invalid-password route from PR #1184');assert.equal(isVisaCalInvalidPasswordErrorUrl(invalidPasswordUrl('שגיאה כללית')),false);assert.equal(isVisaCalInvalidPasswordErrorUrl('https://digital-web.cal-online.co.il/calconnect/error;error=%E0%A4%A'),false,'malformed URL escaping cannot break login classification');

const dailyFixture=fakeScraper(),dailyRequests=[],dailyFetch=fetchFixture(),dailyResult=await adapterFor(dailyFixture.scraper,async(url,options)=>{dailyRequests.push({url,body:JSON.parse(options.body),headers:options.headers});return dailyFetch(url,options)},'quick').scrape();
assert.equal(dailyRequests.length,10,'quick Cal sync performs exactly Frames + Pending + previous/current/next billing months for each of two cards');
assert.deepEqual([...new Set(dailyRequests.filter(row=>row.url.includes('transactionsDetails')).map(row=>`${row.body.year}-${String(row.body.month).padStart(2,'0')}`))],['2026-08','2026-09','2026-10'],'quick Cal sync requests the recent prior month, current month and next month');
assert.equal(dailyResult.accounts.every(account=>account.months.map(row=>row.month).join(',')==='2026-08,2026-09,2026-10'),true,'quick account coverage contains the recent prior month plus current and next month');
assert.equal(dailyResult._dataDiagnostics.length,2,'Cal keeps one transient raw transaction sample per discovered card for the local credit-data diagnostic');
const calWireHeaders=dailyRequests[0].headers;
assert.match(calWireHeaders['User-Agent'],/Chrome\/152\.0\.8112\.50/,'Cal Node fallback preserves the installed browser version instead of a hardcoded Chromium version');
assert.doesNotMatch(calWireHeaders['User-Agent'],/HeadlessChrome|Chrome\/142|Macintosh/,'Cal no longer advertises the stale Chrome/142 macOS fingerprint or a mismatched HeadlessChrome token');
assert.match(calWireHeaders['sec-ch-ua'],/Google Chrome.*152/,'Cal Node fallback carries Client Hints derived from the same native browser identity');
assert.equal(calWireHeaders['sec-ch-ua-platform'],'"Windows"');
assert.equal(dailyFixture.identityState.extraHTTPHeaders['accept-language'],'he-IL,he;q=0.9,en-US;q=0.8,en;q=0.7','Cal browser navigation gets the same stable language policy before login');
assert.match(String(dailyFixture.identityState.preDocument),/webdriver/,'Cal masks navigator.webdriver before issuer navigation without synthetic plugins/languages mocks');

const billedInSeptember=parseVisaCalMonthData({statusCode:1,result:{bankAccounts:[{debitDates:[{transactions:[{...transaction('card-a','2026-08'),trnPurchaseDate:'2026-08-28T00:00:00.000Z',debCrdDate:'2026-09-10T00:00:00.000Z',amtBeforeConvAndIndex:19305.96}]}],immidiateDebits:{debitDays:[]}}]}},{startDate:new Date('2026-09-01T00:00:00.000Z')});
assert.equal(billedInSeptember.length,1,'fast Cal sync keeps a prior-month purchase when its issuer debit date belongs to the current billing month');
assert.equal(billedInSeptember[0].date.slice(0,10),'2026-08-28','Cal purchase date stays exact and separate');
assert.equal(billedInSeptember[0].processedDate.slice(0,10),'2026-09-10','Cal current-month ownership is determined by the issuer debit date');
const billedBeforeCutoff=parseVisaCalMonthData({statusCode:1,result:{bankAccounts:[{debitDates:[{transactions:[{...transaction('card-a','2026-08'),trnPurchaseDate:'2026-08-20T00:00:00.000Z',debCrdDate:'2026-08-25T00:00:00.000Z'}]}],immidiateDebits:{debitDays:[]}}]}},{startDate:new Date('2026-09-01T00:00:00.000Z')});
assert.equal(billedBeforeCutoff.length,0,'the historical cutoff still applies to the billing date and does not leak older debit cycles');

function fakeMaxScraperFixture({homeCards=[{Last4Digits:'4444',CreditLimit:10000,OpenToBuy:9000,CycleSummary:[{Date:'2026-09-10T00:00:00',CurrencySymbol:'₪'}]}],months={}}={}){
  const calls={initialize:0,login:0,terminate:0,requests:[]},page={evaluate:async(_fn,url)=>{calls.requests.push(url);let data;if(url.includes('/api/contents/getCategories'))data={result:[{id:7,name:'חו״ל'}]};else if(url.includes('/api/registered/getHomePageData'))data={Result:{UserCards:{Cards:homeCards}}};else{const parsed=new URL(url),filter=JSON.parse(parsed.searchParams.get('filterData')||'{}'),month=String(filter.date||'').replace(/-(\d)-01$/,'-0$1-01').slice(0,7);data=months[month]||{result:{transactions:[]}}}return {status:200,body:JSON.stringify(data),retryAfter:''}}};
  return {calls,scraper:{page,initialize:async()=>{calls.initialize++},login:async()=>{calls.login++;return {success:true}},terminate:async()=>{calls.terminate++}}};
}
function maxFixtureRaw({id='max-1',card='4444',purchaseDate='2026-08-28T00:00:00',paymentDate='2026-09-10T00:00:00',amount=321,originalAmount=321,originalCurrency='ILS',paymentCurrency=376,merchantName='fixture max merchant',planName='רגילה',planTypeId=5,purchaseTime='14:27',comments='',categoryId=7,fundsTransferComment=''}={}){return {shortCardNumber:card,paymentDate,purchaseDate,actualPaymentAmount:String(amount),paymentCurrency,originalCurrency,originalAmount,planName,planTypeId,comments,fundsTransferComment,merchantName,categoryId,dealData:{arn:id,purchaseTime}}}

let genericOptions=null;
const maxFixture=fakeMaxScraperFixture({months:{'2026-08':{result:{transactions:[maxFixtureRaw()]}},'2026-09':{result:{transactions:[maxFixtureRaw({id:'max-pending-1',purchaseDate:'2026-09-03T00:00:00',paymentDate:null,amount:120,originalAmount:120,purchaseTime:'05:10'})]}},'2026-10':{result:{transactions:[]}}}});
const genericAdapter=new MaxAdapter({profile:{profileId:'max-billing',provider:'max',label:'MAX billing',credentials:{username:'u',password:'p'}},companyId:'max',createScraper:options=>{genericOptions=options;return maxFixture.scraper},now:()=>new Date(fixedNow),syncMode:'quick'});
const genericResult=await genericAdapter.scrape();
assert.equal(MAX_PROVIDER_SCHEMA_VERSION,'max-netunim-v2+upstream-login-6.10.0');
assert.equal(genericOptions.outputData?.enableTransactionsFilterByDate,false,'MAX keeps upstream date filtering disabled while Netunim owns the canonical billing-date boundary');
assert.equal(genericOptions.includeRawTransaction,true,'MAX keeps raw provider rows in-memory only long enough to normalize proven fields and diagnostics');
assert.equal(maxFixture.calls.initialize,1);assert.equal(maxFixture.calls.login,1);assert.equal(maxFixture.calls.terminate,1,'the local MAX adapter owns exactly one authenticated browser lifecycle');
assert.equal(genericResult.accounts[0].months.find(row=>row.month==='2026-09').transactions[0].transactionTime,'14:27','MAX maps the live provider field dealData.purchaseTime even when purchaseDate itself is date-only midnight');
assert.equal(genericResult.accounts[0].months.find(row=>row.month==='2026-09').transactions[0].id,'max-1','MAX groups a previous-month purchase into the current issuer billing month instead of dropping it');
assert.equal(genericResult.accounts[0].pendingTransactions.length,1,'MAX pending status remains authoritative when paymentDate is absent');
assert.equal(genericResult.accounts[0].pendingTransactions[0].id,'max-pending-1');
assert.equal(genericResult.accounts[0].months.flatMap(row=>row.transactions).some(tx=>tx.id==='max-pending-1'),false,'a pending approval can never be promoted into finalized monthly billing');
assert.equal(genericResult.accounts[0].pendingTransactions[0].transactionTime,'05:10','MAX pending rows use the same proven dealData.purchaseTime provider field');
assert.equal(genericResult._dataDiagnostics.some(row=>row.kind==='providerResponseShape'),true,'MAX keeps value-free response structure evidence so a future provider schema move is diagnosable even when no rows are normalized');
assert.equal(genericResult._dataDiagnostics.some(row=>row.rawTransaction?.merchantName==='fixture max merchant'),true,'MAX keeps one bounded local raw evidence sample per card for the separate data-diagnostic export');
assert.equal('rawTransaction' in genericResult.accounts[0].months.find(row=>row.month==='2026-09').transactions[0],false,'raw MAX provider payload never survives into normalized/cloud transaction rows');
assert.deepEqual(maxRawTransactionTime({purchaseDate:'2026-09-14T00:00:00',dealData:{purchaseTime:'14:27'}}),{time:'14:27',sourcePath:'dealData.purchaseTime',ambiguous:false,candidates:[{path:'dealData.purchaseTime',time:'14:27',value:'14:27'}]});
assert.equal(maxRawTransactionTime({dealData:{purchaseTime:'09:42:00'}}).time,'09:42','MAX accepts the exact live purchase-time field including seconds');
assert.equal(maxRawTransactionTime({transactionTime:'14:27',purchaseTime:'14:28',dealData:{purchaseHour:'0510'}}).time,'','unproven look-alike time fields never influence production MAX mapping');
const creditDataDiagnostic=buildCreditDataDiagnosticPayload({correlationId:'corr-test',profiles:[genericResult],rawSamples:genericResult._dataDiagnostics});
assert.equal(creditDataDiagnostic.schemaVersion,3,'credit data diagnostics preserve provider response structure plus bounded suspicious MAX candidate evidence without exposing credentials or full card numbers');
assert.equal(creditDataDiagnostic.profiles[0].accounts[0].accountSuffix,'4444');
assert.equal(creditDataDiagnostic.profiles[0].accounts[0].rawSample.timeEvidence.time,'14:27');
assert.equal(creditDataDiagnostic.profiles[0].providerEvidence.length,3,'MAX exports one sanitized structural record for every requested month');
assert.equal(creditDataDiagnostic.profiles[0].providerEvidence.some(row=>row.arrayPaths.some(item=>item.path==='result.transactions')),true);
assert.equal(creditDataDiagnostic.profiles[0].accounts[0].balance,-1000,'MAX home-card balance semantics remain CreditLimit minus OpenToBuy');
assert.equal(JSON.stringify(creditDataDiagnostic).includes('fixture max merchant'),true,'credit data diagnostics retain bounded provider sample values needed to discover useful fields');
assert.equal(JSON.stringify(creditDataDiagnostic).includes('password'),false,'credit data diagnostics never include login credentials');
const redactedDiagnostic=buildCreditDataDiagnosticPayload({profiles:[{profileId:'safe',provider:'max',accounts:[{accountNumber:'1234567812345678',txns:[]}]}],rawSamples:[{profileId:'safe',accountNumber:'1234567812345678',rawTransaction:{password:'never-export',authorization:'Bearer secret',cardNumber:'1234567812345678',transactionId:'sensitive-id',transactionTime:'10:11'}}]});
const redactedText=JSON.stringify(redactedDiagnostic);assert.equal(redactedText.includes('never-export'),false);assert.equal(redactedText.includes('Bearer secret'),false);assert.equal(redactedText.includes('1234567812345678'),false,'full card/account values are masked in local data diagnostics');assert.equal(redactedText.includes('sensitive-id'),false,'provider transaction identifiers are suffix-masked in local data diagnostics');

const nestedForeignRaw=maxFixtureRaw({id:'fx-akusoli-110',purchaseDate:'2026-09-30T00:00:00',paymentDate:'2026-10-02T00:00:00',amount:110,originalAmount:29.5,originalCurrency:'EUR',paymentCurrency:376,merchantName:'AKUSOLI.COM VILNIUS LT',planName:''});
const nestedForeignResponse={result:{transactions:[],foreignAndCurrency:{chargedNow:[nestedForeignRaw,maxFixtureRaw({...{id:'fx-akusoli-12',purchaseDate:'2026-09-30T00:00:00',paymentDate:'2026-10-02T00:00:00',amount:12,originalAmount:3.2,originalCurrency:'EUR',paymentCurrency:376,merchantName:'AKUSOLI.COM VILNIUS LT',planName:''}})]}}};
const nestedParsed=extractMaxTransactionCandidates(nestedForeignResponse);
assert.equal(nestedParsed.transactions.length,2,'MAX parser discovers transaction-shaped rows anywhere under result instead of depending on the legacy result.transactions array');
assert.equal(extractMaxTransactionCandidates({result:{transactions:[nestedForeignRaw]}}).transactions.length,1,'MAX no longer drops a valid foreign transaction merely because planName is blank');
assert.equal(nestedParsed.evidence.legacyTransactionsCount,0,'the regression fixture proves the rows can exist outside the legacy upstream array');
assert.equal(nestedParsed.evidence.candidatePaths.includes('result.foreignAndCurrency.chargedNow[]'),true);
const normalizedNested=normalizeMaxRawTransaction(nestedForeignRaw,new Map([[7,'חו״ל']]));
assert.equal(normalizedNested.status,'completed');assert.equal(normalizedNested.processedDate.slice(0,10),'2026-10-02');assert.equal(normalizedNested.chargedAmount,-110);assert.equal(normalizedNested.chargedCurrency,'ILS');assert.equal(normalizedNested.originalCurrency,'EUR','a foreign purchase charged in shekels preserves both currencies without inventing a conversion');

const foreignNow=new Date('2026-10-04T05:00:00.000Z'),foreignRows=[110,12,21,27].map((amount,index)=>maxFixtureRaw({id:`fx-${index}`,card:'5521',purchaseDate:'2026-09-30T00:00:00',paymentDate:'2026-10-02T00:00:00',amount,originalAmount:amount,originalCurrency:'ILS',paymentCurrency:376,merchantName:'AKUSOLI.COM VILNIUS LT',planName:'חיוב עסקות מיידי',planTypeId:5,comments:'חיוב עסקת חו"ל בש"ח',categoryId:14})),foreignFixture=fakeMaxScraperFixture({homeCards:[{Last4Digits:'5521',CreditLimit:20000,OpenToBuy:19830,CycleSummary:[{Date:'2026-10-10T00:00:00',CurrencySymbol:'₪'}]}],months:{'2026-09':{result:{transactions:[]}},'2026-10':{result:{transactions:foreignRows}},'2026-11':{result:{transactions:[]}}}}),foreignAdapter=new MaxAdapter({profile:{profileId:'max-fx',provider:'max',label:'MAX-5521',credentials:{username:'u',password:'p'}},companyId:'max',createScraper:()=>foreignFixture.scraper,now:()=>new Date(foreignNow),syncMode:'quick'}),foreignResult=await foreignAdapter.scrape(),octoberForeign=foreignResult.accounts[0].months.find(row=>row.month==='2026-10').transactions;
assert.equal(octoberForeign.length,4,'MAX production-shaped getTransactionsAndGraphs rows are retained even though both currencies are ILS');
assert.equal(octoberForeign.reduce((sum,row)=>sum+Math.abs(row.chargedAmount||0),0),170,'the four AKUSOLI immediate foreign charges retain the exact shekel settlement total');
assert.equal(octoberForeign.every(row=>row.processedDate.slice(0,10)==='2026-10-02'),true,'immediate foreign rows belong to the real MAX payment date, not the monthly 10/15 cycle');
assert.equal(octoberForeign.every(row=>row.foreignTransaction===true),true,'MAX provider wording marks the shekel-settled rows as foreign transactions without inventing a non-ILS currency');
assert.equal(octoberForeign.every(row=>row.originalCurrency==='ILS'&&row.chargedCurrency==='ILS'),true,'the explicit foreign marker does not falsify the currencies MAX actually returned');
const foreignDiagnostic=buildCreditDataDiagnosticPayload({correlationId:'fx-proof',profiles:[foreignResult],rawSamples:foreignResult._dataDiagnostics}),foreignOctoberEvidence=foreignDiagnostic.profiles[0].providerEvidence.find(row=>row.month==='2026-10');
assert.equal(foreignOctoberEvidence.foreignSignalCandidateCount,4,'MAX diagnostic evidence counts every provider-text foreign candidate before normalization');
assert.equal(foreignOctoberEvidence.offCycleCandidateCount,4,'MAX diagnostic evidence counts finalized immediate debits outside the normal 7-18 cycle window');
assert.equal(foreignOctoberEvidence.candidateAccountSummary[0].accountSuffix,'5521');assert.equal(foreignOctoberEvidence.candidateAccountSummary[0].candidateCount,4);
assert.equal(foreignOctoberEvidence.candidateAuditSamples.length,4,'the bounded evidence contains all four production-shaped regression rows');
assert.equal(foreignOctoberEvidence.candidateAuditSamples.every(row=>row.merchantName==='AKUSOLI.COM VILNIUS LT'&&row.paymentDate.slice(0,10)==='2026-10-02'&&row.foreignSignals.includes('providerText')),true,'diagnostic evidence matches the proven AKUSOLI provider contract: ILS settlement plus explicit foreign wording');
assert.equal(JSON.stringify(foreignOctoberEvidence).includes('fx-0'),false,'MAX diagnostic candidate evidence never exports issuer transaction identifiers');
const pendingForeignRaw=maxFixtureRaw({id:'fx-pending',card:'5521',purchaseDate:'2026-10-04T00:00:00',paymentDate:null,amount:55,originalAmount:55,originalCurrency:'ILS',paymentCurrency:376,merchantName:'FOREIGN PENDING',planName:'חיוב עסקות מיידי',planTypeId:5,comments:'חיוב עסקת חו"ל בש"ח',categoryId:14,purchaseTime:'08:31'}),pendingForeign=normalizeMaxRawTransaction(pendingForeignRaw);
assert.equal(pendingForeign.status,'pending','MAX still treats absence of paymentDate as the authoritative pending state');
assert.equal(pendingForeign.foreignTransaction,true,'the same explicit provider signal classifies a pending foreign transaction before settlement');
assert.equal(pendingForeign.processedDate,null,'a pending foreign transaction is never assigned a guessed billing date');

const homeOnlyFixture=fakeMaxScraperFixture({homeCards:[{Last4Digits:'5555',CreditLimit:5000,OpenToBuy:5000,CycleSummary:[]}],months:{'2026-08':{result:{transactions:[]}},'2026-09':{result:{transactions:[]}},'2026-10':{result:{transactions:[]}}}}),homeOnlyAdapter=new MaxAdapter({profile:{profileId:'max-home-only',provider:'max',label:'MAX home only',credentials:{username:'u',password:'p'}},companyId:'max',createScraper:()=>homeOnlyFixture.scraper,now:()=>new Date(fixedNow),syncMode:'quick'}),homeOnlyResult=await homeOnlyAdapter.scrape();
assert.deepEqual(homeOnlyResult.accounts.map(row=>row.accountNumber),['5555'],'MAX home-page cards remain visible even when the requested months contain zero transaction rows; account discovery no longer depends on transaction parsing');

const maxExcludedEvents=[],maxExcludedFixture=fakeMaxScraperFixture({homeCards:[{Last4Digits:'4444',CreditLimit:1000,OpenToBuy:990,CycleSummary:[]},{Last4Digits:'9999',CreditLimit:1000,OpenToBuy:980,CycleSummary:[]}],months:{'2026-08':{result:{transactions:[maxFixtureRaw({id:'keep-max',card:'4444',amount:10,originalAmount:10,paymentDate:'2026-08-10T00:00:00'}) ,maxFixtureRaw({id:'drop-max',card:'9999',amount:20,originalAmount:20,paymentDate:'2026-08-10T00:00:00'})]}},'2026-09':{result:{transactions:[]}},'2026-10':{result:{transactions:[]}}}}),maxExcludedAdapter=new MaxAdapter({profile:{profileId:'max-excluded',provider:'max',label:'MAX excluded',credentials:{username:'u',password:'p'}},companyId:'max',excludedAccountNumbers:['9999'],createScraper:()=>maxExcludedFixture.scraper,now:()=>new Date(fixedNow),syncMode:'quick',onDiagnostic:event=>maxExcludedEvents.push(event)});
const maxExcludedResult=await maxExcludedAdapter.scrape();assert.deepEqual(maxExcludedResult.accounts.map(row=>row.accountNumber),['4444'],'excluded MAX accounts never reach normalized/cloud connector output even though the issuer request is all-card');assert.equal(maxExcludedResult._dataDiagnostics.some(row=>row.rawTransaction?.shortCardNumber==='9999'),false,'excluded MAX accounts never enter raw transaction diagnostics');const maxExcludedEvidence=maxExcludedResult._dataDiagnostics.filter(row=>row.kind==='providerResponseShape');assert.equal(maxExcludedEvidence.every(row=>row.excludedAccountSuffixes.includes('9999')),true,'structural diagnostics make an all-card exclusion visible without exposing full card numbers');assert.equal(maxExcludedEvidence.every(row=>(row.candidateAccountSummary||[]).every(item=>item.accountSuffix!=='9999')&&(row.candidateAuditSamples||[]).every(item=>item.accountSuffix!=='9999')),true,'bounded MAX candidate evidence respects the same excluded-card boundary as normalized/cloud output');assert.equal(maxExcludedEvents.some(event=>event.stage==='CardExcluded'&&event.accountSuffix==='9999'),true,'MAX exclusion is observable without exposing card details');

const emptyMaxFixture=fakeMaxScraperFixture({homeCards:[],months:{'2026-08':{result:{transactions:[]}},'2026-09':{result:{transactions:[]}},'2026-10':{result:{transactions:[]}}}}),emptyMaxAdapter=new MaxAdapter({profile:{profileId:'max-empty',provider:'max',label:'MAX empty',credentials:{username:'u',password:'p'}},companyId:'max',createScraper:()=>emptyMaxFixture.scraper,now:()=>new Date(fixedNow),syncMode:'quick'});
const emptyMaxResult=await emptyMaxAdapter.scrape();assert.equal(emptyMaxResult.coreComplete,false,'MAX can no longer report a successful empty profile when authenticated issuer data contains neither cards nor recognizable transactions');assert.equal(emptyMaxResult.syncedAt,null,'an empty MAX schema response never advances the successful-sync clock');assert.equal(emptyMaxResult.errors[0].code,'CREDIT_PROVIDER_SCHEMA_ERROR');assert.equal(emptyMaxResult.errors[0].stage,'MaxCards');assert.equal(emptyMaxResult._dataDiagnostics.filter(row=>row.kind==='providerResponseShape').length,3,'schema-failure profiles still return sanitized authenticated response evidence so the next diagnostic can identify a provider-side shape change');

const isracardProfile={profileId:'isracard-digital',provider:'isracard',label:'ישראכרט',credentials:{id:'123456789',card6Digits:'123456',password:'fixed-password'}};
let isracardDigitalOptions=null;const isracardDiagnosticEvents=[];
const isracardDigitalAdapter=createCreditProviderAdapter({profile:isracardProfile,CompanyTypes:{isracard:'isracard'},createScraper:()=>{throw new Error('published legacy Isracard scraper must not own v42')},isracardScrapeImpl:async options=>{isracardDigitalOptions={...options,onDiagnostic:undefined,now:undefined};return {success:true,accounts:[{accountNumber:'7392',balance:-1400,cardFrame:10000,txns:[{identifier:'isr-approved',status:'pending',date:'2026-09-03T05:10:00.000Z',processedDate:'2026-09-03T05:10:00.000Z',chargedAmount:-300,chargedCurrency:'ILS'},{identifier:'isr-approved',status:'pending',date:'2026-09-03T05:10:00.000Z',processedDate:'2026-09-03T05:10:00.000Z',chargedAmount:-300,chargedCurrency:'ILS'}]}]}} ,browserPath:'chrome.exe',identityProbeUrl:'http://127.0.0.1:8765/health',excludedAccountNumbers:['0000'],now:()=>new Date(fixedNow),syncMode:'quick',onDiagnostic:event=>isracardDiagnosticEvents.push(event)});
const isracardDigitalResult=await isracardDigitalAdapter.scrape();
assert.equal(isracardDigitalOptions.browserPath,'chrome.exe','Isracard v42 DigitalV3 uses the installed Chrome/Edge executable');
assert.equal(isracardDigitalOptions.identityProbeUrl,'http://127.0.0.1:8765/health','Isracard DigitalV3 receives the bridge loopback origin used only to recover native Client Hints before issuer navigation');
assert.deepEqual(isracardDigitalOptions.excludedAccountNumbers,['0000'],'Isracard native DigitalV3 receives the authoritative excluded-card selection before its per-card data loop');
const isracardCompleteDiagnostic=isracardDiagnosticEvents.find(event=>event.stage==='Complete');assert(isracardCompleteDiagnostic,'Isracard adapter emits a completion diagnostic');assert.equal(isracardCompleteDiagnostic.syncMode,'quick');assert.equal(isracardCompleteDiagnostic.browserMode,'headless');assert.equal(isracardCompleteDiagnostic.browserProduct,'chrome');assert.equal(isracardCompleteDiagnostic.profileId,isracardProfile.profileId,'credit diagnostics identify the exact profile without exposing credentials');
assert.equal(isracardDigitalResult.accounts[0].pendingTransactions.length,1,'DigitalV3 approvals repeated across billing-month requests are deduplicated by their stable issuer confirmation identity');
assert.equal(isracardDigitalResult.accounts[0].months.flatMap(row=>row.transactions).some(tx=>tx.status==='pending'),false,'Isracard pending approvals stay outside finalized monthly slices');
assert.equal(isracardDigitalResult.accounts[0].months.find(row=>row.month==='2026-09').providerSchemaVersion,ISRACARD_DIGITAL_V3_SCHEMA_VERSION,'Isracard v42 reports the local DigitalV3 connector schema truthfully');
assert.equal(isracardDigitalResult.accounts[0].availableCredit,8600,'Isracard DigitalV3 limitUsed and creditLimit semantics produce issuer available credit without a client-side pending double subtraction');
const isracardApproved=normalizeIsracardDigitalV3ApprovedTransaction({purchaseDate:'07/09/2026',israelTransactionTime:'12:34',businessName:'עסק',originalAmount:75,currencyIso:'ILS',ilsBillingAmount:75,seqConfirmationNumber:'isr-abc'});
assert.equal(isracardApproved.status,'pending');assert.equal(isracardApproved.processedDate,isracardApproved.date,'Isracard DigitalV3 pending rows intentionally carry purchase time in processedDate but remain pending by explicit status');
assert.equal(isracardApproved.transactionTime,'12:34','Isracard preserves the issuer-supplied purchase clock independently of the billing date');
assert.equal(normalizeIsracardDigitalV3ApprovedTransaction({purchaseDate:'07/09/2026',israelTransactionTime:'12:34',businessName:'עסק',originalAmount:75,currencyIso:'ILS',ilsBillingAmount:75,seqConfirmationNumber:'isr-category',branchCodeDescription:'מסעדות'}).category,'מסעדות','Isracard pending DigitalV3 category preserves branchCodeDescription');
assert.equal(normalizeIsracardDigitalV3Voucher({purchaseDate:'07/09/2026',purchaseTime:'12:34:00',businessName:'עסק',originalAmount:75,originalCurrencyIso:'ILS',billingAmount:75,seqVoucherNumber:'isr-voucher-category',transactionDescription:'רכישה רגילה'},'2026-09-10T00:00:00.000Z').category,'רכישה רגילה','Isracard settled DigitalV3 category preserves transactionDescription');

const amexProfile={profileId:'amex-native',provider:'amex',label:'Amex native',credentials:{id:'123456789',card6Digits:'123456',password:'fixed-password'}};
let amexDigitalOptions=null;
const amexDigitalAdapter=createCreditProviderAdapter({profile:amexProfile,CompanyTypes:{amex:'amex'},createScraper:()=>{throw new Error('published 6.10 scraper must not own Amex v41')},amexScrapeImpl:async options=>{amexDigitalOptions={...options,onDiagnostic:undefined,now:undefined};return {success:true,accounts:[{accountNumber:'6774',balance:-1250,balanceDate:'2026-09-10T00:00:00.000Z',cardFrame:10000,txns:[{identifier:'a1',status:'completed',date:'2026-09-07T10:00:00.000Z',transactionDate:'2026-09-07T10:00:00.000Z',processedDate:'2026-09-10T00:00:00.000Z',chargedAmount:-50,chargedCurrency:'ILS'}]}]}} ,browserPath:'chrome.exe',identityProbeUrl:'http://127.0.0.1:8765/health',now:()=>new Date(fixedNow),syncMode:'quick'});
const amexDigitalResult=await amexDigitalAdapter.scrape();
assert.equal(amexDigitalOptions.browserPath,'chrome.exe','Amex v41 primary path runs through the discovered installed Chrome/Edge executable');
assert.equal(amexDigitalOptions.identityProbeUrl,'http://127.0.0.1:8765/health','Amex DigitalV3 receives the same trusted loopback identity probe without contacting the issuer first');
assert.deepEqual(amexDigitalOptions.credentials,amexProfile.credentials,'Amex DigitalV3 receives the official id/card6Digits/password credential contract unchanged');
assert.equal(amexDigitalOptions.futureMonthsToScrape,1,'quick Amex DigitalV3 keeps the bounded recent+next billing horizon');
assert.equal(normalizeAmexDigitalV3ApprovedTransaction({purchaseDate:'07/09/2026',israelTransactionTime:'13:45',businessName:'Amex עסק',originalAmount:90,currencyIso:'ILS',ilsBillingAmount:90,seqConfirmationNumber:'amex-category',branchCodeDescription:'קמעונאות'}).category,'קמעונאות','Amex pending DigitalV3 category preserves branchCodeDescription');
assert.equal(normalizeAmexDigitalV3Voucher({purchaseDate:'07/09/2026',purchaseTime:'13:45:00',businessName:'Amex עסק',originalAmount:90,originalCurrencyIso:'ILS',billingAmount:90,seqVoucherNumber:'amex-voucher-category',transactionDescription:'עסקה מקומית'},'2026-09-10T00:00:00.000Z').category,'עסקה מקומית','Amex settled DigitalV3 category preserves transactionDescription');
assert.equal(amexDigitalResult.coreComplete,true,'successful Amex DigitalV3 completes without entering Camoufox fallback');
assert.equal(amexDigitalResult.accounts[0].months.find(row=>row.month==='2026-09').providerSchemaVersion,AMEX_DIGITAL_V3_SCHEMA_VERSION,'Amex v41 month slices identify the DigitalV3 schema instead of pretending to be the 6.10 legacy scraper');
assert.deepEqual({balance:amexDigitalResult.accounts[0].balance,cardFrame:amexDigitalResult.accounts[0].cardFrame,availableCredit:amexDigitalResult.accounts[0].availableCredit},{balance:-1250,cardFrame:10000,availableCredit:8750},'DigitalV3 issuer limit data keeps the existing utilized/frame/available semantics');

function chromiumIdentityFixture({product='chrome',withBrandedHints=true,initialHintsMissing=false,headlessHintBrands=false,missingHighEntropyKey='',setUserAgentFailure=false}={}){
  const isEdge=product==='edge',major='152',full='152.0.8112.50',productBrand=isEdge?'Microsoft Edge':'Google Chrome';
  const state={userAgent:'',userAgentMetadata:null,userAgentPlatform:'',preDocument:null,extraHTTPHeaders:{},interception:false,requestHandler:null,probed:false,probeUrl:'',probeOptions:null};
  const userAgent=`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/${full} Safari/537.36${isEdge?` Edg/${full}`:''}`;
  const hintedBrand=headlessHintBrands?'HeadlessChrome':productBrand;
  const brands=[{brand:'Not(A:Brand',version:'99'},{brand:'Chromium',version:major},...(withBrandedHints?[{brand:hintedBrand,version:major}]:[])];
  const fullVersionList=[{brand:'Not(A:Brand',version:'99.0.0.0'},{brand:'Chromium',version:full},...(withBrandedHints?[{brand:hintedBrand,version:full}]:[])];
  return {state,page:{
    evaluate:async(...args)=>{if(args.length>1)throw new TypeError('Failed to fetch');const userAgentData=initialHintsMissing&&!state.probed?null:{brands,mobile:false,platform:'Windows',architecture:'x86',bitness:'64',model:'',platformVersion:'19.0.0',uaFullVersion:full,fullVersionList,wow64:false};if(userAgentData&&missingHighEntropyKey)delete userAgentData[missingHighEntropyKey];return {userAgent,navigatorPlatform:'Win32',userAgentData}},
    goto:async(url,options)=>{state.probed=true;state.probeUrl=String(url);state.probeOptions=options;return {ok:()=>true}},
    setUserAgent:async value=>{if(setUserAgentFailure)throw new Error('Protocol error (Network.setUserAgentOverride): invalid metadata');if(typeof value!=='string')for(const key of ['architecture','mobile','model','platform','platformVersion'])if(!Object.prototype.hasOwnProperty.call(value.userAgentMetadata||{},key))throw new Error(`Protocol error: missing ${key}`);state.userAgent=typeof value==='string'?value:value.userAgent;state.userAgentMetadata=typeof value==='string'?null:value.userAgentMetadata;state.userAgentPlatform=typeof value==='string'?'':value.platform||''},
    evaluateOnNewDocument:async fn=>{state.preDocument=fn},
    setExtraHTTPHeaders:async headers=>{state.extraHTTPHeaders={...headers}},
    setRequestInterception:async value=>{state.interception=value},
    on:(event,handler)=>{if(event==='request')state.requestHandler=handler},
  }};
}
const calIdentityFixture=chromiumIdentityFixture(),calIdentity=await prepareVisaCalBrowserIdentity(calIdentityFixture.page);
assert.equal(calIdentity.clientHintsState,'preserved');assert.equal(calIdentity.browserMajorVersion,152);assert.match(calIdentity.requestHeaders['sec-ch-ua'],/Google Chrome.*152/);assert.equal(calIdentity.requestHeaders['sec-ch-ua-mobile'],'?0');assert.equal(calIdentity.requestHeaders['sec-ch-ua-platform'],'"Windows"');assert.equal(calIdentityFixture.state.extraHTTPHeaders['accept-language'],'he-IL,he;q=0.9,en-US;q=0.8,en;q=0.7');assert.match(String(calIdentityFixture.state.preDocument),/webdriver/);assert.doesNotMatch(String(calIdentityFixture.state.preDocument),/plugins|languages/,'Cal keeps the minimal live-tested automation mask and does not synthesize navigator.plugins/languages');
const amexIdentityFixture=chromiumIdentityFixture(),amexIdentity=await prepareAmexDigitalV3Page(amexIdentityFixture.page);
assert.equal(amexIdentity.webdriver,'undefined');assert.equal(amexIdentity.clientHintsState,'preserved');assert.equal(amexIdentity.browserMajorVersion,152);assert.equal(amexIdentityFixture.state.userAgent.includes('HeadlessChrome'),false);assert(amexIdentityFixture.state.userAgent.includes('Chrome/152.0.8112.50'));assert.equal(amexIdentityFixture.state.interception,true);assert.equal(typeof amexIdentityFixture.state.preDocument,'function');assert.equal(amexIdentityFixture.state.userAgentMetadata.model,'','desktop Chromium model stays present as the native empty string because CDP requires the field');assert.equal(amexIdentityFixture.state.userAgentMetadata.architecture,'x86');assert.equal(amexIdentityFixture.state.userAgentMetadata.platformVersion,'19.0.0');
assert.equal(amexIdentityFixture.state.userAgentPlatform,'Win32','UA override preserves the installed browser navigator.platform instead of inventing one');
assert(amexIdentityFixture.state.userAgentMetadata.brands.some(row=>row.brand==='Google Chrome'&&row.version==='152'),'the installed Chrome low-entropy brand is preserved in native Client Hints metadata');
assert(amexIdentityFixture.state.userAgentMetadata.fullVersionList.some(row=>row.brand==='Google Chrome'&&row.version==='152.0.8112.50'),'the installed Chrome full-version brand is preserved exactly, not synthesized');
assert.match(String(amexIdentityFixture.state.preDocument),/webdriver/);assert.match(String(amexIdentityFixture.state.preDocument),/undefined/,'the current live-tested Amex login masks navigator.webdriver as undefined, not false');
let detectorAbort=null;amexIdentityFixture.state.requestHandler({url:()=> 'https://he.americanexpress.co.il/detector-dom.min.js',abort:(reason,priority)=>{detectorAbort={reason,priority}},continue:()=>{throw new Error('detector request must be aborted')}});await new Promise(resolve=>setImmediate(resolve));assert.equal(detectorAbort.priority,1000,'DigitalV3 login preserves the maintained detector-dom abort priority');
let normalContinue=null;amexIdentityFixture.state.requestHandler({url:()=> 'https://he.americanexpress.co.il/personalarea/Login',abort:()=>{throw new Error('normal request must continue')},continue:(overrides,priority)=>{normalContinue={overrides,priority}}});await new Promise(resolve=>setImmediate(resolve));assert.equal(normalContinue.priority,10,'DigitalV3 login keeps upstream cooperative request flow; Client Hints are preserved via CDP identity metadata, not per-request header rewriting');
const edgeIdentityFixture=chromiumIdentityFixture({product:'edge'}),edgeIdentity=await preserveInstalledChromiumIdentity(edgeIdentityFixture.page);
assert.equal(edgeIdentity.product,'edge');assert.equal(edgeIdentity.clientHintsState,'preserved');assert(edgeIdentityFixture.state.userAgentMetadata.brands.some(row=>row.brand==='Microsoft Edge'),'installed Edge keeps its native branded Client Hints instead of being rewritten as Chrome');
const secureProbeIdentityFixture=chromiumIdentityFixture({initialHintsMissing:true}),secureProbeIdentity=await preserveInstalledChromiumIdentity(secureProbeIdentityFixture.page,{probeUrl:'http://127.0.0.1:8765/health'});
assert.equal(secureProbeIdentity.clientHintsState,'preserved','a fresh page that omits secure-context UA Client Hints recovers the installed browser identity from the trusted loopback bridge origin');assert.equal(secureProbeIdentityFixture.state.probeUrl,'http://127.0.0.1:8765/health');assert.equal(secureProbeIdentityFixture.state.probeOptions.waitUntil,'domcontentloaded');assert.equal(secureProbeIdentityFixture.state.userAgent.includes('HeadlessChrome'),false,'the secure local identity probe still applies only the classic HeadlessChrome token mask');
const rejectedProbeIdentityFixture=chromiumIdentityFixture({initialHintsMissing:true}),rejectedProbeIdentity=await preserveInstalledChromiumIdentity(rejectedProbeIdentityFixture.page,{probeUrl:'https://example.com/identity'});
assert.equal(rejectedProbeIdentity.ok,false,'browser identity remains fail-closed when native hints are missing and the requested probe is not loopback');assert.equal(rejectedProbeIdentityFixture.state.probeUrl,'','identity discovery never navigates to an arbitrary remote host');
const incompleteIdentityFixture=chromiumIdentityFixture({missingHighEntropyKey:'model'}),incompleteIdentity=await preserveInstalledChromiumIdentity(incompleteIdentityFixture.page);
assert.equal(incompleteIdentity.ok,false);assert.equal(incompleteIdentity.clientHintsState,'incomplete','native UA-CH missing a required CDP metadata field fails closed instead of inventing it');assert.equal(incompleteIdentityFixture.state.userAgent,'','an incomplete Client Hints contract is never applied');
const rejectedOverrideFixture=chromiumIdentityFixture({setUserAgentFailure:true}),rejectedOverrideIdentity=await preserveInstalledChromiumIdentity(rejectedOverrideFixture.page);
assert.equal(rejectedOverrideIdentity.ok,false);assert.equal(rejectedOverrideIdentity.clientHintsState,'override-failed','a CDP user-agent override rejection remains a BrowserIdentity failure instead of escaping as a generic provider error');
const nativeHeadlessIdentityFixture=chromiumIdentityFixture({headlessHintBrands:true}),nativeHeadlessIdentity=await preserveInstalledChromiumIdentity(nativeHeadlessIdentityFixture.page);
assert.equal(nativeHeadlessIdentity.ok,true);assert.equal(nativeHeadlessIdentity.identityMode,'native-headless','when Chromium itself reports HeadlessChrome in Client Hints the bridge keeps the complete native identity instead of forging headful hints');assert.match(nativeHeadlessIdentity.userAgent,/HeadlessChrome\//);assert.equal(nativeHeadlessIdentityFixture.state.userAgent,'','native headless identity is not passed through a partial UA override that could desynchronize Client Hints');
const unbrandedIdentityFixture=chromiumIdentityFixture({withBrandedHints:false});await assert.rejects(()=>prepareAmexDigitalV3Page(unbrandedIdentityFixture.page),error=>error.code==='CREDIT_BROWSER_IDENTITY_UNAVAILABLE'&&error.stage==='BrowserIdentity'&&error.clientHintsState==='unbranded','Amex fails closed before issuer navigation when Chrome/Edge cannot expose branded native Client Hints');assert.equal(unbrandedIdentityFixture.state.userAgent,'','an incomplete browser identity is never applied to the page');
const amexCredentials={id:'123456789',card6Digits:'123456',password:'fixed-password'};
const logonWithoutUserName=buildAmexDigitalV3LogonRequest({returnCode:'1'},amexCredentials),logonWithoutUserNameWire=JSON.parse(JSON.stringify(logonWithoutUserName));
assert.equal(logonWithoutUserName.KodMishtamesh,undefined,'PR #1159 models ValidateIdDataBean.userName as optional');
assert.equal(Object.hasOwn(logonWithoutUserNameWire,'KodMishtamesh'),false,'when Amex omits optional userName, the wire request omits KodMishtamesh exactly as upstream JSON serialization does');
assert.deepEqual(logonWithoutUserNameWire,{MisparZihuy:'123456789',Sisma:'fixed-password',cardSuffix:'123456',countryCode:'212',idType:'1'},'missing userName never falls back to an invented ID/username value');
assert.equal(buildAmexDigitalV3LogonRequest({returnCode:'1',userName:'issuer-user'},amexCredentials).KodMishtamesh,'issuer-user','when Amex supplies userName, performLogonI preserves it unchanged');
const amexLoginAccepted=classifyAmexDigitalV3LogonResult({status:'1'});
assert.equal(amexLoginAccepted.ok,true,'PR #1159 status=1 remains a valid Amex login even when that response omits returnCode');
const amexLoginAcceptedWithReturnCode=classifyAmexDigitalV3LogonResult({status:'1',returnCode:'1'});
assert.equal(amexLoginAcceptedWithReturnCode.ok,true,'the newer live Amex 1/1 success pair is accepted');
const amexLoginRejected=classifyAmexDigitalV3LogonResult({status:'2',returnCode:'E',message:'provider text must not be persisted'});
assert.deepEqual({ok:amexLoginRejected.ok,code:amexLoginRejected.code,providerStatus:amexLoginRejected.providerStatus,providerReturnCode:amexLoginRejected.providerReturnCode},{ok:false,code:'CREDIT_LOGIN_REJECTED',providerStatus:'2',providerReturnCode:'E'},'Amex 2/E is a login rejection, not proof that the password field itself is wrong');
assert.match(amexLoginRejected.message,/אינה מוכיחה שהסיסמה עצמה שגויה/,'the user-facing Amex rejection does not make an unsupported bad-password claim');
assert.equal(classifyAmexDigitalV3LogonResult({status:'3'}).code,'CREDIT_CHANGE_PASSWORD','the established change-password status stays terminal');
assert.equal(classifyAmexDigitalV3LogonResult({status:'9',returnCode:'Z'}).code,'CREDIT_PROVIDER_SCHEMA_ERROR','unknown Amex login statuses fail closed as an unrecognized provider response');
const approved=normalizeAmexDigitalV3ApprovedTransaction({purchaseDate:'07/09/2026',israelTransactionTime:'12:34',businessName:'עסק',originalAmount:75,currencyIso:'ILS',ilsBillingAmount:75,seqConfirmationNumber:'abc',extraDetails:'memo'});
assert.equal(approved.status,'pending');assert.equal(approved.originalAmount,-75);assert.equal(approved.chargedAmount,-75);assert.equal(approved.date,approved.transactionDate,'DigitalV3 pending rows preserve the exact purchase date separately for ordering/audit');
assert.equal(approved.transactionTime,'12:34','Amex pending approvals preserve the explicit issuer transaction clock');
const voucher=normalizeAmexDigitalV3Voucher({purchaseDate:'06/09/2026',purchaseTime:'08:15:00',businessName:'עסק 2',originalAmount:300,originalCurrencyIso:'ILS',billingAmount:100,seqVoucherNumber:'v1',currentInstallmentNum:2,numberOfInstallment:3},'2026-09-10T00:00:00.000Z');
assert.deepEqual(voucher.installments,{number:2,total:3});assert.equal(voucher.processedDate,'2026-09-10T00:00:00.000Z');assert.equal(voucher.transactionDate,voucher.date,'DigitalV3 settled rows retain purchase date before installment billing-date normalization');
assert.equal(normalizeAmexDigitalV3Voucher({purchaseDate:'06/09/2026',billingAmount:100},null).processedDate,null,'a missing DigitalV3 billing date remains missing instead of inheriting the requested month start');
assert.equal(voucher.transactionTime,'08:15','Amex completed vouchers preserve purchaseTime for the transactions table');
const amexBadPassword=createCreditProviderAdapter({profile:amexProfile,CompanyTypes:{amex:'amex'},amexScrapeImpl:async()=>{const error=new Error('invalid');error.code='CREDIT_INVALID_PASSWORD';error.stage='LoginPassword';throw error},browserPath:'chrome.exe',allowCamoufoxFallback:true,now:()=>new Date(fixedNow)});
await assert.rejects(()=>amexBadPassword.scrape(),error=>error.code==='CREDIT_INVALID_PASSWORD'&&error.browserEngine==='chromium','invalid Amex credentials never trigger a second browser engine login attempt');
const amexRejectedLogin=createCreditProviderAdapter({profile:amexProfile,CompanyTypes:{amex:'amex'},amexScrapeImpl:async()=>{const error=new Error('issuer rejected login');error.code='CREDIT_LOGIN_REJECTED';error.stage='LoginPassword';error.providerStatus='2';error.providerReturnCode='E';throw error},browserPath:'chrome.exe',allowCamoufoxFallback:true,now:()=>new Date(fixedNow)});
await assert.rejects(()=>amexRejectedLogin.scrape(),error=>error.code==='CREDIT_LOGIN_REJECTED'&&error.browserEngine==='chromium'&&error.providerStatus==='2'&&error.providerReturnCode==='E','an Amex provider rejection is terminal for that run and never causes a duplicate credential attempt in Camoufox');
const amexCamoufoxPaused=createCreditProviderAdapter({profile:amexProfile,CompanyTypes:{amex:'amex'},amexScrapeImpl:async()=>{const error=new Error('html');error.code='CREDIT_LOGIN_HTML_RESPONSE';error.stage='LoginApi';throw error},browserPath:'chrome.exe',allowCamoufoxFallback:false,now:()=>new Date(fixedNow)});
await assert.rejects(()=>amexCamoufoxPaused.scrape(),error=>error.code==='CREDIT_LOGIN_HTML_RESPONSE'&&error.browserEngine==='chromium','a Camoufox cooldown disables only the fallback; DigitalV3 Chromium is still attempted and its current failure remains explicit');

const excludedFixture=fakeScraper(),excludedRequests=[],excludedFetch=fetchFixture(),excludedResult=await adapterFor(excludedFixture.scraper,async(url,options)=>{excludedRequests.push({url,body:JSON.parse(options.body)});return excludedFetch(url,options)},'recovery',{excludedAccountNumbers:['1111']}).scrape();
assert.equal(excludedRequests.length,20,'a known excluded Cal card sends zero Frames/Pending/month requests while one included card keeps the complete recovery horizon');
assert.equal(excludedRequests.some(row=>JSON.stringify(row.body).includes('card-a')),false,'excluded Cal suffix is filtered before every issuer data request');
assert.deepEqual(excludedResult.accounts.map(account=>account.accountNumber),['2222'],'the profile result contains only cards that were actually refreshed; the browser merge preserves previously known excluded cards');

const forecastFixture=fakeScraper(),forecastResult=await adapterFor(forecastFixture.scraper,fetchFixture({failureMonth:'2026-11',failureCard:'card-a'})).scrape();
assert.equal(forecastFixture.calls.login,1,'all Cal cards and months share exactly one login');
assert.equal(forecastFixture.calls.initialize,1);assert.equal(forecastFixture.calls.terminate,1);
assert.equal(forecastResult.coreComplete,true,'one later forecast failure does not fail required profile coverage');
assert.equal(forecastResult.accounts.find(account=>account.accountNumber==='1111').months.find(row=>row.month==='2026-11').fetchStatus,'provider_error');
assert.equal(forecastResult.accounts.find(account=>account.accountNumber==='2222').months.find(row=>row.month==='2026-11').fetchStatus,'success','one card failure cannot discard another card');
assert(forecastResult.errors.some(error=>error.code==='CREDIT_PARTIAL_FORECAST'));

const schemaFixture=fakeScraper(),schemaResult=await adapterFor(schemaFixture.scraper,fetchFixture({failureMonth:'2026-10',failureCard:'card-a',failureKind:'schema'})).scrape();
assert.equal(schemaResult.coreComplete,false,'a schema change in the nearest future/core month prevents a full-success timestamp');
assert.equal(schemaResult.accounts[0].months.find(row=>row.month==='2026-10').fetchStatus,'schema_error');
assert(schemaResult.errors.some(error=>error.code==='CREDIT_CORE_COVERAGE_INCOMPLETE'));

const htmlFailure=classifyCreditHttpResponse({status:200,text:'<!DOCTYPE html><html>challenge</html>',stage:'Transactions 2026-11'});
assert.equal(htmlFailure.code,'CREDIT_PROVIDER_RESPONSE_NOT_JSON');
assert.equal(htmlFailure.message.includes('<html>'),false,'raw issuer HTML never enters a public error');
const blockedFailure=classifyCreditHttpResponse({status:403,text:'forbidden body must stay private',stage:'Frames'});
assert.equal(blockedFailure.code,'CREDIT_AUTOMATION_BLOCKED','403 is a durable automation block, not a generic HTTP error');
assert.equal(blockedFailure.message.includes('forbidden body'),false,'the 403 response body never enters a public error');
const cloudflareBodyFailure=classifyCreditHttpResponse({status:200,text:'<!doctype html><title>Attention Required! | Cloudflare</title><div id="cf-error-details">Sorry, you have been blocked</div>',stage:'Pending'});
assert.equal(cloudflareBodyFailure.code,'CREDIT_AUTOMATION_BLOCKED','a Cloudflare challenge page is classified as an automation block before generic HTML/JSON parsing');
assert.equal(cloudflareBodyFailure.message.includes('Cloudflare'),false,'challenge HTML remains private even when it is recognized as a bot block');
assert.throws(()=>parseVisaCalMonthData({statusCode:1,result:{newSchema:true}}),error=>error.code==='CREDIT_PROVIDER_SCHEMA_ERROR');
assert.throws(()=>parseVisaCalMonthData({statusCode:17,title:'failed month'}),error=>error.code==='CREDIT_PROVIDER_DATA_ERROR');
assert.throws(()=>parseVisaCalMonthData({statusCode:17,statusTitle:'provider title',statusDescription:'provider description'}),error=>error.code==='CREDIT_PROVIDER_DATA_ERROR'&&error.message==='provider title','Cal provider statusTitle is preserved instead of collapsing into a generic parser error');

const missingFrames=parseVisaCalFrame({}, {cardUniqueId:'card-a'}),nullFrames=parseVisaCalFrame({result:null},{cardUniqueId:'card-a'});
assert.equal(missingFrames.frameStatus,'missing','Frames without result is optional/unavailable under the official 6.9.0 contract');
assert.equal(nullFrames.frameStatus,'missing','Frames result:null is treated as unavailable rather than an invented schema change');
assert.equal(missingFrames.warning.code,'CREDIT_FRAMES_UNAVAILABLE');
const irrelevantFrames=parseVisaCalFrame({statusCode:87,statusTitle:'לא נמצאו כרטיסים רלוונטיים להצגה',result:null},{cardUniqueId:'card-a'});
assert.equal(irrelevantFrames.frameStatus,'missing');assert.equal(irrelevantFrames.frameFetchStatus,'unavailable');assert.equal(irrelevantFrames.warning,null,'Cal Frames status 87 is non-applicable frame data, not a failed card synchronization');
assert.throws(()=>parseVisaCalFrame({statusCode:17,title:'issuer rejected'},{cardUniqueId:'card-a'}),error=>error.code==='CREDIT_PROVIDER_DATA_ERROR'&&error.stage==='Frames');
const bankOnly=parseVisaCalFrame({result:{bankIssuedCards:{cardLevelFrames:[{cardUniqueId:'card-a',nextTotalDebit:125,nextDebitDate:'2026-09-15'}],frameLimitForCardAmount:7000}}},{cardUniqueId:'card-a'});
assert.deepEqual({balance:bankOnly.balance,cardFrame:bankOnly.cardFrame,cardType:bankOnly.cardType},{balance:-125,cardFrame:7000,cardType:'bankIssued'});
const calOnly=parseVisaCalFrame({result:{calIssuedCards:{cardLevelFrames:[{cardUniqueId:'card-a',nextTotalDebit:90}],frameLimitForCardAmount:6000}}},{cardUniqueId:'card-a'});
assert.deepEqual({balance:calOnly.balance,cardFrame:calOnly.cardFrame,cardType:calOnly.cardType},{balance:-90,cardFrame:6000,cardType:'companyIssued'});
const accountFallback=parseVisaCalFrame({result:{bankIssuedCards:{cardLevelFrames:[{cardUniqueId:'different-card'}],nextTotalDebitForAccount:310,nextTotalDebitDateForAccount:'2026-09-20',frameLimitForCardAmount:8000}}},{cardUniqueId:'card-a'});
assert.deepEqual({balance:accountFallback.balance,balanceDate:accountFallback.balanceDate,cardFrame:accountFallback.cardFrame},{balance:-310,balanceDate:'2026-09-20T00:00:00.000Z',cardFrame:8000},'a sole matching account group supplies the official account-level fallback when no card frame matches');
const fictiveBalanceFallback=parseVisaCalFrame({result:{calIssuedCards:{frameLimitForCardAmount:10000,fictiveMaxAccAmt:7600}}},{cardUniqueId:'card-a'});
assert.deepEqual({balance:fictiveBalanceFallback.balance,cardFrame:fictiveBalanceFallback.cardFrame,cardType:fictiveBalanceFallback.cardType},{balance:-2400,cardFrame:10000,cardType:'companyIssued'},'Cal v6.12.1 fictiveMaxAccAmt fallback is ported without replacing Netunim frame-group isolation');
assert.throws(()=>parseVisaCalFrame({result:{calIssuedCards:{frameLimitForCardAmount:10000,fictiveMaxAccAmt:'7600'}}},{cardUniqueId:'card-a'}),error=>error.code==='CREDIT_PROVIDER_SCHEMA_ERROR'&&error.stage==='Frames','fictiveMaxAccAmt remains fail-closed when Cal changes its numeric contract');
assert.throws(()=>parseVisaCalFrame({result:{bankIssuedCards:'impossible-group'}},{cardUniqueId:'card-a'}),error=>error.code==='CREDIT_PROVIDER_SCHEMA_ERROR'&&error.stage==='Frames');

const framesWarningFixture=fakeScraper(),framesWarningResult=await adapterFor(framesWarningFixture.scraper,fetchFixture({framesBody:{}})).scrape();
assert.equal(framesWarningResult.coreComplete,true,'Frames unavailable never changes Core transaction coverage');
assert.equal(framesWarningResult.accounts[0].frameStatus,'missing');
assert(framesWarningResult.errors.some(error=>error.component==='frames'&&error.severity==='warning'&&error.code==='CREDIT_FRAMES_UNAVAILABLE'));
assert.equal(framesWarningResult.errors.some(error=>error.severity==='error'),false,'successful Core plus a Frames warning contains no profile error');
const irrelevantFramesFixture=fakeScraper(),irrelevantFramesResult=await adapterFor(irrelevantFramesFixture.scraper,fetchFixture({framesBody:{statusCode:87,statusTitle:'לא נמצאו כרטיסים רלוונטיים להצגה',result:null}}),'quick').scrape();
assert.equal(irrelevantFramesResult.coreComplete,true);assert.equal(irrelevantFramesResult.errors.length,0,'Frames status 87 cannot create a false provider error when monthly transactions succeed');
assert.equal(irrelevantFramesResult.accounts.every(account=>account.frameFetchStatus==='unavailable'&&account.months.every(month=>month.fetchStatus==='success')),true,'status 87 leaves frame unavailable while transaction synchronization remains fully successful');
const pendingWarningFixture=fakeScraper(),pendingWarningResult=await adapterFor(pendingWarningFixture.scraper,fetchFixture({pendingBody:{statusCode:17,title:'pending unavailable'}})).scrape();
assert.equal(pendingWarningResult.coreComplete,true,'Pending is a warning component and never changes Core transaction coverage');assert(pendingWarningResult.errors.some(error=>error.component==='pending'&&error.severity==='warning'));

let rateLimitedCalls=0;const rateLimitedFixture=fakeScraper(),rateLimitedResult=await adapterFor(rateLimitedFixture.scraper,async()=>{rateLimitedCalls++;return response('',{status:429,headers:{'retry-after':'7200'}})}).scrape();
assert.equal(rateLimitedCalls,1,'after the first 429 the current Cal session performs no additional Frames, Pending or monthly HTTP calls');
assert.equal(rateLimitedResult.coreComplete,false);assert(rateLimitedResult.errors.some(error=>error.severity==='deferred'&&error.component==='core_transactions'));

const shape=safeCreditResponseShape({statusCode:1,title:'secret title',authorization:'Bearer secret-token',result:{bankIssuedCards:{nextTotalDebitForAccount:987654,cardLevelFrames:[{cardUniqueId:'full-sensitive-card-id',nextTotalDebit:123456}]}}}),shapeSerialized=JSON.stringify(shape),shapeHash=responseShapeFingerprint(shape);
assert.deepEqual(shape.topLevelKeys,['authorization','result','statusCode','title']);
assert.equal(shape.statusCode,1,'safe diagnostics retain only the numeric Cal provider status code needed to distinguish semantic null responses');
assert.equal(shape.bankIssuedCards.cardLevelFrames.count,1);assert.equal(shape.bankIssuedCards.cardLevelFrames.type,'array');
for(const secret of ['Bearer secret-token','full-sensitive-card-id','987654','123456'])assert.equal(shapeSerialized.includes(secret),false,`safe response shape excludes response value ${secret}`);
assert.equal(shapeHash.length,24);assert.equal(shapeHash,responseShapeFingerprint(safeCreditResponseShape({statusCode:2,title:'different values',authorization:'changed',result:{bankIssuedCards:{nextTotalDebitForAccount:1,cardLevelFrames:[{cardUniqueId:'other'}]}}})),'shape fingerprints depend only on structure/presence, never response values');

let policyCredentials=null,policyUrl='https://www.cal-online.co.il/dashboard';const policyPage={evaluate:async()=>policyUrl,url:()=>policyUrl,frames:()=>[],click:async()=>{}};const policyScraper={page:policyPage,getLoginOptions:credentials=>{policyCredentials=credentials;return {loginUrl:'https://www.cal-online.co.il/',waitUntil:undefined,checkReadiness:async()=>{},preAction:async()=>{},postAction:async()=>{throw new Error('the upstream navigation wait must be replaced')},possibleResults:{SUCCESS:[/dashboard/i]},fields:[],submitButtonSelector:'button'}}};
applyVisaCalLoginNavigationPolicy(policyScraper,{loginResultTimeoutMs:1000,loginResultPollMs:25});const policyOptions=policyScraper.getLoginOptions({username:'safe-user',password:'safe-password'});
assert.equal(policyOptions.waitUntil,'domcontentloaded','Cal initial navigation waits only for DOMContentLoaded; the upstream explicit login-button readiness gate remains the authority');assert.equal(policyOptions.loginUrl,'https://www.cal-online.co.il/');assert.equal(policyCredentials.username,'safe-user');assert.equal(policyScraper.__netunimLoginStep,'navigation');await policyOptions.checkReadiness();assert.equal(policyScraper.__netunimLoginStep,'open-login-popup');await policyOptions.preAction();assert.equal(policyScraper.__netunimLoginStep,'credentials-submit');await policyOptions.postAction();assert.equal(policyScraper.__netunimLoginStep,'result-detection','Cal post-submit synchronization uses upstream result detection instead of a main-page navigation event');
let changePasswordChecks=0;const changePasswordFrame={url:()=> 'https://connect.cal-online.co.il/change-password'},changePasswordPage={evaluate:async()=> 'https://www.cal-online.co.il/',url:()=> 'https://www.cal-online.co.il/',frames:()=>[changePasswordFrame],click:async()=>{}};const changePasswordScraper={page:changePasswordPage,getLoginOptions:()=>({loginUrl:'https://www.cal-online.co.il/',fields:[],submitButtonSelector:'button',possibleResults:{SUCCESS:[/dashboard/i],CHANGE_PASSWORD:[async({page})=>{changePasswordChecks++;return page.frames().some(frame=>frame.url().includes('/change-password'))}]}})};
applyVisaCalLoginNavigationPolicy(changePasswordScraper,{loginResultTimeoutMs:1000,loginResultPollMs:25});await changePasswordScraper.getLoginOptions({}).postAction();assert.equal(changePasswordChecks,1,'Cal reuses the installed scraper possibleResults function for iframe-local change-password detection rather than copying provider selectors');
let invalidChecks=0;const invalidFrame={url:()=> 'https://connect.cal-online.co.il/login'},invalidPage={evaluate:async()=> 'https://www.cal-online.co.il/',url:()=> 'https://www.cal-online.co.il/',frames:()=>[invalidFrame],click:async()=>{}};const invalidScraper={page:invalidPage,getLoginOptions:()=>({loginUrl:'https://www.cal-online.co.il/',fields:[],submitButtonSelector:'button',possibleResults:{INVALID_PASSWORD:[async()=>{invalidChecks++;return true}]}})};
applyVisaCalLoginNavigationPolicy(invalidScraper,{loginResultTimeoutMs:1000,loginResultPollMs:25});await invalidScraper.getLoginOptions({}).postAction();assert.equal(invalidChecks,1,'Cal upstream invalid-password detector stays authoritative');
const routedInvalidFrame={url:()=>invalidPasswordUrl('שם המשתמש או הסיסמה שהוזנו שגויים')},routedInvalidPage={evaluate:async()=> 'https://www.cal-online.co.il/',url:()=> 'https://www.cal-online.co.il/',frames:()=>[routedInvalidFrame],click:async()=>{}};const routedInvalidScraper={page:routedInvalidPage,getLoginOptions:()=>({loginUrl:'https://www.cal-online.co.il/',fields:[],submitButtonSelector:'button',possibleResults:{INVALID_PASSWORD:[async()=>false]}})};applyVisaCalLoginNavigationPolicy(routedInvalidScraper,{loginResultTimeoutMs:1000,loginResultPollMs:25});const routedInvalidOptions=routedInvalidScraper.getLoginOptions({});await routedInvalidOptions.postAction();assert.equal(await routedInvalidOptions.possibleResults.INVALID_PASSWORD[0]({page:routedInvalidPage}),true,'Cal augments possibleResults itself so both the local postAction and upstream BaseScraper classify the new iframe error as INVALID_PASSWORD');
const sessionUrl='https://www.cal-online.co.il/',authenticatedSessionPage={evaluate:async fn=>String(fn).includes('sessionStorage.getItem')?'authenticated':sessionUrl,url:()=>sessionUrl,frames:()=>[],click:async()=>{}};const authenticatedSessionScraper={page:authenticatedSessionPage,getLoginOptions:()=>({loginUrl:sessionUrl,fields:[],submitButtonSelector:'button',possibleResults:{SUCCESS:[/dashboard/i]}})};applyVisaCalLoginNavigationPolicy(authenticatedSessionScraper,{loginResultTimeoutMs:1000,loginResultPollMs:25});const authenticatedSessionOptions=authenticatedSessionScraper.getLoginOptions({});assert.equal(await visaCalHasAuthenticatedSessionState(authenticatedSessionPage),true,'Cal treats the same init + auth-module sessionStorage contract used by getCards/getAuthorizationHeader as authenticated state');await authenticatedSessionOptions.postAction();assert.equal(await authenticatedSessionOptions.possibleResults.SUCCESS[0]({page:authenticatedSessionPage}),true,'Cal login can complete from authoritative authenticated session state even when the SPA main URL never becomes /dashboard');
const partialSessionPage={evaluate:async fn=>String(fn).includes('sessionStorage.getItem')?'init-only':sessionUrl,url:()=>sessionUrl,frames:()=>[],click:async()=>{}};const partialSessionScraper={page:partialSessionPage,getLoginOptions:()=>({loginUrl:sessionUrl,fields:[],submitButtonSelector:'button',possibleResults:{SUCCESS:[/dashboard/i]}})};applyVisaCalLoginNavigationPolicy(partialSessionScraper,{loginResultTimeoutMs:80,loginResultPollMs:25});await assert.rejects(()=>partialSessionScraper.getLoginOptions({}).postAction(),error=>error.name==='TimeoutError'&&error.loginState==='session-init-only','Cal never promotes partial init-only session state to success and preserves a bounded safe timeout state for diagnostics');
let tutorialUrl='https://www.cal-online.co.il/site-tutorial',tutorialClicks=0;const tutorialPage={evaluate:async()=>tutorialUrl,url:()=>tutorialUrl,frames:()=>[],click:async selector=>{assert.equal(selector,'button.btn-close');tutorialClicks++;tutorialUrl='https://www.cal-online.co.il/dashboard'}};const tutorialScraper={page:tutorialPage,getLoginOptions:()=>({loginUrl:'https://www.cal-online.co.il/',fields:[],submitButtonSelector:'button',possibleResults:{SUCCESS:[/dashboard/i]}})};
applyVisaCalLoginNavigationPolicy(tutorialScraper,{loginResultTimeoutMs:1000,loginResultPollMs:25});await tutorialScraper.getLoginOptions({}).postAction();assert.equal(tutorialClicks,1,'Cal site tutorial is closed once and result detection continues to the upstream dashboard success condition');
assert.throws(()=>applyVisaCalLoginNavigationPolicy({}),error=>error.code==='CREDIT_CONNECTOR_COMPATIBILITY_ERROR'&&error.stage==='LoginSetup','a future incompatible upstream Cal login contract fails closed instead of silently dropping the navigation policy');
const missingResultsScraper={getLoginOptions:()=>({loginUrl:'https://www.cal-online.co.il/',fields:[],submitButtonSelector:'button'})};applyVisaCalLoginNavigationPolicy(missingResultsScraper);assert.throws(()=>missingResultsScraper.getLoginOptions({}),error=>error.code==='CREDIT_CONNECTOR_COMPATIBILITY_ERROR'&&error.stage==='LoginSetup','Cal refuses to invent local result selectors if a future upstream version removes possibleResults');

const initFixture=fakeScraper({getCards:async()=>{throw new Error('init missing')}});
await assert.rejects(()=>adapterFor(initFixture.scraper,fetchFixture()).scrape(),error=>error.code==='CREDIT_SESSION_INIT_MISSING');
const authFixture=fakeScraper({getAuthorizationHeader:async()=>{throw new Error('auth missing')}});
await assert.rejects(()=>adapterFor(authFixture.scraper,fetchFixture()).scrape(),error=>error.code==='CREDIT_AUTH_TOKEN_MISSING');
const loginFixture=fakeScraper({login:async()=>{throw new Error('failed to extract login iframe #regular-login')}});
await assert.rejects(()=>adapterFor(loginFixture.scraper,fetchFixture()).scrape(),error=>error.code==='CREDIT_LOGIN_UI_UNAVAILABLE');
const loginTimeoutFixture=fakeScraper({login:async()=>{const error=new Error('Navigation timeout of 45000 ms exceeded');error.name='TimeoutError';error.loginState='connect-frame';throw error}}),loginTimeoutEvents=[];
await assert.rejects(()=>adapterFor(loginTimeoutFixture.scraper,fetchFixture(),'quick',{onDiagnostic:event=>loginTimeoutEvents.push(event)}).scrape(),error=>error.code==='CREDIT_LOGIN_TIMEOUT'&&error.stage==='LoginFlow');
const loginTimeoutEvent=loginTimeoutEvents.find(event=>event.errorClass==='CREDIT_LOGIN_TIMEOUT');assert(loginTimeoutEvent,'Cal navigation timeout emits a dedicated LoginFlow diagnostic');assert.equal(loginTimeoutEvent.stage,'LoginFlow');assert.equal(loginTimeoutEvent.connectorVersion,VISA_CAL_PROVIDER_SCHEMA_VERSION);assert.equal(typeof loginTimeoutEvent.durationMs,'number');assert.equal(loginTimeoutEvent.loginStep,'navigation','Cal login timeout diagnostics preserve a bounded sub-step without raw page data');assert.equal(loginTimeoutEvent.loginState,'connect-frame','Cal timeout diagnostics preserve only the bounded state class, never a raw issuer URL or token');

const retryBase=Date.parse('2026-09-03T06:00:00.000Z');
assert.equal(parseRetryAfter('7200',retryBase),'2026-09-03T08:00:00.000Z');
assert.equal(classifyCreditHttpResponse({status:429,text:'',stage:'Pending',retryAfter:'7200',now:retryBase}).retryAfterAt,'2026-09-03T08:00:00.000Z','Retry-After controls the next eligible attempt');

const diagnostic=sanitizeCreditDiagnosticEvent({provider:'amex',profileId:'p',syncMode:'forecast',browserMode:'headless',browserProduct:'edge',clientHintsState:'preserved',browserMajorVersion:152,userAgent:'Mozilla secret fingerprint',userAgentMetadata:{brands:[{brand:'secret',version:'152'}]},stage:'LoginPage',httpStatus:403,responseShape:shape,startupFailureReason:'timeout',identityState:'legacy_unverified',profileRecovery:'fresh_profile',launchAttempt:2,providerStatus:'2',providerReturnCode:'E',username:'secret-user',password:'secret-password',rawHtml:'<html>secret</html>',authorization:'Bearer secret'}),serializedDiagnostic=JSON.stringify(diagnostic);
assert.equal(serializedDiagnostic.includes('secret'),false,'diagnostics use an allowlist and cannot retain credentials, tokens, raw HTML, User-Agent or raw Client Hints');
assert.equal(diagnostic.httpStatus,403);assert.equal(diagnostic.syncMode,'forecast');assert.equal(diagnostic.browserMode,'headless');assert.equal(diagnostic.browserProduct,'edge');assert.equal(diagnostic.clientHintsState,'preserved');assert.equal(diagnostic.browserMajorVersion,152);assert.equal(diagnostic.fingerprint.length,16);assert.equal(diagnostic.startupFailureReason,'timeout');assert.equal(diagnostic.identityState,'legacy_unverified');assert.equal(diagnostic.profileRecovery,'fresh_profile');assert.equal(diagnostic.launchAttempt,2);assert.equal(diagnostic.providerStatus,'2');assert.equal(diagnostic.providerReturnCode,'E');const boundedIdentityDiagnostic=sanitizeCreditDiagnosticEvent({provider:'amex',stage:'BrowserIdentity',errorClass:'CREDIT_BROWSER_IDENTITY_UNAVAILABLE',clientHintsState:'override-failed'});assert.equal(boundedIdentityDiagnostic.clientHintsState,'override-failed');const boundedLoginDiagnostic=sanitizeCreditDiagnosticEvent({provider:'visaCal',stage:'LoginFlow',errorClass:'CREDIT_LOGIN_TIMEOUT',loginStep:'open-login-popup',loginState:'session-auth-only'});assert.equal(boundedLoginDiagnostic.loginStep,'open-login-popup');assert.equal(boundedLoginDiagnostic.loginState,'session-auth-only');assert.equal(JSON.stringify(sanitizeCreditDiagnosticEvent({loginStep:'selector:#secret',loginState:'raw-url:https://secret'})).includes('secret'),false,'unknown Cal login details and raw login state are dropped by the diagnostic allowlist');
assert.equal(diagnostic.responseShapeFingerprint,shapeHash);assert.equal(diagnostic.responseShape.statusCode,1);assert.equal(serializedDiagnostic.includes('full-sensitive-card-id'),false);
const diagnosticOverrideRoot=await fs.mkdtemp(path.join(os.tmpdir(),'netunim-credit-diagnostic-version-'));try{const log=createCreditDiagnosticLog({directory:diagnosticOverrideRoot,bridgeVersion:42,connectorVersion:'israeli-bank-scrapers-6.10.0'});await log.record({provider:'amex',stage:'LoginApi',connectorVersion:AMEX_DIGITAL_V3_SCHEMA_VERSION});assert.equal((await log.summary({limit:1}))[0].connectorVersion,AMEX_DIGITAL_V3_SCHEMA_VERSION,'Amex v41 diagnostics identify the local DigitalV3 connector instead of the unrelated published 6.10 Amex implementation')}finally{await fs.rm(diagnosticOverrideRoot,{recursive:true,force:true})}

const identityRoot=await fs.mkdtemp(path.join(os.tmpdir(),'netunim-credit-v2-'));
try{
  const identityDir=creditIdentityDirectory(path.join(identityRoot,'credit-identities'),{provider:'amex',credentials:{id:'123456789'}}),otherDir=creditIdentityDirectory(path.join(identityRoot,'credit-identities'),{provider:'amex',credentials:{id:'987654321'}}),launches=[];
  const fakeCamoufox=async options=>{launches.push(structuredClone(options));if(!options.config['navigator.userAgent'])options.config['navigator.userAgent']='stable-firefox';if(!options.config['canvas:seed'])options.config['canvas:seed']=12345;return {close:async()=>{}}};
  await launchCamoufox(fakeCamoufox,{identityDir,enableCache:true});await launchCamoufox(fakeCamoufox,{identityDir,enableCache:true});
  assert.equal(launches.length,2);assert.equal(launches[0].user_data_dir,launches[1].user_data_dir,'two launches reuse the same persistent BrowserContext directory');
  assert.equal(launches[1].config['navigator.userAgent'],'stable-firefox');assert.equal(launches[1].config['canvas:seed'],12345,'the generated identity config and anti-fingerprinting seed survive a restart');
  const recoveryDir=creditIdentityDirectory(path.join(identityRoot,'credit-identities'),{provider:'amex',credentials:{id:'555555555'}}),recoveryLaunches=[];
  const flakyCamoufox=async options=>{recoveryLaunches.push(structuredClone(options));if(recoveryLaunches.length===1){options.config['poisoned:seed']='must-not-persist';throw new Error('browserType.launchPersistentContext: Timeout 180000ms exceeded')}options.config['navigator.userAgent']='recovered-firefox';return {close:async()=>{}}};
  await launchCamoufox(flakyCamoufox,{identityDir:recoveryDir,enableCache:true});
  assert.equal(recoveryLaunches.length,2,'a local BrowserContext startup failure gets exactly one bounded retry before any issuer navigation exists');
  assert.equal(recoveryLaunches[1].config['poisoned:seed'],undefined,'a config mutated by a failed launch is never committed into the retry candidate');
  const recoveredIdentity=JSON.parse(await fs.readFile(path.join(recoveryDir,'camoufox-identity.json'),'utf8'));
  assert.equal(recoveredIdentity['navigator.userAgent'],'recovered-firefox');assert.equal(recoveredIdentity['poisoned:seed'],undefined,'only the identity from a successful BrowserContext launch becomes durable');
  assert.equal(JSON.parse(await fs.readFile(path.join(recoveryDir,'camoufox-ready.json'),'utf8')).version,1,'successful startup marks the persistent identity as locally verified');
  const failedDir=creditIdentityDirectory(path.join(identityRoot,'credit-identities'),{provider:'amex',credentials:{id:'444444444'}});let failedLaunches=0;
  await assert.rejects(()=>launchCamoufox(async options=>{failedLaunches++;options.config['failed:seed']=failedLaunches;throw new Error('browserType.launchPersistentContext: Timeout 180000ms exceeded')},{identityDir:failedDir}),error=>error.code==='CREDIT_CAMOUFOX_STARTUP_FAILED'&&error.stage==='BrowserLaunch'&&error.startupFailureReason==='timeout');
  assert.equal(failedLaunches,2,'startup recovery is bounded and cannot turn into an identity-generation loop');
  await assert.rejects(()=>fs.stat(path.join(failedDir,'camoufox-identity.json')),error=>error.code==='ENOENT','a never-started identity is not persisted after both local attempts fail');
  await fs.mkdir(otherDir,{recursive:true});await fs.writeFile(path.join(otherDir,'keep.txt'),'keep');
  await deleteCreditIdentity(path.join(identityRoot,'credit-identities'),{provider:'amex',credentials:{id:'123456789'}});
  await assert.rejects(()=>fs.stat(identityDir),error=>error.code==='ENOENT');assert.equal((await fs.readFile(path.join(otherDir,'keep.txt'),'utf8')),'keep','deleting one connection removes only its browser identity');
  const diagnosticLog=createCreditDiagnosticLog({directory:path.join(identityRoot,'diagnostics'),maxBytes:64,fileCount:2,retentionMs:100});
  await diagnosticLog.record({provider:'amex',stage:'old'});await fs.utimes(diagnosticLog.logPath,new Date(0),new Date(0));await diagnosticLog.record({provider:'max',stage:'new'});
  assert.deepEqual((await diagnosticLog.summary()).map(event=>event.provider),['max'],'expired diagnostics are pruned before a new event can revive an old log file');
  await diagnosticLog.record({provider:'visaCal',stage:'rotate'});assert.equal((await diagnosticLog.summary()).length,2,'diagnostic rotation stays within its configured file count');
}finally{await fs.rm(identityRoot,{recursive:true,force:true})}

console.log('PASS Credit Connector v2: monthly Cal isolation, core/forecast coverage, persistent identity, Retry-After and safe diagnostics are deterministic');
