import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8');

test('orders site exposes one unified search with site, file and content filters over loopback bridge',()=>{
  const html=read('netunim-orders/site/index.html');
  const main=read('netunim-orders/site/assets/js/main.js');
  const client=read('netunim-orders/site/assets/js/domains/documents/bridge.js');
  const headers=read('netunim-orders/site/_headers');
  assert.match(html,/global-search-head[\s\S]*global-search-input-wrap/);
  assert.doesNotMatch(html,/globalSearchSiteMode|globalSearchDocumentsMode|globalSearchDocumentNameMode|globalSearchDocumentContentMode/);
  assert.match(html,/globalSearchFilterAll[\s\S]*הכל<\/button>[\s\S]*globalSearchFilterSite[\s\S]*חיפוש באתר<\/button>[\s\S]*globalSearchFilterFiles[\s\S]*חיפוש קבצים<\/button>[\s\S]*globalSearchFilterContent[\s\S]*חיפוש תוכן<\/button>/);
  assert.match(html,/globalSearchFilterAll[^>]*class="global-search-filter active"[^>]*aria-selected="true"/);
  assert.match(html,/id="globalSearchFileType"[\s\S]*value="all"[\s\S]*>הכל<[\s\S]*value="audio"[\s\S]*>אודיו<[\s\S]*value="documents"[\s\S]*>מסמכים<[\s\S]*value="folders"[\s\S]*>תיקיות<[\s\S]*value="images"[\s\S]*>תמונות<[\s\S]*value="video"[\s\S]*>וידאו<[\s\S]*value="pdf"[\s\S]*>PDF<[\s\S]*value="word"[\s\S]*>Word</);
  assert.match(html,/globalSearchDocumentPreview/);
  assert.doesNotMatch(html,/globalSearchPreviewTitle|globalSearchPreviewMeta|globalSearchPreviewOpen|פתח במחשב/);
  assert.match(html,/globalSearchPreviewMatches/);
  assert.match(main,/createDomainsDocumentBridge/);
  assert.match(main,/documentBridge:domainsDocumentBridge/);
  assert.match(client,/http:\/\/127\.0\.0\.1:8766/);
  assert.match(client,/mode==='content'\?'content':'everything'/);
  assert.match(client,/documents\/warm/);
  assert.match(client,/documents\/recent/);
  assert.match(client,/recent=async\(\{limit=150,scopePath='',fileType='all',signal=null\}/);
  assert.match(client,/fileType:String\(fileType\|\|'all'\)/);
  assert.match(client,/documents\/select-folder/);
  assert.match(client,/const selectFolder=async\(\)=>\{try\{const runtime=await health\(\);requireBridgeVersion/);
  assert.match(client,/documents\/preview/);
  assert.match(client,/documents\/preview-file/);
  assert.match(client,/documents\/matches/);
  assert.match(client,/documents\/native-preview/);
  assert.match(client,/nativePreview/);
  assert.match(headers,/connect-src[^\n]*http:\/\/127\.0\.0\.1:8766/);
});

test('manual PDF refresh is a separate search action backed by the short-lived maintenance worker',()=>{
  const orders=read('netunim-orders/site/index.html'),kupa=read('netunim-kupa/site/index.html');
  const server=read('netunim-orders/document-bridge/server.mjs');
  const client=read('shared/document-search/domains/documents/bridge.js');
  const source=read('shared/document-search/domains/documents/search-source.js');
  for(const html of [orders,kupa]){
    const inputIndex=html.indexOf('id="globalSearchInput"');
    const menuIndex=html.indexOf('id="globalSearchContentOptionsMenu"');
    const folderIndex=html.indexOf('id="globalSearchFolderScope"');
    const refreshIndex=html.indexOf('id="globalSearchPdfRefresh"');
    const wholeWordIndex=html.indexOf('data-content-word-match="whole"');
    assert.ok(inputIndex>=0&&menuIndex>inputIndex&&refreshIndex>wholeWordIndex&&refreshIndex<folderIndex,'PDF refresh must live at the end of the content-options popover, not in the search header row');
    assert.match(html,/globalSearchPdfRefreshStatus[^>]*role="status"[^>]*aria-live="polite"/);
  }
  assert.match(server,/documents\/pdf-index\/status/);
  assert.match(server,/documents\/pdf-index\/start/);
  assert.match(server,/documents\/pdf-index\/stop/);
  assert.match(server,/spawn\(process\.execPath,\[fileURLToPath\(import\.meta\.url\),'--refresh-pdf-index','--force'\]/);
  assert.match(server,/manualPdfMaintenance\?\.running\|\|await activePdfMaintenanceLock\(\)/);
  assert.match(server,/pdfFormIndexRefreshAbortController\?\.abort\(\)/);
  assert.match(server,/await compactPdfFormIndex\(\{pending,pdfCount:pdfFormIndexInventoryCount\}\)/);
  assert.match(client,/pdfIndexRequest\('\/documents\/pdf-index\/start'/);
  assert.match(client,/DOCUMENT_BRIDGE_UPGRADE_REQUIRED/);
  assert.match(source,/get supportsPdfIndexRefresh/);
  assert.match(source,/return localBridge\.startPdfIndex\(\)/);
});

test('bridge searches the complete Everything index and forces Unicode ES transport',()=>{
  const installer=read('netunim-orders/document-bridge/install_document_bridge.bat');
  const server=read('netunim-orders/document-bridge/server.mjs');
  const lib=read('netunim-orders/document-bridge/lib.mjs');
  const pdfIndex=read('netunim-orders/document-bridge/pdf_form_index.mjs');
  const policy=read('netunim-orders/document-bridge/pdf-index-policy.mjs');
  const client=read('shared/document-search/domains/documents/bridge.js');
  assert.match(installer,/--ensure-everything/);
  assert.doesNotMatch(installer,/configure_document_bridge\.ps1/);
  assert.match(server,/scope=everything-index/);
  assert.doesNotMatch(server,/config\.roots/);
  assert.doesNotMatch(server,/pathInsideRoot/);
  assert.match(lib,/'-argv','-cp','65001','-ipc3'/);
  assert.match(lib,/'--',String\(search\)/);
  assert.match(lib,/'-max-results',String\(count\)/);
  assert.doesNotMatch(lib,/'-search',String\(search\)/);
  assert.doesNotMatch(lib,/'-n',String\(count\)/);
  assert.doesNotMatch(lib,/'-path',rootPath/);
  assert.match(lib,/'-path',scope/);
  assert.match(lib,/normalizeSearchScopePath/);
  assert.match(server,/probeEverything\(\{fresh:true,autoStart:true\}\)/);
  assert.match(server,/everythingProbePromise/);
  assert.match(server,/Promise\.any\(candidates\.map\(instance=>probeOne\(instance\)\)\)/);
  assert.match(server,/filter\(instance=>!preferred\|\|instance!==preferred\)/);
  assert.match(server,/documents\/warm/);
  assert.match(server,/documents\/recent/);
  assert.match(server,/documents\/select-folder/);
  assert.match(server,/PICK_FOLDER/);
  assert.match(server,/RECENT scope=everything-index scopePath=.* fileType=\$\{normalizedFileType\} sort=date-modified-descending/);
  assert.match(server,/cachedEsPath/);
  assert.match(server,/listen\(BRIDGE_PORT,'127\.0\.0\.1'/);
  assert.match(server,/refreshPdfFormIndex/);
  assert.match(server,/searchPdfFormIndex/);
  assert.match(server,/scope=everything-index\+interactive-pdf/);
  assert.match(server,/extractInteractivePdfText/);
  assert.match(server,/buildPdfFormMatchAnchors/,'interactive PDF preview matches must retain Bridge-known page geometry');
  assert.match(server,/formAnchorsAuthoritative=formMatchInfo\.anchors\.length>0/,'an empty Bridge geometry payload must never suppress the browser PDF annotation fallback');
  assert.match(server,/PDF_FORM_INDEX_SCHEMA=3/,'AcroForm revisions and geometry remain persisted');
  assert.match(server,/PDF_FORM_DETECTION_REVISION=2/);
  assert.match(server,/PDF_FORM_SEARCH_TEXT_REVISION=2/);
  assert.match(server,/PDF_FORM_GEOMETRY_REVISION=1/);
  assert.match(server,/fingerprintCurrent&&detectionCurrent&&cached&&!cached\.hasForm&&!cached\.failed/,'only current-fingerprint negative PDF records may suppress on-demand form reinspection');
  assert.match(policy,/if\(Number\(existing\.detectionRevision\)<detectionRevision\)return true/);
  assert.match(policy,/return Number\(existing\.searchTextRevision\)<searchTextRevision/);
  assert.match(server,/previewTextCache\.delete\(key\)/,'form-index upgrades invalidate stale preview text cache entries');
  assert.doesNotMatch(server,/geometryCurrent=.*formFields/,'missing geometry must not trigger a library-wide reindex');
  assert.match(server,/includePageText:!geometryOnly/,'legacy preview migration must recover geometry without re-reading every page text layer');
  assert.match(server,/extractPdfOnDemand\(fullPath/,'preview enrichment must run in a short-lived process');
  assert.match(pdfIndex,/collectPdfFormFields/,'interactive PDF index must persist field page and rectangle metadata');
  assert.match(pdfIndex,/buildPdfFormMatchAnchors/,'interactive PDF index must map value hits back to field geometry');
  assert.match(pdfIndex,/pdfjs\/legacy\/build\/pdf\.mjs/,'Node bridge must prefer the PDF.js legacy build recommended for Node.js');
  assert.doesNotMatch(pdfIndex,/pdfjs\/build\/pdf\.mjs/,'Node extraction must fail fast instead of silently falling back to the browser modern build');
  assert.match(pdfIndex,/PDFJS_NODE_LEGACY_RUNTIME_MISSING/,'missing Node legacy runtime must fail with a diagnosable error');
  assert.match(pdfIndex,/PDFJS_NODE_INTEGRITY_MISMATCH/,'Node legacy runtime must be checked against the pinned vendor manifest');
  assert.match(pdfIndex,/mode:'text-extraction-only'/,'Node PDF.js runtime must declare that it is used only for text/annotation extraction');
  assert.match(pdfIndex,/shouldSuppressTextOnlyImportWarnings/,'known PDF.js optional-canvas warnings should be classified instead of leaking as installer errors');
  assert.match(pdfIndex,/Cannot find module \'@napi-rs\/canvas\'/,'only the exact missing optional canvas package warning may be suppressed');
  assert.doesNotMatch(pdfIndex,/console\.warn=\(\.\.\.args\)=>\{\}/,'PDF.js warnings must never be disabled wholesale');
  assert.match(server,/verifyNodePdfJsRuntime\(\)/,'installer doctor must import and validate the Node legacy runtime before activation');
  assert.match(installer,/pdf_form_index\.mjs/);
  assert.match(installer,/pdf-index-policy\.mjs/);
  assert.match(installer,/pdf-extract-worker\.mjs/);
  assert.match(installer,/assets\\vendor\\pdfjs/);
  assert.doesNotMatch(installer,/--refresh-pdf-index --install-warmup/,'installer must never block on PDF indexing');
  assert.match(server,/PDF_FORM_MAINTENANCE_MAX_FILES=300/);
  assert.match(server,/PDF_FORM_MAINTENANCE_MAX_MS=15\*60\*1000/);
  assert.doesNotMatch(server,/schedulePdfFormIndexRefresh/,'the always-on listener must not schedule PDF parsing');
  const nodeInstaller=read('netunim-orders/document-bridge/install_node_runtime.ps1');
  const startBridge=read('netunim-orders/document-bridge/start_document_bridge.bat');
  const configureBridge=read('netunim-orders/document-bridge/configure_document_bridge.bat');
  const maintenanceRunner=read('netunim-orders/document-bridge/run_pdf_maintenance.ps1');
  assert.doesNotMatch(installer,/where node/i,'installer must not resolve the Bridge runtime through PATH');
  assert.match(installer,/install_node_runtime\.ps1/,'installer must provision the private Node runtime before staging the Bridge');
  assert.match(installer,/node-runtime\.txt/,'installer must activate private Node through an explicit pointer');
  assert.match(installer,/process\.versions\.node==='24\.21\.0'/,'installer must verify the exact reviewed Node version');
  assert.ok(installer.indexOf('install_node_runtime.ps1')<installer.indexOf('mkdir "%STAGING%"'),'private Node must be verified before Bridge staging starts');
  assert.match(nodeInstaller,/\$version = '24\.21\.0'/);
  assert.match(nodeInstaller,/https:\/\/nodejs\.org\/download\/release\/v\$version\/\$asset/);
  assert.match(nodeInstaller,/158f7685b44de51f6c0df1d153526cbcd3e1bc739a8dfc607721cef75de9e541/,'private Node archive must be pinned to the reviewed official SHA-256');
  assert.match(nodeInstaller,/ba4e6d110e8c1592a1ecd390f6b05f3da124b13871a5be62b341a07a853c6c32/,'extracted node.exe must be pinned independently');
  assert.match(nodeInstaller,/Downloads/,'filtered PCs must support a verified local Node archive');
  assert.match(nodeInstaller,/TimeoutSec/,'network Node download must have a bounded timeout');
  assert.doesNotMatch(nodeInstaller,/latest/i,'private Node installer must never follow a moving latest alias');
  assert.ok(nodeInstaller.indexOf('Assert-ArchiveHash $archivePath')<nodeInstaller.indexOf('Extract-NodeExecutable $archivePath'),'Node archive must be verified before extraction');
  assert.match(nodeInstaller,/Get-FileHash[^\n]*SHA256/,'downloaded Node binary must be hashed before activation');
  assert.match(nodeInstaller,/Move-Item[^\n]*\$tempPointer[^\n]*\$pointerPath[^\n]*-Force/,'Node pointer activation must be a single-file replacement after verification');
  assert.match(lib,/BRIDGE_NODE_VERSION='24\.21\.0'/);
  assert.match(lib,/BRIDGE_NODE_WIN_X64_SHA256='ba4e6d110e8c1592a1ecd390f6b05f3da124b13871a5be62b341a07a853c6c32'/);
  assert.match(server,/privateNodeRuntimeInfoSync/,'Windows Bridge must validate that process.execPath is the private pinned runtime');
  assert.match(server,/NODE_RUNTIME_NOT_PRIVATE/);
  assert.match(server,/NODE_RUNTIME_INTEGRITY_MISMATCH/);
  assert.match(startBridge,/node-runtime\.txt/);
  assert.doesNotMatch(startBridge,/(?:^|[\s"])(?:node|node\.exe)[ \t]+"%~dp0server\.mjs"/im,'normal startup must not use a PATH-resolved Node executable');
  assert.match(configureBridge,/active-runtime\.txt/,'manual configuration must resolve the active side-by-side Bridge runtime');
  assert.doesNotMatch(configureBridge,/set "APPDIR=%APPROOT%\\app"/i,'manual configuration must not use the removed legacy app directory');
  assert.match(configureBridge,/node-runtime\.txt/,'manual configuration must use the same private Node pointer');
  assert.match(maintenanceRunner,/node-runtime\.txt/,'scheduled PDF maintenance must use the same private Node pointer');
  assert.doesNotMatch(maintenanceRunner,/Get-Command node\.exe/i,'scheduled maintenance must never fall back to PATH');
  assert.match(installer,/--doctor --allow-unready-task/,'pre-activation doctor may inspect a missing, disabled or stale Task Scheduler registration without accepting it after activation');
  assert.match(installer,/install_pdf_maintenance_task\.ps1/);
  assert.ok(installer.indexOf('set \"TASKUPDATED=yes\"')<installer.indexOf('\"%NODE_EXE%\" \"%RUNTIME%\\server.mjs\" --doctor'),'strict doctor must validate the newly registered task after it joins the activation transaction');
  const task=read('netunim-orders/document-bridge/install_pdf_maintenance_task.ps1');
  assert.match(task,/New-ScheduledTaskTrigger -Daily/);
  assert.match(task,/New-ScheduledTaskSettingsSet -StartWhenAvailable/);
  assert.match(task,/Export-ScheduledTask -TaskName/,'task replacement must snapshot an existing registration before changing it');
  assert.match(task,/Restore-TaskBackup/,'task installer must have an explicit rollback path');
  assert.match(task,/Get-ScheduledTaskInfo -TaskName/,'task installer must validate runtime scheduling metadata after registration');
  assert.match(task,/NextRunTime/,'task installer must reject a task that has no actual next run');
  assert.match(installer,/set "TASKUPDATED=yes"/,'parent installer must remember when Task Scheduler state became part of the transaction');
  assert.match(installer,/-RestoreBackup/,'parent rollback must restore Task Scheduler when a later activation check fails');
  assert.match(installer,/run_pdf_maintenance\.before-install\.ps1/,'maintenance runner must be backed up transactionally');
  assert.match(installer,/configure_document_bridge\.before-install\.bat/,'manual configuration helper must be backed up transactionally');
  assert.match(installer,/:restore_helper/,'top-level helper files must have a rollback routine');
  assert.doesNotMatch(task,/-AllowStartIfOnBatteries/);
  assert.match(task,/-MultipleInstances IgnoreNew/);
  assert.match(server,/Get-ScheduledTask -TaskName/,'doctor must query Task Scheduler directly');
  assert.match(server,/Get-ScheduledTaskInfo -TaskName/,'doctor must report Task Scheduler runtime information');
  assert.match(server,/Last Run Time/);
  assert.match(server,/Last Result/);
  assert.match(server,/Next Run Time/);
  assert.match(server,/schedule active=/,'doctor must say whether the registered schedule is actually active');
  assert.doesNotMatch(server,/schtasks(?:\.exe)?/i,'Task Scheduler diagnostics must not spawn schtasks');
  assert.equal((server.match(/pdfMaintenanceTaskDiagnostics\(\)/g)||[]).length,3,'Task Scheduler probing must stay confined to the diagnostic helper, doctor and install summary');
  assert.match(server,/hasForm:!!extracted\.hasForm/,'ordinary PDFs must be negatively cached after inspection');
  assert.match(server,/pending:pdfFormIndexPending/,'incremental progress must be persisted across restarts');
  assert.match(server,/pdf-form-index\.journal\.jsonl/,'incremental PDF inspection progress must be journaled without rewriting the whole snapshot every batch');
  assert.match(server,/PDF_FORM_RECONCILE_INTERVAL_MS=PDF_FORM_MAINTENANCE_INTERVAL_MS/);
  assert.match(server,/pdfMaintenanceInventoryPlan\(\{force,now:started/,'manual force and scheduled cadence must share the tested inventory planner');
  assert.match(server,/INSTALL_STOP_FORCE/,'upgrades must be able to terminate an old Bridge that closed the port but kept indexing');
  assert.match(server,/taskkill\.exe/);
  assert.match(installer,/Preserving local interactive PDF text index/);
  assert.match(installer,/:move_dir_with_retry/);
  assert.match(installer,/active-runtime\.txt/,'upgrades must activate a side-by-side runtime through an explicit pointer');
  assert.match(installer,/app-v37-/,'new runtime must be versioned so old Windows handles cannot block activation');
  assert.doesNotMatch(installer,/move \"%APPDIR%\"/,'installer must never rename the active runtime as a prerequisite for upgrade success');
  assert.match(installer,/stop_runtime_helpers\.ps1/,'installer should clean verified stale bridge helpers without depending on old runtime deletion');
  assert.match(server,/RUNTIME_ROOT=fileURLToPath/,'runtime-owned executables must resolve relative to the active versioned runtime');
  assert.match(server,/cwd:APP_ROOT/,'child processes must not inherit the runtime directory as their current directory');
  assert.match(server,/runEs\(esPath,args,\{timeout=18000,signal=null\}/,'ES inventory work must be abortable during shutdown');
  assert.match(server,/preparePdfFormIndexForSearch/);
  assert.doesNotMatch(server,/PDF_FORM_INDEX_INITIAL_WAIT_MS/,'content requests must never wait on a full PDF-form index refresh');
  assert.doesNotMatch(lib,/contentMatchRanges\(String\(value\?\?''\),query,\{\.\.\.options,maxMatches:5000\}\)\.ranges\.length>0/,'supplemental-index filtering must stop at boolean match semantics instead of materializing highlight ranges');
  assert.match(pdfIndex,/fileURLToPath/);
  assert.match(pdfIndex,/BinaryDataFactory:LocalPdfBinaryDataFactory/);
  assert.match(pdfIndex,/VerbosityLevel\?\.ERRORS/);
  assert.match(lib,/BRIDGE_VERSION=37/);
  assert.match(client,/EXPECTED_BRIDGE_VERSION=37/);
  assert.match(client,/requireBridgeVersion\(data\?\.bridgeVersion,'לקבל מיקומי התאמות בתוך PDF אינטראקטיבי'\)/,'preview-match geometry refuses a stale local Bridge runtime');
});

test('file and folder opening use the Windows graphical shell through UseShellExecute',()=>{
  const server=read('netunim-orders/document-bridge/server.mjs');
  assert.match(server,/System\.Diagnostics\.ProcessStartInfo/);
  assert.match(server,/UseShellExecute=\$true/);
  assert.match(server,/System\.Diagnostics\.Process\]::Start/);
  assert.doesNotMatch(server,/Shell\.Application; \$s\.Open/);
  assert.doesNotMatch(server,/execFile\('explorer\.exe'/);
  assert.match(server,/await fs\.stat\(row\.fullPath\)/);
  assert.match(server,/shell=UseShellExecute/);
  assert.match(server,/body\.id/);
  assert.doesNotMatch(server,/body\.path/);
});

test('local document results expose Explorer reveal and recycle-bin delete through opaque result ids',()=>{
  const server=read('netunim-orders/document-bridge/server.mjs');
  const client=read('netunim-orders/site/assets/js/domains/documents/bridge.js');
  const ui=read('shared/global-document-search.js');
  const menu=read('netunim-orders/site/assets/js/ui/document-result-menu.js');
  const modal=read('netunim-orders/site/assets/js/ui/modal.js');
  const css=read('shared/global-document-search.css');
  assert.match(server,/documents\/reveal/);
  assert.match(server,/documents\/delete/);
  assert.match(server,/NETUNIM_REVEAL_TARGET/);
  assert.match(server,/NETUNIM_DELETE_TARGET/);
  assert.match(server,/RecycleOption\]::SendToRecycleBin/);
  assert.match(server,/invalidateResultPath/);
  assert.doesNotMatch(server,/body\.path/);
  assert.match(client,/provider:'everything'/);
  assert.match(client,/revealDocument/);
  assert.match(client,/deleteDocument/);
  assert.match(menu,/data-document-menu-action="open"/);
  assert.match(menu,/data-document-menu-action="reveal"/);
  assert.match(menu,/data-document-menu-action="delete"/);
  assert.match(ui,/event\.key==='Delete'/);
  assert.match(menu,/confirmDialog\('למחוק את הקובץ\?'/);
  assert.match(menu,/defaultFocus:'confirm',confirmOnEnter:true/);
  assert.match(modal,/event\.key==='Enter'&&activeConfirm\.options\.confirmOnEnter===true/);
  assert.match(modal,/document\.addEventListener\('keydown',[\s\S]*\},true\);/);
  assert.match(css,/document-result-context-menu/);
});

test('preview stays local: filename Office preview stays native while content search uses controlled local document renderers',()=>{
  const server=read('netunim-orders/document-bridge/server.mjs');
  const lib=read('netunim-orders/document-bridge/lib.mjs');
  const ui=read('shared/global-document-search.js');
  const documentView=read('netunim-orders/site/assets/js/ui/document-search-view.js');
  const folderScope=read('netunim-orders/site/assets/js/ui/document-search-folder-scope.js');
  const contentOptions=read('netunim-orders/site/assets/js/ui/document-search-content-options.js');
  const client=read('netunim-orders/site/assets/js/domains/documents/bridge.js');
  const installer=read('netunim-orders/document-bridge/install_document_bridge.bat');
  const build=read('netunim-orders/document-bridge/build_native_preview.ps1');
  const host=read('netunim-orders/document-bridge/native_preview_host.cs');
  assert.match(server,/documents\/preview/);
  assert.match(server,/documents\/preview-file/);
  assert.match(server,/documents\/matches/);
  assert.match(server,/documents\/native-preview/);
  assert.match(server,/NATIVE_PREVIEW_HOST/);
  assert.match(server,/source:'windows-preview-handler'/);
  assert.match(server,/kind:'structured'/);
  assert.match(server,/structuredPreviewKind/);
  assert.match(server,/STRUCTURED_PREVIEW_MIME/);
  assert.doesNotMatch(server,/OFFICE_PREVIEW_SCRIPT/);
  assert.doesNotMatch(server,/ensureOfficePreview/);
  assert.doesNotMatch(server,/source:'office-pdf'/);
  assert.match(lib,/officePreviewKind/);
  assert.match(lib,/structuredPreviewKind/);
  assert.match(lib,/buildEsContentPreviewArgs/);
  assert.match(lib,/buildContentMatchInfo/);
  assert.match(installer,/build_native_preview\.ps1/);
  assert.match(installer,/native_preview_host\.cs/);
  assert.match(installer,/NetunimPreviewHost\.exe/);
  assert.doesNotMatch(installer,/office_preview\.ps1/);
  assert.match(build,/csc\.exe/);
  assert.match(host,/interface IPreviewHandler/);
  assert.match(host,/IInitializeWithFile/);
  assert.match(host,/IInitializeWithItem/);
  assert.match(host,/8895b1c6-b41f-4c1c-a562-0d564250836f/i);
  assert.match(host,/handler\.SetWindow/);
  assert.match(host,/handler\.SetRect/);
  assert.match(host,/handler\.DoPreview/);
  assert.match(host,/SetProcessDpiAwarenessContext/);
  assert.match(host,/PerMonitorAwareV2/);
  assert.match(host,/GetClientRect/);
  assert.match(host,/interface IOleWindow/);
  assert.match(host,/GetParent\(previewWindow\) == Handle/);
  assert.match(host,/SynchronizePreviewBounds/);
  assert.match(host,/PICK_FOLDER/);
  assert.match(host,/interface IFileOpenDialog/);
  assert.match(host,/FileOpenDialogCom/);
  assert.match(host,/PickFolders = 0x00000020/);
  assert.match(host,/ForceFileSystem = 0x00000040/);
  assert.match(host,/ModernFolderPicker\.Pick/);
  assert.doesNotMatch(host,/FolderBrowserDialog/);
  assert.match(host,/settlePassesRemaining/);
  assert.match(host,/SetWindowLongPtr/);
  assert.match(host,/SetWindowPos/);
  assert.equal([...Buffer.from(host,'utf8')].some(byte=>byte>0x7f),false,'native_preview_host.cs must remain ASCII-only');
  assert.equal([...Buffer.from(build,'utf8')].some(byte=>byte>0x7f),false,'build_native_preview.ps1 must remain ASCII-only');
  assert.match(client,/nativePreview/);
  assert.match(client,/moveNativePreview/);
  assert.match(client,/hideNativePreview/);
  assert.match(ui,/filter='all'/);
  assert.match(ui,/requestedDocumentModes/);
  assert.match(ui,/documentBridge\.search\(raw,\{mode,contentSearch:mode==='content'\?documentContentOptions\.value\(\):undefined,scopePath:documentFolderScope\.path,fileType:documentFileType\.value\(\),limit:DOCUMENT_RESULT_BATCH,offset:0/);
  assert.match(ui,/documentBridge\.recent\(\{limit:RECENT_DOCUMENT_LIMIT,scopePath:documentFolderScope\.path/);
  assert.match(folderScope,/supportsFolderScope/);
  assert.match(folderScope,/documentBridge\.selectFolder\(\)/);
  assert.match(contentOptions,/MATCH_MODES=new Set\(\['phrase','all','any','proximity'\]\)/);
  assert.match(ui,/const RECENT_DOCUMENT_LIMIT=150/);
  assert.match(ui,/const SITE_RESULT_BATCH=150/);
  assert.match(ui,/const DOCUMENT_RESULT_BATCH=150/);
  assert.match(ui,/const DOCUMENT_RESULT_MAX=5000/);
  assert.match(ui,/function loadMoreDocumentResults\(requestedMode=''\)/);
  assert.match(ui,/offset=before\.rows\.length/);
  assert.match(ui,/data-site-load-more/);
  assert.match(ui,/data-document-load-more/);
  assert.match(ui,/maybeLoadMoreDocumentResults\(\)/);
  assert.match(server,/body\.offset/);
  assert.match(server,/hasMore/);
  assert.match(client,/limit=150,offset=0/);
  assert.match(ui,/function recentDocumentLabel\(\).*?'פריטים אחרונים'.*?'תיקיות אחרונות'.*?'קבצים אחרונים'/s);

  assert.match(client,/const recent=async\(\{limit=150,scopePath='',fileType='all',signal=null\}=\{\}\)=>/);
  assert.match(server,/RECENT_RESULT_LIMIT/);
  assert.match(ui,/RECENT_DOCUMENT_TTL_MS=15000/);
  assert.match(ui,/function warmDocumentSearchBridge\(\)/);
  assert.match(ui,/documentBridge\.warm\(\)/);
  assert.match(ui,/DOCUMENT_BRIDGE_WARM_TTL_MS=25000/);
  assert.ok((ui.match(/warmDocumentSearchBridge\(\);/g)||[]).length>=2,'Bridge warm-up should run at bind time and when the search opens');
  assert.match(ui,/window\.devicePixelRatio/);
  assert.match(ui,/window\.addEventListener\('focus'/);
  assert.match(ui,/data.kind==='native'/);
  assert.match(ui,/dblclick/);
  assert.match(ui,/selectDocumentResult/);
  assert.match(documentView,/document-results-table/);
  assert.match(ui,/document-preview-frame/);
  assert.match(ui,/createTextSearchViewer/);
  assert.match(ui,/createDocxSearchViewer/);
  assert.match(ui,/createSpreadsheetSearchViewer/);
  assert.match(ui,/createPdfSearchViewer/);
  assert.match(ui,/previewSearchViewer\.previous\(\)/);
  assert.match(ui,/previewSearchViewer\.next\(\)/);
  assert.match(ui,/onPreviewSearchMatchState/);
  assert.match(documentView,/document-preview-match-term/);
  assert.match(ui,/buildPdfPreviewSrc\(previewObjectUrl,\{query\}\)/);
  assert.doesNotMatch(ui,/syncPdfPreviewMatch/);
  assert.match(ui,/loadPreviewMatches/);
  const pdfViewer=read('netunim-orders/site/assets/js/domains/documents/pdf-search-viewer.js');
  const css=read('shared/global-document-search.css');
  assert.match(pdfViewer,/PDFFindController/);
  assert.match(pdfViewer,/highlightAll:true/);
  assert.match(pdfViewer,/next\(\)\{if\(combinedReady&&combinedMatches\.length\)return goCombined\(combinedIndex\+1\);dispatch\('again',false\)\}/);
  assert.match(pdfViewer,/previous\(\)\{if\(combinedReady&&combinedMatches\.length\)return goCombined\(combinedIndex-1\);dispatch\('again',true\)\}/);
  assert.match(pdfViewer,/findPdfFormFieldMatches/);
  assert.match(pdfViewer,/buildCombinedMatches/);
  assert.match(pdfViewer,/ensurePdfFormOverlay/);
  assert.match(pdfViewer,/convertToViewportPoint/);
  assert.doesNotMatch(pdfViewer,/\.convertToViewportRectangle\b/);
  assert.match(pdfViewer,/installPdfJsBrowserCompatibility/);
  assert.match(pdfViewer,/Map\.prototype\.getOrInsertComputed/);
  assert.match(pdfViewer,/eventBus\.on\('pagerendered',renderFormLayerForEvent\)/);
  assert.match(css,/document-pdf-form-match-marker/);
  assert.match(pdfViewer,/updatefindmatchescount/);
  assert.match(pdfViewer,/currentScaleValue='page-width'/);
  assert.match(pdfViewer,/ResizeObserver/);
  assert.match(pdfViewer,/resize\(options=\{\}\)/);
  assert.match(ui,/preloadPdfSearchRuntime/);
  assert.match(ui,/previewSearchViewer\?\.resize/);
  assert.match(css,/document-pdfjs-container \.pdfViewer \.page\{box-sizing:content-box/);
  assert.match(css,/highlight\.selected\{background-color:rgba\(255,149,38,\.36\)/);
  assert.doesNotMatch(css,/highlight\.selected\{[^}]*?(?:outline|box-shadow|border)/);
  assert.doesNotMatch(pdfViewer,/import\(runtime\.(?:pdf|viewer)\)/);
  assert.match(server,/extension==='pdf'\?buildContentMatchInfo\(content\.text,query,\{\.\.\.search,contextChars:96,maxSnippets:500,maxMatches:500\}\)/);
});

test('installer keeps Everything hidden background startup and no longer asks for Bridge roots',()=>{
  const installer=read('netunim-orders/document-bridge/install_document_bridge.bat');
  const server=read('netunim-orders/document-bridge/server.mjs');
  assert.match(installer,/background mode/);
  assert.match(installer,/complete Everything index/i);
  assert.match(installer,/--doctor/);
  assert.match(installer,/--check-running/);
  assert.match(server,/'-startup','-first-instance'/);
  assert.match(server,/Search scope: complete Everything index/);
  assert.match(server,/COMPLETE EVERYTHING INDEX/);
});

test('PowerShell configurator remains code-page independent even though v4 no longer uses it during install',()=>{
  const bytes=fs.readFileSync(new URL('../netunim-orders/document-bridge/configure_document_bridge.ps1',import.meta.url));
  assert.equal([...bytes].some(byte=>byte>0x7f),false,'configure_document_bridge.ps1 must remain ASCII-only');
});

test('unified search uses a full-screen header search, four result filters and a headerless resizable preview',()=>{
  const html=read('netunim-orders/site/index.html');
  const css=read('shared/global-document-search.css');
  const ui=read('shared/global-document-search.js');
  const documentView=read('netunim-orders/site/assets/js/ui/document-search-view.js');
  const folderScope=read('netunim-orders/site/assets/js/ui/document-search-folder-scope.js');
  const contentOptions=read('netunim-orders/site/assets/js/ui/document-search-content-options.js');
  assert.doesNotMatch(html,/id="globalSearchTitle"/);
  assert.match(html,/global-search-head[\s\S]*globalSearchFilterAll[\s\S]*globalSearchFilterSite[\s\S]*globalSearchFilterFiles[\s\S]*globalSearchFilterContent[\s\S]*globalSearchInput[\s\S]*globalSearchFileType[\s\S]*globalSearchContentOptionsButton/);
  assert.match(html,/globalSearchFolderScope[\s\S]*globalSearchFolderPick[\s\S]*globalSearchFolderLabel[\s\S]*globalSearchFolderClear/);
  assert.match(css,/global-search-options-button\{/);
  assert.match(css,/global-search-options-popover\{position:fixed/);
  assert.match(css,/global-search-word-toggle/);
  assert.match(css,/global-search-folder-scope/);
  assert.match(ui,/createDocumentSearchFolderScope/);
  assert.match(folderScope,/let path='',label=''/);
  assert.match(folderScope,/async function choose\(\)/);
  assert.match(folderScope,/function clear\(\)/);
  assert.match(contentOptions,/createDocumentContentSearchOptions/);
  assert.match(contentOptions,/wordMatch/);
  assert.match(html,/globalSearchContentOptionsMenu[\s\S]*data-content-match-mode="phrase"[\s\S]*data-content-match-mode="all"[\s\S]*data-content-match-mode="any"[\s\S]*data-content-match-mode="proximity"/);
  assert.match(html,/data-content-word-match="partial"[\s\S]*data-content-word-match="whole"/);
  assert.match(html,/globalSearchProximityWords/);
  const headerBeforeInput=html.slice(html.indexOf('global-search-head'),html.indexOf('id="globalSearchInput"'));
  const optionsMenuSlice=html.slice(html.indexOf('id="globalSearchContentOptionsMenu"'),html.indexOf('id="globalSearchFolderScope"'));
  assert.doesNotMatch(headerBeforeInput,/globalSearchPdfRefresh/);
  assert.match(optionsMenuSlice,/data-content-word-match="whole"[\s\S]*globalSearchPdfRefresh[\s\S]*globalSearchPdfRefreshStatus/);
  assert.match(css,/global-search-pdf-refresh-wrap\{display:grid;grid-template-columns:auto minmax\(0,1fr\)/);
  assert.doesNotMatch(html,/global-search-statusbar/);
  assert.match(html,/globalSearchMeta[^>]*global-search-live-status|global-search-live-status[^>]*globalSearchMeta/);
  assert.doesNotMatch(html,/global-search-filterbar/);
  assert.doesNotMatch(html,/global-search-modebar|document-search-modebar|globalSearchPreviewOpen/);
  assert.match(html,/globalSearchDocumentSplitter/);
  assert.match(css,/global-search-dialog\{width:100vw;height:100dvh/);
  assert.match(css,/global-search-source-section\+\.global-search-source-section/);
  assert.match(css,/global-search-workspace\.preview-active/);
  assert.match(css,/--document-preview-width:58%/);
  assert.match(css,/document-result-icon\.pdf/);
  assert.match(css,/document-result-icon\.word/);
  assert.match(css,/document-result-icon\.folder/);
  assert.match(css,/document-preview-matches/);
  assert.match(css,/document-preview-inline-match/);
  assert.match(css,/document-docx-search-viewer\{[^}]*overflow-x:hidden/);
  assert.match(css,/netunim-docx-wrapper>section\.netunim-docx/);
  const docxViewer=read('netunim-orders/site/assets/js/domains/documents/docx-search-viewer.js');
  assert.match(docxViewer,/ignoreWidth:true/);
  assert.match(docxViewer,/horizontalScroll:false/);
  assert.match(ui,/previewWidthKey/);
  assert.match(ui,/filter='all'/);
  assert.match(ui,/requestedDocumentModes/);
  assert.match(ui,/documentContentOptions\.value\(\)/);
  assert.match(ui,/documentBridge\.search\(raw,\{mode,contentSearch:mode==='content'\?documentContentOptions\.value\(\):undefined,scopePath:documentFolderScope\.path,fileType:documentFileType\.value\(\),limit:DOCUMENT_RESULT_BATCH,offset:0/);
  assert.match(ui,/documentBridge\.recent\(\{limit:RECENT_DOCUMENT_LIMIT,scopePath:documentFolderScope\.path/);
  assert.match(folderScope,/supportsFolderScope/);
  assert.match(folderScope,/documentBridge\.selectFolder\(\)/);
  assert.match(contentOptions,/MATCH_MODES=new Set\(\['phrase','all','any','proximity'\]\)/);
  assert.match(ui,/function recentDocumentLabel\(\).*?'פריטים אחרונים'.*?'תיקיות אחרונות'.*?'קבצים אחרונים'/s);
  assert.match(ui,/RECENT_DOCUMENT_TTL_MS=15000/);
  assert.match(documentView,/documentIconKind/);
  assert.match(ui,/documentResultsTableHtml/);
  assert.match(ui,/document-search-view\.js/);
  assert.match(ui,/settledEmpty:data\.total===0/);
  assert.match(ui,/settledEmpty:state\.status==='done'&&count===0/);
  assert.match(ui,/hideEmptySources=filter==='all'/);
  assert.match(ui,/const header=hasRows\?'':sourceHeader/);
  assert.match(ui,/sections\.join\(''\)\|\|\(loading\?/);
  assert.match(ui,/setPointerCapture/);
});

test('orders service worker contains both current document search providers after asset synchronization',()=>{
  const sw=read('netunim-orders/site/service-worker.js');
  assert.match(sw,/\.\/assets\/js\/domains\/documents\/bridge\.js/);
  assert.match(sw,/\.\/assets\/js\/domains\/documents\/google-drive\.js/);
  assert.match(sw,/\.\/assets\/js\/domains\/documents\/search-source\.js/);
});

test('document search rejects stale bridge runtimes instead of silently using a broken newer process',()=>{
  const lib=read('netunim-orders/document-bridge/lib.mjs');
  const server=read('netunim-orders/document-bridge/server.mjs');
  const client=read('netunim-orders/site/assets/js/domains/documents/bridge.js');
  assert.match(lib,/BRIDGE_VERSION=37/);
  assert.match(server,/bridgeVersion:BRIDGE_VERSION/);
  assert.match(server,/normalizeDocumentFileType\(fileType\)/);
  assert.match(server,/documentFileTypeIncludesPdf\(normalizedFileType\)\?searchPdfFormIndex/,'interactive-PDF supplemental results must obey the active type filter');
  assert.match(server,/Number\(response\.data\?\.version\)!==BRIDGE_VERSION/);
  assert.match(client,/EXPECTED_BRIDGE_VERSION=37/);
  assert.match(client,/DOCUMENT_BRIDGE_UPGRADE_REQUIRED/);
});
