import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8');

test('orders site exposes one unified search with site, file and content filters over loopback bridge',()=>{
  const html=read('netunim-orders/site/index.html');
  const main=read('netunim-orders/site/assets/js/main.js');
  const client=read('netunim-orders/site/assets/js/domains/documents/bridge.js');
  const headers=read('netunim-orders/site/_headers');
  assert.match(html,/global-search-head[\s\S]*global-search-input-wrap/);
  assert.doesNotMatch(html,/globalSearchSiteMode|globalSearchDocumentsMode|globalSearchDocumentNameMode|globalSearchDocumentContentMode/);
  assert.match(html,/globalSearchFilterAll[\s\S]*הכל<\/button>[\s\S]*globalSearchFilterSite[\s\S]*חיפוש באתר<\/button>[\s\S]*globalSearchFilterFiles[\s\S]*חיפוש קבצים<\/button>[\s\S]*globalSearchFilterContent[\s\S]*חיפוש תוכן<\/button>/);
  assert.match(html,/globalSearchFilterAll[^>]*class="global-search-filter active"[^>]*aria-selected="true"/);
  assert.match(html,/globalSearchDocumentPreview/);
  assert.doesNotMatch(html,/globalSearchPreviewTitle|globalSearchPreviewMeta|globalSearchPreviewOpen|פתח במחשב/);
  assert.match(html,/globalSearchPreviewMatches/);
  assert.match(main,/createDomainsDocumentBridge/);
  assert.match(main,/documentBridge:domainsDocumentBridge/);
  assert.match(client,/http:\/\/127\.0\.0\.1:8766/);
  assert.match(client,/mode==='content'\?'content':'everything'/);
  assert.match(client,/documents\/warm/);
  assert.match(client,/documents\/recent/);
  assert.match(client,/documents\/select-folder/);
  assert.match(client,/const selectFolder=async\(\)=>\{try\{const runtime=await health\(\);requireBridgeVersion/);
  assert.match(client,/documents\/preview/);
  assert.match(client,/documents\/preview-file/);
  assert.match(client,/documents\/matches/);
  assert.match(client,/documents\/native-preview/);
  assert.match(client,/nativePreview/);
  assert.match(headers,/connect-src[^\n]*http:\/\/127\.0\.0\.1:8766/);
});

test('bridge searches the complete Everything index and forces Unicode ES transport',()=>{
  const installer=read('netunim-orders/document-bridge/install_document_bridge.bat');
  const server=read('netunim-orders/document-bridge/server.mjs');
  const lib=read('netunim-orders/document-bridge/lib.mjs');
  const pdfIndex=read('netunim-orders/document-bridge/pdf_form_index.mjs');
  const client=read('shared/document-search/domains/documents/bridge.js');
  assert.match(installer,/--ensure-everything/);
  assert.doesNotMatch(installer,/configure_document_bridge\.ps1/);
  assert.match(server,/scope=everything-index/);
  assert.doesNotMatch(server,/config\.roots/);
  assert.doesNotMatch(server,/pathInsideRoot/);
  assert.match(lib,/'-argv','-cp','65001','-ipc3'/);
  assert.match(lib,/'--',String\(search\)/);
  assert.match(lib,/'-max-results',String\(count\)/);
  assert.doesNotMatch(lib,/'-search',String\(search\)/);
  assert.doesNotMatch(lib,/'-n',String\(count\)/);
  assert.doesNotMatch(lib,/'-path',rootPath/);
  assert.match(lib,/'-path',scope/);
  assert.match(lib,/normalizeSearchScopePath/);
  assert.match(server,/probeEverything\(\{fresh:true,autoStart:true\}\)/);
  assert.match(server,/everythingProbePromise/);
  assert.match(server,/Promise\.any\(candidates\.map\(instance=>probeOne\(instance\)\)\)/);
  assert.match(server,/filter\(instance=>!preferred\|\|instance!==preferred\)/);
  assert.match(server,/documents\/warm/);
  assert.match(server,/documents\/recent/);
  assert.match(server,/documents\/select-folder/);
  assert.match(server,/PICK_FOLDER/);
  assert.match(server,/RECENT scope=everything-index scopePath=.* files-only=true sort=date-modified-descending/);
  assert.match(server,/cachedEsPath/);
  assert.match(server,/listen\(BRIDGE_PORT,'127\.0\.0\.1'/);
  assert.match(server,/refreshPdfFormIndex/);
  assert.match(server,/searchPdfFormIndex/);
  assert.match(server,/scope=everything-index\+interactive-pdf/);
  assert.match(server,/extractInteractivePdfText/);
  assert.match(server,/buildPdfFormMatchAnchors/,'interactive PDF preview matches must retain Bridge-known page geometry');
  assert.match(server,/formAnchorsAuthoritative=formMatchInfo\.anchors\.length>0/,'an empty Bridge geometry payload must never suppress the browser PDF annotation fallback');
  assert.match(server,/PDF_FORM_INDEX_SCHEMA=2/,'AcroForm geometry remains persisted in the supplemental index');
  assert.match(server,/PDF_FORM_EXTRACTOR_REVISION=2/,'interactive PDF cache entries carry an extractor revision so old negative results are revalidated');
  assert.match(server,/extractorCurrent&&cached&&!cached\.hasForm&&!cached\.failed/,'only current-extractor negative PDF records may suppress on-demand form reinspection');
  assert.match(server,/existing\?\.fingerprint===fingerprint&&extractorCurrent&&geometryCurrent/,'unchanged legacy PDF records still enter the migration backlog when their extractor revision is stale');
  assert.match(server,/previewTextCache\.delete\(key\)/,'form-index upgrades invalidate stale preview text cache entries');
  assert.match(server,/geometryCurrent=!existing\?\.hasForm\|\|Array\.isArray\(existing\.formFields\)/,'unchanged legacy interactive PDFs must be reindexed when geometry is missing');
  assert.match(server,/includePageText:!geometryOnly/,'legacy preview migration must recover geometry without re-reading every page text layer');
  assert.match(pdfIndex,/collectPdfFormFields/,'interactive PDF index must persist field page and rectangle metadata');
  assert.match(pdfIndex,/buildPdfFormMatchAnchors/,'interactive PDF index must map value hits back to field geometry');
  assert.match(pdfIndex,/pdfjs\/legacy\/build\/pdf\.mjs/,'Node bridge must prefer the PDF.js legacy build recommended for Node.js');
  assert.match(pdfIndex,/pdfjs\/build\/pdf\.mjs/,'already-installed bridges retain a guarded modern-build fallback until the next runtime refresh');
  assert.match(installer,/pdf_form_index\.mjs/);
  assert.match(installer,/assets\\vendor\\pdfjs/);
  assert.doesNotMatch(installer,/--refresh-pdf-index --install-warmup/,'installer must never block on PDF indexing');
  assert.match(server,/PDF_FORM_INDEX_BACKGROUND_BATCH=8/);
  assert.match(server,/PDF_FORM_INDEX_CONCURRENCY=1/);
  assert.match(server,/hasForm:!!extracted\.hasForm/,'ordinary PDFs must be negatively cached after inspection');
  assert.match(server,/pending:pdfFormIndexPending/,'incremental progress must be persisted across restarts');
  assert.match(server,/pdf-form-index\.journal\.jsonl/,'incremental PDF inspection progress must be journaled without rewriting the whole snapshot every batch');
  assert.match(server,/PDF_FORM_INDEX_COMPACT_EVERY=500/);
  assert.match(server,/PDF_FORM_INDEX_INVENTORY_REFRESH_MS=5\*60\*1000/,'a large backlog must not re-enumerate the complete PDF inventory before every small batch');
  assert.match(server,/INSTALL_STOP_FORCE/,'upgrades must be able to terminate an old Bridge that closed the port but kept indexing');
  assert.match(server,/taskkill\.exe/);
  assert.match(installer,/Preserving local interactive PDF text index/);
  assert.match(installer,/:move_dir_with_retry/);
  assert.match(installer,/active-runtime\.txt/,'upgrades must activate a side-by-side runtime through an explicit pointer');
  assert.match(installer,/app-v30-/,'new runtime must be versioned so old Windows handles cannot block activation');
  assert.doesNotMatch(installer,/move \"%APPDIR%\"/,'installer must never rename the active runtime as a prerequisite for upgrade success');
  assert.match(installer,/stop_runtime_helpers\.ps1/,'installer should clean verified stale bridge helpers without depending on old runtime deletion');
  assert.match(server,/RUNTIME_ROOT=fileURLToPath/,'runtime-owned executables must resolve relative to the active versioned runtime');
  assert.match(server,/cwd:APP_ROOT/,'child processes must not inherit the runtime directory as their current directory');
  assert.match(server,/runEs\(esPath,args,\{timeout=18000,signal=null\}/,'ES inventory work must be abortable during shutdown');
  assert.match(server,/preparePdfFormIndexForSearch/);
  assert.doesNotMatch(server,/PDF_FORM_INDEX_INITIAL_WAIT_MS/,'content requests must never wait on a full PDF-form index refresh');
  assert.doesNotMatch(lib,/contentMatchRanges\(String\(value\?\?''\),query,\{\.\.\.options,maxMatches:5000\}\)\.ranges\.length>0/,'supplemental-index filtering must stop at boolean match semantics instead of materializing highlight ranges');
  assert.match(pdfIndex,/fileURLToPath/);
  assert.match(pdfIndex,/BinaryDataFactory:LocalPdfBinaryDataFactory/);
  assert.match(pdfIndex,/VerbosityLevel\?\.ERRORS/);
  assert.match(lib,/BRIDGE_VERSION=30/);
  assert.match(client,/EXPECTED_BRIDGE_VERSION=30/);
  assert.match(client,/requireBridgeVersion\(data\?\.bridgeVersion,'לקבל מיקומי התאמות בתוך PDF אינטראקטיבי'\)/,'preview-match geometry refuses a stale local Bridge runtime');
});

test('file and folder opening use the Windows graphical shell through UseShellExecute',()=>{
  const server=read('netunim-orders/document-bridge/server.mjs');
  assert.match(server,/System\.Diagnostics\.ProcessStartInfo/);
  assert.match(server,/UseShellExecute=\$true/);
  assert.match(server,/System\.Diagnostics\.Process\]::Start/);
  assert.doesNotMatch(server,/Shell\.Application; \$s\.Open/);
  assert.doesNotMatch(server,/execFile\('explorer\.exe'/);
  assert.match(server,/await fs\.stat\(row\.fullPath\)/);
  assert.match(server,/shell=UseShellExecute/);
  assert.match(server,/body\.id/);
  assert.doesNotMatch(server,/body\.path/);
});

test('local document results expose Explorer reveal and recycle-bin delete through opaque result ids',()=>{
  const server=read('netunim-orders/document-bridge/server.mjs');
  const client=read('netunim-orders/site/assets/js/domains/documents/bridge.js');
  const ui=read('shared/global-document-search.js');
  const menu=read('netunim-orders/site/assets/js/ui/document-result-menu.js');
  const modal=read('netunim-orders/site/assets/js/ui/modal.js');
  const css=read('shared/global-document-search.css');
  assert.match(server,/documents\/reveal/);
  assert.match(server,/documents\/delete/);
  assert.match(server,/NETUNIM_REVEAL_TARGET/);
  assert.match(server,/NETUNIM_DELETE_TARGET/);
  assert.match(server,/RecycleOption\]::SendToRecycleBin/);
  assert.match(server,/invalidateResultPath/);
  assert.doesNotMatch(server,/body\.path/);
  assert.match(client,/provider:'everything'/);
  assert.match(client,/revealDocument/);
  assert.match(client,/deleteDocument/);
  assert.match(menu,/data-document-menu-action="open"/);
  assert.match(menu,/data-document-menu-action="reveal"/);
  assert.match(menu,/data-document-menu-action="delete"/);
  assert.match(ui,/event\.key==='Delete'/);
  assert.match(menu,/confirmDialog\('למחוק את הקובץ\?'/);
  assert.match(menu,/defaultFocus:'confirm',confirmOnEnter:true/);
  assert.match(modal,/event\.key==='Enter'&&activeConfirm\.options\.confirmOnEnter===true/);
  assert.match(modal,/document\.addEventListener\('keydown',[\s\S]*\},true\);/);
  assert.match(css,/document-result-context-menu/);
});

test('preview stays local: filename Office preview stays native while content search uses controlled local document renderers',()=>{
  const server=read('netunim-orders/document-bridge/server.mjs');
  const lib=read('netunim-orders/document-bridge/lib.mjs');
  const ui=read('shared/global-document-search.js');
  const documentView=read('netunim-orders/site/assets/js/ui/document-search-view.js');
  const folderScope=read('netunim-orders/site/assets/js/ui/document-search-folder-scope.js');
  const contentOptions=read('netunim-orders/site/assets/js/ui/document-search-content-options.js');
  const client=read('netunim-orders/site/assets/js/domains/documents/bridge.js');
  const installer=read('netunim-orders/document-bridge/install_document_bridge.bat');
  const build=read('netunim-orders/document-bridge/build_native_preview.ps1');
  const host=read('netunim-orders/document-bridge/native_preview_host.cs');
  assert.match(server,/documents\/preview/);
  assert.match(server,/documents\/preview-file/);
  assert.match(server,/documents\/matches/);
  assert.match(server,/documents\/native-preview/);
  assert.match(server,/NATIVE_PREVIEW_HOST/);
  assert.match(server,/source:'windows-preview-handler'/);
  assert.match(server,/kind:'structured'/);
  assert.match(server,/structuredPreviewKind/);
  assert.match(server,/STRUCTURED_PREVIEW_MIME/);
  assert.doesNotMatch(server,/OFFICE_PREVIEW_SCRIPT/);
  assert.doesNotMatch(server,/ensureOfficePreview/);
  assert.doesNotMatch(server,/source:'office-pdf'/);
  assert.match(lib,/officePreviewKind/);
  assert.match(lib,/structuredPreviewKind/);
  assert.match(lib,/buildEsContentPreviewArgs/);
  assert.match(lib,/buildContentMatchInfo/);
  assert.match(installer,/build_native_preview\.ps1/);
  assert.match(installer,/native_preview_host\.cs/);
  assert.match(installer,/NetunimPreviewHost\.exe/);
  assert.doesNotMatch(installer,/office_preview\.ps1/);
  assert.match(build,/csc\.exe/);
  assert.match(host,/interface IPreviewHandler/);
  assert.match(host,/IInitializeWithFile/);
  assert.match(host,/IInitializeWithItem/);
  assert.match(host,/8895b1c6-b41f-4c1c-a562-0d564250836f/i);
  assert.match(host,/handler\.SetWindow/);
  assert.match(host,/handler\.SetRect/);
  assert.match(host,/handler\.DoPreview/);
  assert.match(host,/SetProcessDpiAwarenessContext/);
  assert.match(host,/PerMonitorAwareV2/);
  assert.match(host,/GetClientRect/);
  assert.match(host,/interface IOleWindow/);
  assert.match(host,/GetParent\(previewWindow\) == Handle/);
  assert.match(host,/SynchronizePreviewBounds/);
  assert.match(host,/PICK_FOLDER/);
  assert.match(host,/interface IFileOpenDialog/);
  assert.match(host,/FileOpenDialogCom/);
  assert.match(host,/PickFolders = 0x00000020/);
  assert.match(host,/ForceFileSystem = 0x00000040/);
  assert.match(host,/ModernFolderPicker\.Pick/);
  assert.doesNotMatch(host,/FolderBrowserDialog/);
  assert.match(host,/settlePassesRemaining/);
  assert.match(host,/SetWindowLongPtr/);
  assert.match(host,/SetWindowPos/);
  assert.equal([...Buffer.from(host,'utf8')].some(byte=>byte>0x7f),false,'native_preview_host.cs must remain ASCII-only');
  assert.equal([...Buffer.from(build,'utf8')].some(byte=>byte>0x7f),false,'build_native_preview.ps1 must remain ASCII-only');
  assert.match(client,/nativePreview/);
  assert.match(client,/moveNativePreview/);
  assert.match(client,/hideNativePreview/);
  assert.match(ui,/filter='all'/);
  assert.match(ui,/requestedDocumentModes/);
  assert.match(ui,/documentBridge\.search\(raw,\{mode,contentSearch:mode==='content'\?documentContentOptions\.value\(\):undefined,scopePath:documentFolderScope\.path,limit:DOCUMENT_RESULT_BATCH,offset:0/);
  assert.match(ui,/documentBridge\.recent\(\{limit:RECENT_DOCUMENT_LIMIT,scopePath:documentFolderScope\.path/);
  assert.match(folderScope,/supportsFolderScope/);
  assert.match(folderScope,/documentBridge\.selectFolder\(\)/);
  assert.match(contentOptions,/MATCH_MODES=new Set\(\['phrase','all','any','proximity'\]\)/);
  assert.match(ui,/const RECENT_DOCUMENT_LIMIT=150/);
  assert.match(ui,/const SITE_RESULT_BATCH=150/);
  assert.match(ui,/const DOCUMENT_RESULT_BATCH=150/);
  assert.match(ui,/const DOCUMENT_RESULT_MAX=5000/);
  assert.match(ui,/function loadMoreDocumentResults\(requestedMode=''\)/);
  assert.match(ui,/offset=before\.rows\.length/);
  assert.match(ui,/data-site-load-more/);
  assert.match(ui,/data-document-load-more/);
  assert.match(ui,/maybeLoadMoreDocumentResults\(\)/);
  assert.match(server,/body\.offset/);
  assert.match(server,/hasMore/);
  assert.match(client,/limit=150,offset=0/);
  assert.match(ui,/label:'קבצים אחרונים'/);

  assert.match(client,/const recent=\(\{limit=150,scopePath='',signal=null\}=\{\}\)=>/);
  assert.match(server,/RECENT_RESULT_LIMIT/);
  assert.match(ui,/RECENT_DOCUMENT_TTL_MS=15000/);
  assert.match(ui,/function warmDocumentSearchBridge\(\)/);
  assert.match(ui,/documentBridge\.warm\(\)/);
  assert.match(ui,/DOCUMENT_BRIDGE_WARM_TTL_MS=25000/);
  assert.ok((ui.match(/warmDocumentSearchBridge\(\);/g)||[]).length>=2,'Bridge warm-up should run at bind time and when the search opens');
  assert.match(ui,/window\.devicePixelRatio/);
  assert.match(ui,/window\.addEventListener\('focus'/);
  assert.match(ui,/data.kind==='native'/);
  assert.match(ui,/dblclick/);
  assert.match(ui,/selectDocumentResult/);
  assert.match(documentView,/document-results-table/);
  assert.match(ui,/document-preview-frame/);
  assert.match(ui,/createTextSearchViewer/);
  assert.match(ui,/createDocxSearchViewer/);
  assert.match(ui,/createSpreadsheetSearchViewer/);
  assert.match(ui,/createPdfSearchViewer/);
  assert.match(ui,/previewSearchViewer\.previous\(\)/);
  assert.match(ui,/previewSearchViewer\.next\(\)/);
  assert.match(ui,/onPreviewSearchMatchState/);
  assert.match(documentView,/document-preview-match-term/);
  assert.match(ui,/buildPdfPreviewSrc\(previewObjectUrl,\{query\}\)/);
  assert.doesNotMatch(ui,/syncPdfPreviewMatch/);
  assert.match(ui,/loadPreviewMatches/);
  const pdfViewer=read('netunim-orders/site/assets/js/domains/documents/pdf-search-viewer.js');
  const css=read('shared/global-document-search.css');
  assert.match(pdfViewer,/PDFFindController/);
  assert.match(pdfViewer,/highlightAll:true/);
  assert.match(pdfViewer,/next\(\)\{if\(combinedReady&&combinedMatches\.length\)return goCombined\(combinedIndex\+1\);dispatch\('again',false\)\}/);
  assert.match(pdfViewer,/previous\(\)\{if\(combinedReady&&combinedMatches\.length\)return goCombined\(combinedIndex-1\);dispatch\('again',true\)\}/);
  assert.match(pdfViewer,/findPdfFormFieldMatches/);
  assert.match(pdfViewer,/buildCombinedMatches/);
  assert.match(pdfViewer,/ensurePdfFormOverlay/);
  assert.match(pdfViewer,/convertToViewportPoint/);
  assert.doesNotMatch(pdfViewer,/\.convertToViewportRectangle\b/);
  assert.match(pdfViewer,/installPdfJsBrowserCompatibility/);
  assert.match(pdfViewer,/Map\.prototype\.getOrInsertComputed/);
  assert.match(pdfViewer,/eventBus\.on\('pagerendered',renderFormLayerForEvent\)/);
  assert.match(css,/document-pdf-form-match-marker/);
  assert.match(pdfViewer,/updatefindmatchescount/);
  assert.match(pdfViewer,/currentScaleValue='page-width'/);
  assert.match(pdfViewer,/ResizeObserver/);
  assert.match(pdfViewer,/resize\(options=\{\}\)/);
  assert.match(ui,/preloadPdfSearchRuntime/);
  assert.match(ui,/previewSearchViewer\?\.resize/);
  assert.match(css,/document-pdfjs-container \.pdfViewer \.page\{box-sizing:content-box/);
  assert.match(css,/highlight\.selected\{background-color:rgba\(255,149,38,\.36\)/);
  assert.doesNotMatch(css,/highlight\.selected\{[^}]*?(?:outline|box-shadow|border)/);
  assert.doesNotMatch(pdfViewer,/import\(runtime\.(?:pdf|viewer)\)/);
  assert.match(server,/extension==='pdf'\?buildContentMatchInfo\(content\.text,query,\{\.\.\.search,contextChars:96,maxSnippets:500,maxMatches:500\}\)/);
});

test('installer keeps Everything hidden background startup and no longer asks for Bridge roots',()=>{
  const installer=read('netunim-orders/document-bridge/install_document_bridge.bat');
  const server=read('netunim-orders/document-bridge/server.mjs');
  assert.match(installer,/background mode/);
  assert.match(installer,/complete Everything index/i);
  assert.match(installer,/--doctor/);
  assert.match(installer,/--check-running/);
  assert.match(server,/'-startup','-first-instance'/);
  assert.match(server,/Search scope: complete Everything index/);
  assert.match(server,/COMPLETE EVERYTHING INDEX/);
});

test('PowerShell configurator remains code-page independent even though v4 no longer uses it during install',()=>{
  const bytes=fs.readFileSync(new URL('../netunim-orders/document-bridge/configure_document_bridge.ps1',import.meta.url));
  assert.equal([...bytes].some(byte=>byte>0x7f),false,'configure_document_bridge.ps1 must remain ASCII-only');
});

test('unified search uses a full-screen header search, four result filters and a headerless resizable preview',()=>{
  const html=read('netunim-orders/site/index.html');
  const css=read('shared/global-document-search.css');
  const ui=read('shared/global-document-search.js');
  const documentView=read('netunim-orders/site/assets/js/ui/document-search-view.js');
  const folderScope=read('netunim-orders/site/assets/js/ui/document-search-folder-scope.js');
  const contentOptions=read('netunim-orders/site/assets/js/ui/document-search-content-options.js');
  assert.doesNotMatch(html,/id="globalSearchTitle"/);
  assert.match(html,/global-search-head[\s\S]*globalSearchFilterAll[\s\S]*globalSearchFilterSite[\s\S]*globalSearchFilterFiles[\s\S]*globalSearchFilterContent[\s\S]*globalSearchInput[\s\S]*globalSearchContentMatchMode/);
  assert.match(html,/globalSearchFolderScope[\s\S]*globalSearchFolderPick[\s\S]*globalSearchFolderLabel[\s\S]*globalSearchFolderClear/);
  assert.match(css,/global-search-option-select select\{width:auto;min-width:0/);
  assert.doesNotMatch(css,/global-search-option-select select\{min-width:122px/);
  assert.match(css,/global-search-folder-scope/);
  assert.match(ui,/createDocumentSearchFolderScope/);
  assert.match(folderScope,/let path='',label=''/);
  assert.match(folderScope,/async function choose\(\)/);
  assert.match(folderScope,/function clear\(\)/);
  assert.match(contentOptions,/createDocumentContentSearchOptions/);
  assert.match(html,/globalSearchContentMatchMode[\s\S]*value="phrase"[\s\S]*value="all"[\s\S]*value="any"[\s\S]*value="proximity"/);
  assert.match(html,/globalSearchProximityWords/);
  assert.doesNotMatch(html,/global-search-statusbar/);
  assert.match(html,/globalSearchMeta[^>]*global-search-live-status|global-search-live-status[^>]*globalSearchMeta/);
  assert.doesNotMatch(html,/global-search-filterbar/);
  assert.doesNotMatch(html,/global-search-modebar|document-search-modebar|globalSearchPreviewOpen/);
  assert.match(html,/globalSearchDocumentSplitter/);
  assert.match(css,/global-search-dialog\{width:100vw;height:100dvh/);
  assert.match(css,/global-search-source-section\+\.global-search-source-section/);
  assert.match(css,/global-search-workspace\.preview-active/);
  assert.match(css,/--document-preview-width:58%/);
  assert.match(css,/document-result-icon\.pdf/);
  assert.match(css,/document-result-icon\.word/);
  assert.match(css,/document-result-icon\.folder/);
  assert.match(css,/document-preview-matches/);
  assert.match(css,/document-preview-inline-match/);
  assert.match(css,/document-docx-search-viewer\{[^}]*overflow-x:hidden/);
  assert.match(css,/netunim-docx-wrapper>section\.netunim-docx/);
  const docxViewer=read('netunim-orders/site/assets/js/domains/documents/docx-search-viewer.js');
  assert.match(docxViewer,/ignoreWidth:true/);
  assert.match(docxViewer,/horizontalScroll:false/);
  assert.match(ui,/previewWidthKey/);
  assert.match(ui,/filter='all'/);
  assert.match(ui,/requestedDocumentModes/);
  assert.match(ui,/documentContentOptions\.value\(\)/);
  assert.match(ui,/documentBridge\.search\(raw,\{mode,contentSearch:mode==='content'\?documentContentOptions\.value\(\):undefined,scopePath:documentFolderScope\.path,limit:DOCUMENT_RESULT_BATCH,offset:0/);
  assert.match(ui,/documentBridge\.recent\(\{limit:RECENT_DOCUMENT_LIMIT,scopePath:documentFolderScope\.path/);
  assert.match(folderScope,/supportsFolderScope/);
  assert.match(folderScope,/documentBridge\.selectFolder\(\)/);
  assert.match(contentOptions,/MATCH_MODES=new Set\(\['phrase','all','any','proximity'\]\)/);
  assert.match(ui,/label:'קבצים אחרונים'/);
  assert.match(ui,/RECENT_DOCUMENT_TTL_MS=15000/);
  assert.match(documentView,/documentIconKind/);
  assert.match(ui,/documentResultsTableHtml/);
  assert.match(ui,/document-search-view\.js/);
  assert.match(ui,/settledEmpty:data\.total===0/);
  assert.match(ui,/settledEmpty:state\.status==='done'&&count===0/);
  assert.match(ui,/hideEmptySources=filter==='all'/);
  assert.match(ui,/const header=hasRows\?'':sourceHeader/);
  assert.match(ui,/sections\.join\(''\)\|\|\(loading\?/);
  assert.match(ui,/setPointerCapture/);
});

test('orders service worker contains both current document search providers after asset synchronization',()=>{
  const sw=read('netunim-orders/site/service-worker.js');
  assert.match(sw,/\.\/assets\/js\/domains\/documents\/bridge\.js/);
  assert.match(sw,/\.\/assets\/js\/domains\/documents\/google-drive\.js/);
  assert.match(sw,/\.\/assets\/js\/domains\/documents\/search-source\.js/);
});

test('document search rejects stale bridge runtimes instead of silently using a broken newer process',()=>{
  const lib=read('netunim-orders/document-bridge/lib.mjs');
  const server=read('netunim-orders/document-bridge/server.mjs');
  const client=read('netunim-orders/site/assets/js/domains/documents/bridge.js');
  assert.match(lib,/BRIDGE_VERSION=30/);
  assert.match(server,/bridgeVersion:BRIDGE_VERSION/);
  assert.match(server,/Number\(response\.data\?\.version\)!==BRIDGE_VERSION/);
  assert.match(client,/EXPECTED_BRIDGE_VERSION=30/);
  assert.match(client,/DOCUMENT_BRIDGE_UPGRADE_REQUIRED/);
});
