
-- Financial sync data is intentionally isolated from kupa_documents backups.
create table if not exists public.finance_sync_documents (
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null default 'main',
  revision bigint not null default 1 check (revision > 0),
  state jsonb not null default '{"bank":null,"creditSync":null}'::jsonb check (jsonb_typeof(state)='object'),
  updated_at timestamptz not null default now(),
  primary key (owner_id, document_name)
);
alter table public.finance_sync_documents enable row level security;
revoke all on table public.finance_sync_documents from anon, authenticated;
grant select on table public.finance_sync_documents to authenticated;
drop policy if exists "finance_sync_select_own" on public.finance_sync_documents;
create policy "finance_sync_select_own" on public.finance_sync_documents for select to authenticated using ((select auth.uid()) = owner_id);

create or replace function public.save_finance_sync_document(p_document_name text, p_expected_revision bigint, p_state jsonb)
returns table(revision bigint, updated_at timestamptz, state jsonb)
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  v_owner uuid := auth.uid();
  v_current bigint;
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  if p_document_name is null or btrim(p_document_name)='' then raise exception 'invalid_document_name' using errcode='22023'; end if;
  if p_expected_revision is null or p_expected_revision < 0 then raise exception 'invalid_expected_revision' using errcode='22023'; end if;
  if p_state is null or jsonb_typeof(p_state) is distinct from 'object' then raise exception 'invalid_finance_sync_state' using errcode='22023'; end if;

  select d.revision into v_current from public.finance_sync_documents d
  where d.owner_id=v_owner and d.document_name=p_document_name for update;
  if v_current is null then
    if p_expected_revision<>0 then raise exception 'revision_conflict' using errcode='40001'; end if;
    insert into public.finance_sync_documents(owner_id,document_name,revision,state,updated_at)
    values(v_owner,p_document_name,1,p_state,now())
    returning finance_sync_documents.revision,finance_sync_documents.updated_at,finance_sync_documents.state
    into revision,updated_at,state;
    return next; return;
  end if;
  if v_current<>p_expected_revision then raise exception 'revision_conflict' using errcode='40001'; end if;
  update public.finance_sync_documents d set revision=d.revision+1,state=p_state,updated_at=now()
  where d.owner_id=v_owner and d.document_name=p_document_name
  returning d.revision,d.updated_at,d.state into revision,updated_at,state;
  return next;
end $$;
revoke all on function public.save_finance_sync_document(text,bigint,jsonb) from public, anon;
grant execute on function public.save_finance_sync_document(text,bigint,jsonb) to authenticated;

create table if not exists public.bank_transactions (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  account_key text not null,
  account_role text not null check (account_role in ('business','home')),
  merge_key text not null,
  transaction_date timestamptz,
  processed_date timestamptz,
  amount numeric not null,
  currency text not null default 'ILS',
  description text not null default '',
  memo text not null default '',
  party_name text not null default '',
  party_headline text not null default '',
  message_headline text not null default '',
  message_detail text not null default '',
  status text not null default 'completed' check(status in ('pending','completed')),
  balance_after numeric,
  bank_reference text not null default '',
  bank_serial text not null default '',
  activity_type_code integer,
  cheque boolean not null default false,
  check_details jsonb,
  first_seen_at timestamptz not null default now(),
  last_changed_at timestamptz not null default now(),
  unique(owner_id,account_key,merge_key)
);
create index if not exists bank_transactions_owner_account_date_idx on public.bank_transactions(owner_id,account_key,transaction_date desc);
create index if not exists bank_transactions_owner_reference_idx on public.bank_transactions(owner_id,account_key,bank_reference) where bank_reference<>'';
alter table public.bank_transactions enable row level security;
revoke all on table public.bank_transactions from anon, authenticated;
grant select on table public.bank_transactions to authenticated;
drop policy if exists "bank_transactions_select_own" on public.bank_transactions;
create policy "bank_transactions_select_own" on public.bank_transactions for select to authenticated using ((select auth.uid())=owner_id);

create or replace function public.merge_bank_transactions(p_account_key text,p_account_role text,p_transactions jsonb)
returns table(inserted_count integer, updated_count integer, total_count integer)
language plpgsql
set search_path=pg_catalog,public
as $$
declare
  v_owner uuid:=auth.uid(); r jsonb; v_id bigint; v_inserted int:=0; v_updated int:=0; v_candidates int; v_candidate bigint;
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  if coalesce(btrim(p_account_key),'')='' or p_account_role not in ('business','home') or jsonb_typeof(p_transactions) is distinct from 'array' then raise exception 'invalid_bank_merge_input' using errcode='22023'; end if;
  for r in select value from jsonb_array_elements(p_transactions) loop
    v_id:=null;
    -- Strong identifiers first.
    if coalesce(r->>'bankReference','')<>'' then
      select id into v_id from public.bank_transactions where owner_id=v_owner and account_key=p_account_key and bank_reference=r->>'bankReference' and amount=(r->>'amount')::numeric order by id desc limit 1;
    end if;
    if v_id is null and coalesce(r->>'bankSerial','') not in ('','0') then
      select id into v_id from public.bank_transactions where owner_id=v_owner and account_key=p_account_key and bank_serial=r->>'bankSerial' and amount=(r->>'amount')::numeric order by id desc limit 1;
    end if;
    -- Pending -> completed reconciliation only when exactly one candidate exists.
    if v_id is null and coalesce(r->>'status','completed')='completed' then
      select count(*),min(id) into v_candidates,v_candidate from public.bank_transactions
      where owner_id=v_owner and account_key=p_account_key and status='pending' and amount=(r->>'amount')::numeric
        and description=coalesce(r->>'description','')
        and transaction_date between ((r->>'date')::timestamptz-interval '3 days') and ((r->>'date')::timestamptz+interval '3 days');
      if v_candidates=1 then v_id:=v_candidate; end if;
    end if;
    if v_id is null then
      select id into v_id from public.bank_transactions where owner_id=v_owner and account_key=p_account_key and merge_key=r->>'mergeKey' limit 1;
    end if;
    if v_id is null then
      insert into public.bank_transactions(owner_id,account_key,account_role,merge_key,transaction_date,processed_date,amount,currency,description,memo,party_name,party_headline,message_headline,message_detail,status,balance_after,bank_reference,bank_serial,activity_type_code,cheque,check_details)
      values(v_owner,p_account_key,p_account_role,r->>'mergeKey',nullif(r->>'date','')::timestamptz,nullif(r->>'processedDate','')::timestamptz,(r->>'amount')::numeric,coalesce(nullif(r->>'currency',''),'ILS'),coalesce(r->>'description',''),coalesce(r->>'memo',''),coalesce(r->>'partyName',''),coalesce(r->>'partyHeadline',''),coalesce(r->>'messageHeadline',''),coalesce(r->>'messageDetail',''),case when r->>'status'='pending' then 'pending' else 'completed' end,nullif(r->>'balanceAfter','')::numeric,coalesce(r->>'bankReference',''),coalesce(r->>'bankSerial',''),nullif(r->>'activityTypeCode','')::integer,coalesce((r->>'cheque')::boolean,false),r->'checkDetails');
      v_inserted:=v_inserted+1;
    else
      update public.bank_transactions set
        merge_key=coalesce(nullif(r->>'mergeKey',''),merge_key), transaction_date=coalesce(nullif(r->>'date','')::timestamptz,transaction_date), processed_date=coalesce(nullif(r->>'processedDate','')::timestamptz,processed_date),
        currency=coalesce(nullif(r->>'currency',''),currency), description=coalesce(nullif(r->>'description',''),description), memo=coalesce(r->>'memo',memo), party_name=coalesce(r->>'partyName',party_name),party_headline=coalesce(r->>'partyHeadline',party_headline),message_headline=coalesce(r->>'messageHeadline',message_headline),message_detail=coalesce(r->>'messageDetail',message_detail),
        status=case when r->>'status'='pending' and status='completed' then status else coalesce(r->>'status',status) end, balance_after=coalesce(nullif(r->>'balanceAfter','')::numeric,balance_after), bank_reference=coalesce(nullif(r->>'bankReference',''),bank_reference),bank_serial=coalesce(nullif(r->>'bankSerial',''),bank_serial),activity_type_code=coalesce(nullif(r->>'activityTypeCode','')::integer,activity_type_code),cheque=coalesce((r->>'cheque')::boolean,cheque),check_details=coalesce(r->'checkDetails',check_details),last_changed_at=now()
      where id=v_id;
      v_updated:=v_updated+1;
    end if;
  end loop;
  select count(*)::int into total_count from public.bank_transactions where owner_id=v_owner and account_key=p_account_key;
  inserted_count:=v_inserted; updated_count:=v_updated; return next;
end $$;
revoke all on function public.merge_bank_transactions(text,text,jsonb) from public,anon;
grant execute on function public.merge_bank_transactions(text,text,jsonb) to authenticated;

-- Owner-scoped writes for the invoker-rights RPCs.
grant insert, update on table public.finance_sync_documents to authenticated;
drop policy if exists "finance_sync_insert_own" on public.finance_sync_documents;
create policy "finance_sync_insert_own" on public.finance_sync_documents for insert to authenticated with check ((select auth.uid())=owner_id);
drop policy if exists "finance_sync_update_own" on public.finance_sync_documents;
create policy "finance_sync_update_own" on public.finance_sync_documents for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
grant insert, update on table public.bank_transactions to authenticated;
grant usage, select on sequence public.bank_transactions_id_seq to authenticated;
drop policy if exists "bank_transactions_insert_own" on public.bank_transactions;
create policy "bank_transactions_insert_own" on public.bank_transactions for insert to authenticated with check ((select auth.uid())=owner_id);
drop policy if exists "bank_transactions_update_own" on public.bank_transactions;
create policy "bank_transactions_update_own" on public.bank_transactions for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
