
-- Financial sync data is intentionally isolated from kupa_documents backups.
create table if not exists public.finance_sync_documents (
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null default 'main',
  revision bigint not null default 1 check (revision > 0),
  state jsonb not null default '{"bank":null,"creditSync":null}'::jsonb check (jsonb_typeof(state)='object'),
  updated_at timestamptz not null default now(),
  primary key (owner_id, document_name)
);
alter table public.finance_sync_documents enable row level security;
revoke all on table public.finance_sync_documents from anon, authenticated;
grant select on table public.finance_sync_documents to authenticated;
drop policy if exists "finance_sync_select_own" on public.finance_sync_documents;
create policy "finance_sync_select_own" on public.finance_sync_documents for select to authenticated using ((select auth.uid()) = owner_id);

create or replace function public.save_finance_sync_document(p_document_name text, p_expected_revision bigint, p_state jsonb)
returns table(revision bigint, updated_at timestamptz, state jsonb)
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  v_owner uuid := auth.uid();
  v_current bigint;
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  -- Shared per-user financial writer gate: fail fast instead of filling the PostgREST pool.
  if not pg_try_advisory_xact_lock(
    hashtextextended('netunim_financial_write:' || v_owner::text, 0)
  ) then
    raise exception 'save_busy'
      using errcode = 'PT429',
            hint = 'Another financial save is already in progress. Retry later.';
  end if;
  perform set_config('lock_timeout', '100ms', true);
  if p_document_name is null or btrim(p_document_name)='' then raise exception 'invalid_document_name' using errcode='22023'; end if;
  if p_expected_revision is null or p_expected_revision < 0 then raise exception 'invalid_expected_revision' using errcode='22023'; end if;
  if p_state is null or jsonb_typeof(p_state) is distinct from 'object' then raise exception 'invalid_finance_sync_state' using errcode='22023'; end if;

  select d.revision into v_current from public.finance_sync_documents d
  where d.owner_id=v_owner and d.document_name=p_document_name for update;
  if v_current is null then
    if p_expected_revision<>0 then raise exception 'revision_conflict' using errcode='40001'; end if;
    insert into public.finance_sync_documents(owner_id,document_name,revision,state,updated_at)
    values(v_owner,p_document_name,1,p_state,now())
    returning finance_sync_documents.revision,finance_sync_documents.updated_at,finance_sync_documents.state
    into revision,updated_at,state;
    return next; return;
  end if;
  if v_current<>p_expected_revision then raise exception 'revision_conflict' using errcode='40001'; end if;
  update public.finance_sync_documents d set revision=d.revision+1,state=p_state,updated_at=now()
  where d.owner_id=v_owner and d.document_name=p_document_name
  returning d.revision,d.updated_at,d.state into revision,updated_at,state;
  return next;
end $$;
revoke all on function public.save_finance_sync_document(text,bigint,jsonb) from public, anon;
grant execute on function public.save_finance_sync_document(text,bigint,jsonb) to authenticated;

create table if not exists public.bank_transactions (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  account_key text not null,
  account_role text not null check (account_role in ('business','home')),
  merge_key text not null,
  transaction_date timestamptz,
  processed_date timestamptz,
  amount numeric not null,
  currency text not null default 'ILS',
  description text not null default '',
  memo text not null default '',
  party_name text not null default '',
  party_headline text not null default '',
  message_headline text not null default '',
  message_detail text not null default '',
  status text not null default 'completed' check(status in ('pending','completed')),
  balance_after numeric,
  bank_reference text not null default '',
  bank_serial text not null default '',
  activity_type_code integer,
  cheque boolean not null default false,
  check_details jsonb,
  first_seen_at timestamptz not null default now(),
  last_changed_at timestamptz not null default now(),
  unique(owner_id,account_key,merge_key)
);
create index if not exists bank_transactions_owner_account_date_idx on public.bank_transactions(owner_id,account_key,transaction_date desc);
create index if not exists bank_transactions_owner_reference_idx on public.bank_transactions(owner_id,account_key,bank_reference) where bank_reference<>'';
alter table public.bank_transactions enable row level security;
revoke all on table public.bank_transactions from anon, authenticated;
grant select on table public.bank_transactions to authenticated;
drop policy if exists "bank_transactions_select_own" on public.bank_transactions;
create policy "bank_transactions_select_own" on public.bank_transactions for select to authenticated using ((select auth.uid())=owner_id);

create or replace function public.merge_bank_transactions(p_account_key text,p_account_role text,p_transactions jsonb)
returns table(inserted_count integer, updated_count integer, total_count integer)
language plpgsql
set search_path=pg_catalog,public
as $$
declare
  v_owner uuid:=auth.uid();
  r jsonb;
  v_id bigint;
  v_inserted int:=0;
  v_updated int:=0;
  v_candidates int;
  v_candidate bigint;
  v_date timestamptz;
  v_processed timestamptz;
  v_amount numeric;
  v_serial text;
  v_reference text;
  v_description text;
  v_memo text;
  v_party_name text;
  v_status text;
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  -- Shared per-user financial writer gate: fail fast instead of filling the PostgREST pool.
  if not pg_try_advisory_xact_lock(
    hashtextextended('netunim_financial_write:' || v_owner::text, 0)
  ) then
    raise exception 'save_busy'
      using errcode = 'PT429',
            hint = 'Another financial save is already in progress. Retry later.';
  end if;
  perform set_config('lock_timeout', '100ms', true);
  if coalesce(btrim(p_account_key),'')='' or p_account_role not in ('business','home') or jsonb_typeof(p_transactions) is distinct from 'array' then raise exception 'invalid_bank_merge_input' using errcode='22023'; end if;

  -- A duplicate merge key means the client could not distinguish two source rows. Fail atomically
  -- instead of silently collapsing financial movements. Fallback rows receive occurrence suffixes.
  if exists (
    select 1
    from jsonb_array_elements(p_transactions) x(value)
    group by x.value->>'mergeKey'
    having coalesce(x.value->>'mergeKey','')='' or count(*)>1
  ) then
    raise exception 'bank_archive_ambiguous_source_identity'
      using errcode='22023', hint='The bank returned rows that cannot be given unique stable identities. No archive rows were changed.';
  end if;

  for r in select value from jsonb_array_elements(p_transactions) loop
    if nullif(r->>'amount','') is null then raise exception 'invalid_bank_transaction_amount' using errcode='22023'; end if;
    v_date:=nullif(r->>'date','')::timestamptz;
    v_processed:=nullif(r->>'processedDate','')::timestamptz;
    v_amount:=(r->>'amount')::numeric;
    v_serial:=coalesce(r->>'bankSerial','');
    v_reference:=coalesce(r->>'bankReference','');
    v_description:=coalesce(r->>'description','');
    v_memo:=coalesce(r->>'memo','');
    v_party_name:=coalesce(r->>'partyName','');
    v_status:=case when r->>'status'='pending' then 'pending' else 'completed' end;
    v_id:=null;

    -- Hapoalim reference numbers are not globally unique. The bank serial is day-scoped and is
    -- the strongest stable identifier available for completed rows, so date is part of every match.
    if v_date is not null and v_serial not in ('','0') then
      select count(*),min(b.id) into v_candidates,v_candidate
      from public.bank_transactions b
      where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role
        and b.transaction_date::date=v_date::date and b.bank_serial=v_serial and b.amount=v_amount;
      if v_candidates>1 then
        raise exception 'bank_archive_existing_identity_collision'
          using errcode='40001', hint='More than one archived row matches the same bank date/serial/amount identity. No merge was committed.';
      elsif v_candidates=1 then v_id:=v_candidate; end if;
    end if;
    if v_id is null and v_date is not null and v_reference<>'' then
      select count(*),min(b.id) into v_candidates,v_candidate
      from public.bank_transactions b
      where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role
        and b.transaction_date::date=v_date::date and b.bank_reference=v_reference and b.amount=v_amount
        and b.description=v_description and b.memo=v_memo;
      if v_candidates>1 then
        raise exception 'bank_archive_existing_identity_collision'
          using errcode='40001', hint='More than one archived row matches the same bank date/reference/amount/content identity. No merge was committed.';
      elsif v_candidates=1 then v_id:=v_candidate; end if;
    end if;

    -- Pending -> completed reconciliation is deliberately conservative. Prefer the same bank
    -- reference across a small date shift; only fall back to content when at least one strong
    -- beneficiary/memo field exists and every supplied strong field matches exactly.
    if v_id is null and v_status='completed' and v_date is not null and v_reference<>'' then
      select count(*),min(b.id) into v_candidates,v_candidate
      from public.bank_transactions b
      where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role
        and b.status='pending' and b.amount=v_amount and b.bank_reference=v_reference
        and b.transaction_date between (v_date-interval '3 days') and (v_date+interval '3 days');
      if v_candidates=1 then v_id:=v_candidate; end if;
    end if;
    if v_id is null and v_status='completed' and v_date is not null and (v_memo<>'' or v_party_name<>'') then
      select count(*),min(b.id) into v_candidates,v_candidate
      from public.bank_transactions b
      where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role
        and b.status='pending' and b.amount=v_amount and b.description=v_description
        and (v_memo='' or b.memo=v_memo) and (v_party_name='' or b.party_name=v_party_name)
        and b.transaction_date between (v_date-interval '3 days') and (v_date+interval '3 days');
      if v_candidates=1 then v_id:=v_candidate; end if;
    end if;
    if v_id is null and coalesce(r->>'mergeKey','')<>'' then
      select count(*),min(b.id) into v_candidates,v_candidate
      from public.bank_transactions b
      where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role and b.merge_key=r->>'mergeKey';
      if v_candidates>1 then
        raise exception 'bank_archive_existing_merge_key_collision'
          using errcode='40001', hint='More than one archived row has the same merge key. No merge was committed.';
      elsif v_candidates=1 then v_id:=v_candidate; end if;
    end if;

    if v_id is null then
      insert into public.bank_transactions(owner_id,account_key,account_role,merge_key,transaction_date,processed_date,amount,currency,description,memo,party_name,party_headline,message_headline,message_detail,status,balance_after,bank_reference,bank_serial,activity_type_code,cheque,check_details)
      values(v_owner,p_account_key,p_account_role,r->>'mergeKey',v_date,v_processed,v_amount,coalesce(nullif(r->>'currency',''),'ILS'),v_description,coalesce(r->>'memo',''),coalesce(r->>'partyName',''),coalesce(r->>'partyHeadline',''),coalesce(r->>'messageHeadline',''),coalesce(r->>'messageDetail',''),v_status,nullif(r->>'balanceAfter','')::numeric,v_reference,v_serial,nullif(r->>'activityTypeCode','')::integer,coalesce((r->>'cheque')::boolean,false),r->'checkDetails');
      v_inserted:=v_inserted+1;
    else
      update public.bank_transactions b set
        merge_key=coalesce(nullif(r->>'mergeKey',''),b.merge_key),
        transaction_date=coalesce(v_date,b.transaction_date),
        processed_date=coalesce(v_processed,b.processed_date),
        currency=coalesce(nullif(r->>'currency',''),b.currency),
        description=coalesce(nullif(r->>'description',''),b.description),
        memo=coalesce(r->>'memo',b.memo),
        party_name=coalesce(r->>'partyName',b.party_name),
        party_headline=coalesce(r->>'partyHeadline',b.party_headline),
        message_headline=coalesce(r->>'messageHeadline',b.message_headline),
        message_detail=coalesce(r->>'messageDetail',b.message_detail),
        status=case when v_status='pending' and b.status='completed' then b.status else v_status end,
        balance_after=coalesce(nullif(r->>'balanceAfter','')::numeric,b.balance_after),
        bank_reference=coalesce(nullif(r->>'bankReference',''),b.bank_reference),
        bank_serial=coalesce(nullif(r->>'bankSerial',''),b.bank_serial),
        activity_type_code=coalesce(nullif(r->>'activityTypeCode','')::integer,b.activity_type_code),
        cheque=coalesce((r->>'cheque')::boolean,b.cheque),
        check_details=coalesce(r->'checkDetails',b.check_details),
        last_changed_at=now()
      where b.id=v_id and (
        b.merge_key is distinct from coalesce(nullif(r->>'mergeKey',''),b.merge_key)
        or b.transaction_date is distinct from coalesce(v_date,b.transaction_date)
        or b.processed_date is distinct from coalesce(v_processed,b.processed_date)
        or b.currency is distinct from coalesce(nullif(r->>'currency',''),b.currency)
        or b.description is distinct from coalesce(nullif(r->>'description',''),b.description)
        or b.memo is distinct from coalesce(r->>'memo',b.memo)
        or b.party_name is distinct from coalesce(r->>'partyName',b.party_name)
        or b.party_headline is distinct from coalesce(r->>'partyHeadline',b.party_headline)
        or b.message_headline is distinct from coalesce(r->>'messageHeadline',b.message_headline)
        or b.message_detail is distinct from coalesce(r->>'messageDetail',b.message_detail)
        or b.status is distinct from (case when v_status='pending' and b.status='completed' then b.status else v_status end)
        or b.balance_after is distinct from coalesce(nullif(r->>'balanceAfter','')::numeric,b.balance_after)
        or b.bank_reference is distinct from coalesce(nullif(r->>'bankReference',''),b.bank_reference)
        or b.bank_serial is distinct from coalesce(nullif(r->>'bankSerial',''),b.bank_serial)
        or b.activity_type_code is distinct from coalesce(nullif(r->>'activityTypeCode','')::integer,b.activity_type_code)
        or b.cheque is distinct from coalesce((r->>'cheque')::boolean,b.cheque)
        or b.check_details is distinct from coalesce(r->'checkDetails',b.check_details)
      );
      if found then v_updated:=v_updated+1; end if;
    end if;
  end loop;
  -- Self-verify the statement before returning. If any source row failed to become the exact
  -- archived row for its merge key, raise and let PostgreSQL roll the whole RPC statement back.
  if exists (
    select 1
    from jsonb_array_elements(p_transactions) x(value)
    where not exists (
      select 1 from public.bank_transactions b
      where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role
        and b.merge_key=x.value->>'mergeKey'
        and (nullif(x.value->>'date','') is null or b.transaction_date is not distinct from (x.value->>'date')::timestamptz)
        and (nullif(x.value->>'processedDate','') is null or b.processed_date is not distinct from (x.value->>'processedDate')::timestamptz)
        and b.amount=(x.value->>'amount')::numeric
        and b.description=coalesce(x.value->>'description','')
        and b.memo=coalesce(x.value->>'memo','')
        and (coalesce(x.value->>'bankReference','')='' or b.bank_reference=x.value->>'bankReference')
        and (coalesce(x.value->>'bankSerial','')='' or b.bank_serial=x.value->>'bankSerial')
        and (case when x.value->>'status'='pending' then b.status in ('pending','completed') else b.status='completed' end)
    )
  ) then
    raise exception 'bank_archive_merge_verification_failed'
      using errcode='40001', hint='The transaction merge did not reproduce every bank row exactly. The entire RPC was rolled back.';
  end if;

  select count(*)::int into total_count from public.bank_transactions b where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role;
  inserted_count:=v_inserted; updated_count:=v_updated; return next;
end $$;
revoke all on function public.merge_bank_transactions(text,text,jsonb) from public,anon;
grant execute on function public.merge_bank_transactions(text,text,jsonb) to authenticated;

-- Owner-scoped writes for the invoker-rights RPCs.
grant insert, update on table public.finance_sync_documents to authenticated;
drop policy if exists "finance_sync_insert_own" on public.finance_sync_documents;
create policy "finance_sync_insert_own" on public.finance_sync_documents for insert to authenticated with check ((select auth.uid())=owner_id);
drop policy if exists "finance_sync_update_own" on public.finance_sync_documents;
create policy "finance_sync_update_own" on public.finance_sync_documents for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
grant insert, update on table public.bank_transactions to authenticated;
grant usage, select on sequence public.bank_transactions_id_seq to authenticated;
drop policy if exists "bank_transactions_insert_own" on public.bank_transactions;
create policy "bank_transactions_insert_own" on public.bank_transactions for insert to authenticated with check ((select auth.uid())=owner_id);
drop policy if exists "bank_transactions_update_own" on public.bank_transactions;
create policy "bank_transactions_update_own" on public.bank_transactions for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
