-- ניהול קופה — Supabase Cloud Sync / Data Safety v4 (post-cutover)
-- מיועד למבנה החדש שבו צ'קים נשמרים אך ורק ב-shared_checks_documents.
-- למעבר ממבנה ישן שבו checks נמצא בתוך kupa_documents יש להריץ netunim-orders/supabase/shared/cutover.sql.

begin;
set local lock_timeout = '10s';
set local statement_timeout = '90s';

-- אותו sequence משמש את RPC הקופה (צילום יתרה) ואת RPC הצ'קים (הפקדה).
create sequence if not exists public.shared_financial_event_seq as bigint;
revoke all on sequence public.shared_financial_event_seq from public, anon, authenticated;
grant usage on sequence public.shared_financial_event_seq to authenticated;

create table if not exists public.kupa_documents (
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null default 'main',
  revision bigint not null default 1 check (revision > 0),
  state jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (owner_id, document_name)
);
create table if not exists public.kupa_document_backups (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null,
  revision bigint not null,
  state jsonb not null,
  saved_at timestamptz not null default now()
);
create table if not exists public.kupa_periodic_backups (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null,
  revision bigint not null,
  state jsonb not null,
  saved_at timestamptz not null default now()
);

create index if not exists kupa_document_backups_owner_doc_saved_idx
  on public.kupa_document_backups(owner_id, document_name, saved_at desc);
create index if not exists kupa_periodic_backups_owner_doc_saved_idx
  on public.kupa_periodic_backups(owner_id, document_name, saved_at desc);
create unique index if not exists kupa_document_backups_owner_doc_revision_uidx
  on public.kupa_document_backups(owner_id, document_name, revision);
create unique index if not exists kupa_periodic_backups_owner_doc_revision_uidx
  on public.kupa_periodic_backups(owner_id, document_name, revision);

-- מסמך חי: checks אסור במפורש. bank.adjustments אינו רשאי להכיל check_deposit.
alter table public.kupa_documents drop constraint if exists kupa_documents_state_shape_check;
alter table public.kupa_documents
  add constraint kupa_documents_state_shape_check
  check (
    jsonb_typeof(state) = 'object'
    and not (state ? 'checks')
    and jsonb_typeof(state->'credits') = 'array'
    and jsonb_typeof(state->'cash') = 'array'
    and jsonb_typeof(state->'expenses') = 'array'
    and jsonb_typeof(state->'cards') = 'array'
    and jsonb_typeof(state->'bank') = 'object'
    and jsonb_typeof(state#>'{bank,adjustments}') = 'array'
  ) not valid;

-- גיבויים חייבים להמשיך לקבל גם snapshots היסטוריים מלפני ה-cutover שבהם checks היה קיים.
alter table public.kupa_document_backups drop constraint if exists kupa_document_backups_revision_check;
alter table public.kupa_document_backups
  add constraint kupa_document_backups_revision_check check (revision > 0) not valid;
alter table public.kupa_document_backups drop constraint if exists kupa_document_backups_state_shape_check;
alter table public.kupa_document_backups
  add constraint kupa_document_backups_state_shape_check
  check (
    jsonb_typeof(state) = 'object'
    and (not (state ? 'checks') or jsonb_typeof(state->'checks') = 'array')
    and jsonb_typeof(state->'credits') = 'array'
    and jsonb_typeof(state->'cash') = 'array'
    and jsonb_typeof(state->'expenses') = 'array'
    and jsonb_typeof(state->'cards') = 'array'
  ) not valid;
alter table public.kupa_periodic_backups drop constraint if exists kupa_periodic_backups_revision_check;
alter table public.kupa_periodic_backups
  add constraint kupa_periodic_backups_revision_check check (revision > 0) not valid;
alter table public.kupa_periodic_backups drop constraint if exists kupa_periodic_backups_state_shape_check;
alter table public.kupa_periodic_backups
  add constraint kupa_periodic_backups_state_shape_check
  check (
    jsonb_typeof(state) = 'object'
    and (not (state ? 'checks') or jsonb_typeof(state->'checks') = 'array')
    and jsonb_typeof(state->'credits') = 'array'
    and jsonb_typeof(state->'cash') = 'array'
    and jsonb_typeof(state->'expenses') = 'array'
    and jsonb_typeof(state->'cards') = 'array'
  ) not valid;

alter table public.kupa_documents validate constraint kupa_documents_state_shape_check;
alter table public.kupa_document_backups validate constraint kupa_document_backups_revision_check;
alter table public.kupa_document_backups validate constraint kupa_document_backups_state_shape_check;
alter table public.kupa_periodic_backups validate constraint kupa_periodic_backups_revision_check;
alter table public.kupa_periodic_backups validate constraint kupa_periodic_backups_state_shape_check;

alter table public.kupa_documents enable row level security;
alter table public.kupa_document_backups enable row level security;
alter table public.kupa_periodic_backups enable row level security;
revoke all on table public.kupa_documents from anon, authenticated;
revoke all on table public.kupa_document_backups from anon, authenticated;
revoke all on table public.kupa_periodic_backups from anon, authenticated;
grant select, insert, update on table public.kupa_documents to authenticated;
grant select, insert, delete on table public.kupa_document_backups to authenticated;
grant select, insert, delete on table public.kupa_periodic_backups to authenticated;
revoke all on sequence public.kupa_document_backups_id_seq from public, anon;
revoke all on sequence public.kupa_periodic_backups_id_seq from public, anon;
grant usage, select on sequence public.kupa_document_backups_id_seq to authenticated;
grant usage, select on sequence public.kupa_periodic_backups_id_seq to authenticated;

drop policy if exists "kupa_documents_select_own" on public.kupa_documents;
create policy "kupa_documents_select_own" on public.kupa_documents
for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "kupa_documents_insert_own" on public.kupa_documents;
create policy "kupa_documents_insert_own" on public.kupa_documents
for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "kupa_documents_update_own" on public.kupa_documents;
create policy "kupa_documents_update_own" on public.kupa_documents
for update to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id)
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists "kupa_backups_select_own" on public.kupa_document_backups;
create policy "kupa_backups_select_own" on public.kupa_document_backups
for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "kupa_backups_insert_own" on public.kupa_document_backups;
create policy "kupa_backups_insert_own" on public.kupa_document_backups
for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "kupa_backups_delete_own" on public.kupa_document_backups;
create policy "kupa_backups_delete_own" on public.kupa_document_backups
for delete to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists "kupa_periodic_backups_select_own" on public.kupa_periodic_backups;
create policy "kupa_periodic_backups_select_own" on public.kupa_periodic_backups
for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "kupa_periodic_backups_insert_own" on public.kupa_periodic_backups;
create policy "kupa_periodic_backups_insert_own" on public.kupa_periodic_backups
for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "kupa_periodic_backups_delete_own" on public.kupa_periodic_backups;
create policy "kupa_periodic_backups_delete_own" on public.kupa_periodic_backups
for delete to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

create or replace function public.kupa_guard_document_write()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
begin
  if current_user = 'authenticated'
     and coalesce(current_setting('app.kupa_rpc_write', true), '') <> '1' then
    raise exception 'direct_kupa_write_forbidden'
      using errcode = '42501',
            hint = 'Use save_kupa_document RPC so revision checks and backups cannot be bypassed.';
  end if;
  if tg_op = 'UPDATE' and (
       new.owner_id is distinct from old.owner_id
       or new.document_name is distinct from old.document_name
     ) then
    raise exception 'kupa_document_identity_change_forbidden' using errcode = '22023';
  end if;
  return new;
end;
$$;
revoke all on function public.kupa_guard_document_write() from public, anon;
grant execute on function public.kupa_guard_document_write() to authenticated;
drop trigger if exists kupa_documents_write_guard on public.kupa_documents;
create trigger kupa_documents_write_guard
before insert or update on public.kupa_documents
for each row execute function public.kupa_guard_document_write();

-- הפלט כולל את state שהשרת אישר, משום snapshotSeq/updatedAt של צילום בנק הם server-authoritative.
drop function if exists public.save_kupa_document(text, bigint, jsonb);
create function public.save_kupa_document(
  p_document_name text,
  p_expected_revision bigint,
  p_state jsonb
)
returns table(revision bigint, updated_at timestamptz, state jsonb)
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_owner uuid := auth.uid();
  v_current_revision bigint;
  v_old_state jsonb;
  v_old_updated_at timestamptz;
  v_server_state jsonb;
  v_bank jsonb;
  v_old_bank jsonb;
  v_new_token text;
  v_old_token text;
  v_requested_snapshot_num numeric;
  v_requested_snapshot_seq bigint;
  v_old_snapshot_seq bigint := 0;
  v_shared_max_seq bigint := 0;
  v_now timestamptz;
  v_new_revision bigint;
  v_new_updated_at timestamptz;
begin
  if v_owner is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;
  if p_document_name is null or btrim(p_document_name) = '' then
    raise exception 'invalid_document_name' using errcode = '22023';
  end if;
  if p_expected_revision is null or p_expected_revision < 0 then
    raise exception 'invalid_expected_revision' using errcode = '22023';
  end if;
  if p_state is null
     or jsonb_typeof(p_state) is distinct from 'object'
     or (p_state ? 'checks')
     or jsonb_typeof(p_state->'credits') is distinct from 'array'
     or jsonb_typeof(p_state->'cash') is distinct from 'array'
     or jsonb_typeof(p_state->'expenses') is distinct from 'array'
     or jsonb_typeof(p_state->'cards') is distinct from 'array'
     or jsonb_typeof(p_state->'bank') is distinct from 'object'
     or jsonb_typeof(p_state#>'{bank,adjustments}') is distinct from 'array' then
    raise exception 'invalid_kupa_state'
      using errcode = '22023',
            hint = 'Post-cutover state must contain credits/cash/expenses/cards arrays and bank object, without checks.';
  end if;
  if exists (
    select 1 from jsonb_array_elements(p_state#>'{bank,adjustments}') a
    where a->>'type' = 'check_deposit'
  ) then
    raise exception 'legacy_check_deposit_forbidden'
      using errcode = '22023', hint = 'Check deposits are derived from shared_checks_documents after cutover.';
  end if;

  perform set_config('app.kupa_rpc_write', '1', true);

  select d.revision, d.state, d.updated_at
    into v_current_revision, v_old_state, v_old_updated_at
  from public.kupa_documents d
  where d.owner_id = v_owner and d.document_name = p_document_name
  for update;

  v_server_state := p_state;
  v_bank := p_state->'bank';
  v_old_bank := coalesce(v_old_state->'bank','{}'::jsonb);
  v_new_token := nullif(v_bank->>'snapshotToken','');
  v_old_token := nullif(v_old_bank->>'snapshotToken','');

  if v_new_token is distinct from v_old_token and v_new_token is not null then
    if jsonb_typeof(v_bank->'currentBalance') is distinct from 'number'
       or jsonb_typeof(v_bank->'snapshotSeq') is distinct from 'number' then
      raise exception 'invalid_bank_snapshot' using errcode = '22023';
    end if;

    -- snapshotSeq הוא watermark שהלקוח באמת ראה אחרי sync של מאגר הצ'קים.
    -- אסור לשרת להקצות כאן sequence חדש: אירוע צ'ק מקביל שלא נצפה חייב להישאר אחרי ה-baseline.
    v_requested_snapshot_num := (v_bank->>'snapshotSeq')::numeric;
    if v_requested_snapshot_num < 0
       or v_requested_snapshot_num <> trunc(v_requested_snapshot_num)
       or v_requested_snapshot_num > 9223372036854775807::numeric then
      raise exception 'invalid_bank_snapshot_sequence' using errcode = '22023';
    end if;
    v_requested_snapshot_seq := v_requested_snapshot_num::bigint;

    if jsonb_typeof(v_old_bank->'snapshotSeq') = 'number' then
      begin
        v_old_snapshot_seq := greatest(0, (v_old_bank->>'snapshotSeq')::bigint);
      exception when others then
        raise exception 'invalid_existing_bank_snapshot_sequence' using errcode = '22023';
      end;
    end if;

    select coalesce(max((e.value->>'seq')::bigint), 0)
      into v_shared_max_seq
    from public.shared_checks_documents s
    left join lateral jsonb_array_elements(
      case when jsonb_typeof(s.state->'bankEvents')='array' then s.state->'bankEvents' else '[]'::jsonb end
    ) e(value) on true
    where s.owner_id = v_owner and s.document_name = 'main';
    v_shared_max_seq := coalesce(v_shared_max_seq, 0);

    if v_requested_snapshot_seq < v_old_snapshot_seq then
      raise exception 'stale_bank_snapshot_watermark'
        using errcode = '40001', hint = 'Refresh shared checks before saving a new bank snapshot.';
    end if;
    if v_requested_snapshot_seq > greatest(v_old_snapshot_seq, v_shared_max_seq) then
      raise exception 'bank_snapshot_watermark_ahead_of_server'
        using errcode = '22023', hint = 'The client watermark was not observed in shared check events.';
    end if;

    v_now := clock_timestamp();
    v_bank := v_bank || jsonb_build_object('snapshotSeq', v_requested_snapshot_seq, 'updatedAt', v_now);
  elsif v_old_state is not null then
    -- metadata שהשרת הקצה אינו ניתן לשכתוב מה-client; retry נשאר idempotent.
    v_bank := v_bank || jsonb_build_object(
      'snapshotSeq', coalesce(v_old_bank->'snapshotSeq','null'::jsonb),
      'updatedAt', coalesce(v_old_bank->'updatedAt','null'::jsonb)
    );
  else
    v_bank := v_bank || jsonb_build_object('snapshotSeq', null);
  end if;
  v_server_state := (v_server_state - 'bank') || jsonb_build_object('bank', v_bank);

  if v_current_revision is null then
    if coalesce(p_expected_revision,0) <> 0 then
      raise exception 'revision_conflict' using errcode = '40001';
    end if;
    insert into public.kupa_documents(owner_id, document_name, revision, state, updated_at)
    values (v_owner, p_document_name, 1, v_server_state, now())
    returning kupa_documents.revision, kupa_documents.updated_at, kupa_documents.state
      into v_new_revision, v_new_updated_at, v_server_state;
    insert into public.kupa_periodic_backups(owner_id, document_name, revision, state, saved_at)
    values (v_owner, p_document_name, v_new_revision, v_server_state, v_new_updated_at)
    on conflict do nothing;
    return query select v_new_revision, v_new_updated_at, v_server_state;
    return;
  end if;

  -- ACK שאבד: קודם בודקים אם התוכן שכבר בשרת הוא בדיוק התוכן המבוקש.
  if v_old_state = v_server_state then
    return query select v_current_revision, v_old_updated_at, v_old_state;
    return;
  end if;
  if v_current_revision <> p_expected_revision then
    raise exception 'revision_conflict' using errcode = '40001';
  end if;

  insert into public.kupa_document_backups(owner_id, document_name, revision, state, saved_at)
  values (v_owner, p_document_name, v_current_revision, v_old_state, v_old_updated_at)
  on conflict do nothing;

  update public.kupa_documents d
  set revision = d.revision + 1, state = v_server_state, updated_at = now()
  where d.owner_id = v_owner and d.document_name = p_document_name
  returning d.revision, d.updated_at, d.state
    into v_new_revision, v_new_updated_at, v_server_state;

  if not exists (
    select 1 from public.kupa_periodic_backups p
    where p.owner_id = v_owner and p.document_name = p_document_name
      and p.saved_at > now() - interval '12 hours'
  ) then
    insert into public.kupa_periodic_backups(owner_id, document_name, revision, state, saved_at)
    values (v_owner, p_document_name, v_new_revision, v_server_state, v_new_updated_at)
    on conflict do nothing;
  end if;

  delete from public.kupa_periodic_backups p
  where p.owner_id = v_owner and p.document_name = p_document_name
    and p.saved_at < now() - interval '365 days';
  delete from public.kupa_document_backups b
  where b.owner_id = v_owner and b.document_name = p_document_name
    and b.id in (
      select x.id from public.kupa_document_backups x
      where x.owner_id = v_owner and x.document_name = p_document_name
      order by x.saved_at desc, x.id desc offset 200
    );

  return query select v_new_revision, v_new_updated_at, v_server_state;
end;
$$;
revoke all on function public.save_kupa_document(text, bigint, jsonb) from public, anon;
grant execute on function public.save_kupa_document(text, bigint, jsonb) to authenticated;

insert into public.kupa_periodic_backups(owner_id, document_name, revision, state, saved_at)
select d.owner_id, d.document_name, d.revision, d.state, d.updated_at
from public.kupa_documents d
where not exists (
  select 1 from public.kupa_periodic_backups p
  where p.owner_id=d.owner_id and p.document_name=d.document_name
)
on conflict (owner_id, document_name, revision) do nothing;

commit;
