-- ניהול קופה — Supabase Cloud Sync / Data Safety v4 (post-cutover)
-- מיועד למבנה החדש שבו צ'קים נשמרים אך ורק ב-shared_checks_documents.
-- למעבר ממבנה ישן שבו checks נמצא בתוך kupa_documents יש להריץ netunim-orders/supabase/shared/cutover.sql.

begin;
set local lock_timeout = '10s';
set local statement_timeout = '90s';

-- אותו sequence משמש את RPC הקופה (צילום יתרה) ואת RPC הצ'קים (הפקדה).
create sequence if not exists public.shared_financial_event_seq as bigint;
revoke all on sequence public.shared_financial_event_seq from public, anon, authenticated;
grant usage on sequence public.shared_financial_event_seq to authenticated;

create table if not exists public.kupa_documents (
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null default 'main',
  revision bigint not null default 1 check (revision > 0),
  state jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (owner_id, document_name)
);
create table if not exists public.kupa_document_backups (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null,
  revision bigint not null,
  state jsonb not null,
  saved_at timestamptz not null default now()
);
create table if not exists public.kupa_periodic_backups (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null,
  revision bigint not null,
  state jsonb not null,
  saved_at timestamptz not null default now()
);

create index if not exists kupa_document_backups_owner_doc_saved_idx
  on public.kupa_document_backups(owner_id, document_name, saved_at desc);
create index if not exists kupa_periodic_backups_owner_doc_saved_idx
  on public.kupa_periodic_backups(owner_id, document_name, saved_at desc);
create unique index if not exists kupa_document_backups_owner_doc_revision_uidx
  on public.kupa_document_backups(owner_id, document_name, revision);
create unique index if not exists kupa_periodic_backups_owner_doc_revision_uidx
  on public.kupa_periodic_backups(owner_id, document_name, revision);

-- מסמך חי: checks אסור במפורש. bank.adjustments אינו רשאי להכיל check_deposit.
alter table public.kupa_documents drop constraint if exists kupa_documents_state_shape_check;
alter table public.kupa_documents
  add constraint kupa_documents_state_shape_check
  check (
    jsonb_typeof(state) = 'object'
    and not (state ? 'checks')
    and jsonb_typeof(state->'credits') = 'array'
    and jsonb_typeof(state->'cash') = 'array'
    and jsonb_typeof(state->'expenses') = 'array'
    and jsonb_typeof(state->'cards') = 'array'
    and jsonb_typeof(state->'bank') = 'object'
    and jsonb_typeof(state#>'{bank,adjustments}') = 'array'
  ) not valid;

-- גיבויים חייבים להמשיך לקבל גם snapshots היסטוריים מלפני ה-cutover שבהם checks היה קיים.
alter table public.kupa_document_backups drop constraint if exists kupa_document_backups_revision_check;
alter table public.kupa_document_backups
  add constraint kupa_document_backups_revision_check check (revision > 0) not valid;
alter table public.kupa_document_backups drop constraint if exists kupa_document_backups_state_shape_check;
alter table public.kupa_document_backups
  add constraint kupa_document_backups_state_shape_check
  check (
    jsonb_typeof(state) = 'object'
    and (not (state ? 'checks') or jsonb_typeof(state->'checks') = 'array')
    and jsonb_typeof(state->'credits') = 'array'
    and jsonb_typeof(state->'cash') = 'array'
    and jsonb_typeof(state->'expenses') = 'array'
    and jsonb_typeof(state->'cards') = 'array'
  ) not valid;
alter table public.kupa_periodic_backups drop constraint if exists kupa_periodic_backups_revision_check;
alter table public.kupa_periodic_backups
  add constraint kupa_periodic_backups_revision_check check (revision > 0) not valid;
alter table public.kupa_periodic_backups drop constraint if exists kupa_periodic_backups_state_shape_check;
alter table public.kupa_periodic_backups
  add constraint kupa_periodic_backups_state_shape_check
  check (
    jsonb_typeof(state) = 'object'
    and (not (state ? 'checks') or jsonb_typeof(state->'checks') = 'array')
    and jsonb_typeof(state->'credits') = 'array'
    and jsonb_typeof(state->'cash') = 'array'
    and jsonb_typeof(state->'expenses') = 'array'
    and jsonb_typeof(state->'cards') = 'array'
  ) not valid;

alter table public.kupa_documents validate constraint kupa_documents_state_shape_check;
alter table public.kupa_document_backups validate constraint kupa_document_backups_revision_check;
alter table public.kupa_document_backups validate constraint kupa_document_backups_state_shape_check;
alter table public.kupa_periodic_backups validate constraint kupa_periodic_backups_revision_check;
alter table public.kupa_periodic_backups validate constraint kupa_periodic_backups_state_shape_check;

alter table public.kupa_documents enable row level security;
alter table public.kupa_document_backups enable row level security;
alter table public.kupa_periodic_backups enable row level security;
revoke all on table public.kupa_documents from anon, authenticated;
revoke all on table public.kupa_document_backups from anon, authenticated;
revoke all on table public.kupa_periodic_backups from anon, authenticated;
grant select, insert, update on table public.kupa_documents to authenticated;
grant select, insert, delete on table public.kupa_document_backups to authenticated;
grant select, insert, delete on table public.kupa_periodic_backups to authenticated;
revoke all on sequence public.kupa_document_backups_id_seq from public, anon;
revoke all on sequence public.kupa_periodic_backups_id_seq from public, anon;
grant usage, select on sequence public.kupa_document_backups_id_seq to authenticated;
grant usage, select on sequence public.kupa_periodic_backups_id_seq to authenticated;

drop policy if exists "kupa_documents_select_own" on public.kupa_documents;
create policy "kupa_documents_select_own" on public.kupa_documents
for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "kupa_documents_insert_own" on public.kupa_documents;
create policy "kupa_documents_insert_own" on public.kupa_documents
for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "kupa_documents_update_own" on public.kupa_documents;
create policy "kupa_documents_update_own" on public.kupa_documents
for update to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id)
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists "kupa_backups_select_own" on public.kupa_document_backups;
create policy "kupa_backups_select_own" on public.kupa_document_backups
for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "kupa_backups_insert_own" on public.kupa_document_backups;
create policy "kupa_backups_insert_own" on public.kupa_document_backups
for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "kupa_backups_delete_own" on public.kupa_document_backups;
create policy "kupa_backups_delete_own" on public.kupa_document_backups
for delete to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists "kupa_periodic_backups_select_own" on public.kupa_periodic_backups;
create policy "kupa_periodic_backups_select_own" on public.kupa_periodic_backups
for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "kupa_periodic_backups_insert_own" on public.kupa_periodic_backups;
create policy "kupa_periodic_backups_insert_own" on public.kupa_periodic_backups
for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "kupa_periodic_backups_delete_own" on public.kupa_periodic_backups;
create policy "kupa_periodic_backups_delete_own" on public.kupa_periodic_backups
for delete to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

create or replace function public.kupa_guard_document_write()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
begin
  if current_user = 'authenticated'
     and coalesce(current_setting('app.kupa_rpc_write', true), '') <> '1' then
    raise exception 'direct_kupa_write_forbidden'
      using errcode = '42501',
            hint = 'Use save_kupa_document RPC so revision checks and backups cannot be bypassed.';
  end if;
  if tg_op = 'UPDATE' and (
       new.owner_id is distinct from old.owner_id
       or new.document_name is distinct from old.document_name
     ) then
    raise exception 'kupa_document_identity_change_forbidden' using errcode = '22023';
  end if;
  return new;
end;
$$;
revoke all on function public.kupa_guard_document_write() from public, anon;
grant execute on function public.kupa_guard_document_write() to authenticated;
drop trigger if exists kupa_documents_write_guard on public.kupa_documents;
create trigger kupa_documents_write_guard
before insert or update on public.kupa_documents
for each row execute function public.kupa_guard_document_write();

-- הפלט כולל את state שהשרת אישר, משום snapshotSeq/updatedAt של צילום בנק הם server-authoritative.
drop function if exists public.save_kupa_document(text, bigint, jsonb);
create function public.save_kupa_document(
  p_document_name text,
  p_expected_revision bigint,
  p_state jsonb
)
returns table(revision bigint, updated_at timestamptz, state jsonb)
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_owner uuid := auth.uid();
  v_current_revision bigint;
  v_old_state jsonb;
  v_old_updated_at timestamptz;
  v_server_state jsonb;
  v_bank jsonb;
  v_old_bank jsonb;
  v_new_token text;
  v_old_token text;
  v_requested_snapshot_num numeric;
  v_requested_snapshot_seq bigint;
  v_old_snapshot_seq bigint := 0;
  v_shared_max_seq bigint := 0;
  v_now timestamptz;
  v_new_revision bigint;
  v_new_updated_at timestamptz;
begin
  if v_owner is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;
  if p_document_name is null or btrim(p_document_name) = '' then
    raise exception 'invalid_document_name' using errcode = '22023';
  end if;
  if p_expected_revision is null or p_expected_revision < 0 then
    raise exception 'invalid_expected_revision' using errcode = '22023';
  end if;
  if p_state is null
     or jsonb_typeof(p_state) is distinct from 'object'
     or (p_state ? 'checks')
     or jsonb_typeof(p_state->'credits') is distinct from 'array'
     or jsonb_typeof(p_state->'cash') is distinct from 'array'
     or jsonb_typeof(p_state->'expenses') is distinct from 'array'
     or jsonb_typeof(p_state->'cards') is distinct from 'array'
     or jsonb_typeof(p_state->'bank') is distinct from 'object'
     or jsonb_typeof(p_state#>'{bank,adjustments}') is distinct from 'array' then
    raise exception 'invalid_kupa_state'
      using errcode = '22023',
            hint = 'Post-cutover state must contain credits/cash/expenses/cards arrays and bank object, without checks.';
  end if;
  if exists (
    select 1 from jsonb_array_elements(p_state#>'{bank,adjustments}') a
    where a->>'type' = 'check_deposit'
  ) then
    raise exception 'legacy_check_deposit_forbidden'
      using errcode = '22023', hint = 'Check deposits are derived from shared_checks_documents after cutover.';
  end if;

  perform set_config('app.kupa_rpc_write', '1', true);

  select d.revision, d.state, d.updated_at
    into v_current_revision, v_old_state, v_old_updated_at
  from public.kupa_documents d
  where d.owner_id = v_owner and d.document_name = p_document_name
  for update;

  v_server_state := p_state;
  v_bank := p_state->'bank';
  v_old_bank := coalesce(v_old_state->'bank','{}'::jsonb);
  v_new_token := nullif(v_bank->>'snapshotToken','');
  v_old_token := nullif(v_old_bank->>'snapshotToken','');

  if v_new_token is distinct from v_old_token and v_new_token is not null then
    if jsonb_typeof(v_bank->'currentBalance') is distinct from 'number'
       or jsonb_typeof(v_bank->'snapshotSeq') is distinct from 'number' then
      raise exception 'invalid_bank_snapshot' using errcode = '22023';
    end if;

    -- snapshotSeq הוא watermark שהלקוח באמת ראה אחרי sync של מאגר הצ'קים.
    -- אסור לשרת להקצות כאן sequence חדש: אירוע צ'ק מקביל שלא נצפה חייב להישאר אחרי ה-baseline.
    v_requested_snapshot_num := (v_bank->>'snapshotSeq')::numeric;
    if v_requested_snapshot_num < 0
       or v_requested_snapshot_num <> trunc(v_requested_snapshot_num)
       or v_requested_snapshot_num > 9223372036854775807::numeric then
      raise exception 'invalid_bank_snapshot_sequence' using errcode = '22023';
    end if;
    v_requested_snapshot_seq := v_requested_snapshot_num::bigint;

    if jsonb_typeof(v_old_bank->'snapshotSeq') = 'number' then
      begin
        v_old_snapshot_seq := greatest(0, (v_old_bank->>'snapshotSeq')::bigint);
      exception when others then
        raise exception 'invalid_existing_bank_snapshot_sequence' using errcode = '22023';
      end;
    end if;

    select coalesce(max((e.value->>'seq')::bigint), 0)
      into v_shared_max_seq
    from public.shared_checks_documents s
    left join lateral jsonb_array_elements(
      case when jsonb_typeof(s.state->'bankEvents')='array' then s.state->'bankEvents' else '[]'::jsonb end
    ) e(value) on true
    where s.owner_id = v_owner and s.document_name = 'main';
    v_shared_max_seq := coalesce(v_shared_max_seq, 0);

    if v_requested_snapshot_seq < v_old_snapshot_seq then
      raise exception 'stale_bank_snapshot_watermark'
        using errcode = '40001', hint = 'Refresh shared checks before saving a new bank snapshot.';
    end if;
    if v_requested_snapshot_seq > greatest(v_old_snapshot_seq, v_shared_max_seq) then
      raise exception 'bank_snapshot_watermark_ahead_of_server'
        using errcode = '22023', hint = 'The client watermark was not observed in shared check events.';
    end if;

    v_now := clock_timestamp();
    v_bank := v_bank || jsonb_build_object('snapshotSeq', v_requested_snapshot_seq, 'updatedAt', v_now);
  elsif v_old_state is not null then
    -- metadata שהשרת הקצה אינו ניתן לשכתוב מה-client; retry נשאר idempotent.
    v_bank := v_bank || jsonb_build_object(
      'snapshotSeq', coalesce(v_old_bank->'snapshotSeq','null'::jsonb),
      'updatedAt', coalesce(v_old_bank->'updatedAt','null'::jsonb)
    );
  else
    v_bank := v_bank || jsonb_build_object('snapshotSeq', null);
  end if;
  v_server_state := (v_server_state - 'bank') || jsonb_build_object('bank', v_bank);

  if v_current_revision is null then
    if coalesce(p_expected_revision,0) <> 0 then
      raise exception 'revision_conflict' using errcode = '40001';
    end if;
    insert into public.kupa_documents(owner_id, document_name, revision, state, updated_at)
    values (v_owner, p_document_name, 1, v_server_state, now())
    returning kupa_documents.revision, kupa_documents.updated_at, kupa_documents.state
      into v_new_revision, v_new_updated_at, v_server_state;
    insert into public.kupa_periodic_backups(owner_id, document_name, revision, state, saved_at)
    values (v_owner, p_document_name, v_new_revision, v_server_state, v_new_updated_at)
    on conflict do nothing;
    return query select v_new_revision, v_new_updated_at, v_server_state;
    return;
  end if;

  -- ACK שאבד: קודם בודקים אם התוכן שכבר בשרת הוא בדיוק התוכן המבוקש.
  if v_old_state = v_server_state then
    return query select v_current_revision, v_old_updated_at, v_old_state;
    return;
  end if;
  if v_current_revision <> p_expected_revision then
    raise exception 'revision_conflict' using errcode = '40001';
  end if;

  insert into public.kupa_document_backups(owner_id, document_name, revision, state, saved_at)
  values (v_owner, p_document_name, v_current_revision, v_old_state, v_old_updated_at)
  on conflict do nothing;

  update public.kupa_documents d
  set revision = d.revision + 1, state = v_server_state, updated_at = now()
  where d.owner_id = v_owner and d.document_name = p_document_name
  returning d.revision, d.updated_at, d.state
    into v_new_revision, v_new_updated_at, v_server_state;

  if not exists (
    select 1 from public.kupa_periodic_backups p
    where p.owner_id = v_owner and p.document_name = p_document_name
      and p.saved_at > now() - interval '12 hours'
  ) then
    insert into public.kupa_periodic_backups(owner_id, document_name, revision, state, saved_at)
    values (v_owner, p_document_name, v_new_revision, v_server_state, v_new_updated_at)
    on conflict do nothing;
  end if;

  delete from public.kupa_periodic_backups p
  where p.owner_id = v_owner and p.document_name = p_document_name
    and p.saved_at < now() - interval '365 days';
  delete from public.kupa_document_backups b
  where b.owner_id = v_owner and b.document_name = p_document_name
    and b.id in (
      select x.id from public.kupa_document_backups x
      where x.owner_id = v_owner and x.document_name = p_document_name
      order by x.saved_at desc, x.id desc offset 200
    );

  return query select v_new_revision, v_new_updated_at, v_server_state;
end;
$$;
revoke all on function public.save_kupa_document(text, bigint, jsonb) from public, anon;
grant execute on function public.save_kupa_document(text, bigint, jsonb) to authenticated;

insert into public.kupa_periodic_backups(owner_id, document_name, revision, state, saved_at)
select d.owner_id, d.document_name, d.revision, d.state, d.updated_at
from public.kupa_documents d
where not exists (
  select 1 from public.kupa_periodic_backups p
  where p.owner_id=d.owner_id and p.document_name=d.document_name
)
on conflict (owner_id, document_name, revision) do nothing;

commit;

-- Financial sync data is intentionally isolated from kupa_documents backups.
create table if not exists public.finance_sync_documents (
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null default 'main',
  revision bigint not null default 1 check (revision > 0),
  state jsonb not null default '{"bank":null,"creditSync":null}'::jsonb check (jsonb_typeof(state)='object'),
  updated_at timestamptz not null default now(),
  primary key (owner_id, document_name)
);
alter table public.finance_sync_documents enable row level security;
revoke all on table public.finance_sync_documents from anon, authenticated;
grant select on table public.finance_sync_documents to authenticated;
drop policy if exists "finance_sync_select_own" on public.finance_sync_documents;
create policy "finance_sync_select_own" on public.finance_sync_documents for select to authenticated using ((select auth.uid()) = owner_id);

create or replace function public.save_finance_sync_document(p_document_name text, p_expected_revision bigint, p_state jsonb)
returns table(revision bigint, updated_at timestamptz, state jsonb)
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  v_owner uuid := auth.uid();
  v_current bigint;
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  if p_document_name is null or btrim(p_document_name)='' then raise exception 'invalid_document_name' using errcode='22023'; end if;
  if p_expected_revision is null or p_expected_revision < 0 then raise exception 'invalid_expected_revision' using errcode='22023'; end if;
  if p_state is null or jsonb_typeof(p_state) is distinct from 'object' then raise exception 'invalid_finance_sync_state' using errcode='22023'; end if;

  select d.revision into v_current from public.finance_sync_documents d
  where d.owner_id=v_owner and d.document_name=p_document_name for update;
  if v_current is null then
    if p_expected_revision<>0 then raise exception 'revision_conflict' using errcode='40001'; end if;
    insert into public.finance_sync_documents(owner_id,document_name,revision,state,updated_at)
    values(v_owner,p_document_name,1,p_state,now())
    returning finance_sync_documents.revision,finance_sync_documents.updated_at,finance_sync_documents.state
    into revision,updated_at,state;
    return next; return;
  end if;
  if v_current<>p_expected_revision then raise exception 'revision_conflict' using errcode='40001'; end if;
  update public.finance_sync_documents d set revision=d.revision+1,state=p_state,updated_at=now()
  where d.owner_id=v_owner and d.document_name=p_document_name
  returning d.revision,d.updated_at,d.state into revision,updated_at,state;
  return next;
end $$;
revoke all on function public.save_finance_sync_document(text,bigint,jsonb) from public, anon;
grant execute on function public.save_finance_sync_document(text,bigint,jsonb) to authenticated;

create table if not exists public.bank_transactions (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  account_key text not null,
  account_role text not null check (account_role in ('business','home')),
  merge_key text not null,
  transaction_date timestamptz,
  processed_date timestamptz,
  amount numeric not null,
  currency text not null default 'ILS',
  description text not null default '',
  memo text not null default '',
  party_name text not null default '',
  party_headline text not null default '',
  message_headline text not null default '',
  message_detail text not null default '',
  status text not null default 'completed' check(status in ('pending','completed')),
  balance_after numeric,
  bank_reference text not null default '',
  bank_serial text not null default '',
  activity_type_code integer,
  cheque boolean not null default false,
  check_details jsonb,
  first_seen_at timestamptz not null default now(),
  last_changed_at timestamptz not null default now(),
  unique(owner_id,account_key,merge_key)
);
create index if not exists bank_transactions_owner_account_date_idx on public.bank_transactions(owner_id,account_key,transaction_date desc);
create index if not exists bank_transactions_owner_reference_idx on public.bank_transactions(owner_id,account_key,bank_reference) where bank_reference<>'';
alter table public.bank_transactions enable row level security;
revoke all on table public.bank_transactions from anon, authenticated;
grant select on table public.bank_transactions to authenticated;
drop policy if exists "bank_transactions_select_own" on public.bank_transactions;
create policy "bank_transactions_select_own" on public.bank_transactions for select to authenticated using ((select auth.uid())=owner_id);

create or replace function public.merge_bank_transactions(p_account_key text,p_account_role text,p_transactions jsonb)
returns table(inserted_count integer, updated_count integer, total_count integer)
language plpgsql
set search_path=pg_catalog,public
as $$
declare
  v_owner uuid:=auth.uid(); r jsonb; v_id bigint; v_inserted int:=0; v_updated int:=0; v_candidates int; v_candidate bigint;
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  if coalesce(btrim(p_account_key),'')='' or p_account_role not in ('business','home') or jsonb_typeof(p_transactions) is distinct from 'array' then raise exception 'invalid_bank_merge_input' using errcode='22023'; end if;
  for r in select value from jsonb_array_elements(p_transactions) loop
    v_id:=null;
    -- Strong identifiers first.
    if coalesce(r->>'bankReference','')<>'' then
      select id into v_id from public.bank_transactions where owner_id=v_owner and account_key=p_account_key and bank_reference=r->>'bankReference' and amount=(r->>'amount')::numeric order by id desc limit 1;
    end if;
    if v_id is null and coalesce(r->>'bankSerial','') not in ('','0') then
      select id into v_id from public.bank_transactions where owner_id=v_owner and account_key=p_account_key and bank_serial=r->>'bankSerial' and amount=(r->>'amount')::numeric order by id desc limit 1;
    end if;
    -- Pending -> completed reconciliation only when exactly one candidate exists.
    if v_id is null and coalesce(r->>'status','completed')='completed' then
      select count(*),min(id) into v_candidates,v_candidate from public.bank_transactions
      where owner_id=v_owner and account_key=p_account_key and status='pending' and amount=(r->>'amount')::numeric
        and description=coalesce(r->>'description','')
        and transaction_date between ((r->>'date')::timestamptz-interval '3 days') and ((r->>'date')::timestamptz+interval '3 days');
      if v_candidates=1 then v_id:=v_candidate; end if;
    end if;
    if v_id is null then
      select id into v_id from public.bank_transactions where owner_id=v_owner and account_key=p_account_key and merge_key=r->>'mergeKey' limit 1;
    end if;
    if v_id is null then
      insert into public.bank_transactions(owner_id,account_key,account_role,merge_key,transaction_date,processed_date,amount,currency,description,memo,party_name,party_headline,message_headline,message_detail,status,balance_after,bank_reference,bank_serial,activity_type_code,cheque,check_details)
      values(v_owner,p_account_key,p_account_role,r->>'mergeKey',nullif(r->>'date','')::timestamptz,nullif(r->>'processedDate','')::timestamptz,(r->>'amount')::numeric,coalesce(nullif(r->>'currency',''),'ILS'),coalesce(r->>'description',''),coalesce(r->>'memo',''),coalesce(r->>'partyName',''),coalesce(r->>'partyHeadline',''),coalesce(r->>'messageHeadline',''),coalesce(r->>'messageDetail',''),case when r->>'status'='pending' then 'pending' else 'completed' end,nullif(r->>'balanceAfter','')::numeric,coalesce(r->>'bankReference',''),coalesce(r->>'bankSerial',''),nullif(r->>'activityTypeCode','')::integer,coalesce((r->>'cheque')::boolean,false),r->'checkDetails');
      v_inserted:=v_inserted+1;
    else
      update public.bank_transactions set
        merge_key=coalesce(nullif(r->>'mergeKey',''),merge_key), transaction_date=coalesce(nullif(r->>'date','')::timestamptz,transaction_date), processed_date=coalesce(nullif(r->>'processedDate','')::timestamptz,processed_date),
        currency=coalesce(nullif(r->>'currency',''),currency), description=coalesce(nullif(r->>'description',''),description), memo=coalesce(r->>'memo',memo), party_name=coalesce(r->>'partyName',party_name),party_headline=coalesce(r->>'partyHeadline',party_headline),message_headline=coalesce(r->>'messageHeadline',message_headline),message_detail=coalesce(r->>'messageDetail',message_detail),
        status=case when r->>'status'='pending' and status='completed' then status else coalesce(r->>'status',status) end, balance_after=coalesce(nullif(r->>'balanceAfter','')::numeric,balance_after), bank_reference=coalesce(nullif(r->>'bankReference',''),bank_reference),bank_serial=coalesce(nullif(r->>'bankSerial',''),bank_serial),activity_type_code=coalesce(nullif(r->>'activityTypeCode','')::integer,activity_type_code),cheque=coalesce((r->>'cheque')::boolean,cheque),check_details=coalesce(r->'checkDetails',check_details),last_changed_at=now()
      where id=v_id;
      v_updated:=v_updated+1;
    end if;
  end loop;
  select count(*)::int into total_count from public.bank_transactions where owner_id=v_owner and account_key=p_account_key;
  inserted_count:=v_inserted; updated_count:=v_updated; return next;
end $$;
revoke all on function public.merge_bank_transactions(text,text,jsonb) from public,anon;
grant execute on function public.merge_bank_transactions(text,text,jsonb) to authenticated;

-- Write access is still owner-scoped by RLS; RPCs do not use service_role.
grant insert, update on table public.finance_sync_documents to authenticated;
drop policy if exists "finance_sync_insert_own" on public.finance_sync_documents;
create policy "finance_sync_insert_own" on public.finance_sync_documents for insert to authenticated with check ((select auth.uid())=owner_id);
drop policy if exists "finance_sync_update_own" on public.finance_sync_documents;
create policy "finance_sync_update_own" on public.finance_sync_documents for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
grant insert, update on table public.bank_transactions to authenticated;
grant usage, select on sequence public.bank_transactions_id_seq to authenticated;
drop policy if exists "bank_transactions_insert_own" on public.bank_transactions;
create policy "bank_transactions_insert_own" on public.bank_transactions for insert to authenticated with check ((select auth.uid())=owner_id);
drop policy if exists "bank_transactions_update_own" on public.bank_transactions;
create policy "bank_transactions_update_own" on public.bank_transactions for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
