-- ניהול קופה — Supabase Cloud Sync / Data Safety v4 (post-cutover)
-- מיועד למבנה החדש שבו צ'קים נשמרים אך ורק ב-shared_checks_documents.
-- למעבר ממבנה ישן שבו checks נמצא בתוך kupa_documents יש להריץ netunim-orders/supabase/shared/cutover.sql.

begin;
set local lock_timeout = '10s';
set local statement_timeout = '90s';

-- אותו sequence משמש את RPC הקופה (צילום יתרה) ואת RPC הצ'קים (הפקדה).
create sequence if not exists public.shared_financial_event_seq as bigint;
revoke all on sequence public.shared_financial_event_seq from public, anon, authenticated;
grant usage on sequence public.shared_financial_event_seq to authenticated;

create table if not exists public.kupa_documents (
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null default 'main',
  revision bigint not null default 1 check (revision > 0),
  state jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (owner_id, document_name)
);
create table if not exists public.kupa_document_backups (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null,
  revision bigint not null,
  state jsonb not null,
  saved_at timestamptz not null default now()
);
create table if not exists public.kupa_periodic_backups (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null,
  revision bigint not null,
  state jsonb not null,
  saved_at timestamptz not null default now()
);

create index if not exists kupa_document_backups_owner_doc_saved_idx
  on public.kupa_document_backups(owner_id, document_name, saved_at desc);
create index if not exists kupa_periodic_backups_owner_doc_saved_idx
  on public.kupa_periodic_backups(owner_id, document_name, saved_at desc);
create unique index if not exists kupa_document_backups_owner_doc_revision_uidx
  on public.kupa_document_backups(owner_id, document_name, revision);
create unique index if not exists kupa_periodic_backups_owner_doc_revision_uidx
  on public.kupa_periodic_backups(owner_id, document_name, revision);

-- מסמך חי: checks אסור במפורש. bank.adjustments אינו רשאי להכיל check_deposit.
alter table public.kupa_documents drop constraint if exists kupa_documents_state_shape_check;
alter table public.kupa_documents
  add constraint kupa_documents_state_shape_check
  check (
    jsonb_typeof(state) = 'object'
    and not (state ? 'checks')
    and jsonb_typeof(state->'credits') = 'array'
    and jsonb_typeof(state->'cash') = 'array'
    and jsonb_typeof(state->'expenses') = 'array'
    and jsonb_typeof(state->'cards') = 'array'
    and jsonb_typeof(state->'bank') = 'object'
    and jsonb_typeof(state#>'{bank,adjustments}') = 'array'
  ) not valid;

-- גיבויים חייבים להמשיך לקבל גם snapshots היסטוריים מלפני ה-cutover שבהם checks היה קיים.
alter table public.kupa_document_backups drop constraint if exists kupa_document_backups_revision_check;
alter table public.kupa_document_backups
  add constraint kupa_document_backups_revision_check check (revision > 0) not valid;
alter table public.kupa_document_backups drop constraint if exists kupa_document_backups_state_shape_check;
alter table public.kupa_document_backups
  add constraint kupa_document_backups_state_shape_check
  check (
    jsonb_typeof(state) = 'object'
    and (not (state ? 'checks') or jsonb_typeof(state->'checks') = 'array')
    and jsonb_typeof(state->'credits') = 'array'
    and jsonb_typeof(state->'cash') = 'array'
    and jsonb_typeof(state->'expenses') = 'array'
    and jsonb_typeof(state->'cards') = 'array'
  ) not valid;
alter table public.kupa_periodic_backups drop constraint if exists kupa_periodic_backups_revision_check;
alter table public.kupa_periodic_backups
  add constraint kupa_periodic_backups_revision_check check (revision > 0) not valid;
alter table public.kupa_periodic_backups drop constraint if exists kupa_periodic_backups_state_shape_check;
alter table public.kupa_periodic_backups
  add constraint kupa_periodic_backups_state_shape_check
  check (
    jsonb_typeof(state) = 'object'
    and (not (state ? 'checks') or jsonb_typeof(state->'checks') = 'array')
    and jsonb_typeof(state->'credits') = 'array'
    and jsonb_typeof(state->'cash') = 'array'
    and jsonb_typeof(state->'expenses') = 'array'
    and jsonb_typeof(state->'cards') = 'array'
  ) not valid;

alter table public.kupa_documents validate constraint kupa_documents_state_shape_check;
alter table public.kupa_document_backups validate constraint kupa_document_backups_revision_check;
alter table public.kupa_document_backups validate constraint kupa_document_backups_state_shape_check;
alter table public.kupa_periodic_backups validate constraint kupa_periodic_backups_revision_check;
alter table public.kupa_periodic_backups validate constraint kupa_periodic_backups_state_shape_check;

alter table public.kupa_documents enable row level security;
alter table public.kupa_document_backups enable row level security;
alter table public.kupa_periodic_backups enable row level security;
revoke all on table public.kupa_documents from anon, authenticated;
revoke all on table public.kupa_document_backups from anon, authenticated;
revoke all on table public.kupa_periodic_backups from anon, authenticated;
grant select, insert, update on table public.kupa_documents to authenticated;
grant select, insert, delete on table public.kupa_document_backups to authenticated;
grant select, insert, delete on table public.kupa_periodic_backups to authenticated;
revoke all on sequence public.kupa_document_backups_id_seq from public, anon;
revoke all on sequence public.kupa_periodic_backups_id_seq from public, anon;
grant usage, select on sequence public.kupa_document_backups_id_seq to authenticated;
grant usage, select on sequence public.kupa_periodic_backups_id_seq to authenticated;

drop policy if exists "kupa_documents_select_own" on public.kupa_documents;
create policy "kupa_documents_select_own" on public.kupa_documents
for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "kupa_documents_insert_own" on public.kupa_documents;
create policy "kupa_documents_insert_own" on public.kupa_documents
for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "kupa_documents_update_own" on public.kupa_documents;
create policy "kupa_documents_update_own" on public.kupa_documents
for update to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id)
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists "kupa_backups_select_own" on public.kupa_document_backups;
create policy "kupa_backups_select_own" on public.kupa_document_backups
for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "kupa_backups_insert_own" on public.kupa_document_backups;
create policy "kupa_backups_insert_own" on public.kupa_document_backups
for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "kupa_backups_delete_own" on public.kupa_document_backups;
create policy "kupa_backups_delete_own" on public.kupa_document_backups
for delete to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists "kupa_periodic_backups_select_own" on public.kupa_periodic_backups;
create policy "kupa_periodic_backups_select_own" on public.kupa_periodic_backups
for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "kupa_periodic_backups_insert_own" on public.kupa_periodic_backups;
create policy "kupa_periodic_backups_insert_own" on public.kupa_periodic_backups
for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "kupa_periodic_backups_delete_own" on public.kupa_periodic_backups;
create policy "kupa_periodic_backups_delete_own" on public.kupa_periodic_backups
for delete to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

create or replace function public.kupa_guard_document_write()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
begin
  if current_user = 'authenticated'
     and coalesce(current_setting('app.kupa_rpc_write', true), '') <> '1' then
    raise exception 'direct_kupa_write_forbidden'
      using errcode = '42501',
            hint = 'Use save_kupa_document RPC so revision checks and backups cannot be bypassed.';
  end if;
  if tg_op = 'UPDATE' and (
       new.owner_id is distinct from old.owner_id
       or new.document_name is distinct from old.document_name
     ) then
    raise exception 'kupa_document_identity_change_forbidden' using errcode = '22023';
  end if;
  return new;
end;
$$;
revoke all on function public.kupa_guard_document_write() from public, anon;
grant execute on function public.kupa_guard_document_write() to authenticated;
drop trigger if exists kupa_documents_write_guard on public.kupa_documents;
create trigger kupa_documents_write_guard
before insert or update on public.kupa_documents
for each row execute function public.kupa_guard_document_write();

-- הפלט כולל את state שהשרת אישר, משום snapshotSeq/updatedAt של צילום בנק הם server-authoritative.
drop function if exists public.save_kupa_document(text, bigint, jsonb);
create function public.save_kupa_document(
  p_document_name text,
  p_expected_revision bigint,
  p_state jsonb
)
returns table(revision bigint, updated_at timestamptz, state jsonb)
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_owner uuid := auth.uid();
  v_current_revision bigint;
  v_old_state jsonb;
  v_old_updated_at timestamptz;
  v_server_state jsonb;
  v_bank jsonb;
  v_old_bank jsonb;
  v_new_token text;
  v_old_token text;
  v_requested_snapshot_num numeric;
  v_requested_snapshot_seq bigint;
  v_old_snapshot_seq bigint := 0;
  v_shared_max_seq bigint := 0;
  v_now timestamptz;
  v_new_revision bigint;
  v_new_updated_at timestamptz;
begin
  if v_owner is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;
  -- Shared per-user financial writer gate: fail fast instead of filling the PostgREST pool.
  if not pg_try_advisory_xact_lock(
    hashtextextended('netunim_financial_write:' || v_owner::text, 0)
  ) then
    raise exception 'save_busy'
      using errcode = 'PT429',
            hint = 'Another financial save is already in progress. Retry later.';
  end if;
  perform set_config('lock_timeout', '100ms', true);
  if p_document_name is null or btrim(p_document_name) = '' then
    raise exception 'invalid_document_name' using errcode = '22023';
  end if;
  if p_expected_revision is null or p_expected_revision < 0 then
    raise exception 'invalid_expected_revision' using errcode = '22023';
  end if;
  if p_state is null
     or jsonb_typeof(p_state) is distinct from 'object'
     or (p_state ? 'checks')
     or jsonb_typeof(p_state->'credits') is distinct from 'array'
     or jsonb_typeof(p_state->'cash') is distinct from 'array'
     or jsonb_typeof(p_state->'expenses') is distinct from 'array'
     or jsonb_typeof(p_state->'cards') is distinct from 'array'
     or jsonb_typeof(p_state->'bank') is distinct from 'object'
     or jsonb_typeof(p_state#>'{bank,adjustments}') is distinct from 'array' then
    raise exception 'invalid_kupa_state'
      using errcode = '22023',
            hint = 'Post-cutover state must contain credits/cash/expenses/cards arrays and bank object, without checks.';
  end if;
  if exists (
    select 1 from jsonb_array_elements(p_state#>'{bank,adjustments}') a
    where a->>'type' = 'check_deposit'
  ) then
    raise exception 'legacy_check_deposit_forbidden'
      using errcode = '22023', hint = 'Check deposits are derived from shared_checks_documents after cutover.';
  end if;

  perform set_config('app.kupa_rpc_write', '1', true);

  select d.revision, d.state, d.updated_at
    into v_current_revision, v_old_state, v_old_updated_at
  from public.kupa_documents d
  where d.owner_id = v_owner and d.document_name = p_document_name
  for update;

  v_server_state := p_state;
  v_bank := p_state->'bank';
  v_old_bank := coalesce(v_old_state->'bank','{}'::jsonb);
  v_new_token := nullif(v_bank->>'snapshotToken','');
  v_old_token := nullif(v_old_bank->>'snapshotToken','');

  if v_new_token is distinct from v_old_token and v_new_token is not null then
    if jsonb_typeof(v_bank->'snapshotSeq') is distinct from 'number'
       or (v_bank->>'source' = 'manual' and jsonb_typeof(v_bank->'currentBalance') is distinct from 'number') then
      raise exception 'invalid_bank_snapshot' using errcode = '22023';
    end if;

    -- snapshotSeq הוא watermark שהלקוח באמת ראה אחרי sync של מאגר הצ'קים.
    -- אסור לשרת להקצות כאן sequence חדש: אירוע צ'ק מקביל שלא נצפה חייב להישאר אחרי ה-baseline.
    v_requested_snapshot_num := (v_bank->>'snapshotSeq')::numeric;
    if v_requested_snapshot_num < 0
       or v_requested_snapshot_num <> trunc(v_requested_snapshot_num)
       or v_requested_snapshot_num > 9223372036854775807::numeric then
      raise exception 'invalid_bank_snapshot_sequence' using errcode = '22023';
    end if;
    v_requested_snapshot_seq := v_requested_snapshot_num::bigint;

    if jsonb_typeof(v_old_bank->'snapshotSeq') = 'number' then
      begin
        v_old_snapshot_seq := greatest(0, (v_old_bank->>'snapshotSeq')::bigint);
      exception when others then
        raise exception 'invalid_existing_bank_snapshot_sequence' using errcode = '22023';
      end;
    end if;

    select coalesce(max((e.value->>'seq')::bigint), 0)
      into v_shared_max_seq
    from public.shared_checks_documents s
    left join lateral jsonb_array_elements(
      case when jsonb_typeof(s.state->'bankEvents')='array' then s.state->'bankEvents' else '[]'::jsonb end
    ) e(value) on true
    where s.owner_id = v_owner and s.document_name = 'main';
    v_shared_max_seq := coalesce(v_shared_max_seq, 0);

    if v_requested_snapshot_seq < v_old_snapshot_seq then
      raise exception 'stale_bank_snapshot_watermark'
        using errcode = '40001', hint = 'Refresh shared checks before saving a new bank snapshot.';
    end if;
    if v_requested_snapshot_seq > greatest(v_old_snapshot_seq, v_shared_max_seq) then
      raise exception 'bank_snapshot_watermark_ahead_of_server'
        using errcode = '22023', hint = 'The client watermark was not observed in shared check events.';
    end if;

    v_now := clock_timestamp();
    v_bank := v_bank || jsonb_build_object('snapshotSeq', v_requested_snapshot_seq);
    if v_bank->>'source' = 'manual' then
      v_bank := v_bank || jsonb_build_object('updatedAt', v_now);
    end if;
  elsif v_old_state is not null then
    -- Lightweight bank snapshot metadata is server-authoritative; ordinary Kupa saves cannot roll it back.
    v_bank := v_bank || jsonb_build_object(
      'snapshotToken', coalesce(v_old_bank->'snapshotToken','null'::jsonb),
      'snapshotSeq', coalesce(v_old_bank->'snapshotSeq','null'::jsonb),
      'updatedAt', case when v_bank->>'source' = 'manual' then coalesce(v_old_bank->'updatedAt','null'::jsonb) else 'null'::jsonb end
    );
  else
    v_bank := v_bank || jsonb_build_object('snapshotSeq', null);
  end if;

  -- Financial feeds and credit-company sync are stored in finance_sync_documents / bank_transactions,
  -- never in the Kupa document or its snapshot backups. Keep only the tiny Kupa-owned bank baseline metadata.
  v_bank := jsonb_build_object(
    'currentBalance', case when v_bank->>'source' = 'manual' then coalesce(v_bank->'currentBalance','null'::jsonb) else 'null'::jsonb end,
    'updatedAt', case when v_bank->>'source' = 'manual' then coalesce(v_bank->'updatedAt','null'::jsonb) else 'null'::jsonb end,
    'asOfDate', case when v_bank->>'source' = 'manual' then coalesce(v_bank->'asOfDate','null'::jsonb) else 'null'::jsonb end,
    'adjustments', coalesce(v_bank->'adjustments','[]'::jsonb),
    'source', case when v_bank->>'source' = 'manual' then 'manual'::text else null end,
    'sourceAccount', null,
    'snapshotToken', coalesce(v_bank->'snapshotToken','null'::jsonb),
    'snapshotSeq', coalesce(v_bank->'snapshotSeq','null'::jsonb)
  );
  v_server_state := (v_server_state - 'bank' - 'creditSync') || jsonb_build_object('bank', v_bank);

  if v_current_revision is null then
    if coalesce(p_expected_revision,0) <> 0 then
      raise exception 'revision_conflict' using errcode = '40001';
    end if;
    insert into public.kupa_documents(owner_id, document_name, revision, state, updated_at)
    values (v_owner, p_document_name, 1, v_server_state, now())
    returning kupa_documents.revision, kupa_documents.updated_at, kupa_documents.state
      into v_new_revision, v_new_updated_at, v_server_state;
    insert into public.kupa_periodic_backups(owner_id, document_name, revision, state, saved_at)
    values (v_owner, p_document_name, v_new_revision, v_server_state, v_new_updated_at)
    on conflict do nothing;
    return query select v_new_revision, v_new_updated_at, v_server_state;
    return;
  end if;

  -- ACK שאבד: קודם בודקים אם התוכן שכבר בשרת הוא בדיוק התוכן המבוקש.
  if v_old_state = v_server_state then
    return query select v_current_revision, v_old_updated_at, v_old_state;
    return;
  end if;
  if v_current_revision <> p_expected_revision then
    raise exception 'revision_conflict' using errcode = '40001';
  end if;

  insert into public.kupa_document_backups(owner_id, document_name, revision, state, saved_at)
  values (v_owner, p_document_name, v_current_revision, v_old_state, v_old_updated_at)
  on conflict do nothing;

  update public.kupa_documents d
  set revision = d.revision + 1, state = v_server_state, updated_at = now()
  where d.owner_id = v_owner and d.document_name = p_document_name
  returning d.revision, d.updated_at, d.state
    into v_new_revision, v_new_updated_at, v_server_state;

  if not exists (
    select 1 from public.kupa_periodic_backups p
    where p.owner_id = v_owner and p.document_name = p_document_name
      and p.saved_at > now() - interval '12 hours'
  ) then
    insert into public.kupa_periodic_backups(owner_id, document_name, revision, state, saved_at)
    values (v_owner, p_document_name, v_new_revision, v_server_state, v_new_updated_at)
    on conflict do nothing;
  end if;

  delete from public.kupa_periodic_backups p
  where p.owner_id = v_owner and p.document_name = p_document_name
    and p.saved_at < now() - interval '365 days';
  delete from public.kupa_document_backups b
  where b.owner_id = v_owner and b.document_name = p_document_name
    and b.id in (
      select x.id from public.kupa_document_backups x
      where x.owner_id = v_owner and x.document_name = p_document_name
      order by x.saved_at desc, x.id desc offset 200
    );

  return query select v_new_revision, v_new_updated_at, v_server_state;
end;
$$;
revoke all on function public.save_kupa_document(text, bigint, jsonb) from public, anon;
grant execute on function public.save_kupa_document(text, bigint, jsonb) to authenticated;

insert into public.kupa_periodic_backups(owner_id, document_name, revision, state, saved_at)
select d.owner_id, d.document_name, d.revision, d.state, d.updated_at
from public.kupa_documents d
where not exists (
  select 1 from public.kupa_periodic_backups p
  where p.owner_id=d.owner_id and p.document_name=d.document_name
)
on conflict (owner_id, document_name, revision) do nothing;

commit;

-- Financial sync data is intentionally isolated from kupa_documents backups.
create table if not exists public.finance_sync_documents (
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null default 'main',
  revision bigint not null default 1 check (revision > 0),
  state jsonb not null default '{"bank":null,"creditSync":null}'::jsonb check (jsonb_typeof(state)='object'),
  updated_at timestamptz not null default now(),
  primary key (owner_id, document_name)
);
alter table public.finance_sync_documents enable row level security;
revoke all on table public.finance_sync_documents from anon, authenticated;
grant select on table public.finance_sync_documents to authenticated;
drop policy if exists "finance_sync_select_own" on public.finance_sync_documents;
create policy "finance_sync_select_own" on public.finance_sync_documents for select to authenticated using ((select auth.uid()) = owner_id);

create or replace function public.save_finance_sync_document(p_document_name text, p_expected_revision bigint, p_state jsonb)
returns table(revision bigint, updated_at timestamptz, state jsonb)
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  v_owner uuid := auth.uid();
  v_current bigint;
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  -- Shared per-user financial writer gate: fail fast instead of filling the PostgREST pool.
  if not pg_try_advisory_xact_lock(
    hashtextextended('netunim_financial_write:' || v_owner::text, 0)
  ) then
    raise exception 'save_busy'
      using errcode = 'PT429',
            hint = 'Another financial save is already in progress. Retry later.';
  end if;
  perform set_config('lock_timeout', '100ms', true);
  if p_document_name is null or btrim(p_document_name)='' then raise exception 'invalid_document_name' using errcode='22023'; end if;
  if p_expected_revision is null or p_expected_revision < 0 then raise exception 'invalid_expected_revision' using errcode='22023'; end if;
  if p_state is null or jsonb_typeof(p_state) is distinct from 'object' then raise exception 'invalid_finance_sync_state' using errcode='22023'; end if;

  select d.revision into v_current from public.finance_sync_documents d
  where d.owner_id=v_owner and d.document_name=p_document_name for update;
  if v_current is null then
    if p_expected_revision<>0 then raise exception 'revision_conflict' using errcode='40001'; end if;
    insert into public.finance_sync_documents(owner_id,document_name,revision,state,updated_at)
    values(v_owner,p_document_name,1,p_state,now())
    returning finance_sync_documents.revision,finance_sync_documents.updated_at,finance_sync_documents.state
    into revision,updated_at,state;
    return next; return;
  end if;
  if v_current<>p_expected_revision then raise exception 'revision_conflict' using errcode='40001'; end if;
  update public.finance_sync_documents d set revision=d.revision+1,state=p_state,updated_at=now()
  where d.owner_id=v_owner and d.document_name=p_document_name
  returning d.revision,d.updated_at,d.state into revision,updated_at,state;
  return next;
end $$;
revoke all on function public.save_finance_sync_document(text,bigint,jsonb) from public, anon;
grant execute on function public.save_finance_sync_document(text,bigint,jsonb) to authenticated;



-- Atomically publish a verified bank snapshot and advance the Kupa cheque watermark.
-- The heavy bank payload stays only in finance_sync_documents; kupa_documents retains only
-- the tiny snapshot metadata needed to apply cheque events exactly once.
-- Cross-device lease for bank / credit synchronization.
-- One authenticated user can hold one lease per synchronization kind.
create table if not exists public.finance_sync_leases (
  owner_id uuid not null references auth.users(id) on delete cascade,
  lease_name text not null check (lease_name in ('bank','credit')),
  lease_token text not null,
  leased_until timestamptz not null,
  updated_at timestamptz not null default now(),
  primary key(owner_id,lease_name)
);

alter table public.finance_sync_leases enable row level security;
revoke all on table public.finance_sync_leases from anon, authenticated;
grant select, insert, update on table public.finance_sync_leases to authenticated;

drop policy if exists "finance_sync_leases_select_own" on public.finance_sync_leases;
create policy "finance_sync_leases_select_own" on public.finance_sync_leases
for select to authenticated
using ((select auth.uid())=owner_id);

drop policy if exists "finance_sync_leases_insert_own" on public.finance_sync_leases;
create policy "finance_sync_leases_insert_own" on public.finance_sync_leases
for insert to authenticated
with check ((select auth.uid())=owner_id);

drop policy if exists "finance_sync_leases_update_own" on public.finance_sync_leases;
create policy "finance_sync_leases_update_own" on public.finance_sync_leases
for update to authenticated
using ((select auth.uid())=owner_id)
with check ((select auth.uid())=owner_id);

create or replace function public.claim_finance_sync_lease(
  p_lease_name text,
  p_lease_token text,
  p_ttl_seconds integer default 1200
)
returns table(acquired boolean, leased_until timestamptz)
language plpgsql
security invoker
set search_path=pg_catalog,public
as $$
declare
  v_owner uuid:=auth.uid();
  v_name text:=btrim(coalesce(p_lease_name,''));
  v_token text:=btrim(coalesce(p_lease_token,''));
  v_now timestamptz:=clock_timestamp();
  v_until timestamptz;
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  if v_name not in ('bank','credit') then raise exception 'invalid_finance_sync_lease_name' using errcode='22023'; end if;
  if v_token='' or length(v_token)>200 then raise exception 'invalid_finance_sync_lease_token' using errcode='22023'; end if;
  if p_ttl_seconds is null or p_ttl_seconds<60 or p_ttl_seconds>1800 then raise exception 'invalid_finance_sync_lease_ttl' using errcode='22023'; end if;
  v_until:=v_now+make_interval(secs=>p_ttl_seconds);

  insert into public.finance_sync_leases as lease(owner_id,lease_name,lease_token,leased_until,updated_at)
  values(v_owner,v_name,v_token,v_until,v_now)
  on conflict(owner_id,lease_name) do update
  set lease_token=excluded.lease_token,
      leased_until=excluded.leased_until,
      updated_at=excluded.updated_at
  where lease.leased_until<=v_now or lease.lease_token=excluded.lease_token
  returning true,lease.leased_until into acquired,leased_until;

  if found then return next; return; end if;

  select false,lease.leased_until into acquired,leased_until
  from public.finance_sync_leases lease
  where lease.owner_id=v_owner and lease.lease_name=v_name;
  if not found then acquired:=false;leased_until:=null;end if;
  return next;
end $$;

revoke all on function public.claim_finance_sync_lease(text,text,integer) from public,anon;
grant execute on function public.claim_finance_sync_lease(text,text,integer) to authenticated;

create or replace function public.release_finance_sync_lease(
  p_lease_name text,
  p_lease_token text
)
returns boolean
language plpgsql
security invoker
set search_path=pg_catalog,public
as $$
declare
  v_owner uuid:=auth.uid();
  v_name text:=btrim(coalesce(p_lease_name,''));
  v_token text:=btrim(coalesce(p_lease_token,''));
  v_now timestamptz:=clock_timestamp();
  v_released boolean:=false;
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  if v_name not in ('bank','credit') then raise exception 'invalid_finance_sync_lease_name' using errcode='22023'; end if;
  if v_token='' or length(v_token)>200 then raise exception 'invalid_finance_sync_lease_token' using errcode='22023'; end if;

  update public.finance_sync_leases lease
  set leased_until=v_now,updated_at=v_now
  where lease.owner_id=v_owner and lease.lease_name=v_name and lease.lease_token=v_token
  returning true into v_released;
  return coalesce(v_released,false);
end $$;

revoke all on function public.release_finance_sync_lease(text,text) from public,anon;
grant execute on function public.release_finance_sync_lease(text,text) to authenticated;

create or replace function public.save_bank_sync_snapshot(
  p_document_name text,
  p_bank_state jsonb,
  p_snapshot_token text,
  p_snapshot_seq bigint
)
returns table(finance_revision bigint, kupa_revision bigint, updated_at timestamptz)
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_owner uuid := auth.uid();
  v_kupa_state jsonb;
  v_kupa_bank jsonb;
  v_old_snapshot_seq bigint := 0;
  v_shared_max_seq bigint := 0;
  v_finance_state jsonb;
  v_finance_revision bigint;
  v_kupa_revision bigint;
  v_now timestamptz := clock_timestamp();
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  -- Shared per-user financial writer gate: fail fast instead of filling the PostgREST pool.
  if not pg_try_advisory_xact_lock(
    hashtextextended('netunim_financial_write:' || v_owner::text, 0)
  ) then
    raise exception 'save_busy'
      using errcode = 'PT429',
            hint = 'Another financial save is already in progress. Retry later.';
  end if;
  perform set_config('lock_timeout', '100ms', true);
  if p_document_name is null or btrim(p_document_name)='' then raise exception 'invalid_document_name' using errcode='22023'; end if;
  if p_bank_state is null or jsonb_typeof(p_bank_state) is distinct from 'object' then raise exception 'invalid_bank_sync_state' using errcode='22023'; end if;
  if coalesce(btrim(p_snapshot_token),'')='' then raise exception 'invalid_bank_snapshot_token' using errcode='22023'; end if;
  if p_snapshot_seq is null or p_snapshot_seq<0 then raise exception 'invalid_bank_snapshot_sequence' using errcode='22023'; end if;

  -- Lock Kupa first. No other finance RPC locks both rows, so this gives one deterministic order.
  select d.state,d.revision into v_kupa_state,v_kupa_revision
  from public.kupa_documents d
  where d.owner_id=v_owner and d.document_name=p_document_name
  for update;
  if v_kupa_state is null then raise exception 'kupa_document_not_found' using errcode='P0002'; end if;

  v_kupa_bank:=coalesce(v_kupa_state->'bank','{}'::jsonb);
  if jsonb_typeof(v_kupa_bank->'snapshotSeq')='number' then
    begin v_old_snapshot_seq:=greatest(0,(v_kupa_bank->>'snapshotSeq')::bigint);
    exception when others then raise exception 'invalid_existing_bank_snapshot_sequence' using errcode='22023'; end;
  end if;

  select coalesce(max((e.value->>'seq')::bigint),0) into v_shared_max_seq
  from public.shared_checks_documents s
  left join lateral jsonb_array_elements(case when jsonb_typeof(s.state->'bankEvents')='array' then s.state->'bankEvents' else '[]'::jsonb end) e(value) on true
  where s.owner_id=v_owner and s.document_name='main';
  v_shared_max_seq:=coalesce(v_shared_max_seq,0);

  if p_snapshot_seq<v_old_snapshot_seq then
    raise exception 'stale_bank_snapshot_watermark' using errcode='40001',hint='Refresh shared checks before saving the bank snapshot.';
  end if;
  if p_snapshot_seq>greatest(v_old_snapshot_seq,v_shared_max_seq) then
    raise exception 'bank_snapshot_watermark_ahead_of_server' using errcode='22023',hint='The requested watermark was not observed in shared check events.';
  end if;

  select f.state,f.revision into v_finance_state,v_finance_revision
  from public.finance_sync_documents f
  where f.owner_id=v_owner and f.document_name=p_document_name
  for update;

  if v_finance_revision is null then
    insert into public.finance_sync_documents(owner_id,document_name,revision,state,updated_at)
    values(v_owner,p_document_name,1,jsonb_build_object('bank',p_bank_state,'creditSync',null),v_now)
    returning revision into v_finance_revision;
  else
    v_finance_state:=coalesce(v_finance_state,'{}'::jsonb);
    update public.finance_sync_documents f
    set revision=f.revision+1,
        state=jsonb_set(v_finance_state,'{bank}',p_bank_state,true),
        updated_at=v_now
    where f.owner_id=v_owner and f.document_name=p_document_name
    returning f.revision into v_finance_revision;
  end if;

  -- Direct Kupa writes are guarded; mark this transaction as an approved RPC write.
  perform set_config('app.kupa_rpc_write','1',true);
  v_kupa_bank:=jsonb_build_object(
    'currentBalance',null,
    'updatedAt',null,
    'asOfDate',null,
    'adjustments',coalesce(v_kupa_bank->'adjustments','[]'::jsonb),
    'source',null,
    'sourceAccount',null,
    'snapshotToken',p_snapshot_token,
    'snapshotSeq',p_snapshot_seq
  );
  v_kupa_state:=(v_kupa_state-'bank'-'creditSync')||jsonb_build_object('bank',v_kupa_bank);
  update public.kupa_documents d
  set revision=d.revision+1,state=v_kupa_state,updated_at=v_now
  where d.owner_id=v_owner and d.document_name=p_document_name
  returning d.revision into v_kupa_revision;

  finance_revision:=v_finance_revision;kupa_revision:=v_kupa_revision;updated_at:=v_now;return next;
end $$;
revoke all on function public.save_bank_sync_snapshot(text,jsonb,text,bigint) from public,anon;
grant execute on function public.save_bank_sync_snapshot(text,jsonb,text,bigint) to authenticated;

create table if not exists public.bank_transactions (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  account_key text not null,
  account_role text not null check (account_role in ('business','home')),
  merge_key text not null,
  transaction_date timestamptz,
  processed_date timestamptz,
  amount numeric not null,
  currency text not null default 'ILS',
  description text not null default '',
  memo text not null default '',
  party_name text not null default '',
  party_headline text not null default '',
  message_headline text not null default '',
  message_detail text not null default '',
  status text not null default 'completed' check(status in ('pending','completed')),
  balance_after numeric,
  bank_reference text not null default '',
  bank_serial text not null default '',
  activity_type_code integer,
  cheque boolean not null default false,
  check_details jsonb,
  first_seen_at timestamptz not null default now(),
  last_changed_at timestamptz not null default now(),
  unique(owner_id,account_key,merge_key)
);
create index if not exists bank_transactions_owner_account_date_idx on public.bank_transactions(owner_id,account_key,transaction_date desc);
create index if not exists bank_transactions_owner_reference_idx on public.bank_transactions(owner_id,account_key,bank_reference) where bank_reference<>'';
alter table public.bank_transactions enable row level security;
revoke all on table public.bank_transactions from anon, authenticated;
grant select on table public.bank_transactions to authenticated;
drop policy if exists "bank_transactions_select_own" on public.bank_transactions;
create policy "bank_transactions_select_own" on public.bank_transactions for select to authenticated using ((select auth.uid())=owner_id);

create or replace function public.merge_bank_transactions(p_account_key text,p_account_role text,p_transactions jsonb)
returns table(inserted_count integer, updated_count integer, total_count integer)
language plpgsql
set search_path=pg_catalog,public
as $$
declare
  v_owner uuid:=auth.uid();
  r jsonb;
  v_id bigint;
  v_inserted int:=0;
  v_updated int:=0;
  v_candidates int;
  v_candidate bigint;
  v_date timestamptz;
  v_processed timestamptz;
  v_amount numeric;
  v_serial text;
  v_reference text;
  v_description text;
  v_memo text;
  v_party_name text;
  v_party_norm text;
  v_detail_digits text;
  v_status text;
  v_balance numeric;
  v_activity integer;
  v_pending_id bigint;
  v_pending_in_source boolean;
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  -- Shared per-user financial writer gate: fail fast instead of filling the PostgREST pool.
  if not pg_try_advisory_xact_lock(
    hashtextextended('netunim_financial_write:' || v_owner::text, 0)
  ) then
    raise exception 'save_busy'
      using errcode = 'PT429',
            hint = 'Another financial save is already in progress. Retry later.';
  end if;
  perform set_config('lock_timeout', '100ms', true);
  if coalesce(btrim(p_account_key),'')='' or p_account_role not in ('business','home') or jsonb_typeof(p_transactions) is distinct from 'array' then raise exception 'invalid_bank_merge_input' using errcode='22023'; end if;

  -- A duplicate merge key means the client could not distinguish two source rows. Fail atomically
  -- instead of silently collapsing financial movements. Fallback rows receive occurrence suffixes.
  if exists (
    select 1
    from jsonb_array_elements(p_transactions) x(value)
    group by x.value->>'mergeKey'
    having coalesce(x.value->>'mergeKey','')='' or count(*)>1
  ) then
    raise exception 'bank_archive_ambiguous_source_identity'
      using errcode='22023', hint='The bank returned rows that cannot be given unique stable identities. No archive rows were changed.';
  end if;

  for r in select value from jsonb_array_elements(p_transactions) loop
    if nullif(r->>'amount','') is null then raise exception 'invalid_bank_transaction_amount' using errcode='22023'; end if;
    v_date:=nullif(r->>'date','')::timestamptz;
    v_processed:=nullif(r->>'processedDate','')::timestamptz;
    v_amount:=(r->>'amount')::numeric;
    v_serial:=coalesce(r->>'bankSerial','');
    v_reference:=coalesce(r->>'bankReference','');
    v_description:=coalesce(r->>'description','');
    v_memo:=coalesce(r->>'memo','');
    v_party_name:=coalesce(r->>'partyName','');
    v_party_norm:=lower(regexp_replace(btrim(v_party_name),'[[:space:]]+',' ','g'));
    v_detail_digits:=regexp_replace(coalesce(nullif(r->>'messageDetail',''),r->>'memo',''),'[^0-9]','','g');
    v_status:=case when r->>'status'='pending' then 'pending' else 'completed' end;
    v_balance:=nullif(r->>'balanceAfter','')::numeric;
    v_activity:=nullif(r->>'activityTypeCode','')::integer;
    v_id:=null;
    v_pending_id:=null;
    v_pending_in_source:=false;

    -- Hapoalim reference numbers are not globally unique. The bank serial is day-scoped and is
    -- the strongest stable identifier available for completed rows, so date is part of every match.
    if v_date is not null and v_serial not in ('','0') then
      select count(*),min(b.id) into v_candidates,v_candidate
      from public.bank_transactions b
      where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role
        and b.transaction_date::date=v_date::date and b.bank_serial=v_serial and b.amount=v_amount;
      if v_candidates>1 then
        raise exception 'bank_archive_existing_identity_collision'
          using errcode='40001', hint='More than one archived row matches the same bank date/serial/amount identity. No merge was committed.';
      elsif v_candidates=1 then v_id:=v_candidate; end if;
    end if;
    if v_id is null and v_date is not null and v_reference<>'' then
      select count(*),min(b.id) into v_candidates,v_candidate
      from public.bank_transactions b
      where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role
        and b.transaction_date::date=v_date::date and b.bank_reference=v_reference and b.amount=v_amount
        and b.description=v_description and b.memo=v_memo;
      if v_candidates>1 then
        raise exception 'bank_archive_existing_identity_collision'
          using errcode='40001', hint='More than one archived row matches the same bank date/reference/amount/content identity. No merge was committed.';
      elsif v_candidates=1 then v_id:=v_candidate; end if;
    end if;

    if v_id is null and coalesce(r->>'mergeKey','')<>'' then
      select count(*),min(b.id) into v_candidates,v_candidate
      from public.bank_transactions b
      where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role and b.merge_key=r->>'mergeKey';
      if v_candidates>1 then
        raise exception 'bank_archive_existing_merge_key_collision'
          using errcode='40001', hint='More than one archived row has the same merge key. No merge was committed.';
      elsif v_candidates=1 then v_id:=v_candidate; end if;
    end if;

    -- A Hapoalim pending row is a temporary state of the same movement. While pending, the bank
    -- commonly returns serial=0 and can later change both the activity label and beneficiary text.
    -- Reference/balance matches remain preferred. Instant credits (including Zahav-style credits)
    -- get one additional fail-closed identity: same positive amount, same/adjacent bank day,
    -- compatible activity direction, a long beneficiary-name phrase contained in the other state,
    -- and the same >=8-digit account suffix from messageDetail (memo is only a fallback source).
    -- The candidate must still be UNIQUE; ambiguity deliberately leaves rows separate.
    if v_status='completed' and v_date is not null then
      select count(*),min(b.id) into v_candidates,v_candidate
      from public.bank_transactions b
      cross join lateral (
        select
          lower(regexp_replace(btrim(coalesce(b.party_name,'')),'[[:space:]]+',' ','g')) as pending_party_norm,
          regexp_replace(coalesce(nullif(b.message_detail,''),b.memo,''),'[^0-9]','','g') as pending_detail_digits
      ) hints
      where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role
        and b.status='pending' and b.amount=v_amount
        and b.transaction_date between (v_date-interval '3 days') and (v_date+interval '3 days')
        and (
          (v_reference not in ('','0') and b.bank_reference=v_reference
            and (v_activity is null or b.activity_type_code is null or b.activity_type_code=v_activity))
          or
          (v_balance is not null and v_activity is not null
            and b.balance_after is not distinct from v_balance
            and b.activity_type_code=v_activity
            and b.description=v_description)
          or
          (
            v_amount>0
            and (v_description ~ 'מיידי|זה.?ב' or coalesce(b.description,'') ~ 'מיידי|זה.?ב')
            and b.transaction_date between (v_date-interval '1 day') and (v_date+interval '1 day')
            and (v_activity is null or b.activity_type_code is null or b.activity_type_code=v_activity)
            and length(v_party_norm)>=8 and length(hints.pending_party_norm)>=8
            and array_length(regexp_split_to_array(v_party_norm,'[[:space:]]+'),1)>=2
            and array_length(regexp_split_to_array(hints.pending_party_norm,'[[:space:]]+'),1)>=2
            and (
              position(' '||v_party_norm||' ' in ' '||hints.pending_party_norm||' ')>0
              or position(' '||hints.pending_party_norm||' ' in ' '||v_party_norm||' ')>0
            )
            and length(v_detail_digits)>=8 and length(hints.pending_detail_digits)>=8
            and right(v_detail_digits,least(length(v_detail_digits),length(hints.pending_detail_digits)))
              =right(hints.pending_detail_digits,least(length(v_detail_digits),length(hints.pending_detail_digits)))
          )
        );
      if v_candidates=1 then
        v_pending_id:=v_candidate;

        -- Never delete a pending row that the current bank payload still exposes. The exact merge
        -- key is preferred, but connector upgrades are allowed to change derived client identities,
        -- so a conservative stable-facts fallback also counts as "still present".
        select exists(
          select 1
          from public.bank_transactions pb
          cross join lateral jsonb_array_elements(p_transactions) x(value)
          where pb.id=v_pending_id and x.value->>'status'='pending'
            and (
              x.value->>'mergeKey'=pb.merge_key
              or (
                nullif(x.value->>'amount','') is not null
                and (x.value->>'amount')::numeric=pb.amount
                and (
                  (coalesce(x.value->>'bankReference','') not in ('','0')
                    and x.value->>'bankReference'=pb.bank_reference)
                  or
                  (nullif(x.value->>'balanceAfter','') is not null
                    and nullif(x.value->>'activityTypeCode','') is not null
                    and (x.value->>'balanceAfter')::numeric is not distinct from pb.balance_after
                    and (x.value->>'activityTypeCode')::integer is not distinct from pb.activity_type_code)
                  or
                  (coalesce(x.value->>'description','')=pb.description
                    and nullif(x.value->>'date','') is not null
                    and (x.value->>'date')::timestamptz between (pb.transaction_date-interval '1 day') and (pb.transaction_date+interval '1 day'))
                )
              )
            )
        ) into v_pending_in_source;

        if not v_pending_in_source and v_id is null then
          v_id:=v_pending_id;
        end if;
      end if;
    end if;

    if v_id is null then
      insert into public.bank_transactions(owner_id,account_key,account_role,merge_key,transaction_date,processed_date,amount,currency,description,memo,party_name,party_headline,message_headline,message_detail,status,balance_after,bank_reference,bank_serial,activity_type_code,cheque,check_details)
      values(v_owner,p_account_key,p_account_role,r->>'mergeKey',v_date,v_processed,v_amount,coalesce(nullif(r->>'currency',''),'ILS'),v_description,coalesce(r->>'memo',''),coalesce(r->>'partyName',''),coalesce(r->>'partyHeadline',''),coalesce(r->>'messageHeadline',''),coalesce(r->>'messageDetail',''),v_status,v_balance,v_reference,v_serial,v_activity,coalesce((r->>'cheque')::boolean,false),r->'checkDetails');
      v_inserted:=v_inserted+1;
    else
      update public.bank_transactions b set
        merge_key=coalesce(nullif(r->>'mergeKey',''),b.merge_key),
        transaction_date=coalesce(v_date,b.transaction_date),
        processed_date=coalesce(v_processed,b.processed_date),
        currency=coalesce(nullif(r->>'currency',''),b.currency),
        description=coalesce(nullif(r->>'description',''),b.description),
        memo=coalesce(r->>'memo',b.memo),
        party_name=coalesce(r->>'partyName',b.party_name),
        party_headline=coalesce(r->>'partyHeadline',b.party_headline),
        message_headline=coalesce(r->>'messageHeadline',b.message_headline),
        message_detail=coalesce(r->>'messageDetail',b.message_detail),
        status=case when v_status='pending' and b.status='completed' then b.status else v_status end,
        balance_after=coalesce(v_balance,b.balance_after),
        bank_reference=coalesce(nullif(r->>'bankReference',''),b.bank_reference),
        bank_serial=coalesce(nullif(r->>'bankSerial',''),b.bank_serial),
        activity_type_code=coalesce(v_activity,b.activity_type_code),
        cheque=coalesce((r->>'cheque')::boolean,b.cheque),
        check_details=coalesce(r->'checkDetails',b.check_details),
        last_changed_at=now()
      where b.id=v_id and (
        b.merge_key is distinct from coalesce(nullif(r->>'mergeKey',''),b.merge_key)
        or b.transaction_date is distinct from coalesce(v_date,b.transaction_date)
        or b.processed_date is distinct from coalesce(v_processed,b.processed_date)
        or b.currency is distinct from coalesce(nullif(r->>'currency',''),b.currency)
        or b.description is distinct from coalesce(nullif(r->>'description',''),b.description)
        or b.memo is distinct from coalesce(r->>'memo',b.memo)
        or b.party_name is distinct from coalesce(r->>'partyName',b.party_name)
        or b.party_headline is distinct from coalesce(r->>'partyHeadline',b.party_headline)
        or b.message_headline is distinct from coalesce(r->>'messageHeadline',b.message_headline)
        or b.message_detail is distinct from coalesce(r->>'messageDetail',b.message_detail)
        or b.status is distinct from (case when v_status='pending' and b.status='completed' then b.status else v_status end)
        or b.balance_after is distinct from coalesce(v_balance,b.balance_after)
        or b.bank_reference is distinct from coalesce(nullif(r->>'bankReference',''),b.bank_reference)
        or b.bank_serial is distinct from coalesce(nullif(r->>'bankSerial',''),b.bank_serial)
        or b.activity_type_code is distinct from coalesce(v_activity,b.activity_type_code)
        or b.cheque is distinct from coalesce((r->>'cheque')::boolean,b.cheque)
        or b.check_details is distinct from coalesce(r->'checkDetails',b.check_details)
      );
      if found then v_updated:=v_updated+1; end if;
    end if;
  end loop;
  -- Self-verify the statement before returning. If any source row failed to become the exact
  -- archived row for its merge key, raise and let PostgreSQL roll the whole RPC statement back.
  if exists (
    select 1
    from jsonb_array_elements(p_transactions) x(value)
    where not exists (
      select 1 from public.bank_transactions b
      where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role
        and b.merge_key=x.value->>'mergeKey'
        and (nullif(x.value->>'date','') is null or b.transaction_date is not distinct from (x.value->>'date')::timestamptz)
        and (nullif(x.value->>'processedDate','') is null or b.processed_date is not distinct from (x.value->>'processedDate')::timestamptz)
        and b.amount=(x.value->>'amount')::numeric
        and b.description=coalesce(x.value->>'description','')
        and b.memo=coalesce(x.value->>'memo','')
        and (coalesce(x.value->>'bankReference','')='' or b.bank_reference=x.value->>'bankReference')
        and (coalesce(x.value->>'bankSerial','')='' or b.bank_serial=x.value->>'bankSerial')
        and (case when x.value->>'status'='pending' then b.status in ('pending','completed') else b.status='completed' end)
    )
  ) then
    raise exception 'bank_archive_merge_verification_failed'
      using errcode='40001', hint='The transaction merge did not reproduce every bank row exactly. The entire RPC was rolled back.';
  end if;

  select count(*)::int into total_count from public.bank_transactions b where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role;
  inserted_count:=v_inserted; updated_count:=v_updated; return next;
end $$;
revoke all on function public.merge_bank_transactions(text,text,jsonb) from public,anon;
grant execute on function public.merge_bank_transactions(text,text,jsonb) to authenticated;

-- Write access is still owner-scoped by RLS; RPCs do not use service_role.
grant insert, update on table public.finance_sync_documents to authenticated;
drop policy if exists "finance_sync_insert_own" on public.finance_sync_documents;
create policy "finance_sync_insert_own" on public.finance_sync_documents for insert to authenticated with check ((select auth.uid())=owner_id);
drop policy if exists "finance_sync_update_own" on public.finance_sync_documents;
create policy "finance_sync_update_own" on public.finance_sync_documents for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
grant insert, update on table public.bank_transactions to authenticated;
grant usage, select on sequence public.bank_transactions_id_seq to authenticated;
drop policy if exists "bank_transactions_insert_own" on public.bank_transactions;
create policy "bank_transactions_insert_own" on public.bank_transactions for insert to authenticated with check ((select auth.uid())=owner_id);
drop policy if exists "bank_transactions_update_own" on public.bank_transactions;
create policy "bank_transactions_update_own" on public.bank_transactions for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);

-- Bank complete-snapshot reconciliation v1 (authoritative clean-install/maintenance source)

alter table public.bank_transactions
  add column if not exists presence_state text not null default 'unknown',
  add column if not exists last_seen_at timestamptz,
  add column if not exists missing_since timestamptz,
  add column if not exists missing_acknowledged_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid='public.bank_transactions'::regclass
      and conname='bank_transactions_presence_state_check'
  ) then
    alter table public.bank_transactions
      add constraint bank_transactions_presence_state_check
      check (presence_state in ('unknown','present','missing'));
  end if;
end $$;

create index if not exists bank_transactions_owner_missing_idx
  on public.bank_transactions(owner_id,account_key,account_role,missing_since desc)
  where presence_state='missing' and missing_acknowledged_at is null;

create table if not exists public.bank_transaction_snapshots (
  owner_id uuid not null references auth.users(id) on delete cascade,
  account_key text not null,
  account_role text not null check (account_role in ('business','home')),
  snapshot_at timestamptz not null,
  coverage_from date not null,
  coverage_to date not null,
  transaction_count integer not null check (transaction_count >= 0),
  transactions jsonb not null check (jsonb_typeof(transactions)='array'),
  updated_at timestamptz not null default now(),
  primary key(owner_id,account_key,account_role),
  check (coverage_to >= coverage_from)
);

alter table public.bank_transaction_snapshots enable row level security;
revoke all on table public.bank_transaction_snapshots from anon,authenticated;
grant select,insert,update on table public.bank_transaction_snapshots to authenticated;
drop policy if exists "bank_transaction_snapshots_select_own" on public.bank_transaction_snapshots;
create policy "bank_transaction_snapshots_select_own"
  on public.bank_transaction_snapshots for select to authenticated
  using ((select auth.uid())=owner_id);
drop policy if exists "bank_transaction_snapshots_insert_own" on public.bank_transaction_snapshots;
create policy "bank_transaction_snapshots_insert_own"
  on public.bank_transaction_snapshots for insert to authenticated
  with check ((select auth.uid())=owner_id);
drop policy if exists "bank_transaction_snapshots_update_own" on public.bank_transaction_snapshots;
create policy "bank_transaction_snapshots_update_own"
  on public.bank_transaction_snapshots for update to authenticated
  using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);

create or replace function public.sync_bank_transactions_snapshot(
  p_account_key text,
  p_account_role text,
  p_transactions jsonb,
  p_snapshot_at timestamptz,
  p_coverage_from date,
  p_coverage_to date,
  p_complete boolean
)
returns table(
  inserted_count integer,
  updated_count integer,
  total_count integer,
  missing_count integer,
  active_missing_count integer,
  snapshot_stored boolean,
  baseline_created boolean
)
language plpgsql
security invoker
set search_path=pg_catalog,public
as $$
declare
  v_owner uuid:=auth.uid();
  v_inserted integer:=0;
  v_updated integer:=0;
  v_total integer:=0;
  v_previous_snapshot_at timestamptz;
  v_had_complete_snapshot boolean:=false;
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  if coalesce(btrim(p_account_key),'')='' or p_account_role not in ('business','home')
     or jsonb_typeof(p_transactions) is distinct from 'array'
     or p_snapshot_at is null then
    raise exception 'invalid_bank_snapshot_input' using errcode='22023';
  end if;
  if coalesce(p_complete,false) and (p_coverage_from is null or p_coverage_to is null or p_coverage_to<p_coverage_from) then
    raise exception 'invalid_bank_snapshot_coverage' using errcode='22023';
  end if;

  -- The public merge boundary owns the shared per-user advisory transaction lock both before and
  -- after core contention hardening. Transaction-scoped advisory locks remain held for this whole
  -- RPC, so merge + reconciliation + snapshot are atomic; any later exception rolls all of it back.
  select m.inserted_count,m.updated_count,m.total_count
    into v_inserted,v_updated,v_total
  from public.merge_bank_transactions(p_account_key,p_account_role,p_transactions) m;

  select s.snapshot_at into v_previous_snapshot_at
  from public.bank_transaction_snapshots s
  where s.owner_id=v_owner and s.account_key=p_account_key and s.account_role=p_account_role
  for update;
  v_had_complete_snapshot:=v_previous_snapshot_at is not null;

  -- A late client cannot mutate presence state after a newer proven-complete bank snapshot. This
  -- applies even to an incomplete read: a stale partial response must not resurrect a row that a
  -- newer complete snapshot already proved missing. Throwing rolls the merge back atomically too.
  if v_previous_snapshot_at is not null and p_snapshot_at<v_previous_snapshot_at then
    raise exception 'bank_snapshot_stale'
      using errcode='40001',hint='A newer complete bank snapshot is already stored. The stale snapshot was not applied.';
  end if;

  -- Rows actually returned by the bank are present. This is safe even for a partial read; absence
  -- is the only fact that is forbidden unless the connector proved the whole requested range.
  -- Reappearance also clears an old acknowledgement so a later disappearance becomes a new incident.
  update public.bank_transactions b set
    presence_state='present',
    last_seen_at=p_snapshot_at,
    missing_since=null,
    missing_acknowledged_at=null
  where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role
    and exists (
      select 1 from jsonb_array_elements(p_transactions) x(value)
      where x.value->>'mergeKey'=b.merge_key
    )
    and (
      b.presence_state is distinct from 'present'
      or b.last_seen_at is distinct from p_snapshot_at
      or b.missing_since is not null
      or b.missing_acknowledged_at is not null
    );

  if coalesce(p_complete,false) then
    -- Pre-upgrade archive rows start UNKNOWN. The first complete snapshot is a baseline only: it
    -- cannot manufacture warnings for old history whose prior presence was never proven. Starting
    -- with the second complete snapshot, only previously PRESENT rows inside the connector-declared
    -- coverage window can transition to MISSING.
    if v_had_complete_snapshot then
      update public.bank_transactions b set
        presence_state='missing',
        missing_since=coalesce(b.missing_since,p_snapshot_at)
      where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role
        and b.presence_state='present'
        and coalesce(b.transaction_date,b.processed_date)::date between p_coverage_from and p_coverage_to
        and (b.last_seen_at is null or b.last_seen_at<p_snapshot_at)
        and not exists (
          select 1 from jsonb_array_elements(p_transactions) x(value)
          where x.value->>'mergeKey'=b.merge_key
        );
    end if;

    insert into public.bank_transaction_snapshots(
      owner_id,account_key,account_role,snapshot_at,coverage_from,coverage_to,
      transaction_count,transactions,updated_at
    ) values (
      v_owner,p_account_key,p_account_role,p_snapshot_at,p_coverage_from,p_coverage_to,
      jsonb_array_length(p_transactions),p_transactions,now()
    )
    on conflict(owner_id,account_key,account_role) do update set
      snapshot_at=excluded.snapshot_at,
      coverage_from=excluded.coverage_from,
      coverage_to=excluded.coverage_to,
      transaction_count=excluded.transaction_count,
      transactions=excluded.transactions,
      updated_at=now()
    where public.bank_transaction_snapshots.snapshot_at<=excluded.snapshot_at;
  end if;

  select count(*)::integer into missing_count
  from public.bank_transactions b
  where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role
    and b.presence_state='missing';

  select count(*)::integer into active_missing_count
  from public.bank_transactions b
  where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role
    and b.presence_state='missing' and b.missing_acknowledged_at is null;

  inserted_count:=coalesce(v_inserted,0);
  updated_count:=coalesce(v_updated,0);
  total_count:=coalesce(v_total,0);
  snapshot_stored:=coalesce(p_complete,false);
  baseline_created:=coalesce(p_complete,false) and not v_had_complete_snapshot;
  return next;
end $$;

revoke all on function public.sync_bank_transactions_snapshot(text,text,jsonb,timestamptz,date,date,boolean) from public,anon;
grant execute on function public.sync_bank_transactions_snapshot(text,text,jsonb,timestamptz,date,date,boolean) to authenticated;

create or replace function public.acknowledge_bank_transaction_missing(p_transaction_id bigint)
returns table(transaction_id bigint,acknowledged_at timestamptz)
language plpgsql
security invoker
set search_path=pg_catalog,public
as $$
declare
  v_owner uuid:=auth.uid();
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  if p_transaction_id is null or p_transaction_id<=0 then raise exception 'invalid_bank_transaction_id' using errcode='22023'; end if;

  update public.bank_transactions b
     set missing_acknowledged_at=coalesce(b.missing_acknowledged_at,now())
   where b.id=p_transaction_id and b.owner_id=v_owner and b.presence_state='missing'
  returning b.id,b.missing_acknowledged_at into transaction_id,acknowledged_at;

  if transaction_id is null then
    raise exception 'bank_missing_transaction_not_found'
      using errcode='P0002',hint='The row is not a missing bank transaction owned by this user.';
  end if;
  return next;
end $$;

revoke all on function public.acknowledge_bank_transaction_missing(bigint) from public,anon;
grant execute on function public.acknowledge_bank_transaction_missing(bigint) to authenticated;

notify pgrst,'reload schema';

-- Durable bank alert acknowledgements v1 (authoritative clean-install/maintenance source)
-- Keeps alert dismissal separate from missing-transaction reconciliation so one incident cannot
-- accidentally suppress another. Alert acknowledgements are per archived bank transaction/kind.


alter table public.bank_transactions
  add column if not exists alert_acknowledgements jsonb not null default '{}'::jsonb;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid='public.bank_transactions'::regclass
      and conname='bank_transactions_alert_acknowledgements_object_check'
  ) then
    alter table public.bank_transactions
      add constraint bank_transactions_alert_acknowledgements_object_check
      check (jsonb_typeof(alert_acknowledgements)='object');
  end if;
end $$;

create or replace function public.acknowledge_bank_transaction_alert(
  p_transaction_id bigint,
  p_alert_kind text
)
returns table(transaction_id bigint,alert_kind text,acknowledged_at timestamptz)
language plpgsql
security invoker
set search_path=pg_catalog,public
as $$
declare
  v_owner uuid:=auth.uid();
  v_kind text:=btrim(coalesce(p_alert_kind,''));
  v_at timestamptz:=now();
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  if p_transaction_id is null or p_transaction_id<=0 then raise exception 'invalid_bank_transaction_id' using errcode='22023'; end if;
  if v_kind not in ('returned_cheque') then raise exception 'unsupported_bank_alert_kind' using errcode='22023'; end if;

  update public.bank_transactions b
     set alert_acknowledgements=coalesce(b.alert_acknowledgements,'{}'::jsonb) || jsonb_build_object(v_kind,v_at)
   where b.id=p_transaction_id and b.owner_id=v_owner
  returning b.id into transaction_id;

  if transaction_id is null then
    raise exception 'bank_alert_transaction_not_found'
      using errcode='P0002',hint='The bank transaction does not exist or is not owned by this user.';
  end if;

  alert_kind:=v_kind;
  acknowledged_at:=v_at;
  return next;
end $$;

revoke all on function public.acknowledge_bank_transaction_alert(bigint,text) from public,anon;
grant execute on function public.acknowledge_bank_transaction_alert(bigint,text) to authenticated;

notify pgrst,'reload schema';
