-- Bank -> Morning document workflow v1.
-- Manual handling is durable on the archived bank row. A bank/document link is written only
-- after the Morning operation is canonically verified; this prevents UI state from outrunning issuance truth.
begin;

alter table public.bank_transactions
  add column if not exists handled_at timestamptz;

alter table public.morning_document_operations
  add column if not exists source_kind text not null default 'standalone',
  add column if not exists source_bank_transaction_id bigint;

alter table public.morning_document_operations
  drop constraint if exists morning_document_operations_source_kind_check;
alter table public.morning_document_operations
  add constraint morning_document_operations_source_kind_check
  check (source_kind in ('standalone','debt','bank'));

alter table public.morning_document_operations
  drop constraint if exists morning_document_operations_source_shape_check;
alter table public.morning_document_operations
  add constraint morning_document_operations_source_shape_check
  check (
    (source_kind='bank' and source_bank_transaction_id is not null)
    or (source_kind in ('standalone','debt') and source_bank_transaction_id is null)
  );

create index if not exists morning_document_operations_bank_source_idx
  on public.morning_document_operations(owner_id,source_bank_transaction_id,created_at desc)
  where source_kind='bank';

-- No FK to bank_transactions on purpose: bank history retention must not erase/block issuance evidence.
create table if not exists public.bank_transaction_document_links (
  id bigint generated by default as identity primary key,
  owner_id uuid not null,
  transaction_id bigint not null,
  operation_id uuid not null references public.morning_document_operations(operation_id) on delete restrict,
  environment text not null check (environment in ('production','sandbox')),
  document_id text not null,
  document_number text not null default '',
  document_type integer not null check (document_type in (320,400)),
  document_amount numeric(14,2) not null check (document_amount>0),
  bank_amount numeric(14,2) not null check (bank_amount>0),
  verified_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique(owner_id,operation_id),
  unique(environment,document_id)
);
create index if not exists bank_transaction_document_links_transaction_idx
  on public.bank_transaction_document_links(owner_id,transaction_id,verified_at desc);
alter table public.bank_transaction_document_links enable row level security;
revoke all on table public.bank_transaction_document_links from public,anon,authenticated;
grant select on table public.bank_transaction_document_links to authenticated;
grant select,insert,update,delete on table public.bank_transaction_document_links to service_role;
drop policy if exists "bank_transaction_document_links_select_own" on public.bank_transaction_document_links;
create policy "bank_transaction_document_links_select_own"
  on public.bank_transaction_document_links for select to authenticated
  using ((select auth.uid())=owner_id);


create or replace function public.list_bank_morning_document_links(
  p_account_key text
)
returns table(
  transaction_id bigint,
  link_id bigint,
  operation_id uuid,
  document_id text,
  document_number text,
  document_type integer,
  document_amount numeric,
  verified_at timestamptz
)
language sql
stable
security invoker
set search_path=pg_catalog,public
as $$
  select l.transaction_id,l.id,l.operation_id,l.document_id,l.document_number,
         l.document_type,l.document_amount,l.verified_at
    from public.bank_transaction_document_links l
    join public.bank_transactions b
      on b.id=l.transaction_id and b.owner_id=l.owner_id
   where l.owner_id=auth.uid()
     and b.account_role='business'
     and b.account_key=trim(coalesce(p_account_key,''))
   order by l.verified_at desc,l.id desc
$$;
revoke all on function public.list_bank_morning_document_links(text) from public,anon;
grant execute on function public.list_bank_morning_document_links(text) to authenticated;

create or replace function public.set_bank_transaction_handled(
  p_transaction_id bigint,
  p_handled boolean
)
returns table(transaction_id bigint,handled_at timestamptz)
language plpgsql
security invoker
set search_path=pg_catalog,public
as $$
declare
  v_owner uuid:=auth.uid();
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  if p_transaction_id is null or p_transaction_id<=0 then raise exception 'invalid_bank_transaction_id' using errcode='22023'; end if;
  if p_handled is null then raise exception 'invalid_bank_transaction_handled_state' using errcode='22023'; end if;

  update public.bank_transactions b
     set handled_at=case when p_handled then coalesce(b.handled_at,now()) else null end
   where b.id=p_transaction_id and b.owner_id=v_owner and b.account_role='business' and b.status='completed'
  returning b.id,b.handled_at into transaction_id,handled_at;

  if transaction_id is null then
    raise exception 'bank_transaction_not_found'
      using errcode='P0002',hint='The business bank transaction does not exist or is not owned by this user.';
  end if;
  return next;
end $$;
revoke all on function public.set_bank_transaction_handled(bigint,boolean) from public,anon;
grant execute on function public.set_bank_transaction_handled(bigint,boolean) to authenticated;

create or replace function public.record_verified_bank_morning_document(
  p_owner_id uuid,
  p_operation_id uuid
)
returns table(transaction_id bigint,handled_at timestamptz,link_id bigint)
language plpgsql
security invoker
set search_path=pg_catalog,public
as $$
declare
  v_op public.morning_document_operations%rowtype;
  v_tx public.bank_transactions%rowtype;
  v_link_id bigint;
begin
  if p_owner_id is null or p_operation_id is null then raise exception 'invalid_bank_morning_link_input' using errcode='22023'; end if;
  if auth.role() is distinct from 'service_role' then raise exception 'service_role_required' using errcode='42501'; end if;

  select * into v_op
    from public.morning_document_operations o
   where o.operation_id=p_operation_id and o.owner_id=p_owner_id
   for update;
  if not found or v_op.source_kind<>'bank' or v_op.source_bank_transaction_id is null
     or v_op.state<>'created' or v_op.document_id is null or v_op.verified_at is null
     or v_op.document_type not in (320,400) then
    raise exception 'bank_morning_operation_not_verified' using errcode='22023';
  end if;

  select * into v_tx
    from public.bank_transactions b
   where b.id=v_op.source_bank_transaction_id and b.owner_id=p_owner_id
   for update;
  if not found or v_tx.account_role<>'business' or v_tx.status<>'completed'
     or upper(coalesce(v_tx.currency,'ILS'))<>'ILS' or v_tx.amount<=0 then
    raise exception 'bank_morning_transaction_not_eligible' using errcode='22023';
  end if;
  if round(v_op.amount::numeric,2) < round(v_tx.amount::numeric,2) then
    raise exception 'bank_morning_document_below_transaction_amount' using errcode='22023';
  end if;

  insert into public.bank_transaction_document_links(
    owner_id,transaction_id,operation_id,environment,document_id,document_number,
    document_type,document_amount,bank_amount,verified_at
  ) values (
    p_owner_id,v_tx.id,v_op.operation_id,v_op.environment,v_op.document_id,coalesce(v_op.document_number,''),
    v_op.document_type,v_op.amount,v_tx.amount,v_op.verified_at
  )
  on conflict (owner_id,operation_id) do update
    set document_id=excluded.document_id,
        document_number=excluded.document_number,
        document_type=excluded.document_type,
        document_amount=excluded.document_amount,
        bank_amount=excluded.bank_amount,
        verified_at=excluded.verified_at
  returning id into v_link_id;

  update public.bank_transactions b
     set handled_at=coalesce(b.handled_at,v_op.verified_at,now())
   where b.id=v_tx.id and b.owner_id=p_owner_id
  returning b.id,b.handled_at into transaction_id,handled_at;

  link_id:=v_link_id;
  return next;
end $$;
revoke all on function public.record_verified_bank_morning_document(uuid,uuid) from public,anon,authenticated;
grant execute on function public.record_verified_bank_morning_document(uuid,uuid) to service_role;

commit;
notify pgrst,'reload schema';
