-- ניהול הזמנות — Supabase Cloud Sync / Data Safety v5 (post-cutover)
-- הצ'קים אינם נשמרים עוד במסמך ניהול ההזמנות; מקור האמת הוא shared_checks_documents/main.
-- למעבר ממבנה ישן יש להריץ supabase/shared/cutover.sql לאחר preflight והקפאת עבודה.

begin;
set local lock_timeout = '10s';
set local statement_timeout = '90s';

create table if not exists public.order_management_documents (
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null default 'suppliers',
  revision bigint not null default 1 check (revision > 0),
  state jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (owner_id, document_name)
);
create table if not exists public.order_management_document_backups (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null,
  revision bigint not null,
  state jsonb not null,
  saved_at timestamptz not null default now()
);
create table if not exists public.order_management_periodic_backups (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null,
  revision bigint not null,
  state jsonb not null,
  saved_at timestamptz not null default now()
);

create index if not exists order_management_backups_owner_doc_saved_idx
  on public.order_management_document_backups(owner_id, document_name, saved_at desc);
create index if not exists order_management_periodic_backups_owner_doc_saved_idx
  on public.order_management_periodic_backups(owner_id, document_name, saved_at desc);
create unique index if not exists order_management_backups_owner_doc_revision_uidx
  on public.order_management_document_backups(owner_id, document_name, revision);
create unique index if not exists order_management_periodic_backups_owner_doc_revision_uidx
  on public.order_management_periodic_backups(owner_id, document_name, revision);

-- חוזה live מפורש: כל collection עסקי מרכזי חייב להיות array; checks אסור לאחר cutover.
alter table public.order_management_documents drop constraint if exists order_management_documents_state_object_check;
alter table public.order_management_documents drop constraint if exists order_management_documents_state_shape_check;
alter table public.order_management_documents
  add constraint order_management_documents_state_shape_check
  check (
    jsonb_typeof(state) = 'object'
    and not (state ? 'checks')
    and jsonb_typeof(state->'suppliers') = 'array'
    and jsonb_typeof(state->'transactions') = 'array'
    and jsonb_typeof(state->'customerDebts') = 'array'
    and jsonb_typeof(state->'customerOrders') = 'array'
    and jsonb_typeof(state->'serviceCalls') = 'array'
    and jsonb_typeof(state->'inventoryItems') = 'array'
    and jsonb_typeof(state->'inventoryCategoryOrder') = 'array'
    and jsonb_typeof(state->'inventoryEvents') = 'array'
    and jsonb_typeof(state->'warehouseOrders') = 'array'
    and jsonb_typeof(state->'notes') = 'array'
  ) not valid;

-- גיבויים היסטוריים יכולים להכיל checks; לכן שם נשמר חוזה object בלבד + revision חיובי.
alter table public.order_management_document_backups drop constraint if exists order_management_document_backups_revision_check;
alter table public.order_management_document_backups
  add constraint order_management_document_backups_revision_check check (revision > 0) not valid;
alter table public.order_management_document_backups drop constraint if exists order_management_document_backups_state_object_check;
alter table public.order_management_document_backups
  add constraint order_management_document_backups_state_object_check check (jsonb_typeof(state) = 'object') not valid;
alter table public.order_management_periodic_backups drop constraint if exists order_management_periodic_backups_revision_check;
alter table public.order_management_periodic_backups
  add constraint order_management_periodic_backups_revision_check check (revision > 0) not valid;
alter table public.order_management_periodic_backups drop constraint if exists order_management_periodic_backups_state_object_check;
alter table public.order_management_periodic_backups
  add constraint order_management_periodic_backups_state_object_check check (jsonb_typeof(state) = 'object') not valid;

alter table public.order_management_documents validate constraint order_management_documents_state_shape_check;
alter table public.order_management_document_backups validate constraint order_management_document_backups_revision_check;
alter table public.order_management_document_backups validate constraint order_management_document_backups_state_object_check;
alter table public.order_management_periodic_backups validate constraint order_management_periodic_backups_revision_check;
alter table public.order_management_periodic_backups validate constraint order_management_periodic_backups_state_object_check;

alter table public.order_management_documents enable row level security;
alter table public.order_management_document_backups enable row level security;
alter table public.order_management_periodic_backups enable row level security;
revoke all on table public.order_management_documents from anon, authenticated;
revoke all on table public.order_management_document_backups from anon, authenticated;
revoke all on table public.order_management_periodic_backups from anon, authenticated;
grant select, insert, update on table public.order_management_documents to authenticated;
grant select, insert, delete on table public.order_management_document_backups to authenticated;
grant select, insert, delete on table public.order_management_periodic_backups to authenticated;
revoke all on sequence public.order_management_document_backups_id_seq from public, anon;
revoke all on sequence public.order_management_periodic_backups_id_seq from public, anon;
grant usage, select on sequence public.order_management_document_backups_id_seq to authenticated;
grant usage, select on sequence public.order_management_periodic_backups_id_seq to authenticated;

drop policy if exists "order_management_documents_select_own" on public.order_management_documents;
create policy "order_management_documents_select_own" on public.order_management_documents
for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "order_management_documents_insert_own" on public.order_management_documents;
create policy "order_management_documents_insert_own" on public.order_management_documents
for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "order_management_documents_update_own" on public.order_management_documents;
create policy "order_management_documents_update_own" on public.order_management_documents
for update to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id)
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists "order_management_backups_select_own" on public.order_management_document_backups;
create policy "order_management_backups_select_own" on public.order_management_document_backups
for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "order_management_backups_insert_own" on public.order_management_document_backups;
create policy "order_management_backups_insert_own" on public.order_management_document_backups
for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "order_management_backups_delete_own" on public.order_management_document_backups;
create policy "order_management_backups_delete_own" on public.order_management_document_backups
for delete to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists "order_management_periodic_backups_select_own" on public.order_management_periodic_backups;
create policy "order_management_periodic_backups_select_own" on public.order_management_periodic_backups
for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "order_management_periodic_backups_insert_own" on public.order_management_periodic_backups;
create policy "order_management_periodic_backups_insert_own" on public.order_management_periodic_backups
for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "order_management_periodic_backups_delete_own" on public.order_management_periodic_backups;
create policy "order_management_periodic_backups_delete_own" on public.order_management_periodic_backups
for delete to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

create or replace function public.order_management_guard_document_write()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
begin
  if current_user = 'authenticated'
     and coalesce(current_setting('app.order_management_rpc_write', true), '') <> '1' then
    raise exception 'direct_order_management_write_forbidden'
      using errcode = '42501',
            hint = 'Use save_order_management_document RPC so revision checks and backups cannot be bypassed.';
  end if;
  if tg_op = 'UPDATE' and (
       new.owner_id is distinct from old.owner_id
       or new.document_name is distinct from old.document_name
     ) then
    raise exception 'order_management_identity_change_forbidden' using errcode = '22023';
  end if;
  return new;
end;
$$;
revoke all on function public.order_management_guard_document_write() from public, anon;
grant execute on function public.order_management_guard_document_write() to authenticated;
drop trigger if exists order_management_documents_write_guard on public.order_management_documents;
create trigger order_management_documents_write_guard
before insert or update on public.order_management_documents
for each row execute function public.order_management_guard_document_write();

create or replace function public.save_order_management_document(
  p_document_name text,
  p_expected_revision bigint,
  p_state jsonb
)
returns table(revision bigint, updated_at timestamptz)
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_owner uuid := auth.uid();
  v_current_revision bigint;
  v_old_state jsonb;
  v_old_updated_at timestamptz;
  v_new_revision bigint;
  v_new_updated_at timestamptz;
begin
  if v_owner is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;
  if p_document_name is null or btrim(p_document_name) = '' then
    raise exception 'invalid_document_name' using errcode = '22023';
  end if;
  if p_expected_revision is null or p_expected_revision < 0 then
    raise exception 'invalid_expected_revision' using errcode = '22023';
  end if;
  if p_state is null
     or jsonb_typeof(p_state) is distinct from 'object'
     or (p_state ? 'checks')
     or jsonb_typeof(p_state->'suppliers') is distinct from 'array'
     or jsonb_typeof(p_state->'transactions') is distinct from 'array'
     or jsonb_typeof(p_state->'customerDebts') is distinct from 'array'
     or jsonb_typeof(p_state->'customerOrders') is distinct from 'array'
     or jsonb_typeof(p_state->'serviceCalls') is distinct from 'array'
     or jsonb_typeof(p_state->'inventoryItems') is distinct from 'array'
     or jsonb_typeof(p_state->'inventoryCategoryOrder') is distinct from 'array'
     or jsonb_typeof(p_state->'inventoryEvents') is distinct from 'array'
     or jsonb_typeof(p_state->'warehouseOrders') is distinct from 'array'
     or jsonb_typeof(p_state->'notes') is distinct from 'array' then
    raise exception 'invalid_order_management_state'
      using errcode = '22023',
            hint = 'Post-cutover order state is missing required arrays or still contains checks.';
  end if;

  perform set_config('app.order_management_rpc_write', '1', true);
  select d.revision, d.state, d.updated_at
    into v_current_revision, v_old_state, v_old_updated_at
  from public.order_management_documents d
  where d.owner_id = v_owner and d.document_name = p_document_name
  for update;

  if v_current_revision is null then
    if coalesce(p_expected_revision,0) <> 0 then
      raise exception 'revision_conflict' using errcode = '40001';
    end if;
    insert into public.order_management_documents(owner_id, document_name, revision, state, updated_at)
    values (v_owner, p_document_name, 1, p_state, now())
    returning order_management_documents.revision, order_management_documents.updated_at
      into v_new_revision, v_new_updated_at;
    insert into public.order_management_periodic_backups(owner_id, document_name, revision, state, saved_at)
    values (v_owner, p_document_name, v_new_revision, p_state, v_new_updated_at)
    on conflict do nothing;
    return query select v_new_revision, v_new_updated_at;
    return;
  end if;

  -- savedAt משתנה בכל prepareState ולכן אינו חלק מהשוואת התוכן העסקי.
  -- הבדיקה קודמת ל-revision conflict כדי לתמוך ב-retry לאחר ACK שאבד.
  if (v_old_state #- '{_meta,savedAt}') = (p_state #- '{_meta,savedAt}') then
    return query select v_current_revision, v_old_updated_at;
    return;
  end if;
  if v_current_revision <> p_expected_revision then
    raise exception 'revision_conflict' using errcode = '40001';
  end if;

  insert into public.order_management_document_backups(owner_id, document_name, revision, state, saved_at)
  values (v_owner, p_document_name, v_current_revision, v_old_state, v_old_updated_at)
  on conflict do nothing;

  update public.order_management_documents d
  set revision=d.revision+1, state=p_state, updated_at=now()
  where d.owner_id=v_owner and d.document_name=p_document_name
  returning d.revision, d.updated_at into v_new_revision, v_new_updated_at;

  if not exists (
    select 1 from public.order_management_periodic_backups p
    where p.owner_id=v_owner and p.document_name=p_document_name
      and p.saved_at > now() - interval '12 hours'
  ) then
    insert into public.order_management_periodic_backups(owner_id, document_name, revision, state, saved_at)
    values (v_owner, p_document_name, v_new_revision, p_state, v_new_updated_at)
    on conflict do nothing;
  end if;

  delete from public.order_management_periodic_backups p
  where p.owner_id=v_owner and p.document_name=p_document_name
    and p.saved_at < now() - interval '365 days';
  delete from public.order_management_document_backups b
  where b.owner_id=v_owner and b.document_name=p_document_name
    and b.id in (
      select x.id from public.order_management_document_backups x
      where x.owner_id=v_owner and x.document_name=p_document_name
      order by x.saved_at desc, x.id desc offset 200
    );

  return query select v_new_revision, v_new_updated_at;
end;
$$;
revoke all on function public.save_order_management_document(text, bigint, jsonb) from public, anon;
grant execute on function public.save_order_management_document(text, bigint, jsonb) to authenticated;

insert into public.order_management_periodic_backups(owner_id, document_name, revision, state, saved_at)
select d.owner_id,d.document_name,d.revision,d.state,d.updated_at
from public.order_management_documents d
where not exists (
  select 1 from public.order_management_periodic_backups p
  where p.owner_id=d.owner_id and p.document_name=d.document_name
)
on conflict (owner_id, document_name, revision) do nothing;

commit;
