-- ניהול הזמנות — Supabase Cloud Sync / Data Safety v5 (post-cutover)
-- הצ'קים אינם נשמרים עוד במסמך ניהול ההזמנות; מקור האמת הוא shared_checks_documents/main.
-- למעבר ממבנה ישן יש להריץ supabase/shared/cutover.sql לאחר preflight והקפאת עבודה.

begin;
set local lock_timeout = '10s';
set local statement_timeout = '90s';

create table if not exists public.order_management_documents (
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null default 'suppliers',
  revision bigint not null default 1 check (revision > 0),
  state jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (owner_id, document_name)
);
create table if not exists public.order_management_document_backups (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null,
  revision bigint not null,
  state jsonb not null,
  saved_at timestamptz not null default now()
);
create table if not exists public.order_management_periodic_backups (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null,
  revision bigint not null,
  state jsonb not null,
  saved_at timestamptz not null default now()
);

create index if not exists order_management_backups_owner_doc_saved_idx
  on public.order_management_document_backups(owner_id, document_name, saved_at desc);
create index if not exists order_management_periodic_backups_owner_doc_saved_idx
  on public.order_management_periodic_backups(owner_id, document_name, saved_at desc);
create unique index if not exists order_management_backups_owner_doc_revision_uidx
  on public.order_management_document_backups(owner_id, document_name, revision);
create unique index if not exists order_management_periodic_backups_owner_doc_revision_uidx
  on public.order_management_periodic_backups(owner_id, document_name, revision);

-- חוזה live מפורש: כל collection עסקי מרכזי חייב להיות array; checks אסור לאחר cutover.
alter table public.order_management_documents drop constraint if exists order_management_documents_state_object_check;
alter table public.order_management_documents drop constraint if exists order_management_documents_state_shape_check;
alter table public.order_management_documents
  add constraint order_management_documents_state_shape_check
  check (
    jsonb_typeof(state) = 'object'
    and not (state ? 'checks')
    and jsonb_typeof(state->'suppliers') = 'array'
    and jsonb_typeof(state->'transactions') = 'array'
    and jsonb_typeof(state->'customerDebts') = 'array'
    and jsonb_typeof(state->'customerOrders') = 'array'
    and jsonb_typeof(state->'serviceCalls') = 'array'
    and jsonb_typeof(state->'inventoryItems') = 'array'
    and jsonb_typeof(state->'inventoryCategoryOrder') = 'array'
    and jsonb_typeof(state->'inventoryEvents') = 'array'
    and jsonb_typeof(state->'warehouseOrders') = 'array'
    and jsonb_typeof(state->'notes') = 'array'
  ) not valid;

-- גיבויים היסטוריים יכולים להכיל checks; לכן שם נשמר חוזה object בלבד + revision חיובי.
alter table public.order_management_document_backups drop constraint if exists order_management_document_backups_revision_check;
alter table public.order_management_document_backups
  add constraint order_management_document_backups_revision_check check (revision > 0) not valid;
alter table public.order_management_document_backups drop constraint if exists order_management_document_backups_state_object_check;
alter table public.order_management_document_backups
  add constraint order_management_document_backups_state_object_check check (jsonb_typeof(state) = 'object') not valid;
alter table public.order_management_periodic_backups drop constraint if exists order_management_periodic_backups_revision_check;
alter table public.order_management_periodic_backups
  add constraint order_management_periodic_backups_revision_check check (revision > 0) not valid;
alter table public.order_management_periodic_backups drop constraint if exists order_management_periodic_backups_state_object_check;
alter table public.order_management_periodic_backups
  add constraint order_management_periodic_backups_state_object_check check (jsonb_typeof(state) = 'object') not valid;

alter table public.order_management_documents validate constraint order_management_documents_state_shape_check;
alter table public.order_management_document_backups validate constraint order_management_document_backups_revision_check;
alter table public.order_management_document_backups validate constraint order_management_document_backups_state_object_check;
alter table public.order_management_periodic_backups validate constraint order_management_periodic_backups_revision_check;
alter table public.order_management_periodic_backups validate constraint order_management_periodic_backups_state_object_check;

alter table public.order_management_documents enable row level security;
alter table public.order_management_document_backups enable row level security;
alter table public.order_management_periodic_backups enable row level security;
revoke all on table public.order_management_documents from anon, authenticated;
revoke all on table public.order_management_document_backups from anon, authenticated;
revoke all on table public.order_management_periodic_backups from anon, authenticated;
grant select, insert, update on table public.order_management_documents to authenticated;
grant select, insert, delete on table public.order_management_document_backups to authenticated;
grant select, insert, delete on table public.order_management_periodic_backups to authenticated;
revoke all on sequence public.order_management_document_backups_id_seq from public, anon;
revoke all on sequence public.order_management_periodic_backups_id_seq from public, anon;
grant usage, select on sequence public.order_management_document_backups_id_seq to authenticated;
grant usage, select on sequence public.order_management_periodic_backups_id_seq to authenticated;

drop policy if exists "order_management_documents_select_own" on public.order_management_documents;
create policy "order_management_documents_select_own" on public.order_management_documents
for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "order_management_documents_insert_own" on public.order_management_documents;
create policy "order_management_documents_insert_own" on public.order_management_documents
for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "order_management_documents_update_own" on public.order_management_documents;
create policy "order_management_documents_update_own" on public.order_management_documents
for update to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id)
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists "order_management_backups_select_own" on public.order_management_document_backups;
create policy "order_management_backups_select_own" on public.order_management_document_backups
for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "order_management_backups_insert_own" on public.order_management_document_backups;
create policy "order_management_backups_insert_own" on public.order_management_document_backups
for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "order_management_backups_delete_own" on public.order_management_document_backups;
create policy "order_management_backups_delete_own" on public.order_management_document_backups
for delete to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists "order_management_periodic_backups_select_own" on public.order_management_periodic_backups;
create policy "order_management_periodic_backups_select_own" on public.order_management_periodic_backups
for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "order_management_periodic_backups_insert_own" on public.order_management_periodic_backups;
create policy "order_management_periodic_backups_insert_own" on public.order_management_periodic_backups
for insert to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists "order_management_periodic_backups_delete_own" on public.order_management_periodic_backups;
create policy "order_management_periodic_backups_delete_own" on public.order_management_periodic_backups
for delete to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

create or replace function public.order_management_guard_document_write()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
begin
  if current_user = 'authenticated'
     and coalesce(current_setting('app.order_management_rpc_write', true), '') <> '1' then
    raise exception 'direct_order_management_write_forbidden'
      using errcode = '42501',
            hint = 'Use save_order_management_document RPC so revision checks and backups cannot be bypassed.';
  end if;
  if tg_op = 'UPDATE' and (
       new.owner_id is distinct from old.owner_id
       or new.document_name is distinct from old.document_name
     ) then
    raise exception 'order_management_identity_change_forbidden' using errcode = '22023';
  end if;
  return new;
end;
$$;
revoke all on function public.order_management_guard_document_write() from public, anon;
grant execute on function public.order_management_guard_document_write() to authenticated;
drop trigger if exists order_management_documents_write_guard on public.order_management_documents;
create trigger order_management_documents_write_guard
before insert or update on public.order_management_documents
for each row execute function public.order_management_guard_document_write();

create or replace function public.save_order_management_document(
  p_document_name text,
  p_expected_revision bigint,
  p_state jsonb
)
returns table(revision bigint, updated_at timestamptz)
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_owner uuid := auth.uid();
  v_current_revision bigint;
  v_old_state jsonb;
  v_old_updated_at timestamptz;
  v_new_revision bigint;
  v_new_updated_at timestamptz;
begin
  if v_owner is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;
  if p_document_name is null or btrim(p_document_name) = '' then
    raise exception 'invalid_document_name' using errcode = '22023';
  end if;
  if p_expected_revision is null or p_expected_revision < 0 then
    raise exception 'invalid_expected_revision' using errcode = '22023';
  end if;
  if p_state is null
     or jsonb_typeof(p_state) is distinct from 'object'
     or (p_state ? 'checks')
     or jsonb_typeof(p_state->'suppliers') is distinct from 'array'
     or jsonb_typeof(p_state->'transactions') is distinct from 'array'
     or jsonb_typeof(p_state->'customerDebts') is distinct from 'array'
     or jsonb_typeof(p_state->'customerOrders') is distinct from 'array'
     or jsonb_typeof(p_state->'serviceCalls') is distinct from 'array'
     or jsonb_typeof(p_state->'inventoryItems') is distinct from 'array'
     or jsonb_typeof(p_state->'inventoryCategoryOrder') is distinct from 'array'
     or jsonb_typeof(p_state->'inventoryEvents') is distinct from 'array'
     or jsonb_typeof(p_state->'warehouseOrders') is distinct from 'array'
     or jsonb_typeof(p_state->'notes') is distinct from 'array' then
    raise exception 'invalid_order_management_state'
      using errcode = '22023',
            hint = 'Post-cutover order state is missing required arrays or still contains checks.';
  end if;

  perform set_config('app.order_management_rpc_write', '1', true);

  -- Busy is not a revision conflict. Failing fast prevents a stale/parallel client
  -- from turning one active writer into a PostgREST connection-pool convoy.
  if not pg_try_advisory_xact_lock(
    hashtextextended('order_management:' || v_owner::text || ':' || p_document_name, 0)
  ) then
    raise exception 'save_busy'
      using errcode = 'PT429',
            hint = 'Another save is already in progress. Retry later without refreshing the revision.';
  end if;
  perform set_config('lock_timeout', '100ms', true);

  begin
    select d.revision, d.state, d.updated_at
      into v_current_revision, v_old_state, v_old_updated_at
    from public.order_management_documents d
    where d.owner_id = v_owner and d.document_name = p_document_name
    for update nowait;
  exception when lock_not_available then
    raise exception 'save_busy'
      using errcode = 'PT429',
            hint = 'The document row is temporarily locked. Retry later without refreshing the revision.';
  end;

  if v_current_revision is null then
    if coalesce(p_expected_revision,0) <> 0 then
      raise exception 'revision_conflict' using errcode = '40001';
    end if;
    insert into public.order_management_documents(owner_id, document_name, revision, state, updated_at)
    values (v_owner, p_document_name, 1, p_state, now())
    returning order_management_documents.revision, order_management_documents.updated_at
      into v_new_revision, v_new_updated_at;
    insert into public.order_management_periodic_backups(owner_id, document_name, revision, state, saved_at)
    values (v_owner, p_document_name, v_new_revision, p_state, v_new_updated_at)
    on conflict do nothing;
    return query select v_new_revision, v_new_updated_at;
    return;
  end if;

  -- savedAt משתנה בכל prepareState ולכן אינו חלק מהשוואת התוכן העסקי.
  -- הבדיקה קודמת ל-revision conflict כדי לתמוך ב-retry לאחר ACK שאבד.
  if (v_old_state #- '{_meta,savedAt}') = (p_state #- '{_meta,savedAt}') then
    return query select v_current_revision, v_old_updated_at;
    return;
  end if;
  if v_current_revision <> p_expected_revision then
    raise exception 'revision_conflict' using errcode = '40001';
  end if;

  insert into public.order_management_document_backups(owner_id, document_name, revision, state, saved_at)
  values (v_owner, p_document_name, v_current_revision, v_old_state, v_old_updated_at)
  on conflict do nothing;

  update public.order_management_documents d
  set revision=d.revision+1, state=p_state, updated_at=now()
  where d.owner_id=v_owner and d.document_name=p_document_name
  returning d.revision, d.updated_at into v_new_revision, v_new_updated_at;

  if not exists (
    select 1 from public.order_management_periodic_backups p
    where p.owner_id=v_owner and p.document_name=p_document_name
      and p.saved_at > now() - interval '12 hours'
  ) then
    insert into public.order_management_periodic_backups(owner_id, document_name, revision, state, saved_at)
    values (v_owner, p_document_name, v_new_revision, p_state, v_new_updated_at)
    on conflict do nothing;
  end if;

  delete from public.order_management_periodic_backups p
  where p.owner_id=v_owner and p.document_name=p_document_name
    and p.saved_at < now() - interval '365 days';
  delete from public.order_management_document_backups b
  where b.owner_id=v_owner and b.document_name=p_document_name
    and b.id in (
      select x.id from public.order_management_document_backups x
      where x.owner_id=v_owner and x.document_name=p_document_name
      order by x.saved_at desc, x.id desc offset 200
    );

  return query select v_new_revision, v_new_updated_at;
end;
$$;
revoke all on function public.save_order_management_document(text, bigint, jsonb) from public, anon;
grant execute on function public.save_order_management_document(text, bigint, jsonb) to authenticated;

insert into public.order_management_periodic_backups(owner_id, document_name, revision, state, saved_at)
select d.owner_id,d.document_name,d.revision,d.state,d.updated_at
from public.order_management_documents d
where not exists (
  select 1 from public.order_management_periodic_backups p
  where p.owner_id=d.owner_id and p.document_name=d.document_name
)
on conflict (owner_id, document_name, revision) do nothing;

commit;

-- Financial sync data is intentionally isolated from kupa_documents backups.
create table if not exists public.finance_sync_documents (
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_name text not null default 'main',
  revision bigint not null default 1 check (revision > 0),
  state jsonb not null default '{"bank":null,"creditSync":null}'::jsonb check (jsonb_typeof(state)='object'),
  updated_at timestamptz not null default now(),
  primary key (owner_id, document_name)
);
alter table public.finance_sync_documents enable row level security;
revoke all on table public.finance_sync_documents from anon, authenticated;
grant select on table public.finance_sync_documents to authenticated;
drop policy if exists "finance_sync_select_own" on public.finance_sync_documents;
create policy "finance_sync_select_own" on public.finance_sync_documents for select to authenticated using ((select auth.uid()) = owner_id);

create or replace function public.save_finance_sync_document(p_document_name text, p_expected_revision bigint, p_state jsonb)
returns table(revision bigint, updated_at timestamptz, state jsonb)
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  v_owner uuid := auth.uid();
  v_current bigint;
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  -- Shared per-user financial writer gate: fail fast instead of filling the PostgREST pool.
  if not pg_try_advisory_xact_lock(
    hashtextextended('netunim_financial_write:' || v_owner::text, 0)
  ) then
    raise exception 'save_busy'
      using errcode = 'PT429',
            hint = 'Another financial save is already in progress. Retry later.';
  end if;
  perform set_config('lock_timeout', '100ms', true);
  if p_document_name is null or btrim(p_document_name)='' then raise exception 'invalid_document_name' using errcode='22023'; end if;
  if p_expected_revision is null or p_expected_revision < 0 then raise exception 'invalid_expected_revision' using errcode='22023'; end if;
  if p_state is null or jsonb_typeof(p_state) is distinct from 'object' then raise exception 'invalid_finance_sync_state' using errcode='22023'; end if;

  select d.revision into v_current from public.finance_sync_documents d
  where d.owner_id=v_owner and d.document_name=p_document_name for update;
  if v_current is null then
    if p_expected_revision<>0 then raise exception 'revision_conflict' using errcode='40001'; end if;
    insert into public.finance_sync_documents(owner_id,document_name,revision,state,updated_at)
    values(v_owner,p_document_name,1,p_state,now())
    returning finance_sync_documents.revision,finance_sync_documents.updated_at,finance_sync_documents.state
    into revision,updated_at,state;
    return next; return;
  end if;
  if v_current<>p_expected_revision then raise exception 'revision_conflict' using errcode='40001'; end if;
  update public.finance_sync_documents d set revision=d.revision+1,state=p_state,updated_at=now()
  where d.owner_id=v_owner and d.document_name=p_document_name
  returning d.revision,d.updated_at,d.state into revision,updated_at,state;
  return next;
end $$;
revoke all on function public.save_finance_sync_document(text,bigint,jsonb) from public, anon;
grant execute on function public.save_finance_sync_document(text,bigint,jsonb) to authenticated;



-- Atomically publish a verified bank snapshot and advance the Kupa cheque watermark.
-- The heavy bank payload stays only in finance_sync_documents; kupa_documents retains only
-- the tiny snapshot metadata needed to apply cheque events exactly once.
-- Cross-device lease for bank / credit synchronization.
-- One authenticated user can hold one lease per synchronization kind.
create table if not exists public.finance_sync_leases (
  owner_id uuid not null references auth.users(id) on delete cascade,
  lease_name text not null check (lease_name in ('bank','credit')),
  lease_token text not null,
  leased_until timestamptz not null,
  updated_at timestamptz not null default now(),
  primary key(owner_id,lease_name)
);

alter table public.finance_sync_leases enable row level security;
revoke all on table public.finance_sync_leases from anon, authenticated;
grant select, insert, update on table public.finance_sync_leases to authenticated;

drop policy if exists "finance_sync_leases_select_own" on public.finance_sync_leases;
create policy "finance_sync_leases_select_own" on public.finance_sync_leases
for select to authenticated
using ((select auth.uid())=owner_id);

drop policy if exists "finance_sync_leases_insert_own" on public.finance_sync_leases;
create policy "finance_sync_leases_insert_own" on public.finance_sync_leases
for insert to authenticated
with check ((select auth.uid())=owner_id);

drop policy if exists "finance_sync_leases_update_own" on public.finance_sync_leases;
create policy "finance_sync_leases_update_own" on public.finance_sync_leases
for update to authenticated
using ((select auth.uid())=owner_id)
with check ((select auth.uid())=owner_id);

create or replace function public.claim_finance_sync_lease(
  p_lease_name text,
  p_lease_token text,
  p_ttl_seconds integer default 1200
)
returns table(acquired boolean, leased_until timestamptz)
language plpgsql
security invoker
set search_path=pg_catalog,public
as $$
declare
  v_owner uuid:=auth.uid();
  v_name text:=btrim(coalesce(p_lease_name,''));
  v_token text:=btrim(coalesce(p_lease_token,''));
  v_now timestamptz:=clock_timestamp();
  v_until timestamptz;
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  if v_name not in ('bank','credit') then raise exception 'invalid_finance_sync_lease_name' using errcode='22023'; end if;
  if v_token='' or length(v_token)>200 then raise exception 'invalid_finance_sync_lease_token' using errcode='22023'; end if;
  if p_ttl_seconds is null or p_ttl_seconds<60 or p_ttl_seconds>1800 then raise exception 'invalid_finance_sync_lease_ttl' using errcode='22023'; end if;
  v_until:=v_now+make_interval(secs=>p_ttl_seconds);

  insert into public.finance_sync_leases as lease(owner_id,lease_name,lease_token,leased_until,updated_at)
  values(v_owner,v_name,v_token,v_until,v_now)
  on conflict(owner_id,lease_name) do update
  set lease_token=excluded.lease_token,
      leased_until=excluded.leased_until,
      updated_at=excluded.updated_at
  where lease.leased_until<=v_now or lease.lease_token=excluded.lease_token
  returning true,lease.leased_until into acquired,leased_until;

  if found then return next; return; end if;

  select false,lease.leased_until into acquired,leased_until
  from public.finance_sync_leases lease
  where lease.owner_id=v_owner and lease.lease_name=v_name;
  if not found then acquired:=false;leased_until:=null;end if;
  return next;
end $$;

revoke all on function public.claim_finance_sync_lease(text,text,integer) from public,anon;
grant execute on function public.claim_finance_sync_lease(text,text,integer) to authenticated;

create or replace function public.release_finance_sync_lease(
  p_lease_name text,
  p_lease_token text
)
returns boolean
language plpgsql
security invoker
set search_path=pg_catalog,public
as $$
declare
  v_owner uuid:=auth.uid();
  v_name text:=btrim(coalesce(p_lease_name,''));
  v_token text:=btrim(coalesce(p_lease_token,''));
  v_now timestamptz:=clock_timestamp();
  v_released boolean:=false;
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  if v_name not in ('bank','credit') then raise exception 'invalid_finance_sync_lease_name' using errcode='22023'; end if;
  if v_token='' or length(v_token)>200 then raise exception 'invalid_finance_sync_lease_token' using errcode='22023'; end if;

  update public.finance_sync_leases lease
  set leased_until=v_now,updated_at=v_now
  where lease.owner_id=v_owner and lease.lease_name=v_name and lease.lease_token=v_token
  returning true into v_released;
  return coalesce(v_released,false);
end $$;

revoke all on function public.release_finance_sync_lease(text,text) from public,anon;
grant execute on function public.release_finance_sync_lease(text,text) to authenticated;

create or replace function public.save_bank_sync_snapshot(
  p_document_name text,
  p_bank_state jsonb,
  p_snapshot_token text,
  p_snapshot_seq bigint
)
returns table(finance_revision bigint, kupa_revision bigint, updated_at timestamptz)
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_owner uuid := auth.uid();
  v_kupa_state jsonb;
  v_kupa_bank jsonb;
  v_old_snapshot_seq bigint := 0;
  v_shared_max_seq bigint := 0;
  v_finance_state jsonb;
  v_finance_revision bigint;
  v_kupa_revision bigint;
  v_now timestamptz := clock_timestamp();
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  -- Shared per-user financial writer gate: fail fast instead of filling the PostgREST pool.
  if not pg_try_advisory_xact_lock(
    hashtextextended('netunim_financial_write:' || v_owner::text, 0)
  ) then
    raise exception 'save_busy'
      using errcode = 'PT429',
            hint = 'Another financial save is already in progress. Retry later.';
  end if;
  perform set_config('lock_timeout', '100ms', true);
  if p_document_name is null or btrim(p_document_name)='' then raise exception 'invalid_document_name' using errcode='22023'; end if;
  if p_bank_state is null or jsonb_typeof(p_bank_state) is distinct from 'object' then raise exception 'invalid_bank_sync_state' using errcode='22023'; end if;
  if coalesce(btrim(p_snapshot_token),'')='' then raise exception 'invalid_bank_snapshot_token' using errcode='22023'; end if;
  if p_snapshot_seq is null or p_snapshot_seq<0 then raise exception 'invalid_bank_snapshot_sequence' using errcode='22023'; end if;

  -- Lock Kupa first. No other finance RPC locks both rows, so this gives one deterministic order.
  select d.state,d.revision into v_kupa_state,v_kupa_revision
  from public.kupa_documents d
  where d.owner_id=v_owner and d.document_name=p_document_name
  for update;
  if v_kupa_state is null then raise exception 'kupa_document_not_found' using errcode='P0002'; end if;

  v_kupa_bank:=coalesce(v_kupa_state->'bank','{}'::jsonb);
  if jsonb_typeof(v_kupa_bank->'snapshotSeq')='number' then
    begin v_old_snapshot_seq:=greatest(0,(v_kupa_bank->>'snapshotSeq')::bigint);
    exception when others then raise exception 'invalid_existing_bank_snapshot_sequence' using errcode='22023'; end;
  end if;

  select coalesce(max((e.value->>'seq')::bigint),0) into v_shared_max_seq
  from public.shared_checks_documents s
  left join lateral jsonb_array_elements(case when jsonb_typeof(s.state->'bankEvents')='array' then s.state->'bankEvents' else '[]'::jsonb end) e(value) on true
  where s.owner_id=v_owner and s.document_name='main';
  v_shared_max_seq:=coalesce(v_shared_max_seq,0);

  if p_snapshot_seq<v_old_snapshot_seq then
    raise exception 'stale_bank_snapshot_watermark' using errcode='40001',hint='Refresh shared checks before saving the bank snapshot.';
  end if;
  if p_snapshot_seq>greatest(v_old_snapshot_seq,v_shared_max_seq) then
    raise exception 'bank_snapshot_watermark_ahead_of_server' using errcode='22023',hint='The requested watermark was not observed in shared check events.';
  end if;

  select f.state,f.revision into v_finance_state,v_finance_revision
  from public.finance_sync_documents f
  where f.owner_id=v_owner and f.document_name=p_document_name
  for update;

  if v_finance_revision is null then
    insert into public.finance_sync_documents(owner_id,document_name,revision,state,updated_at)
    values(v_owner,p_document_name,1,jsonb_build_object('bank',p_bank_state,'creditSync',null),v_now)
    returning revision into v_finance_revision;
  else
    v_finance_state:=coalesce(v_finance_state,'{}'::jsonb);
    update public.finance_sync_documents f
    set revision=f.revision+1,
        state=jsonb_set(v_finance_state,'{bank}',p_bank_state,true),
        updated_at=v_now
    where f.owner_id=v_owner and f.document_name=p_document_name
    returning f.revision into v_finance_revision;
  end if;

  -- Direct Kupa writes are guarded; mark this transaction as an approved RPC write.
  perform set_config('app.kupa_rpc_write','1',true);
  v_kupa_bank:=jsonb_build_object(
    'currentBalance',null,
    'updatedAt',null,
    'asOfDate',null,
    'adjustments',coalesce(v_kupa_bank->'adjustments','[]'::jsonb),
    'source',null,
    'sourceAccount',null,
    'snapshotToken',p_snapshot_token,
    'snapshotSeq',p_snapshot_seq
  );
  v_kupa_state:=(v_kupa_state-'bank'-'creditSync')||jsonb_build_object('bank',v_kupa_bank);
  update public.kupa_documents d
  set revision=d.revision+1,state=v_kupa_state,updated_at=v_now
  where d.owner_id=v_owner and d.document_name=p_document_name
  returning d.revision into v_kupa_revision;

  finance_revision:=v_finance_revision;kupa_revision:=v_kupa_revision;updated_at:=v_now;return next;
end $$;
revoke all on function public.save_bank_sync_snapshot(text,jsonb,text,bigint) from public,anon;
grant execute on function public.save_bank_sync_snapshot(text,jsonb,text,bigint) to authenticated;

create table if not exists public.bank_transactions (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  account_key text not null,
  account_role text not null check (account_role in ('business','home')),
  merge_key text not null,
  transaction_date timestamptz,
  processed_date timestamptz,
  amount numeric not null,
  currency text not null default 'ILS',
  description text not null default '',
  memo text not null default '',
  party_name text not null default '',
  party_headline text not null default '',
  message_headline text not null default '',
  message_detail text not null default '',
  status text not null default 'completed' check(status in ('pending','completed')),
  balance_after numeric,
  bank_reference text not null default '',
  bank_serial text not null default '',
  activity_type_code integer,
  cheque boolean not null default false,
  check_details jsonb,
  first_seen_at timestamptz not null default now(),
  last_changed_at timestamptz not null default now(),
  unique(owner_id,account_key,merge_key)
);
create index if not exists bank_transactions_owner_account_date_idx on public.bank_transactions(owner_id,account_key,transaction_date desc);
create index if not exists bank_transactions_owner_reference_idx on public.bank_transactions(owner_id,account_key,bank_reference) where bank_reference<>'';
alter table public.bank_transactions enable row level security;
revoke all on table public.bank_transactions from anon, authenticated;
grant select on table public.bank_transactions to authenticated;
drop policy if exists "bank_transactions_select_own" on public.bank_transactions;
create policy "bank_transactions_select_own" on public.bank_transactions for select to authenticated using ((select auth.uid())=owner_id);

create or replace function public.merge_bank_transactions(p_account_key text,p_account_role text,p_transactions jsonb)
returns table(inserted_count integer, updated_count integer, total_count integer)
language plpgsql
set search_path=pg_catalog,public
as $$
declare
  v_owner uuid:=auth.uid();
  r jsonb;
  v_id bigint;
  v_inserted int:=0;
  v_updated int:=0;
  v_candidates int;
  v_candidate bigint;
  v_date timestamptz;
  v_processed timestamptz;
  v_amount numeric;
  v_serial text;
  v_reference text;
  v_description text;
  v_memo text;
  v_party_name text;
  v_status text;
  v_balance numeric;
  v_activity integer;
  v_pending_id bigint;
  v_pending_in_source boolean;
begin
  if v_owner is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  -- Shared per-user financial writer gate: fail fast instead of filling the PostgREST pool.
  if not pg_try_advisory_xact_lock(
    hashtextextended('netunim_financial_write:' || v_owner::text, 0)
  ) then
    raise exception 'save_busy'
      using errcode = 'PT429',
            hint = 'Another financial save is already in progress. Retry later.';
  end if;
  perform set_config('lock_timeout', '100ms', true);
  if coalesce(btrim(p_account_key),'')='' or p_account_role not in ('business','home') or jsonb_typeof(p_transactions) is distinct from 'array' then raise exception 'invalid_bank_merge_input' using errcode='22023'; end if;

  -- A duplicate merge key means the client could not distinguish two source rows. Fail atomically
  -- instead of silently collapsing financial movements. Fallback rows receive occurrence suffixes.
  if exists (
    select 1
    from jsonb_array_elements(p_transactions) x(value)
    group by x.value->>'mergeKey'
    having coalesce(x.value->>'mergeKey','')='' or count(*)>1
  ) then
    raise exception 'bank_archive_ambiguous_source_identity'
      using errcode='22023', hint='The bank returned rows that cannot be given unique stable identities. No archive rows were changed.';
  end if;

  for r in select value from jsonb_array_elements(p_transactions) loop
    if nullif(r->>'amount','') is null then raise exception 'invalid_bank_transaction_amount' using errcode='22023'; end if;
    v_date:=nullif(r->>'date','')::timestamptz;
    v_processed:=nullif(r->>'processedDate','')::timestamptz;
    v_amount:=(r->>'amount')::numeric;
    v_serial:=coalesce(r->>'bankSerial','');
    v_reference:=coalesce(r->>'bankReference','');
    v_description:=coalesce(r->>'description','');
    v_memo:=coalesce(r->>'memo','');
    v_party_name:=coalesce(r->>'partyName','');
    v_status:=case when r->>'status'='pending' then 'pending' else 'completed' end;
    v_balance:=nullif(r->>'balanceAfter','')::numeric;
    v_activity:=nullif(r->>'activityTypeCode','')::integer;
    v_id:=null;
    v_pending_id:=null;
    v_pending_in_source:=false;

    -- Hapoalim reference numbers are not globally unique. The bank serial is day-scoped and is
    -- the strongest stable identifier available for completed rows, so date is part of every match.
    if v_date is not null and v_serial not in ('','0') then
      select count(*),min(b.id) into v_candidates,v_candidate
      from public.bank_transactions b
      where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role
        and b.transaction_date::date=v_date::date and b.bank_serial=v_serial and b.amount=v_amount;
      if v_candidates>1 then
        raise exception 'bank_archive_existing_identity_collision'
          using errcode='40001', hint='More than one archived row matches the same bank date/serial/amount identity. No merge was committed.';
      elsif v_candidates=1 then v_id:=v_candidate; end if;
    end if;
    if v_id is null and v_date is not null and v_reference<>'' then
      select count(*),min(b.id) into v_candidates,v_candidate
      from public.bank_transactions b
      where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role
        and b.transaction_date::date=v_date::date and b.bank_reference=v_reference and b.amount=v_amount
        and b.description=v_description and b.memo=v_memo;
      if v_candidates>1 then
        raise exception 'bank_archive_existing_identity_collision'
          using errcode='40001', hint='More than one archived row matches the same bank date/reference/amount/content identity. No merge was committed.';
      elsif v_candidates=1 then v_id:=v_candidate; end if;
    end if;

    if v_id is null and coalesce(r->>'mergeKey','')<>'' then
      select count(*),min(b.id) into v_candidates,v_candidate
      from public.bank_transactions b
      where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role and b.merge_key=r->>'mergeKey';
      if v_candidates>1 then
        raise exception 'bank_archive_existing_merge_key_collision'
          using errcode='40001', hint='More than one archived row has the same merge key. No merge was committed.';
      elsif v_candidates=1 then v_id:=v_candidate; end if;
    end if;

    -- A Hapoalim pending row is a temporary state of the same movement. While pending, the bank
    -- commonly returns serial=0 and sparse beneficiary text; after settlement it assigns a serial
    -- and enriches memo/party fields. Those enriched fields must therefore never be required to
    -- identify the old placeholder. Reconcile only one UNIQUE pending candidate using facts that
    -- the current connector preserves across both states: account, amount and a tight date window,
    -- plus either a non-zero bank reference or the exact bank-provided balance/activity pair.
    -- Ambiguity deliberately leaves rows separate rather than risking a false financial merge.
    if v_status='completed' and v_date is not null then
      select count(*),min(b.id) into v_candidates,v_candidate
      from public.bank_transactions b
      where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role
        and b.status='pending' and b.amount=v_amount
        and b.transaction_date between (v_date-interval '3 days') and (v_date+interval '3 days')
        and (
          (v_reference not in ('','0') and b.bank_reference=v_reference
            and (v_activity is null or b.activity_type_code is null or b.activity_type_code=v_activity))
          or
          (v_balance is not null and v_activity is not null
            and b.balance_after is not distinct from v_balance
            and b.activity_type_code=v_activity
            and b.description=v_description)
        );
      if v_candidates=1 then
        v_pending_id:=v_candidate;

        -- Never delete a pending row that the current bank payload still exposes. The exact merge
        -- key is preferred, but connector upgrades are allowed to change derived client identities,
        -- so a conservative stable-facts fallback also counts as "still present".
        select exists(
          select 1
          from public.bank_transactions pb
          cross join lateral jsonb_array_elements(p_transactions) x(value)
          where pb.id=v_pending_id and x.value->>'status'='pending'
            and (
              x.value->>'mergeKey'=pb.merge_key
              or (
                nullif(x.value->>'amount','') is not null
                and (x.value->>'amount')::numeric=pb.amount
                and (
                  (coalesce(x.value->>'bankReference','') not in ('','0')
                    and x.value->>'bankReference'=pb.bank_reference)
                  or
                  (nullif(x.value->>'balanceAfter','') is not null
                    and nullif(x.value->>'activityTypeCode','') is not null
                    and (x.value->>'balanceAfter')::numeric is not distinct from pb.balance_after
                    and (x.value->>'activityTypeCode')::integer is not distinct from pb.activity_type_code)
                  or
                  (coalesce(x.value->>'description','')=pb.description
                    and nullif(x.value->>'date','') is not null
                    and (x.value->>'date')::timestamptz between (pb.transaction_date-interval '1 day') and (pb.transaction_date+interval '1 day'))
                )
              )
            )
        ) into v_pending_in_source;

        if not v_pending_in_source and v_id is null then
          v_id:=v_pending_id;
        end if;
      end if;
    end if;

    if v_id is null then
      insert into public.bank_transactions(owner_id,account_key,account_role,merge_key,transaction_date,processed_date,amount,currency,description,memo,party_name,party_headline,message_headline,message_detail,status,balance_after,bank_reference,bank_serial,activity_type_code,cheque,check_details)
      values(v_owner,p_account_key,p_account_role,r->>'mergeKey',v_date,v_processed,v_amount,coalesce(nullif(r->>'currency',''),'ILS'),v_description,coalesce(r->>'memo',''),coalesce(r->>'partyName',''),coalesce(r->>'partyHeadline',''),coalesce(r->>'messageHeadline',''),coalesce(r->>'messageDetail',''),v_status,v_balance,v_reference,v_serial,v_activity,coalesce((r->>'cheque')::boolean,false),r->'checkDetails');
      v_inserted:=v_inserted+1;
    else
      update public.bank_transactions b set
        merge_key=coalesce(nullif(r->>'mergeKey',''),b.merge_key),
        transaction_date=coalesce(v_date,b.transaction_date),
        processed_date=coalesce(v_processed,b.processed_date),
        currency=coalesce(nullif(r->>'currency',''),b.currency),
        description=coalesce(nullif(r->>'description',''),b.description),
        memo=coalesce(r->>'memo',b.memo),
        party_name=coalesce(r->>'partyName',b.party_name),
        party_headline=coalesce(r->>'partyHeadline',b.party_headline),
        message_headline=coalesce(r->>'messageHeadline',b.message_headline),
        message_detail=coalesce(r->>'messageDetail',b.message_detail),
        status=case when v_status='pending' and b.status='completed' then b.status else v_status end,
        balance_after=coalesce(v_balance,b.balance_after),
        bank_reference=coalesce(nullif(r->>'bankReference',''),b.bank_reference),
        bank_serial=coalesce(nullif(r->>'bankSerial',''),b.bank_serial),
        activity_type_code=coalesce(v_activity,b.activity_type_code),
        cheque=coalesce((r->>'cheque')::boolean,b.cheque),
        check_details=coalesce(r->'checkDetails',b.check_details),
        last_changed_at=now()
      where b.id=v_id and (
        b.merge_key is distinct from coalesce(nullif(r->>'mergeKey',''),b.merge_key)
        or b.transaction_date is distinct from coalesce(v_date,b.transaction_date)
        or b.processed_date is distinct from coalesce(v_processed,b.processed_date)
        or b.currency is distinct from coalesce(nullif(r->>'currency',''),b.currency)
        or b.description is distinct from coalesce(nullif(r->>'description',''),b.description)
        or b.memo is distinct from coalesce(r->>'memo',b.memo)
        or b.party_name is distinct from coalesce(r->>'partyName',b.party_name)
        or b.party_headline is distinct from coalesce(r->>'partyHeadline',b.party_headline)
        or b.message_headline is distinct from coalesce(r->>'messageHeadline',b.message_headline)
        or b.message_detail is distinct from coalesce(r->>'messageDetail',b.message_detail)
        or b.status is distinct from (case when v_status='pending' and b.status='completed' then b.status else v_status end)
        or b.balance_after is distinct from coalesce(v_balance,b.balance_after)
        or b.bank_reference is distinct from coalesce(nullif(r->>'bankReference',''),b.bank_reference)
        or b.bank_serial is distinct from coalesce(nullif(r->>'bankSerial',''),b.bank_serial)
        or b.activity_type_code is distinct from coalesce(v_activity,b.activity_type_code)
        or b.cheque is distinct from coalesce((r->>'cheque')::boolean,b.cheque)
        or b.check_details is distinct from coalesce(r->'checkDetails',b.check_details)
      );
      if found then v_updated:=v_updated+1; end if;
    end if;
  end loop;
  -- Self-verify the statement before returning. If any source row failed to become the exact
  -- archived row for its merge key, raise and let PostgreSQL roll the whole RPC statement back.
  if exists (
    select 1
    from jsonb_array_elements(p_transactions) x(value)
    where not exists (
      select 1 from public.bank_transactions b
      where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role
        and b.merge_key=x.value->>'mergeKey'
        and (nullif(x.value->>'date','') is null or b.transaction_date is not distinct from (x.value->>'date')::timestamptz)
        and (nullif(x.value->>'processedDate','') is null or b.processed_date is not distinct from (x.value->>'processedDate')::timestamptz)
        and b.amount=(x.value->>'amount')::numeric
        and b.description=coalesce(x.value->>'description','')
        and b.memo=coalesce(x.value->>'memo','')
        and (coalesce(x.value->>'bankReference','')='' or b.bank_reference=x.value->>'bankReference')
        and (coalesce(x.value->>'bankSerial','')='' or b.bank_serial=x.value->>'bankSerial')
        and (case when x.value->>'status'='pending' then b.status in ('pending','completed') else b.status='completed' end)
    )
  ) then
    raise exception 'bank_archive_merge_verification_failed'
      using errcode='40001', hint='The transaction merge did not reproduce every bank row exactly. The entire RPC was rolled back.';
  end if;

  select count(*)::int into total_count from public.bank_transactions b where b.owner_id=v_owner and b.account_key=p_account_key and b.account_role=p_account_role;
  inserted_count:=v_inserted; updated_count:=v_updated; return next;
end $$;
revoke all on function public.merge_bank_transactions(text,text,jsonb) from public,anon;
grant execute on function public.merge_bank_transactions(text,text,jsonb) to authenticated;

-- Write access is still owner-scoped by RLS; RPCs do not use service_role.
grant insert, update on table public.finance_sync_documents to authenticated;
drop policy if exists "finance_sync_insert_own" on public.finance_sync_documents;
create policy "finance_sync_insert_own" on public.finance_sync_documents for insert to authenticated with check ((select auth.uid())=owner_id);
drop policy if exists "finance_sync_update_own" on public.finance_sync_documents;
create policy "finance_sync_update_own" on public.finance_sync_documents for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
grant insert, update on table public.bank_transactions to authenticated;
grant usage, select on sequence public.bank_transactions_id_seq to authenticated;
drop policy if exists "bank_transactions_insert_own" on public.bank_transactions;
create policy "bank_transactions_insert_own" on public.bank_transactions for insert to authenticated with check ((select auth.uid())=owner_id);
drop policy if exists "bank_transactions_update_own" on public.bank_transactions;
create policy "bank_transactions_update_own" on public.bank_transactions for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
